# Generated by Django 4.2.11 on 2024-07-04 14:28

import django.db.models.deletion
from django.db import migrations, models

import openforms.registrations.contrib.objects_api.models
import openforms.template.validators
import openforms.utils.validators


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("zgw_consumers", "0012_auto_20210104_1039"),
        ("forms", "0001_initial_to_v320"),
        ("submissions", "0001_initial_to_openforms_v230"),
        ("zgw_consumers", "0019_alter_service_uuid"),
    ]

    operations = [
        migrations.CreateModel(
            name="ObjectsAPIRegistrationData",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pdf_url",
                    models.URLField(
                        blank=True,
                        help_text="The PDF URL of the document on the Documents API.",
                        verbose_name="pdf url",
                    ),
                ),
                (
                    "csv_url",
                    models.URLField(
                        blank=True,
                        help_text="The CSV URL of the document on the Documents API.",
                        verbose_name="csv url",
                    ),
                ),
                (
                    "submission",
                    models.OneToOneField(
                        help_text="The submission linked to the registration data.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="objects_api_registration_data",
                        to="submissions.submission",
                        verbose_name="submission",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ObjectsAPISubmissionAttachment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_url",
                    models.URLField(
                        help_text="The URL of the submission attachment registered in the Documents API.",
                        verbose_name="document_url",
                    ),
                ),
                (
                    "submission_file_attachment",
                    models.ForeignKey(
                        help_text="The submission file attachment.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="submissions.submissionfileattachment",
                        verbose_name="submission file attachment",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ObjectsAPIConfig",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "objecttype",
                    models.URLField(
                        blank=True,
                        editable=False,
                        help_text="Default URL of the ProductAanvraag OBJECTTYPE in the Objecttypes API. The objecttype should have the following three attributes: 1) submission_id; 2) type (the type of productaanvraag); 3) data (the submitted form data)",
                        max_length=1000,
                        verbose_name="objecttype",
                    ),
                ),
                (
                    "objecttype_version",
                    models.IntegerField(
                        blank=True,
                        editable=False,
                        help_text="Default version of the OBJECTTYPE in the Objecttypes API",
                        null=True,
                        verbose_name="objecttype version",
                    ),
                ),
                (
                    "productaanvraag_type",
                    models.CharField(
                        blank=True,
                        help_text="Description of the 'ProductAanvraag' type. This value is saved in the 'type' attribute of the 'ProductAanvraag'.",
                        max_length=255,
                        verbose_name="Productaanvraag type",
                    ),
                ),
                (
                    "objects_service",
                    models.OneToOneField(
                        limit_choices_to={"api_type": "orc"},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="zgw_consumers.service",
                        verbose_name="Objects API",
                    ),
                ),
                (
                    "drc_service",
                    models.OneToOneField(
                        limit_choices_to={"api_type": "drc"},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="zgw_consumers.service",
                        verbose_name="Documenten API",
                    ),
                ),
                (
                    "informatieobjecttype_attachment",
                    models.URLField(
                        blank=True,
                        help_text="Default URL that points to the INFORMATIEOBJECTTYPE in the Catalogi API to be used for the submission attachments",
                        max_length=1000,
                        verbose_name="attachment informatieobjecttype",
                    ),
                ),
                (
                    "informatieobjecttype_submission_report",
                    models.URLField(
                        blank=True,
                        help_text="Default URL that points to the INFORMATIEOBJECTTYPE in the Catalogi API to be used for the submission report PDF",
                        max_length=1000,
                        verbose_name="submission report informatieobjecttype",
                    ),
                ),
                (
                    "organisatie_rsin",
                    models.CharField(
                        blank=True,
                        help_text="Default RSIN of organization, which creates the INFORMATIEOBJECT",
                        max_length=9,
                        validators=[openforms.utils.validators.RSINValidator()],
                        verbose_name="organisation RSIN",
                    ),
                ),
                (
                    "informatieobjecttype_submission_csv",
                    models.URLField(
                        blank=True,
                        help_text="Default URL that points to the INFORMATIEOBJECTTYPE in the Catalogi API to be used for the submission report CSV",
                        max_length=1000,
                        verbose_name="submission report CSV informatieobjecttype",
                    ),
                ),
                (
                    "catalogi_service",
                    models.OneToOneField(
                        limit_choices_to={"api_type": "ztc"},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="zgw_consumers.service",
                        verbose_name="Catalogi API",
                    ),
                ),
                (
                    "content_json",
                    models.TextField(
                        default=openforms.registrations.contrib.objects_api.models.get_content_text,
                        help_text="This template is evaluated with the submission data and the resulting JSON is sent to the objects API.",
                        validators=[
                            openforms.template.validators.DjangoTemplateValidator(
                                backend="openforms.template.openforms_backend"
                            )
                        ],
                        verbose_name="JSON content template",
                    ),
                ),
                (
                    "payment_status_update_json",
                    models.TextField(
                        default=openforms.registrations.contrib.objects_api.models.get_payment_status_update_text,
                        help_text="This template is evaluated with the submission data and the resulting JSON is sent to the objects API with a PATCH to update the payment field.",
                        validators=[
                            openforms.template.validators.DjangoTemplateValidator(
                                backend="openforms.template.openforms_backend"
                            )
                        ],
                        verbose_name="payment status update JSON template",
                    ),
                ),
                (
                    "objecttypes_service",
                    models.OneToOneField(
                        limit_choices_to={"api_type": "orc"},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="zgw_consumers.service",
                        verbose_name="Objecttypes API",
                    ),
                ),
            ],
            options={
                "verbose_name": "Objects API configuration",
            },
        ),
    ]
