# Generated by Django 2.2.24 on 2021-08-02 09:31

from django.db import migrations, models
import django.db.models.deletion
import openforms.utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ("zgw_consumers", "0012_auto_20210104_1039"),
        ("registrations_objects_api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="objectsapiconfig",
            name="drc_service",
            field=models.OneToOneField(
                limit_choices_to={"api_type": "drc"},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="objects_drc_config",
                to="zgw_consumers.Service",
                verbose_name="Documenten API",
            ),
        ),
        migrations.AddField(
            model_name="objectsapiconfig",
            name="informatieobjecttype_attachment",
            field=models.URLField(
                blank=True,
                help_text="Default URL of the INFORMATIEOBJECTTYPE for the submission attachments in the Catalogi API",
                max_length=1000,
                verbose_name="attachment informatieobjecttype",
            ),
        ),
        migrations.AddField(
            model_name="objectsapiconfig",
            name="informatieobjecttype_submission_report",
            field=models.URLField(
                blank=True,
                help_text="Default URL of the INFORMATIEOBJECTTYPE for the submission report in the Catalogi API",
                max_length=1000,
                verbose_name="submission report informatieobjecttype",
            ),
        ),
        migrations.AddField(
            model_name="objectsapiconfig",
            name="organisatie_rsin",
            field=models.CharField(
                blank=True,
                help_text="Default RSIN of organization, which creates the INFORMATIEOBJECT",
                max_length=9,
                validators=[openforms.utils.validators.RSINValidator()],
                verbose_name="organisation RSIN",
            ),
        ),
        migrations.AlterField(
            model_name="objectsapiconfig",
            name="objects_service",
            field=models.OneToOneField(
                limit_choices_to={"api_type": "orc"},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="objects_objects_config",
                to="zgw_consumers.Service",
                verbose_name="Objects API",
            ),
        ),
    ]
