# Generated by Django 2.2.24 on 2021-08-31 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registrations_objects_api", "0002_auto_20210802_1131"),
    ]

    operations = [
        migrations.AlterField(
            model_name="objectsapiconfig",
            name="drc_service",
            field=models.OneToOneField(
                limit_choices_to={"api_type": "drc"},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="zgw_consumers.Service",
                verbose_name="Documenten API",
            ),
        ),
        migrations.AlterField(
            model_name="objectsapiconfig",
            name="objects_service",
            field=models.OneToOneField(
                limit_choices_to={"api_type": "orc"},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="zgw_consumers.Service",
                verbose_name="Objects API",
            ),
        ),
    ]
