# Generated by Django 2.2.24 on 2021-10-15 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registrations_objects_api", "0004_auto_20210902_2120"),
    ]

    operations = [
        migrations.AddField(
            model_name="objectsapiconfig",
            name="informatieobjecttype_submission_csv",
            field=models.URLField(
                blank=True,
                help_text="Default URL that points to the INFORMATIEOBJECTTYPE in the Catalogi API to be used for the submission report CSV",
                max_length=1000,
                verbose_name="submission report CSV informatieobjecttype",
            ),
        ),
        migrations.AlterField(
            model_name="objectsapiconfig",
            name="informatieobjecttype_attachment",
            field=models.URLField(
                blank=True,
                help_text="Default URL that points to the INFORMATIEOBJECTTYPE in the Catalogi API to be used for the submission attachments",
                max_length=1000,
                verbose_name="attachment informatieobjecttype",
            ),
        ),
        migrations.AlterField(
            model_name="objectsapiconfig",
            name="informatieobjecttype_submission_report",
            field=models.URLField(
                blank=True,
                help_text="Default URL that points to the INFORMATIEOBJECTTYPE in the Catalogi API to be used for the submission report PDF",
                max_length=1000,
                verbose_name="submission report informatieobjecttype",
            ),
        ),
    ]
