# Generated by Django 3.2.19 on 2023-06-12 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("zgw_consumers", "0019_alter_service_uuid"),
        ("registrations_objects_api", "0005_auto_20211015_1334"),
    ]

    operations = [
        migrations.AddField(
            model_name="objectsapiconfig",
            name="catalogi_service",
            field=models.OneToOneField(
                limit_choices_to={"api_type": "ztc"},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="zgw_consumers.service",
                verbose_name="Catalogi API",
            ),
        ),
    ]
