# Generated by Django 3.2.18 on 2023-06-20 13:01

from django.db import migrations, models
import functools
import openforms.registrations.contrib.email.models
import openforms.template.validators


class Migration(migrations.Migration):
    dependencies = [
        ("registrations_objects_api", "0005_auto_20211015_1334"),
    ]

    operations = [
        migrations.AddField(
            model_name="objectsapiconfig",
            name="content_json",
            field=models.TextField(
                default=functools.partial(
                    openforms.registrations.contrib.email.models.render_with_language,
                    *("registrations/contrib/objects_api/content_json.txt",),
                    **{}
                ),
                validators=[
                    openforms.template.validators.DjangoTemplateValidator(
                        backend="openforms.template.openforms_backend"
                    )
                ],
                verbose_name="Json field",
            ),
        ),
    ]
