# Generated by Django 3.2.19 on 2023-06-21 14:52

from django.db import migrations, models
import django.db.models.deletion
import openforms.template.validators


class Migration(migrations.Migration):
    dependencies = [
        ("zgw_consumers", "0019_alter_service_uuid"),
        ("registrations_objects_api", "0005_auto_20211015_1334"),
    ]

    operations = [
        migrations.AddField(
            model_name="objectsapiconfig",
            name="catalogi_service",
            field=models.OneToOneField(
                limit_choices_to={"api_type": "ztc"},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="zgw_consumers.service",
                verbose_name="Catalogi API",
            ),
        ),
        migrations.AddField(
            model_name="objectsapiconfig",
            name="content_json",
            field=models.TextField(
                default='{\n  "data": {% json_summary %},\n  "type": "terugbelnotitie",\n  "bsn": "{{ auth_bsn }}",\n  "pdf_url": "{{ submission.pdf_url }}",\n  "attachments": {{ submission.attachments }},\n  "submission_id": "{{ submission.kenmerk }}",\n  "language_code": "{{ submission.language_code }}"\n}',
                help_text="This template is evaluated with the submission data and the resulting JSON is sent to the objects API.",
                validators=[
                    openforms.template.validators.DjangoTemplateValidator(
                        backend="openforms.template.openforms_backend"
                    )
                ],
                verbose_name="JSON content template",
            ),
        ),
    ]
