# Generated by Django 3.2.19 on 2023-06-20 16:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("registrations_objects_api", "0006_objectsapiconfig_catalogi_service"),
        ("registrations_objects_api", "0006_objectsapiconfig_content_json"),
    ]

    operations = []
