# Generated by Django 3.2.19 on 2023-06-23 09:06

from django.db import migrations, models
import openforms.registrations.contrib.objects_api.models
import openforms.template.validators


class Migration(migrations.Migration):

    dependencies = [
        ("registrations_objects_api", "0006_objectsapiconfig_catalogi_service"),
    ]

    operations = [
        migrations.AddField(
            model_name="objectsapiconfig",
            name="content_json",
            field=models.TextField(
                default=openforms.registrations.contrib.objects_api.models.get_content_text,
                help_text="This template is evaluated with the submission data and the resulting JSON is sent to the objects API.",
                validators=[
                    openforms.template.validators.DjangoTemplateValidator(
                        backend="openforms.template.openforms_backend"
                    )
                ],
                verbose_name="JSON content template",
            ),
        ),
    ]
