# Generated by Django 3.2.19 on 2023-06-29 07:10
from django.db import migrations
from django.db.models import Value
from django.db.models.functions import Replace


def replace_terugbelnotitie_with_variable(apps, schema_editor):
    apps.get_model("registrations_objects_api", "objectsapiconfig").objects.update(
        content_json=Replace(
            "content_json",
            Value("terugbelnotitie"),
            Value("{{ productaanvraag_type }}"),
        )
    )


class Migration(migrations.Migration):
    dependencies = [
        ("registrations_objects_api", "0007_objectsapiconfig_content_json"),
    ]

    operations = [
        migrations.RunPython(
            replace_terugbelnotitie_with_variable,
            migrations.RunPython.noop,
        )
    ]
