# Generated by Django 3.2.19 on 2023-06-29 07:10
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("registrations_objects_api", "0007_objectsapiconfig_content_json"),
    ]

    # RunPython operation removed as part of 2.7 release cycle, which requires 2.6.7 to
    # be run first.
    operations = []
