# Generated by Django 3.2.19 on 2023-06-21 11:36

from django.db import migrations, models
import openforms.template.validators


class Migration(migrations.Migration):
    dependencies = [
        ("registrations_objects_api", "0007_merge_20230620_1838"),
    ]

    operations = [
        migrations.AlterField(
            model_name="objectsapiconfig",
            name="content_json",
            field=models.TextField(
                default='{\n  "data": {% json_summary %},\n  "type": "terugbelnotitie",\n  "bsn": "{{ auth_bsn }}",\n  "pdf_url": "{{ submission.pdf_url }}",\n  "attachments": {{ submission.attachments }},\n  "submission_id": "{{ submission.kenmerk }}",\n  "language_code": "{{ submission.language_code }}"\n}',
                validators=[
                    openforms.template.validators.DjangoTemplateValidator(
                        backend="openforms.template.openforms_backend"
                    )
                ],
                verbose_name="Json field",
            ),
        ),
    ]
