# Generated by Django 3.2.23 on 2024-01-31 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("zgw_consumers", "0019_alter_service_uuid"),
        (
            "registrations_objects_api",
            "0009_objectsapiconfig_payment_status_update_json",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="objectsapiconfig",
            name="objecttypes_service",
            field=models.OneToOneField(
                limit_choices_to={"api_type": "orc"},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="zgw_consumers.service",
                verbose_name="Objecttypes API",
            ),
        ),
    ]
