# Generated by Django 3.2.24 on 2024-02-12 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("registrations_objects_api", "0011_create_objecttypesypes_service_from_url"),
        ("forms", "0001_initial_to_v250"),
    ]

    # RunPython operation removed as part of 2.7 release cycle, which requires 2.6.7 to
    # be run first.
    operations = []
