# Generated by Django 4.2.10 on 2024-03-13 10:39

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0004_auto_20231128_1536"),
        ("registrations_objects_api", "0012_fill_required_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="ObjectsAPIRegistrationData",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pdf_url",
                    models.URLField(
                        blank=True,
                        help_text="The PDF URL of the document on the Documents API.",
                        verbose_name="pdf url",
                    ),
                ),
                (
                    "csv_url",
                    models.URLField(
                        blank=True,
                        help_text="The CSV URL of the document on the Documents API.",
                        verbose_name="csv url",
                    ),
                ),
                (
                    "attachment_urls",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.URLField(
                            help_text="The attachment URL on the Documents API.",
                            verbose_name="attachment url",
                        ),
                        blank=True,
                        default=list,
                        help_text="The list of attachment URLs on the Documents API.",
                        size=None,
                        verbose_name="attachment urls",
                    ),
                ),
                (
                    "submission",
                    models.OneToOneField(
                        help_text="The submission linked to the registration data.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="objects_api_registration_data",
                        to="submissions.submission",
                        verbose_name="submission",
                    ),
                ),
            ],
        ),
    ]
