# Generated by Django 4.2.11 on 2024-05-31 10:55

import django.db.models.deletion
from django.db import migrations, models

import openforms.utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ("zgw_consumers", "0020_service_timeout"),
        (
            "registrations_objects_api",
            "0001_initial_to_v267",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ObjectsAPIGroupConfig",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="A recognisable name for this set of Objects APIs.",
                        max_length=255,
                        verbose_name="name",
                    ),
                ),
                (
                    "informatieobjecttype_submission_report",
                    models.URLField(
                        blank=True,
                        help_text="Default URL that points to the INFORMATIEOBJECTTYPE in the Catalogi API to be used for the submission report PDF",
                        max_length=1000,
                        verbose_name="submission report informatieobjecttype",
                    ),
                ),
                (
                    "informatieobjecttype_submission_csv",
                    models.URLField(
                        blank=True,
                        help_text="Default URL that points to the INFORMATIEOBJECTTYPE in the Catalogi API to be used for the submission report CSV",
                        max_length=1000,
                        verbose_name="submission report CSV informatieobjecttype",
                    ),
                ),
                (
                    "informatieobjecttype_attachment",
                    models.URLField(
                        blank=True,
                        help_text="Default URL that points to the INFORMATIEOBJECTTYPE in the Catalogi API to be used for the submission attachments",
                        max_length=1000,
                        verbose_name="attachment informatieobjecttype",
                    ),
                ),
                (
                    "organisatie_rsin",
                    models.CharField(
                        blank=True,
                        help_text="Default RSIN of organization, which creates the INFORMATIEOBJECT",
                        max_length=9,
                        validators=[openforms.utils.validators.RSINValidator()],
                        verbose_name="organisation RSIN",
                    ),
                ),
                (
                    "catalogi_service",
                    models.ForeignKey(
                        limit_choices_to={"api_type": "ztc"},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="zgw_consumers.service",
                        verbose_name="Catalogi API",
                    ),
                ),
                (
                    "drc_service",
                    models.ForeignKey(
                        limit_choices_to={"api_type": "drc"},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="zgw_consumers.service",
                        verbose_name="Documenten API",
                    ),
                ),
                (
                    "objects_service",
                    models.ForeignKey(
                        limit_choices_to={"api_type": "orc"},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="zgw_consumers.service",
                        verbose_name="Objects API",
                    ),
                ),
                (
                    "objecttypes_service",
                    models.ForeignKey(
                        limit_choices_to={"api_type": "orc"},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="zgw_consumers.service",
                        verbose_name="Objecttypes API",
                    ),
                ),
            ],
            options={
                "verbose_name": "Objects API group",
                "verbose_name_plural": "Objects API groups",
            },
        ),
    ]
