# Generated by Django 4.2.23 on 2025-08-05 15:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registrations_objects_api", "0016_v267_to_v300"),
    ]

    operations = [
        migrations.AlterField(
            model_name="objectsapiconfig",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="objectsapiregistrationdata",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="objectsapisubmissionattachment",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
