# Generated by Django 4.2.11 on 2024-05-27 13:06

from django.db import migrations

from django.db.migrations.state import StateApps
from django.db.backends.base.schema import BaseDatabaseSchemaEditor


def move_singleton_data_to_objects_api_set_model(
    apps: StateApps, schema_editor: BaseDatabaseSchemaEditor
) -> None:
    ObjectsAPIConfig = apps.get_model("registrations_objects_api", "ObjectsAPIConfig")
    ObjectsAPIGroupConfig = apps.get_model(
        "registrations_objects_api", "ObjectsAPIGroupConfig"
    )

    solo_model = ObjectsAPIConfig.objects.first()
    if not solo_model:
        return

    new_config_set = ObjectsAPIGroupConfig(
        name="Objects APIs",
        objects_service=solo_model.objects_service,
        objecttypes_service=solo_model.objecttypes_service,
        drc_service=solo_model.drc_service,
        catalogi_service=solo_model.catalogi_service,
        objecttype=solo_model.objecttype,
        objecttype_version=solo_model.objecttype_version,
        productaanvraag_type=solo_model.productaanvraag_type,
        informatieobjecttype_submission_report=solo_model.informatieobjecttype_submission_report,
        informatieobjecttype_submission_csv=solo_model.informatieobjecttype_submission_csv,
        informatieobjecttype_attachment=solo_model.informatieobjecttype_attachment,
        organisatie_rsin=solo_model.organisatie_rsin,
        content_json=solo_model.content_json,
        payment_status_update_json=solo_model.payment_status_update_json,
    )

    new_config_set.save()


def reconfigure_objects_api_solo_model(
    apps: StateApps, schema_editor: BaseDatabaseSchemaEditor
) -> None:
    ObjectsAPIConfig = apps.get_model("registrations_objects_api", "ObjectsAPIConfig")
    ObjectsAPIGroupConfig = apps.get_model(
        "registrations_objects_api", "ObjectsAPIGroupConfig"
    )

    solo_model = ObjectsAPIConfig.objects.first()
    objects_api_group = ObjectsAPIGroupConfig.objects.all().order_by("pk").first()

    if not solo_model or not objects_api_group:
        return

    solo_model.objects_service = objects_api_group.objects_service
    solo_model.objecttypes_service = objects_api_group.objecttypes_service
    solo_model.drc_service = objects_api_group.drc_service
    solo_model.catalogi_service = objects_api_group.catalogi_service
    solo_model.objecttype = objects_api_group.objecttype
    solo_model.objecttype_version = objects_api_group.objecttype_version
    solo_model.productaanvraag_type = objects_api_group.productaanvraag_type
    solo_model.informatieobjecttype_submission_report = (
        objects_api_group.informatieobjecttype_submission_report
    )
    solo_model.informatieobjecttype_submission_csv = (
        objects_api_group.informatieobjecttype_submission_csv
    )
    solo_model.informatieobjecttype_attachment = (
        objects_api_group.informatieobjecttype_attachment
    )
    solo_model.organisatie_rsin = objects_api_group.organisatie_rsin
    solo_model.organisatie_rsin = objects_api_group.organisatie_rsin
    solo_model.content_json = objects_api_group.content_json
    solo_model.payment_status_update_json = objects_api_group.payment_status_update_json
    solo_model.save()


class Migration(migrations.Migration):

    dependencies = [
        ("registrations_objects_api", "0016_objectsapigroupconfig"),
    ]

    operations = [
        migrations.RunPython(
            move_singleton_data_to_objects_api_set_model,
            reconfigure_objects_api_solo_model,
        ),
    ]
