# Generated by Django 4.2.11 on 2024-05-27 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("registrations_objects_api", "0016_objectsapigroupconfig"),
    ]

    # RunPython operation removed as part of the 2.8.0 release cycle
    operations = []
