# Generated by Django 4.2.11 on 2024-05-31 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("registrations_objects_api", "0017_move_singleton_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="objectsapiconfig",
            name="catalogi_service",
        ),
        migrations.RemoveField(
            model_name="objectsapiconfig",
            name="drc_service",
        ),
        migrations.RemoveField(
            model_name="objectsapiconfig",
            name="informatieobjecttype_attachment",
        ),
        migrations.RemoveField(
            model_name="objectsapiconfig",
            name="informatieobjecttype_submission_csv",
        ),
        migrations.RemoveField(
            model_name="objectsapiconfig",
            name="informatieobjecttype_submission_report",
        ),
        migrations.RemoveField(
            model_name="objectsapiconfig",
            name="objects_service",
        ),
        migrations.RemoveField(
            model_name="objectsapiconfig",
            name="objecttype",
        ),
        migrations.RemoveField(
            model_name="objectsapiconfig",
            name="objecttype_version",
        ),
        migrations.RemoveField(
            model_name="objectsapiconfig",
            name="objecttypes_service",
        ),
        migrations.RemoveField(
            model_name="objectsapiconfig",
            name="organisatie_rsin",
        ),
    ]
