# Generated by Django 4.2.11 on 2024-05-27 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("registrations_objects_api", "0017_move_singleton_data"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="objectsapiconfig",
            options={"verbose_name": "Objects APIs configuration"},
        ),
        migrations.RemoveField(
            model_name="objectsapiconfig",
            name="catalogi_service",
        ),
        migrations.RemoveField(
            model_name="objectsapiconfig",
            name="content_json",
        ),
        migrations.RemoveField(
            model_name="objectsapiconfig",
            name="drc_service",
        ),
        migrations.RemoveField(
            model_name="objectsapiconfig",
            name="informatieobjecttype_attachment",
        ),
        migrations.RemoveField(
            model_name="objectsapiconfig",
            name="informatieobjecttype_submission_csv",
        ),
        migrations.RemoveField(
            model_name="objectsapiconfig",
            name="informatieobjecttype_submission_report",
        ),
        migrations.RemoveField(
            model_name="objectsapiconfig",
            name="objects_service",
        ),
        migrations.RemoveField(
            model_name="objectsapiconfig",
            name="objecttype",
        ),
        migrations.RemoveField(
            model_name="objectsapiconfig",
            name="objecttype_version",
        ),
        migrations.RemoveField(
            model_name="objectsapiconfig",
            name="objecttypes_service",
        ),
        migrations.RemoveField(
            model_name="objectsapiconfig",
            name="organisatie_rsin",
        ),
        migrations.RemoveField(
            model_name="objectsapiconfig",
            name="payment_status_update_json",
        ),
        migrations.RemoveField(
            model_name="objectsapiconfig",
            name="productaanvraag_type",
        ),
        migrations.AddField(
            model_name="objectsapiconfig",
            name="default_objects_api_group",
            field=models.ForeignKey(
                help_text="Which Objects API group should be used by default.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="registrations_objects_api.objectsapigroupconfig",
                verbose_name="default Objects API group.",
            ),
        ),
    ]
