# Generated by Django 4.2.11 on 2024-07-02 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "registrations_objects_api",
            "0018_remove_objectsapiconfig_catalogi_service_and_more",
        ),
        (
            "forms",
            "0097_v267_to_v270",
        ),
    ]

    # RunPython operation removed as part of the 2.8.0 release cycle
    operations = []
