# Generated by Django 4.2.14 on 2024-08-01 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "registrations_objects_api",
            "0021_objectsapigroupconfig_catalogue_domain_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="objectsapigroupconfig",
            name="iot_attachment",
            field=models.CharField(
                blank=True,
                help_text=(
                    "Description of the document type in the Catalogi API to be used for the "
                    "submission attachments (i.e. the INFORMATIEOBJECTTYPE.omschrijving "
                    "attribute). The appropriate version will automatically be selected based "
                    "on the submission timestamp and validity dates of the "
                    "document type versions."
                ),
                max_length=80,
                verbose_name="attachment document type description",
            ),
        ),
        migrations.AddField(
            model_name="objectsapigroupconfig",
            name="iot_submission_csv",
            field=models.CharField(
                blank=True,
                help_text=(
                    "Description of the document type in the Catalogi API to be used for the "
                    "submission report CSV (i.e. the INFORMATIEOBJECTTYPE.omschrijving "
                    "attribute). The appropriate version will automatically be selected based "
                    "on the submission timestamp and validity dates of the "
                    "document type versions."
                ),
                max_length=80,
                verbose_name="submission report CSV document type description",
            ),
        ),
        migrations.AddField(
            model_name="objectsapigroupconfig",
            name="iot_submission_report",
            field=models.CharField(
                blank=True,
                help_text=(
                    "Description of the document type in the Catalogi API to be used for the "
                    "submission report PDF (i.e. the INFORMATIEOBJECTTYPE.omschrijving "
                    "attribute). The appropriate version will automatically be selected based "
                    "on the submission timestamp and validity dates of the "
                    "document type versions."
                ),
                max_length=80,
                verbose_name="submission report document type description",
            ),
        ),
        migrations.AddConstraint(
            model_name="objectsapigroupconfig",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("iot_submission_report", ""),
                    models.Q(
                        models.Q(("iot_submission_report", ""), _negated=True),
                        models.Q(("catalogue_domain", ""), _negated=True),
                        models.Q(("catalogue_rsin", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="iot_report_requires_catalogue",
                violation_error_message="You must specify a catalogue when specifying the submission report PDF document type.",
            ),
        ),
        migrations.AddConstraint(
            model_name="objectsapigroupconfig",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("iot_submission_csv", ""),
                    models.Q(
                        models.Q(("iot_submission_csv", ""), _negated=True),
                        models.Q(("catalogue_domain", ""), _negated=True),
                        models.Q(("catalogue_rsin", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="iot_csv_requires_catalogue",
                violation_error_message="You must specify a catalogue when specifying the submission report CSV document type.",
            ),
        ),
        migrations.AddConstraint(
            model_name="objectsapigroupconfig",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("iot_attachment", ""),
                    models.Q(
                        models.Q(("iot_attachment", ""), _negated=True),
                        models.Q(("catalogue_domain", ""), _negated=True),
                        models.Q(("catalogue_rsin", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="iot_attachment_requires_catalogue",
                violation_error_message="You must specify a catalogue when specifying the submission attachment document type.",
            ),
        ),
    ]
