# Generated by Django 4.2.14 on 2024-08-05 07:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "registrations_objects_api",
            "0022_objectsapigroupconfig_iot_attachment_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="objectsapigroupconfig",
            name="catalogue_domain",
            field=models.CharField(
                blank=True,
                help_text="The 'domein' attribute for the Catalogus resource in the Catalogi API.",
                max_length=5,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[A-Z]*$",
                        code="invalid",
                        message="Value must be all uppercase letters.",
                    )
                ],
                verbose_name="catalogus domain",
            ),
        ),
    ]
