# Generated by Django 4.2.21 on 2025-06-03 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_org_oidc', '0001_initial'),
        ('oidc_plugins', '0002_move_data_oidc_config'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrgOpenIDConnectConfig',
        ),
    ]
