# Generated by Django 3.2.21 on 2023-09-21 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bag", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BAGConfig",
        ),
    ]
