# Generated by Django 4.2.27 on 2026-01-22 15:17

from django.db import migrations, models

import privates.fields
import privates.storages

import openforms.translations.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TranslationsMetaData",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language_code",
                    models.CharField(
                        choices=[("nl", "Nederlands"), ("en", "English")],
                        help_text="Selected language.",
                        max_length=10,
                        verbose_name="language",
                    ),
                ),
                (
                    "messages_file",
                    privates.fields.PrivateMediaFileField(
                        blank=True,
                        help_text="JSON file containing user's custom translations.",
                        storage=privates.storages.PrivateMediaFileSystemStorage(),
                        upload_to="messages/uploaded/%Y/%m/%d",
                        verbose_name="messages JSON file",
                    ),
                ),
                (
                    "compiled_asset",
                    privates.fields.PrivateMediaFileField(
                        editable=False,
                        help_text="JSON file containing user's custom translations after it has been successfully compiled.",
                        storage=privates.storages.PrivateMediaFileSystemStorage(),
                        upload_to="messages/compiled/%Y/%m/%d",
                        verbose_name="compiled translations JSON file",
                    ),
                ),
                (
                    "processing_status",
                    models.CharField(
                        choices=[
                            ("in_progress", "In progress"),
                            ("pending", "Pending"),
                            ("done", "Done"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        help_text="The status of the uploaded custom translations JSON file.",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "debug_output",
                    models.TextField(
                        blank=True,
                        help_text="The output from the processing phase, useful for debugging purposes.",
                        verbose_name="output from the processing phase",
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        blank=True,
                        help_text="Keeps track of the last successful processing of the uploaded file. Useful for understanding since when the custom translations are active.",
                        null=True,
                        verbose_name="last updated",
                    ),
                ),
                (
                    "messages_count",
                    models.IntegerField(
                        blank=True,
                        editable=False,
                        help_text="How many custom messages are included, this is set once processing completes successfully.",
                        null=True,
                        verbose_name="number of custom messages",
                    ),
                ),
                (
                    "app_release",
                    models.CharField(
                        blank=True,
                        default=openforms.translations.models.get_app_release,
                        editable=False,
                        help_text="App release/version at the time the messages were added, updated or activated.",
                        max_length=50,
                        verbose_name="application version",
                    ),
                ),
            ],
            options={
                "verbose_name": "translation metadata",
                "verbose_name_plural": "translation metadata",
            },
        ),
    ]
