# Generated by Django 4.2.27 on 2026-02-02 14:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("of_translations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="translationsmetadata",
            name="language_code",
            field=models.CharField(
                choices=[("nl", "Nederlands"), ("en", "English")],
                help_text="Selected language.",
                max_length=10,
                unique=True,
                verbose_name="language",
            ),
        ),
    ]
