# Generated by Django 5.2.14 on 2026-05-15 20:47

from django.db import migrations

import privates.fields


class Migration(migrations.Migration):
    dependencies = [
        ("of_translations", "0002_alter_translationsmetadata_language_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="translationsmetadata",
            name="compiled_asset",
            field=privates.fields.PrivateMediaFileField(
                editable=False,
                help_text="JSON file containing user's custom translations after it has been successfully compiled.",
                upload_to="messages/compiled/%Y/%m/%d",
                verbose_name="compiled translations JSON file",
            ),
        ),
        migrations.AlterField(
            model_name="translationsmetadata",
            name="messages_file",
            field=privates.fields.PrivateMediaFileField(
                blank=True,
                help_text="JSON file containing user's custom translations.",
                upload_to="messages/uploaded/%Y/%m/%d",
                verbose_name="messages JSON file",
            ),
        ),
    ]
