# Generated by Django 3.2.16 on 2022-11-24 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("custom_field_types", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="familymemberstypeconfig",
            table="custom_field_types_familymemberstypeconfig",
        ),
    ]
