# Generated by Django 3.2.16 on 2022-11-24 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("custom_field_types", "0002_alter_familymemberstypeconfig_table"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name="FamilyMembersTypeConfig",
                ),
            ],
            database_operations=[],
        ),
    ]
