# Generated by Django 3.2.20 on 2023-09-11 13:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stuf", "0001_initial_pre_openforms_v230"),
    ]

    operations = [
        migrations.CreateModel(
            name="StufZDSConfig",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gemeentecode",
                    models.CharField(
                        help_text="Municipality code to register zaken",
                        max_length=4,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Expected a numerical value.", regex="^[0-9]+$"
                            )
                        ],
                        verbose_name="Municipality code",
                    ),
                ),
                (
                    "service",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stuf_zds_config",
                        to="stuf.stufservice",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "verbose_name": "StUF-ZDS configuration",
            },
        ),
    ]
