# Generated by Django 2.2.20 on 2021-05-27 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("stuf", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StufZDSConfig",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gemeentecode",
                    models.CharField(
                        max_length=32, verbose_name="Gemeentecode to register Zaken"
                    ),
                ),
                (
                    "zds_zaaktype_code",
                    models.CharField(
                        max_length=32,
                        verbose_name="Zaaktype code for newly created Zaken in StUF-ZDS",
                    ),
                ),
                (
                    "zds_zaaktype_omschrijving",
                    models.CharField(
                        max_length=32,
                        verbose_name="Zaaktype description for newly created Zaken in StUF-ZDS",
                    ),
                ),
                (
                    "service",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stuf_zds_config",
                        to="stuf.SoapService",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
