# Generated by Django 4.2.11 on 2024-04-03 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stuf_zds", "0001_initial_to_openforms_v230"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stufzdsconfig",
            name="gemeentecode",
        ),
    ]
