# Generated by Django 4.2.21 on 2025-06-25 04:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stuf_zds", "0002_remove_stufzdsconfig_gemeentecode"),
    ]

    operations = [
        migrations.AddField(
            model_name="stufzdsconfig",
            name="zaakbetrokkene_partners_omschrijving",
            field=models.CharField(
                blank=True,
                default="",
                help_text="The description that will be added if the zaakbetrokkene registration is used for the partners.",
                max_length=100,
                verbose_name="description for zaakbetrokkene partners registration",
            ),
        ),
    ]
