# Generated by Django 4.2.23 on 2025-07-01 10:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stuf_zds", "0003_stufzdsconfig_zaakbetrokkene_partners_omschrijving"),
    ]

    operations = [
        migrations.AddField(
            model_name="stufzdsconfig",
            name="zaakbetrokkene_cosigner_omschrijving",
            field=models.CharField(
                blank=True,
                default="mede_initiator",
                help_text="The 'zaakbetrokkene.omschrijving' value for the person who cosigned the form submission.",
                max_length=100,
                verbose_name="description for registrator zaakbetrokkene",
            ),
        ),
        migrations.AddField(
            model_name="stufzdsconfig",
            name="zaakbetrokkene_registrator_omschrijving",
            field=models.CharField(
                blank=True,
                default="",
                help_text="The 'zaakbetrokkene.omschrijving' value for the employee who registers the case on behalf of the customer.",
                max_length=100,
                verbose_name="description for registrator zaakbetrokkene",
            ),
        ),
        migrations.AlterField(
            model_name="stufzdsconfig",
            name="zaakbetrokkene_partners_omschrijving",
            field=models.CharField(
                blank=True,
                default="",
                help_text="The 'zaakbetrokkene.omschrijving' value for when the partners of the form submitter are registered as 'betrokkene'.",
                max_length=100,
                verbose_name="description for zaakbetrokkene partners registration",
            ),
        ),
    ]
