# Generated by Django 2.2.24 on 2021-07-22 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stuf_zds", "0004_auto_20210624_2028"),
    ]

    operations = [
        migrations.AddField(
            model_name="stufzdsconfig",
            name="zds_zaaktype_status_omschrijving",
            field=models.CharField(
                default="",
                help_text="Zaaktype status omschrijving for newly created zaken in StUF-ZDS",
                max_length=80,
                verbose_name="Zaaktype status omschrijving",
            ),
            preserve_default=False,
        ),
    ]
