# Generated by Django 4.2.23 on 2025-09-08 11:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "stuf_zds",
            "0004_stufzdsconfig_zaakbetrokkene_cosigner_omschrijving_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="stufzdsconfig",
            name="zaakbetrokkene_children_omschrijving",
            field=models.CharField(
                blank=True,
                default="",
                help_text="The 'zaakbetrokkene.omschrijving' value for when the children of the form submitter are registered as 'betrokkene'.",
                max_length=100,
                verbose_name="description for zaakbetrokkene children registration",
            ),
        ),
    ]
