# Generated by Django 4.2.27 on 2025-12-24 17:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments_ogone", "0004_alter_ogonewebhookconfiguration_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorldlineMerchant",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Human readable label",
                        max_length=255,
                        verbose_name="Label",
                    ),
                ),
                (
                    "pspid",
                    models.CharField(
                        help_text="Worldline PSPID",
                        max_length=255,
                        unique=True,
                        verbose_name="PSPID",
                    ),
                ),
                (
                    "api_key",
                    models.CharField(
                        help_text="API Key created for the specified PSPID",
                        max_length=255,
                        verbose_name="API Key",
                    ),
                ),
                (
                    "api_secret",
                    models.CharField(
                        help_text="API Secret created for the specified PSPID",
                        max_length=255,
                        verbose_name="API Secret",
                    ),
                ),
                (
                    "endpoint",
                    models.URLField(
                        choices=[
                            (
                                "https://payment.preprod.direct.worldline-solutions.com",
                                "Worldline Test",
                            ),
                            (
                                "https://payment.direct.worldline-solutions.com",
                                "Worldline Live",
                            ),
                        ],
                        default="https://payment.preprod.direct.worldline-solutions.com",
                        help_text="Select a common preset endpoint",
                        verbose_name="Preset endpoint",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WorldlineWebhookConfiguration",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "webhook_key_id",
                    models.CharField(
                        default="", max_length=255, verbose_name="Webhook Key ID"
                    ),
                ),
                (
                    "webhook_key_secret",
                    models.CharField(
                        default="", max_length=255, verbose_name="Webhook Key Secret"
                    ),
                ),
                (
                    "pspid",
                    models.CharField(
                        help_text="Worldline PSPID",
                        max_length=255,
                        unique=True,
                        verbose_name="PSPID",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "verbose_name": "Worldline webhook configuration",
                "verbose_name_plural": "Worldline webhook configurations",
            },
        ),
    ]
