# Generated by Django 4.2.23 on 2025-07-22 09:59

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WorldlineMerchant",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Human readable label",
                        max_length=255,
                        verbose_name="Label",
                    ),
                ),
                (
                    "pspid",
                    models.CharField(
                        help_text="Worldline PSPID",
                        max_length=255,
                        verbose_name="PSPID",
                    ),
                ),
                (
                    "api_key",
                    models.CharField(
                        help_text="API Key created for the specified PSPID",
                        max_length=255,
                        verbose_name="API Key",
                    ),
                ),
                (
                    "api_secret",
                    models.CharField(
                        help_text="API Secret created for the specified PSPID",
                        max_length=255,
                        verbose_name="API Secret",
                    ),
                ),
                (
                    "endpoint_preset",
                    models.URLField(
                        choices=[
                            (
                                "https://payment.preprod.direct.worldline-solutions.com/v2/",
                                "Worldline Test",
                            ),
                            (
                                "https://payment.direct.worldline-solutions.com/v2/",
                                "Worldline Live",
                            ),
                        ],
                        default="https://payment.preprod.direct.worldline-solutions.com/v2/",
                        help_text="Select a common preset endpoint",
                        verbose_name="Preset endpoint",
                    ),
                ),
                (
                    "endpoint_custom",
                    models.URLField(
                        blank=True,
                        help_text="Optionally override the preset endpoint",
                        verbose_name="Custom endpoint",
                    ),
                ),
            ],
        ),
    ]
