# Generated by Django 4.2.23 on 2025-07-29 11:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments_worldline", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="worldlinemerchant",
            name="endpoint_preset",
            field=models.URLField(
                choices=[
                    (
                        "https://payment.preprod.direct.worldline-solutions.com",
                        "Worldline Test",
                    ),
                    (
                        "https://payment.direct.worldline-solutions.com",
                        "Worldline Live",
                    ),
                ],
                default="https://payment.preprod.direct.worldline-solutions.com",
                help_text="Select a common preset endpoint",
                verbose_name="Preset endpoint",
            ),
        ),
    ]
