# Generated by Django 4.2.23 on 2025-07-31 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments_worldline", "0002_alter_worldlinemerchant_endpoint_preset"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorldlineAccount",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "webhook_key_id",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        unique=True,
                        verbose_name="Webhook Key ID",
                    ),
                ),
                (
                    "webhook_key_secret",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Webhook Key Secret"
                    ),
                ),
            ],
        ),
    ]
