# Generated by Django 4.2.23 on 2025-08-01 08:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("payments_worldline", "0002_alter_worldlinemerchant_endpoint_preset"),
    ]

    operations = [
        migrations.RenameField(
            model_name="worldlinemerchant",
            old_name="endpoint_preset",
            new_name="endpoint",
        ),
        migrations.RemoveField(
            model_name="worldlinemerchant",
            name="endpoint_custom",
        ),
    ]
