# Generated by Django 4.2.23 on 2025-08-05 12:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments_worldline", "0004_alter_worldlinemerchant_pspid"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorldlineWebhookEntry",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "webhook_key_id",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Webhook Key ID"
                    ),
                ),
                (
                    "webhook_key_secret",
                    models.CharField(max_length=255, verbose_name="Webhook Key Secret"),
                ),
            ],
            options={
                "verbose_name_plural": "Worldline webhook entries",
            },
        ),
    ]
