# Generated by Django 4.2.23 on 2025-08-08 08:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments_worldline", "0005_worldlinewebhookentry"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorldlineWebhookConfiguration",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "webhook_key_id",
                    models.CharField(
                        default="", max_length=255, verbose_name="Webhook Key ID"
                    ),
                ),
                (
                    "webhook_key_secret",
                    models.CharField(
                        default="", max_length=255, verbose_name="Webhook Key Secret"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.DeleteModel(
            name="WorldlineWebhookEntry",
        ),
    ]
