# Generated by Django 4.2.25 on 2025-10-28 18:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments_worldline", "0007_migrate_ogone_to_worldline"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="worldlinewebhookconfiguration",
            options={
                "verbose_name": "Worldline webhook configuration",
                "verbose_name_plural": "Worldline webhook configurations",
            },
        ),
        migrations.AddField(
            model_name="worldlinewebhookconfiguration",
            name="pspid",
            field=models.CharField(
                default="(ONBEKEND)",
                help_text="Worldline PSPID",
                max_length=255,
                unique=True,
                verbose_name="PSPID",
            ),
            preserve_default=False,
        ),
    ]
