# Generated by Django 3.2.20 on 2023-09-11 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("soap", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="JccConfig",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="soap.soapservice",
                    ),
                ),
            ],
            options={
                "verbose_name": "JCC configuration",
            },
        ),
    ]
