# Generated by Django 5.2.13 on 2026-05-12 09:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("jcc", "0001_initial_to_openforms_v230"),
    ]

    operations = [
        migrations.DeleteModel(
            name="JccConfig",
        ),
    ]
