# Generated by Django 3.2.20 on 2023-07-18 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("soap", "0001_initial"),
        ("jcc", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jccconfig",
            name="service",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="soap.soapservice",
            ),
        )
    ]
