# Generated by Django 3.2.20 on 2023-07-26 10:16

import django.db.models.deletion
from django.db import migrations, models

import openforms.utils.validators


class Migration(migrations.Migration):
    dependencies = [
        ("soap", "0001_initial"),
        ("jcc", "0002_alter_jccconfig_service"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jccconfig",
            name="service",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="soap.soapservice",
                validators=[openforms.utils.validators.validate_service_url_not_empty],
            ),
        ),
    ]
