# Generated by Django 3.2.20 on 2023-08-04 15:55

from django.db import migrations, models

import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ("jcc", "0002_alter_jccconfig_service"),
    ]

    operations = [
        migrations.AddField(
            model_name="jccconfig",
            name="required_customer_fields",
            field=django_better_admin_arrayfield.models.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("Address", "Address"),
                        ("Birthday", "Birthday"),
                        ("City", "City"),
                        ("Email", "Email address"),
                        ("Initials", "Initials"),
                        ("Sex", "Sex"),
                        ("MainTel", "Main phone number"),
                        ("MobileTel", "Mobile phone number"),
                        ("AnyTel", "AnyTel"),
                        ("PostalCode", "Postal code"),
                        ("ID", "ID"),
                    ],
                    max_length=50,
                ),
                blank=True,
                default=list,
                help_text="Preferably, customer fields should be marked as required in JCC. However, if that is not an option, you can add fields here to mark as required. Note that you can only mark optional fields as required, not the other way around.",
                size=None,
                verbose_name="Override JCC optional fields",
            ),
        ),
    ]
