# Generated by Django 2.2.24 on 2021-11-12 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("microsoft", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="msgraphservice",
            options={
                "ordering": ("label", "tenant_id"),
                "verbose_name": "Microsoft Graph Service",
            },
        ),
        migrations.AlterField(
            model_name="msgraphservice",
            name="client_id",
            field=models.CharField(
                help_text="Client ID, in GUID format (sometimes called App ID or Application ID)",
                max_length=64,
                verbose_name="client ID",
            ),
        ),
        migrations.AlterField(
            model_name="msgraphservice",
            name="tenant_id",
            field=models.CharField(
                help_text="Tenant ID, in GUID format",
                max_length=64,
                verbose_name="tenant ID",
            ),
        ),
    ]
