# Generated by Django 4.2.10 on 2024-02-22 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("microsoft", "0003_auto_20211210_1804"),
    ]

    operations = [
        migrations.AddField(
            model_name="msgraphservice",
            name="timeout",
            field=models.PositiveSmallIntegerField(
                default=10,
                help_text="Timeout (in seconds) for HTTP calls.",
                verbose_name="timeout",
            ),
        ),
    ]
