<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2019 rel. 3 (x64) (http://www.altova.com) by Shinta Hadiutomo (BKWI) -->
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:smls="http://bkwi.nl/SuwiML/Diensten/KadasterDossierGSD/v0300" targetNamespace="http://bkwi.nl/SuwiML/Diensten/KadasterDossierGSD/v0300">
	<wsdl:import namespace="http://bkwi.nl/SuwiML/Diensten/KadasterDossierGSD/v0300" location="../KadasterDossierGSD.wsdl"/>
	<wsdl:service name="KadasterDossierGSD-v0300">
		<wsdl:port name="BrokerProductie" binding="smls:KadasterBinding">
			<soap:address location="https://broker.prd.suwi.net/suwibroker/soap/KadasterDossierGSD-v0300"/>
		</wsdl:port>
		<wsdl:port name="BrokerIntegratietest" binding="smls:KadasterBinding">
			<soap:address location="https://broker.tst.suwi.net/suwibroker/soap/KadasterDossierGSD-v0300"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>
