# Generated by Django 2.2.16 on 2020-09-21 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formdefinition',
            options={'verbose_name': 'Formulier definitie', 'verbose_name_plural': 'Form definities'},
        ),
        migrations.AddField(
            model_name='formdefinition',
            name='scheme_url',
            field=models.URLField(blank=True, help_text='Indien ingevuld word deze URL gebruikt voor de JSON representatie.', null=True, verbose_name='Schema URL'),
        ),
        migrations.AlterField(
            model_name='formdefinition',
            name='login_required',
            field=models.BooleanField(default=False, help_text='Geef aan of een DigID Login vereist is.'),
        ),
    ]
