# Generated by Django 2.2.16 on 2020-09-25 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_delete_formsubmission"),
    ]

    operations = [
        migrations.AddField(
            model_name="form",
            name="backend",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
