# Generated by Django 2.2.16 on 2020-09-25 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_delete_formsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='backend',
            field=models.CharField(blank=True, choices=[('openforms.core.backends.console_backend', 'console_backend'), ('openforms.core.backends.create_zaak_backend', 'create_zaak_backend')], max_length=100),
        ),
    ]
