# Generated by Django 2.2.16 on 2020-12-03 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_form_product"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="formstep",
            options={"verbose_name": "form step", "verbose_name_plural": "form steps"},
        ),
        migrations.AddField(
            model_name="formstep",
            name="availability_strategy",
            field=models.CharField(
                choices=[
                    ("always", "Always"),
                    ("after_previous_step", "If previous step is completed"),
                ],
                default="always",
                help_text="Availability strategy to use. A step must be available before it can be filled out. Note that this is not validated (yet) during step submission.",
                max_length=50,
                verbose_name="availability",
            ),
        ),
        migrations.AddField(
            model_name="formstep",
            name="optional",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether this step is an optional step in the form. Currently used for form-rendering purposes, this is not (yet) used for validation purposes.",
                verbose_name="optional",
            ),
        ),
    ]
