# Generated by Django 2.2.16 on 2020-09-23 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FormSubmission",
        ),
    ]
