# Generated by Django 2.2.24 on 2021-09-17 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0001_initial_squashed_0037_merge_20210903_1213"),
    ]

    operations = [
        migrations.AddField(
            model_name="form",
            name="internal_name",
            field=models.CharField(
                blank=True,
                help_text="internal name for management purposes",
                max_length=50,
                verbose_name="internal name",
            ),
        ),
        migrations.AddField(
            model_name="formdefinition",
            name="internal_name",
            field=models.CharField(
                blank=True,
                help_text="internal name for management purposes",
                max_length=50,
                verbose_name="internal name",
            ),
        ),
    ]
