# Generated by Django 2.2.24 on 2021-09-10 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0001_initial_squashed_0037_merge_20210903_1213"),
    ]

    operations = [
        migrations.RenameField(
            model_name="formdefinition",
            old_name="name",
            new_name="public_name",
        ),
    ]
