# Generated by Django 2.2.24 on 2021-09-10 09:45

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0002_formdefinition_public_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="formdefinition",
            name="internal_name",
            field=models.CharField(
                blank=True,
                help_text="Optional alternate name for internal identification, not visible to end-users",
                max_length=50,
                verbose_name="internal name",
            ),
        ),
        migrations.AlterField(
            model_name="formdefinition",
            name="public_name",
            field=models.CharField(
                help_text="Visible to end-user. Can be overridden per form-step.",
                max_length=50,
                verbose_name="public name",
            ),
        ),
        migrations.AlterField(
            model_name="formdefinition",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                editable=True,
                max_length=100,
                populate_from="public_name",
                unique=True,
                verbose_name="slug",
            ),
        ),
    ]
