# Generated by Django 2.2.24 on 2021-09-30 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0002_auto_20210917_1114"),
    ]

    operations = [
        migrations.AlterField(
            model_name="form",
            name="internal_name",
            field=models.CharField(
                blank=True,
                help_text="internal name for management purposes",
                max_length=150,
                verbose_name="internal name",
            ),
        ),
        migrations.AlterField(
            model_name="form",
            name="name",
            field=models.CharField(max_length=150, verbose_name="name"),
        ),
    ]
