# Generated by Django 2.2.24 on 2021-09-10 12:25

from django.db import migrations, models

import autoslug.fields


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0004_form_public_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="form",
            name="internal_name",
            field=models.CharField(
                blank=True,
                help_text="Optional alternate name for internal identification, not visible to end-users",
                max_length=50,
                verbose_name="internal name",
            ),
        ),
        migrations.AlterField(
            model_name="form",
            name="public_name",
            field=models.CharField(
                help_text="Visible to end-user.",
                max_length=50,
                verbose_name="public name",
            ),
        ),
        migrations.AlterField(
            model_name="form",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                editable=True,
                max_length=100,
                populate_from="public_name",
                unique=True,
                verbose_name="slug",
            ),
        ),
    ]
