# Generated by Django 2.2.16 on 2021-04-02 12:08
import json

from django.db import migrations


def transform_from_str_to_object(apps, schema_editor):
    FormDefinition = apps.get_model("forms", "FormDefinition")
    for form_definition in FormDefinition.objects.all():
        # it already is a proper object
        if not isinstance(form_definition.configuration, str):
            continue

        configuration = json.loads(form_definition.configuration)
        assert isinstance(
            configuration, dict
        ), f"Expected object, not {type(configuration)}"
        form_definition.configuration = configuration
        form_definition.save()


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0006_auto_20201203_1557"),
    ]

    operations = [
        migrations.RunPython(transform_from_str_to_object, migrations.RunPython.noop),
    ]
