# Generated by Django 2.2.16 on 2021-04-02 12:28

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0007_fix_formdefinition_configuration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formdefinition",
            name="configuration",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                help_text="The form definition as Formio.js JSON schema",
                verbose_name="Formio.js configuration",
            ),
        ),
    ]
