# Generated by Django 2.2.25 on 2021-12-13 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0007_form_explanation_template"),
    ]

    operations = [
        migrations.AddField(
            model_name="form",
            name="submission_allowed",
            field=models.CharField(
                default="yes",
                choices=[
                    ("yes", "Yes"),
                    (
                        "no_with_overview",
                        "No (with overview page)",
                    ),
                    (
                        "no_without_overview",
                        "No (without overview page)",
                    ),
                ],
                help_text="Whether the user is allowed to submit this form or not, and whether the overview page should be shown if they are not.",
                max_length=100,
                verbose_name="submission allowed",
            ),
        ),
    ]
