# Generated by Django 2.2.24 on 2021-12-07 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0007_form_explanation_template"),
        ("forms", "0006_form_auto_login_authentication_backend"),
    ]

    operations = []
