# Generated by Django 2.2.25 on 2021-12-16 15:39

from django.db import migrations

import tinymce.models

import openforms.utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0007_form_explanation_template"),
    ]

    operations = [
        migrations.AlterField(
            model_name="form",
            name="submission_confirmation_template",
            field=tinymce.models.HTMLField(
                blank=True,
                help_text="The content of the submission confirmation page. It can contain variables that will be templated from the submitted form data. If not specified, the global template will be used.",
                validators=[openforms.utils.validators.DjangoTemplateValidator()],
                verbose_name="submission confirmation template",
            ),
        ),
    ]
