# Generated by Django 2.2.20 on 2021-04-26 16:02

import django.contrib.postgres.fields.jsonb
from django.db import migrations

import openforms.registrations.fields


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0008_auto_20210402_1428"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="form",
            name="backend",
        ),
        migrations.AddField(
            model_name="form",
            name="registration_backend",
            field=openforms.registrations.fields.BackendChoiceField(
                blank=True, max_length=100, verbose_name="registration backend"
            ),
        ),
        migrations.AddField(
            model_name="form",
            name="registration_backend_options",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, default=dict, null=True
            ),
        ),
    ]
