# Generated by Django 2.2.19 on 2021-05-03 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0009_auto_20210426_1802"),
    ]

    operations = [
        migrations.AddField(
            model_name="form",
            name="email_property_name",
            field=models.CharField(
                blank=True,
                help_text="The name of the attribute in the submission data that contains the email address to which the confirmation email will be sent. If not specified, `email` will be used.",
                max_length=200,
            ),
        ),
    ]
