# Generated by Django 2.2.25 on 2021-12-13 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0009_transfer_can_submit"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="form",
            name="can_submit",
        ),
    ]
