# Generated by Django 2.2.25 on 2021-12-16 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0010_remove_form_can_submit"),
    ]

    operations = [
        migrations.AddField(
            model_name="formlogic",
            name="is_advanced",
            field=models.BooleanField(
                default=False,
                help_text="Is this an advanced rule (the admin user manually wrote the trigger as JSON)?",
                verbose_name="is advanced",
            ),
        ),
    ]
