# Generated by Django 2.2.20 on 2021-05-07 07:58

from django.db import migrations

import autoslug.fields


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0010_auto_20210506_1236"),
    ]

    operations = [
        migrations.AlterField(
            model_name="form",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                editable=True, max_length=100, populate_from="name", unique=True
            ),
        ),
    ]
