# Generated by Django 2.2.25 on 2021-12-22 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0008_auto_20211216_1639"),
        ("forms", "0011_formlogic_is_advanced"),
    ]

    operations = []
