# Generated by Django 2.2.20 on 2021-05-07 09:36

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0011_auto_20210507_0958"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formdefinition",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                editable=True, max_length=100, populate_from="name", unique=True
            ),
        ),
    ]
