# Generated by Django 2.2.20 on 2021-05-07 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0011_auto_20210507_0958'),
        ('forms', '0009_form__is_deleted'),
    ]

    operations = [
    ]
