# Generated by Django 2.2.25 on 2021-12-20 16:55

from django.db import migrations

from openforms.forms.utils import iter_components


def remove_html5_widget_from_forms(apps, schema_editor):
    FormDefinition = apps.get_model("forms", "FormDefinition")

    form_definitions = FormDefinition.objects.all()
    for form_definition in form_definitions:
        for component in iter_components(form_definition.configuration):
            if component["type"] == "select" and component["widget"] == "html5":
                component["widget"] = "choicesjs"

    FormDefinition.objects.bulk_update(form_definitions, ["configuration"])


def backward_function(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0012_merge_20211222_0831"),
    ]

    operations = [
        migrations.RunPython(remove_html5_widget_from_forms, backward_function),
    ]
