# Generated by Django 2.2.20 on 2021-05-12 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0010_form_email_property_name"),
        ("forms", "0012_merge_20210507_1158"),
    ]

    operations = []
