# Generated by Django 2.2.20 on 2021-05-07 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0012_auto_20210507_1136'),
        ('forms', '0012_merge_20210507_1158'),
    ]

    operations = [
    ]
