# Generated by Django 2.2.25 on 2022-01-03 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0011_merge_20211220_1029"),
        ("forms", "0013_auto_20211220_1755"),
    ]

    operations = []
