# Generated by Django 2.2.20 on 2021-05-14 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0014_auto_20210512_1304"),
        ("forms", "0013_merge_20210512_1022"),
    ]

    operations = []
