# Generated by Django 2.2.26 on 2022-01-14 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0014_file_component"),
        ("forms", "0014_merge_20220103_1539"),
    ]

    operations = []
