# Generated by Django 2.2.26 on 2022-01-14 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0014_file_component"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="formstep",
            options={
                "ordering": ("order",),
                "verbose_name": "form step",
                "verbose_name_plural": "form steps",
            },
        ),
    ]
