# Generated by Django 2.2.26 on 2022-01-18 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0015_auto_20220114_1006"),
        ("forms", "0015_merge_20220114_1201"),
    ]

    operations = []
