# Generated by Django 2.2.26 on 2022-02-01 11:13

from django.db import migrations

import tinymce.models

import csp_post_processor.fields


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0015_auto_20220114_1006"),
    ]

    operations = [
        migrations.AlterField(
            model_name="form",
            name="explanation_template",
            field=csp_post_processor.fields.CSPPostProcessedWYSIWYGField(
                base_field=tinymce.models.HTMLField(
                    blank=True,
                    help_text="Content that will be shown on the start page of the form, below the title and above the log in text.",
                    verbose_name="explanation template",
                ),
                blank=True,
                help_text="Content that will be shown on the start page of the form, below the title and above the log in text.",
                verbose_name="explanation template",
            ),
        ),
    ]
