# Generated by Django 2.2.20 on 2021-05-14 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0015_merge_20210514_1410"),
    ]

    operations = [
        migrations.AlterField(
            model_name="form",
            name="email_property_name",
            field=models.CharField(
                blank=True,
                help_text="The name of the attribute in the submission data that contains the email address to which the confirmation email will be sent. If not specified, `email` will be used.",
                max_length=200,
                verbose_name="veldnaam e-mailadres",
            ),
        ),
    ]
