# Generated by Django 2.2.20 on 2021-05-14 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0016_auto_20210514_1505"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="form",
            options={"verbose_name": "form", "verbose_name_plural": "forms"},
        ),
    ]
