# Generated by Django 2.2.26 on 2022-02-07 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0016_merge_20220118_0925"),
        ("forms", "0016_auto_20220201_1213"),
    ]

    operations = []
