# Generated by Django 3.2.12 on 2022-02-15 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0016_auto_20220201_1213"),
    ]

    operations = [
        migrations.AlterField(
            model_name="form",
            name="payment_backend_options",
            field=models.JSONField(
                blank=True,
                default=dict,
                null=True,
                verbose_name="payment backend options",
            ),
        ),
        migrations.AlterField(
            model_name="form",
            name="registration_backend_options",
            field=models.JSONField(
                blank=True,
                default=dict,
                null=True,
                verbose_name="registration backend options",
            ),
        ),
        migrations.AlterField(
            model_name="formdefinition",
            name="configuration",
            field=models.JSONField(
                help_text="The form definition as Form.io JSON schema",
                verbose_name="Form.io configuration",
            ),
        ),
        migrations.AlterField(
            model_name="formlogic",
            name="actions",
            field=models.JSONField(
                help_text="Which action(s) to perform if the JSON logic evaluates to true.",
                verbose_name="actions",
            ),
        ),
        migrations.AlterField(
            model_name="formlogic",
            name="json_logic_trigger",
            field=models.JSONField(
                help_text="JSON logic associated with a step in a form.",
                verbose_name="JSON logic",
            ),
        ),
        migrations.AlterField(
            model_name="formpricelogic",
            name="json_logic_trigger",
            field=models.JSONField(
                help_text='JSON logic expression that must evaluate to "true" for the price to apply.',
                verbose_name="JSON logic",
            ),
        ),
        migrations.AlterField(
            model_name="formversion",
            name="export_blob",
            field=models.JSONField(
                help_text="The form, form definitions and form steps that make up this version, saved as JSON data."
            ),
        ),
    ]
