# Generated by Django 3.2.12 on 2022-02-21 13:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("forms", "0017_auto_20220215_1715"),
    ]

    operations = [
        migrations.AddField(
            model_name="formversion",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Description/context about this particular version.",
                verbose_name="version description",
            ),
        ),
        migrations.AddField(
            model_name="formversion",
            name="user",
            field=models.ForeignKey(
                help_text="User who authored this version.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
    ]
