# Generated by Django 2.2.20 on 2021-06-17 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0018_auto_20210521_1352"),
    ]

    operations = [
        migrations.AddField(
            model_name="form",
            name="maintenance_mode",
            field=models.BooleanField(
                default=False,
                help_text="Users will not be able to fill in the form if it is in maintenance mode.",
                verbose_name="maintenance mode",
            ),
        ),
    ]
