# Generated by Django 3.2.12 on 2022-02-28 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0006_form_display_main_website_link"),
        ("forms", "0018_auto_20220221_1405"),
    ]

    operations = []
