# Generated by Django 2.2.20 on 2021-06-01 10:43

import django.contrib.postgres.fields.jsonb
from django.db import migrations
import openforms.appointments.fields


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0018_auto_20210521_1352"),
    ]

    operations = [
        migrations.AddField(
            model_name="form",
            name="appointment_backend",
            field=openforms.appointments.fields.AppointmentBackendChoiceField(
                blank=True, max_length=100, verbose_name="appointment backend"
            ),
        ),
        migrations.AddField(
            model_name="form",
            name="appointment_backend_options",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True,
                default=dict,
                null=True,
                verbose_name="appointment backend options",
            ),
        ),
    ]
