# Generated by Django 3.2.12 on 2022-03-07 14:33

from django.db import migrations

from glom import glom

from openforms.formio.utils import iter_components


def migrate_kvk_prefill_from_hoofdvestiging_to_basisprofiel(apps, _):
    FormDefinition = apps.get_model("forms", "FormDefinition")

    # add the `embedded.hoofdVestiging` prefix for KVK prefills
    for form_definition in FormDefinition.objects.all():
        for component in iter_components(form_definition.configuration, recursive=True):
            plugin_id = glom(component, "prefill.plugin", default=None)
            attribute = glom(component, "prefill.attribute", default=None)
            if plugin_id != "kvk-kvknumber":
                continue

            if not attribute:
                continue

            # these are lifted from the API schema in a custom fashion and don't need the
            # prefix, see the plugin code
            if attribute.startswith("bezoekadres.") or attribute.startswith(
                "correspondentieadres."
            ):
                continue

            new_attribute = f"_embedded.hoofdvestiging.{attribute}"
            component["prefill"]["attribute"] = new_attribute
        form_definition.save(update_fields=["configuration"])


def migrate_kvk_prefill_from_basisprofiel_to_hoofdvestiging(apps, _):
    FormDefinition = apps.get_model("forms", "FormDefinition")

    # remove the `embedded.hoofdVestiging` prefix for KVK prefills
    for form_definition in FormDefinition.objects.all():
        for component in iter_components(form_definition.configuration, recursive=True):
            plugin_id = glom(component, "prefill.plugin", default=None)
            attribute = glom(component, "prefill.attribute", default=None)
            if plugin_id != "kvk-kvknumber":
                continue

            if not attribute:
                continue

            new_attribute = attribute.replace("_embedded.hoofdvestiging.", "", 1)
            component["prefill"]["attribute"] = new_attribute
        form_definition.save(update_fields=["configuration"])


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0019_merge_20220228_1207"),
    ]

    operations = [
        migrations.RunPython(
            migrate_kvk_prefill_from_hoofdvestiging_to_basisprofiel,
            migrate_kvk_prefill_from_basisprofiel_to_hoofdvestiging,
        )
    ]
