# Generated by Django 2.2.20 on 2021-06-17 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0019_form_maintenance_mode"),
        ("forms", "0019_form_authentication_backends"),
    ]

    operations = []
