# Generated by Django 2.2.20 on 2021-06-21 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0019_form_authentication_backends"),
    ]

    operations = [
        migrations.AddField(
            model_name="form",
            name="submission_confirmation_template",
            field=models.TextField(
                blank=True,
                help_text="The content of the submission confirmation page. It can contain variables that will be templated from the submitted form data. If not specified, the global template will be used.",
                verbose_name="submission confirmation template",
            ),
        ),
    ]
