# Generated by Django 3.2.12 on 2022-03-14 13:58

from django.db import migrations
import openforms.authentication.fields


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0020_migrate_kvk_prefill"),
    ]

    operations = [
        migrations.AddField(
            model_name="form",
            name="auto_login_authentication_backend",
            field=openforms.authentication.fields.AuthenticationBackendChoiceField(
                blank=True, max_length=100, verbose_name="automatic login"
            ),
        ),
    ]
