# Generated by Django 2.2.20 on 2021-06-18 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0020_merge_20210617_1542"),
    ]

    operations = [
        migrations.AlterField(
            model_name="form",
            name="maintenance_mode",
            field=models.BooleanField(
                default=False,
                help_text="Users will not be able to start the form if it is in maintenance mode.",
                verbose_name="maintenance mode",
            ),
        ),
    ]
