# Generated by Django 3.2.13 on 2022-04-15 11:37

from django.db import migrations, models
import openforms.utils.files
import privates.fields
import privates.storages


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0021_form_auto_login_authentication_backend"),
    ]

    operations = [
        migrations.CreateModel(
            name="FormsExport",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "export_content",
                    privates.fields.PrivateMediaFileField(
                        help_text="Zip file containing all the exported forms",
                        storage=privates.storages.PrivateMediaFileSystemStorage(),
                        upload_to="exports/%Y/%m/%d",
                        verbose_name="export content",
                    ),
                ),
                (
                    "downloaded",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the zip file has already been downloaded",
                        verbose_name="downloaded",
                    ),
                ),
                (
                    "date_downloaded",
                    models.DateField(
                        blank=True,
                        help_text="The date on which the zip file was downloaded",
                        null=True,
                        verbose_name="date downloaded",
                    ),
                ),
                (
                    "user_email",
                    models.EmailField(
                        help_text="The email address that the user entered when requesting the export",
                        max_length=254,
                        verbose_name="user email",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        help_text="The unique username of the user that requested the download",
                        max_length=150,
                        verbose_name="username",
                    ),
                ),
            ],
            options={
                "verbose_name": "forms export",
                "verbose_name_plural": "forms exports",
            },
            bases=(openforms.utils.files.DeleteFileFieldFilesMixin, models.Model),
        ),
    ]
