# Generated by Django 2.2.20 on 2021-06-23 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0022_merge_20210621_1740"),
        ("forms", "0022_remove_form_email_property_name"),
    ]

    operations = []
