# Generated by Django 2.2.20 on 2021-06-24 08:29

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0023_merge_20210623_1350"),
    ]

    operations = [
        migrations.AlterField(
            model_name="form",
            name="submission_confirmation_template",
            field=tinymce.models.HTMLField(
                blank=True,
                help_text="The content of the submission confirmation page. It can contain variables that will be templated from the submitted form data. If not specified, the global template will be used.",
                verbose_name="submission confirmation template",
            ),
        ),
    ]
