# Generated by Django 3.2.13 on 2022-06-01 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0024_formvariable"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="formvariable",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        models.Q(("prefill_plugin", ""), ("prefill_attribute", "")),
                        models.Q(
                            models.Q(("prefill_plugin", ""), _negated=True),
                            models.Q(("prefill_attribute", ""), _negated=True),
                        ),
                        _connector="OR",
                    )
                ),
                name="Valid prefill configuration",
            ),
        ),
    ]
