# Generated by Django 2.2.20 on 2021-07-05 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0024_auto_20210624_1029"),
    ]

    operations = [
        migrations.AddField(
            model_name="form",
            name="begin_text",
            field=models.CharField(
                default="Begin form",
                help_text="The text that will be displayed at the start of the form to indicate the user can begin",
                max_length=50,
                verbose_name="Begin Text",
            ),
        ),
        migrations.AddField(
            model_name="form",
            name="change_text",
            field=models.CharField(
                default="Change",
                help_text="The text that will be displayed in the overview page to change a certain step",
                max_length=50,
                verbose_name="Change Text",
            ),
        ),
        migrations.AddField(
            model_name="form",
            name="confirm_text",
            field=models.CharField(
                default="Confirm",
                help_text="The text that will be displayed in the overview page to confirm the data is correct",
                max_length=50,
                verbose_name="Confirm Text",
            ),
        ),
        migrations.AddField(
            model_name="form",
            name="previous_text",
            field=models.CharField(
                default="Previous page",
                help_text="The text that will be displayed in the overview page to go to the previous step",
                max_length=50,
                verbose_name="Previous Text",
            ),
        ),
        migrations.AddField(
            model_name="formdefinition",
            name="next_text",
            field=models.CharField(
                default="Next",
                help_text="The text that will be displayed in the form step to go to the next step",
                max_length=50,
                verbose_name="Next Text",
            ),
        ),
        migrations.AddField(
            model_name="formdefinition",
            name="previous_text",
            field=models.CharField(
                default="Previous page",
                help_text="The text that will be displayed in the form step to go to the previous step",
                max_length=50,
                verbose_name="Previous Text",
            ),
        ),
        migrations.AddField(
            model_name="formdefinition",
            name="save_text",
            field=models.CharField(
                default="Save current information",
                help_text="The text that will be displayed in the form step to save the current information",
                max_length=50,
                verbose_name="Save Text",
            ),
        ),
    ]
