# Generated by Django 3.2.13 on 2022-06-10 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0025_auto_20220524_1022"),
        ("forms", "0025_formvariable_valid_prefill_configuration"),
    ]

    operations = []
