# Generated by Django 2.2.20 on 2021-07-15 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0025_auto_20210709_1414"),
        ("forms", "0025_form_show_progress_indicator"),
    ]

    operations = []
