# Generated by Django 2.2.24 on 2021-07-24 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0026_merge_20210715_1337"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formstep",
            name="next_text",
            field=models.CharField(
                blank=True,
                help_text="The text that will be displayed in the form step to go to the next step. Leave blank to get value from global configuration.",
                max_length=50,
                verbose_name="step next text",
            ),
        ),
        migrations.AlterField(
            model_name="formstep",
            name="previous_text",
            field=models.CharField(
                blank=True,
                help_text="The text that will be displayed in the form step to go to the previous step. Leave blank to get value from global configuration.",
                max_length=50,
                verbose_name="step previous text",
            ),
        ),
        migrations.AlterField(
            model_name="formstep",
            name="save_text",
            field=models.CharField(
                blank=True,
                help_text="The text that will be displayed in the form step to save the current information. Leave blank to get value from global configuration.",
                max_length=50,
                verbose_name="step save text",
            ),
        ),
    ]
