# Generated by Django 2.2.24 on 2021-07-19 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0026_merge_20210715_1337"),
    ]

    operations = [
        migrations.CreateModel(
            name="FormVersion",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time of creation of the form version.",
                        verbose_name="date of creation",
                    ),
                ),
                (
                    "form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="forms.Form",
                        verbose_name="form",
                    ),
                ),
            ],
            options={
                "verbose_name": "form version",
                "verbose_name_plural": "form versions",
            },
        ),
    ]
