# Generated by Django 2.2.24 on 2021-07-26 13:14

import django.contrib.postgres.fields.jsonb
from django.db import migrations
import openforms.payments.fields


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0026_merge_20210715_1337"),
    ]

    operations = [
        migrations.AddField(
            model_name="form",
            name="payment_backend",
            field=openforms.payments.fields.PaymentBackendChoiceField(
                blank=True, max_length=100, verbose_name="payment backend"
            ),
        ),
        migrations.AddField(
            model_name="form",
            name="payment_backend_options",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True,
                default=dict,
                null=True,
                verbose_name="payment backend options",
            ),
        ),
    ]
