# Generated by Django 3.2.13 on 2022-06-21 07:26

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0026_merge_20220610_1302"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formvariable",
            name="key",
            field=models.CharField(
                help_text="Key of the variable, should be unique with the form.",
                max_length=100,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Invalid variable key. It must only contain alphanumeric characters, underscores, dots and dashes and should not be ended by dash or dot.",
                        regex=re.compile("^\\w[\\w.\\-]*\\w$"),
                    )
                ],
                verbose_name="key",
            ),
        ),
    ]
