# Generated by Django 3.2.13 on 2022-06-23 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0027_alter_formvariable_key"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="formlogic",
            options={"ordering": ("order",)},
        ),
        migrations.AddField(
            model_name="formlogic",
            name="order",
            field=models.PositiveIntegerField(
                db_index=True, default=0, editable=False, verbose_name="order"
            ),
            preserve_default=False,
        ),
    ]
