# Generated by Django 2.2.24 on 2021-07-26 09:02

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import openforms.utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0027_auto_20210724_0801"),
    ]

    operations = [
        migrations.CreateModel(
            name="FormVersion",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    openforms.utils.fields.StringUUIDField(
                        default=uuid.uuid4, unique=True, verbose_name="UUID"
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time of creation of the form version.",
                        verbose_name="date of creation",
                    ),
                ),
                (
                    "export_blob",
                    django.contrib.postgres.fields.jsonb.JSONField(
                        help_text="The form, form definitions and form steps that make up this version, saved as JSON data."
                    ),
                ),
                (
                    "form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="forms.Form",
                        verbose_name="form",
                    ),
                ),
            ],
            options={
                "verbose_name": "form version",
                "verbose_name_plural": "form versions",
            },
        ),
    ]
