# Generated by Django 2.2.24 on 2021-08-05 15:17

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0028_formversion"),
    ]

    operations = [
        migrations.CreateModel(
            name="FormLogic",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "json_logic_trigger",
                    django.contrib.postgres.fields.jsonb.JSONField(
                        help_text="JSON logic associated with a step in a form.",
                        verbose_name="JSON logic",
                    ),
                ),
                (
                    "component",
                    models.CharField(
                        help_text="Formio key of the component in the step to which the logic applies.",
                        max_length=100,
                        verbose_name="component",
                    ),
                ),
                (
                    "actions",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=django.contrib.postgres.fields.jsonb.JSONField(
                            default=dict
                        ),
                        help_text="What action to perform if the JSON logic evaluates to true.",
                        size=None,
                        verbose_name="actions",
                    ),
                ),
                (
                    "form_step",
                    models.ForeignKey(
                        help_text="Form step to which the JSON logic applies.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="forms.FormStep",
                    ),
                ),
            ],
        ),
    ]
