# Generated by Django 2.2.24 on 2021-08-02 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0027_auto_20210726_1514"),
        ("forms", "0028_formversion"),
    ]

    operations = []
