# Generated by Django 2.2.24 on 2021-08-02 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0028_formversion"),
    ]

    operations = [
        migrations.AddField(
            model_name="form",
            name="can_submit",
            field=models.BooleanField(
                default=True,
                help_text="Whether the user is allowed to submit this form or not.",
                verbose_name="can submit",
            ),
        ),
    ]
