# Generated by Django 2.2.24 on 2021-08-06 15:26

from django.db import migrations
import openforms.utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0029_formlogic"),
    ]

    operations = [
        migrations.AddField(
            model_name="formlogic",
            name="uuid",
            field=openforms.utils.fields.StringUUIDField(
                default=uuid.uuid4, unique=True, verbose_name="UUID"
            ),
        ),
    ]
