# Generated by Django 3.2.13 on 2022-06-23 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0029_make_logic_order_explicit"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="formlogic",
            options={
                "ordering": ("order",),
                "verbose_name": "form logic",
                "verbose_name_plural": "form logic rules",
            },
        ),
    ]
