# Generated by Django 3.2.13 on 2022-06-29 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0028_auto_20220628_0923"),
        ("forms", "0030_alter_formlogic_options"),
    ]

    operations = []
