# Generated by Django 2.2.24 on 2021-08-18 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0030_auto_20210813_1430"),
        ("forms", "0030_merge_20210812_1536"),
    ]

    operations = []
