# Generated by Django 2.2.24 on 2021-08-16 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0030_merge_20210812_1000"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="formlogic",
            name="component",
        ),
        migrations.RemoveField(
            model_name="formlogic",
            name="form_step",
        ),
        migrations.AddField(
            model_name="formlogic",
            name="form",
            field=models.ForeignKey(
                help_text="Form to which the JSON logic applies.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="forms.Form",
            ),
        ),
    ]
