# Generated by Django 2.2.24 on 2021-08-11 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0029_form_can_submit"),
        ("forms", "0030_formlogic_uuid"),
    ]

    operations = []
