# Generated by Django 2.2.24 on 2021-08-17 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0030_merge_20210812_1536"),
        ("forms", "0031_auto_20210816_1448"),
    ]

    operations = []
