# Generated by Django 3.2.14 on 2022-07-06 11:50

from django.db import migrations
import openforms.forms.models.form_variable


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0031_merge_20220629_0955"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="formvariable",
            managers=[
                ("objects", openforms.forms.models.form_variable.FormVariableManager()),
            ],
        ),
    ]
