# Generated by Django 3.2.14 on 2022-07-06 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0031_merge_20220629_0955"),
    ]

    operations = [
        migrations.AddField(
            model_name="formlogic",
            name="trigger_from_step",
            field=models.ForeignKey(
                blank=True,
                help_text="When set, the trigger will only be checked once the specified step is reached. This means the rule will never trigger for steps before the specified trigger step. If unset, the trigger will always be checked.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="forms.formstep",
                verbose_name="trigger from step",
            ),
        ),
    ]
