# Generated by Django 3.2.13 on 2022-06-09 08:03

from django.db import migrations
from django.db.models import Q


def create_form_variables_for_form(apps, schema_editor):
    Form = apps.get_model("forms", "Form")
    FormVariable = apps.get_model("forms", "FormVariable")

    # Get the ids of the forms already related to form variables
    forms_with_form_variables_id = (
        FormVariable.objects.all().values_list("form__id", flat=True).distinct()
    )

    forms_without_form_variables = Form.objects.filter(
        ~Q(id__in=forms_with_form_variables_id)
    )

    for form in forms_without_form_variables:
        FormVariable.objects.create_for_form(form)


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0032_alter_formvariable_managers"),
    ]

    operations = [
        migrations.RunPython(create_form_variables_for_form, migrations.RunPython.noop),
    ]
