# Generated by Django 2.2.24 on 2021-08-31 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0033_auto_20210819_1624"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="formstep",
            name="availability_strategy",
        ),
    ]
