# Generated by Django 2.2.24 on 2021-08-30 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0033_auto_20210819_1624"),
    ]

    operations = [
        migrations.AddField(
            model_name="formdefinition",
            name="is_reusable",
            field=models.BooleanField(
                default=False,
                help_text="Allow this definition to be re-used in multiple forms",
                verbose_name="is reusable",
            ),
        ),
    ]
