# Generated by Django 3.2.14 on 2022-07-08 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0032_formlogic_trigger_from_step"),
        ("forms", "0033_formvariable_datamigration"),
    ]

    operations = []
