# Generated by Django 2.2.24 on 2021-09-02 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0034_auto_20210825_1336"),
    ]

    operations = [
        migrations.AlterField(
            model_name="form",
            name="active",
            field=models.BooleanField(default=False, verbose_name="active"),
        ),
    ]
