# Generated by Django 3.2.14 on 2022-07-25 07:18

from django.db import migrations, models
import openforms.forms.models.form_version


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0034_merge_20220708_1038"),
    ]

    operations = [
        migrations.AddField(
            model_name="formversion",
            name="app_git_sha",
            field=models.CharField(
                blank=True,
                default=openforms.forms.models.form_version.get_app_git_sha,
                editable=False,
                help_text="Application commit hash at the time this version was created.",
                max_length=50,
                verbose_name="application commit hash",
            ),
        ),
        migrations.AddField(
            model_name="formversion",
            name="app_release",
            field=models.CharField(
                blank=True,
                default=openforms.forms.models.form_version.get_app_release,
                editable=False,
                help_text="App release/version at the time this version was created.",
                max_length=50,
                verbose_name="application version",
            ),
        ),
    ]
