# Generated by Django 2.2.24 on 2021-09-02 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0035_auto_20210902_1238"),
        ("forms", "0034_formdefinition_is_reusable"),
    ]

    operations = []
