# Generated by Django 2.2.24 on 2021-09-01 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0034_auto_20210825_1336"),
        ("forms", "0034_remove_formstep_availability_strategy"),
    ]

    operations = []
