# Generated by Django 2.2.24 on 2021-09-02 19:20

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0035_auto_20210902_1238"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formdefinition",
            name="configuration",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                help_text="The form definition as Form.io JSON schema",
                verbose_name="Form.io configuration",
            ),
        ),
    ]
