# Generated by Django 2.2.24 on 2021-09-10 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0035_merge_20210901_1429"),
        ("forms", "0005_form_internal_name"),
    ]

    operations = []
