# Generated by Django 2.2.24 on 2021-09-03 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0035_merge_20210902_1159"),
        ("forms", "0036_auto_20210902_2120"),
    ]

    operations = []
