# Generated by Django 3.2.15 on 2022-08-11 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0038_formvariable_form_definition_not_null_for_component_vars"),
    ]

    operations = [
        migrations.AddField(
            model_name="formdefinition",
            name="_num_components",
            field=models.PositiveIntegerField(
                default=0,
                help_text="The total number of Formio components used in the configuration",
                verbose_name="number of Formio components",
            ),
        ),
    ]
