# Generated by Django 3.2.15 on 2022-08-26 16:10

from django.db import migrations, models

import openforms.forms.validators


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0041_convert_logic_action_type_value_to_variable"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formdefinition",
            name="configuration",
            field=models.JSONField(
                help_text="The form definition as Form.io JSON schema",
                validators=[openforms.forms.validators.validate_template_expressions],
                verbose_name="Form.io configuration",
            ),
        ),
    ]
