# Generated by Django 3.2.14 on 2022-08-26 15:29

from django.db import migrations


def append_explanation_template_message(apps, schema_editor):

    from openforms.authentication.registry import register as auth_register

    Form = apps.get_model("forms", "Form")

    for form in Form.objects.all():
        plugins = form.authentication_backends
        login_options_count = len(
            [plugin_id for plugin_id in plugins if plugin_id in auth_register._registry]
        )
        can_login = login_options_count > 0
        form_login_required = any(
            form_step.form_definition.login_required
            for form_step in form.formstep_set.all()
        )

        if form_login_required:
            form.explanation_template += "\nPlease authenticate to start the form."
        elif can_login:
            form.explanation_template += (
                "\nPlease authenticate or start the form anonymously."
            )
        else:
            form.explanation_template += (
                "\nPlease click the button below to start the form."
            )

        form.save()


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0041_convert_logic_action_type_value_to_variable"),
    ]

    operations = [
        migrations.RunPython(
            append_explanation_template_message, migrations.RunPython.noop
        ),
    ]
