# Generated by Django 3.2.15 on 2022-08-15 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0041_convert_logic_action_type_value_to_variable"),
    ]

    operations = [
        migrations.AddField(
            model_name="formvariable",
            name="show_in_email",
            field=models.BooleanField(
                default=False,
                help_text="Should be displayed in the confirmation email?",
                verbose_name="show in email",
            ),
        ),
        migrations.AddField(
            model_name="formvariable",
            name="show_in_pdf",
            field=models.BooleanField(
                default=True,
                help_text="Should be displayed in the pdf confirmation report?",
                verbose_name="show in pdf",
            ),
        ),
        migrations.AddField(
            model_name="formvariable",
            name="show_in_summary",
            field=models.BooleanField(
                default=True,
                help_text="Should be displayed in the summary page?",
                verbose_name="show in summary",
            ),
        ),
    ]
