# Generated by Django 3.2.14 on 2022-09-05 16:04
from django.conf import settings
from django.db import migrations
from django.db.models import Prefetch
from django.utils.html import format_html
from django.utils.translation import activate, deactivate_all, gettext as _

from openforms.authentication.registry import register as auth_register


def append_explanation_template_message(apps, schema_editor):
    activate(settings.LANGUAGE_CODE)

    Form = apps.get_model("forms", "Form")
    FormStep = apps.get_model("forms", "FormStep")

    for form in Form.objects.prefetch_related(
        Prefetch(
            "formstep_set",
            queryset=FormStep.objects.select_related("form_definition"),
        )
    ):
        plugins = form.authentication_backends
        login_options_count = len(
            [plugin_id for plugin_id in plugins if plugin_id in auth_register]
        )
        can_login = login_options_count > 0
        form_login_required = any(
            form_step.form_definition.login_required
            for form_step in form.formstep_set.all()
        )

        if form_login_required:
            message = _("Please authenticate to start the form.")
        elif can_login:
            message = _("Please authenticate or start the form anonymously.")
        else:
            message = _("Please click the button below to start the form.")

        form.explanation_template += format_html("<p>{}</p>", message)
        form.save()

    deactivate_all()


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0042_alter_formdefinition_configuration"),
    ]

    operations = [
        migrations.RunPython(
            append_explanation_template_message,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
