# Generated by Django 3.2.15 on 2022-09-07 11:23

from django.db import migrations

from openforms.variables.constants import FormVariableSources
from openforms.variables.utils import check_initial_value


def check_user_defined_variables_initial_value(apps, schema_editor):
    FormVariable = apps.get_model("forms", "FormVariable")

    user_defined_vars = FormVariable.objects.filter(
        source=FormVariableSources.user_defined
    )

    variables_to_update = []
    for variable in user_defined_vars:
        initial_value = check_initial_value(variable.initial_value, variable.data_type)
        if initial_value != variable.initial_value:
            variable.initial_value = initial_value
            variables_to_update.append(variable)

    FormVariable.objects.bulk_update(variables_to_update, fields=["initial_value"])


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0043_explanation_template_data_migration"),
    ]

    operations = [
        migrations.RunPython(
            check_user_defined_variables_initial_value,
            migrations.RunPython.noop,
        ),
    ]
