# Generated by Django 3.2.15 on 2022-09-16 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0044_fix_user_defined_vars_initial_value"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="formstep",
            name="optional",
        ),
    ]
