# Generated by Django 3.2.15 on 2022-09-19 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0001_initial_pre_openforms_v230"),
    ]

    # This was originally a data-migration run as part of the 2.0.0 upgrade, see
    # https://github.com/open-formulieren/open-forms/commit/8a28347250f5140a3a3a92df70315fb190b8d9b3
    # Now, going into the 2.1.0 release cycle, this migration is guaranteed to have
    # been executed due to the upgrade checks. This is why the operations are now empty,
    # the code is removed.
    operations = []
