# Generated by Django 3.2.15 on 2022-09-29 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0046_convert_advanced_logic"),
    ]

    # Similar to migration 0046, the original operations have been executed and been
    # removed.
    operations = []
