# Generated by Django 3.2.15 on 2022-10-03 10:29

from django.db import migrations

from openforms.formio.utils import iter_components


def update_default_value_formio_setting(apps, schema_editor):
    FormDefinition = apps.get_model("forms", "FormDefinition")

    form_definitions = FormDefinition.objects.all()

    form_definitions_to_update = []
    for form_definition in form_definitions:
        updated_form_definition = False
        for comp in iter_components(configuration=form_definition.configuration):
            if comp["type"] == "editgrid":
                comp["inlineEdit"] = True
                updated_form_definition = True

        if updated_form_definition:
            form_definitions_to_update.append(form_definition)

    if form_definitions_to_update:
        FormDefinition.objects.bulk_update(
            form_definitions_to_update, fields=["configuration"]
        )


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0047_fix_broken_converted_rules"),
    ]

    operations = [
        migrations.RunPython(
            update_default_value_formio_setting, migrations.RunPython.noop
        ),
    ]
