# Generated by Django 3.2.15 on 2022-10-03 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0047_fix_broken_converted_rules"),
    ]

    # this used to be a data migration, but it's no longer relevant on 2.3.0+
    operations = []
