# Generated by Django 3.2.15 on 2022-11-09 16:57

import re

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0049_remove_editgrid_open_when_empty"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formvariable",
            name="key",
            field=models.TextField(
                help_text="Key of the variable, should be unique with the form.",
                validators=[
                    django.core.validators.RegexValidator(
                        message="Invalid variable key. It must only contain alphanumeric characters, underscores, dots and dashes and should not be ended by dash or dot.",
                        regex=re.compile("^(\\w|\\w[\\w.\\-]*\\w)$"),
                    )
                ],
                verbose_name="key",
            ),
        ),
    ]
