# Generated by Django 3.2.16 on 2022-10-26 07:09
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0050_auto_20221024_1252"),
    ]

    # this used to be a data migration, but it's no longer relevant on 2.3.0+
    operations = []
