# Generated by Django 3.2.16 on 2022-11-10 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0050_alter_formvariable_key"),
    ]

    # this used to be a data migration, but it's no longer relevant on 2.3.0+
    operations = []
