# Generated by Django 3.2.16 on 2022-10-26 07:09
from django.core.management import call_command
from django.db import migrations


def update_translation_fields(apps, schema_editor):
    """
    Ensure that the values of translatable fields are also updated in the default
    translated field (`..._nl`)
    """
    call_command("update_translation_fields", verbosity=0)


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0050_auto_20221024_1252"),
    ]

    operations = [
        migrations.RunPython(update_translation_fields, migrations.RunPython.noop)
    ]
