# Generated by Django 3.2.16 on 2022-11-22 13:17
from typing import cast

from django.db import migrations

from json_logic.meta import JSONLogicExpression, Operation

from openforms.forms.utils import get_total_form_configuration_wrapper


def fix_rules_for_selectboxes(apps, _):
    Form = apps.get_model("forms", "Form")
    FormLogic = apps.get_model("forms", "FormLogic")

    rules_to_update = []
    for form in Form.objects.all():
        total_config_wrapper = get_total_form_configuration_wrapper(
            form.formstep_set.all()
        )

        for rule in form.formlogic_set.filter(is_advanced=False):
            operation = JSONLogicExpression.from_expression(
                rule.json_logic_trigger
            ).as_tree()
            if not isinstance(operation, Operation):  # it's a primitive or list
                continue

            first_operand = operation.arguments[0]
            if (
                not isinstance(first_operand, Operation)
                or first_operand.operator != "var"
            ):
                continue

            trigger_component_key = cast(str, first_operand.arguments[0])
            if (
                trigger_component_key in total_config_wrapper
                and total_config_wrapper[trigger_component_key]["type"] == "selectboxes"
            ):
                # We know that the trigger is badly formatted, because otherwise the trigger_component_key would
                # be <key>.<value_key>
                compare_value_key = operation.arguments[1]
                rule.json_logic_trigger[operation.operator][0] = {
                    "var": f"{trigger_component_key}.{compare_value_key}"
                }
                rule.json_logic_trigger[operation.operator][1] = True
                rules_to_update.append(rule)

    FormLogic.objects.bulk_update(rules_to_update, fields=["json_logic_trigger"])


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0051_replace_urls_with_uuids"),
    ]

    operations = [
        migrations.RunPython(fix_rules_for_selectboxes, migrations.RunPython.noop),
    ]
