# Generated by Django 3.2.16 on 2022-10-31 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0051_update_translation_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="form",
            name="translation_enabled",
            field=models.BooleanField(
                default=False, verbose_name="translation enabled"
            ),
        ),
    ]
