# Generated by Django 3.2.16 on 2022-11-22 13:17
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0051_replace_urls_with_uuids"),
    ]

    # This data migration is/was part of 2.0.2, and the upgrade constraints require
    # the users to be on at least 2.0.2 before upgrading to 2.1.0.
    # Similarly to 0046 and 0047, the code for this data migration has been removed.
    operations = []
