# Generated by Django 3.2.16 on 2022-11-09 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0050_alter_formvariable_key"),
        ("forms", "0052_form_translation_enabled"),
    ]

    operations = []
