# Generated by Django 3.2.16 on 2022-11-17 16:46
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0054_merge_20221114_1308"),
    ]

    # this used to be a data migration, but it's no longer relevant on 2.3.0+
    operations = []
