# Generated by Django 3.2.16 on 2022-11-22 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0055_make_hidelabel_false"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formvariable",
            name="data_type",
            field=models.CharField(
                choices=[
                    ("string", "String"),
                    ("boolean", "Boolean"),
                    ("object", "Object"),
                    ("array", "Array"),
                    ("int", "Integer"),
                    ("float", "Float"),
                    ("datetime", "Datetime"),
                    ("time", "Time"),
                    ("date", "Date"),
                ],
                help_text="The type of the value that will be associated with this variable",
                max_length=50,
                verbose_name="data type",
            ),
        ),
    ]
