# Generated by Django 3.2.16 on 2022-12-15 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0057_alter_formvariable_data_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="formdefinition",
            name="component_translations",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Translations for literals used in components",
                verbose_name="Component translations",
            ),
        ),
    ]
