# Generated by Django 3.2.16 on 2022-12-16 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0058_formdefinition_component_translations"),
    ]

    # this used to be a data migration, but it's no longer relevant on 2.3.0+
    operations = []
