# Generated by Django 3.2.16 on 2022-12-22 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0059_editgrid_inline_false"),
    ]

    operations = [
        migrations.AddField(
            model_name="formlogic",
            name="description",
            field=models.CharField(
                default="",
                help_text="Logic rule description in natural language.",
                max_length=100,
                verbose_name="description",
            ),
            preserve_default=False,
        ),
    ]
