# Generated by Django 3.2.16 on 2023-01-04 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0061_generate_logic_rule_descriptions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formlogic",
            name="description",
            field=models.CharField(
                blank=True,
                help_text="Logic rule description in natural language.",
                max_length=100,
                verbose_name="description",
            ),
        ),
    ]
