# Generated by Django 3.2.16 on 2023-01-12 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0062_alter_formlogic_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="form",
            name="appointment_enabled",
            field=models.BooleanField(
                default=False,
                help_text="This is experimental mode for appointments",
                verbose_name="appointment enabled",
            ),
        ),
    ]
