# Generated by Django 3.2.16 on 2023-01-13 15:41

from django.db import migrations

import tinymce.models

import openforms.template.validators


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0063_form_include_confirmation_page_content_in_pdf"),
    ]

    operations = [
        migrations.AlterField(
            model_name="form",
            name="submission_confirmation_template",
            field=tinymce.models.HTMLField(
                blank=True,
                help_text="The content of the submission confirmation page. It can contain variables that will be templated from the submitted form data. If not specified, the global template will be used.",
                validators=[
                    openforms.template.validators.DjangoTemplateValidator(
                        backend="openforms.template.openforms_backend"
                    )
                ],
                verbose_name="submission confirmation template",
            ),
        ),
        migrations.AlterField(
            model_name="form",
            name="submission_confirmation_template_en",
            field=tinymce.models.HTMLField(
                blank=True,
                help_text="The content of the submission confirmation page. It can contain variables that will be templated from the submitted form data. If not specified, the global template will be used.",
                null=True,
                validators=[
                    openforms.template.validators.DjangoTemplateValidator(
                        backend="openforms.template.openforms_backend"
                    )
                ],
                verbose_name="submission confirmation template",
            ),
        ),
        migrations.AlterField(
            model_name="form",
            name="submission_confirmation_template_nl",
            field=tinymce.models.HTMLField(
                blank=True,
                help_text="The content of the submission confirmation page. It can contain variables that will be templated from the submitted form data. If not specified, the global template will be used.",
                null=True,
                validators=[
                    openforms.template.validators.DjangoTemplateValidator(
                        backend="openforms.template.openforms_backend"
                    )
                ],
                verbose_name="submission confirmation template",
            ),
        ),
    ]
