# Generated by Django 3.2.16 on 2023-01-19 08:44

from django.db import migrations
from openforms.formio.utils import iter_components


def add_radio_datatype(apps, schema_editor):
    FormDefinition = apps.get_model("forms", "FormDefinition")

    form_definitions = FormDefinition.objects.all()

    form_definitions_to_update = []
    for form_definition in form_definitions:
        updated_form_definition = False
        for comp in iter_components(configuration=form_definition.configuration):
            if comp["type"] == "radio" and "dataType" not in comp:
                comp["dataType"] = "string"
                updated_form_definition = True

        if updated_form_definition:
            form_definitions_to_update.append(form_definition)

    if form_definitions_to_update:
        FormDefinition.objects.bulk_update(
            form_definitions_to_update, fields=["configuration"]
        )


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0064_auto_20230113_1641"),
    ]

    operations = [migrations.RunPython(add_radio_datatype, migrations.RunPython.noop)]
