# Generated by Django 3.2.16 on 2023-01-18 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0053_alter_formvariable_prefill_attribute"),
        ("forms", "0064_auto_20230113_1641"),
    ]

    operations = []
