# Generated by Django 3.2.16 on 2023-01-19 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0065_merge_20230118_1801"),
        ("forms", "0065_set_radio_data_type"),
    ]

    operations = []
