# Generated by Django 3.2.16 on 2023-01-24 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0066_merge_20230119_1618"),
    ]

    # this used to be a data migration, but it's no longer relevant on 2.3.0+
    operations = []
