# Generated by Django 3.2.16 on 2023-01-23 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0067_fix_typo_20230124_1624"),
    ]

    operations = []
