# Generated by Django 3.2.16 on 2023-02-01 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0069_form_appointment_enabled"),
    ]

    # this used to be a data migration, but it's no longer relevant on 2.3.0+
    operations = []
