# Generated by Django 3.2.16 on 2023-02-08 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0070_remove_value_expression"),
    ]

    operations = [
        migrations.AddField(
            model_name="form",
            name="pricing_logic",
            field=models.CharField(
                choices=[
                    ("static", "Use linked product price"),
                    ("dynamic", "Use logic rules to determine the price"),
                    (
                        "from_variable",
                        "Determine the price based on logic rules and user-defined variables",
                    ),
                ],
                default="static",
                help_text="How the price of a product should be determined",
                max_length=24,
                verbose_name="pricing logic",
            ),
        ),
        migrations.AddField(
            model_name="form",
            name="pricing_variable",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="form_variable",
                to="forms.formvariable",
            ),
        ),
    ]
