# Generated by Django 3.2.17 on 2023-02-13 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0067_formvariable_service_fetch_configuration"),
        ("forms", "0070_remove_value_expression"),
    ]

    operations = []
