# Generated by Django 3.2.18 on 2023-03-06 07:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("forms", "0071_merge_20230213_1106")]

    # this used to be a data migration, but it's no longer relevant on 2.3.0+
    operations = []
