# Generated by Django 3.2.18 on 2023-03-16 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0072_check_form_variable_datatype"),
    ]

    operations = []
