# Generated by Django 3.2.18 on 2023-03-16 16:08

from django.db import migrations

from openforms.formio.utils import iter_components


def update_validate_on_change_to_on_blur_bsn(apps, schema_editor):
    FormDefinition = apps.get_model("forms", "FormDefinition")

    form_definitions = FormDefinition.objects.all()

    form_definitions_to_update = []
    for form_definition in form_definitions:
        updated_form_definition = False
        for comp in iter_components(configuration=form_definition.configuration):
            if comp["type"] == "bsn":
                comp["validateOn"] = "blur"
                updated_form_definition = True

        if updated_form_definition:
            form_definitions_to_update.append(form_definition)

    if form_definitions_to_update:
        FormDefinition.objects.bulk_update(
            form_definitions_to_update, fields=["configuration"]
        )


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0072_check_form_variable_datatype"),
    ]

    operations = [
        migrations.RunPython(
            update_validate_on_change_to_on_blur_bsn, migrations.RunPython.noop
        ),
    ]
