# Generated by Django 3.2.18 on 2023-03-31 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0073_change_bsn_validation"),
    ]

    # this used to be a data migration, but it's no longer relevant on 2.3.0+
    operations = []
