# Generated by Django 3.2.18 on 2023-04-14 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0074_add_custom_errors_numbers"),
    ]

    operations = [
        migrations.AddField(
            model_name="form",
            name="send_confirmation_email",
            field=models.BooleanField(
                default=True,
                help_text="Whether a confirmation email should be sent to the end user filling in the form.",
                verbose_name="send confirmation email",
            ),
        ),
    ]
