# Generated by Django 3.2.18 on 2023-04-14 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0075_form_send_confirmation_email"),
    ]

    # this used to be a data migration, but it's no longer relevant on 2.3.0+
    operations = []
