# Generated by Django 3.2.18 on 2023-04-14 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0076_move_confirmation_email_setting"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="form",
            name="confirmation_email_option",
        ),
    ]
