# Generated by Django 3.2.18 on 2023-04-24 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0077_remove_form_confirmation_email_option"),
    ]

    operations = [
        migrations.AddField(
            model_name="form",
            name="suspension_allowed",
            field=models.BooleanField(
                default=True,
                help_text="Whether the user is allowed to suspend this form or not.",
                verbose_name="suspension allowed",
            ),
        ),
    ]
