# Generated by Django 3.2.18 on 2023-05-31 12:14

from django.db import migrations

import openforms.registrations.fields


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0079_replace_cosign_component"),
    ]

    operations = [
        migrations.AddField(
            model_name="form",
            name="registration_backend_instance",
            field=openforms.registrations.fields.RegistrationBackendChoiceField(
                blank=True, max_length=100, verbose_name="registration backend instance"
            ),
        ),
    ]
