# Generated by Django 3.2.18 on 2023-05-23 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0079_replace_cosign_component"),
    ]

    # this used to be a data migration, but it's no longer relevant on 2.3.0+
    operations = []
