# Generated by Django 3.2.18 on 2023-06-12 16:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forms", "0080_add_show_in_summary_default"),
    ]

    operations = [
        migrations.AddField(
            model_name="form",
            name="authentication_backend_options",
            field=models.JSONField(
                blank=True,
                default=dict,
                verbose_name="per form authentication backend config",
            ),
        ),
    ]
