# Generated by Django 3.2.19 on 2023-07-04 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0081_form_authentication_backend_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="form",
            old_name="appointment_enabled",
            new_name="is_appointment",
        ),
    ]
