# Generated by Django 3.2.20 on 2023-07-07 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0083_alter_form_is_appointment"),
    ]

    operations = [
        migrations.AddField(
            model_name="formvariable",
            name="prefill_identifier_role",
            field=models.CharField(
                choices=[("main", "Main"), ("authorised_person", "Authorised person")],
                default="main",
                help_text="The role of the identifier. Used to distinguish between the 'main' identifier and the identifiers of someone logging in on behalf of someone/something else.",
                max_length=100,
                verbose_name="prefill identifier role",
            ),
        ),
    ]
