# Generated by Django 3.2.20 on 2023-07-07 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0083_alter_form_is_appointment"),
    ]

    operations = [
        migrations.AddField(
            model_name="formvariable",
            name="prefill_identifier_role",
            field=models.CharField(
                choices=[("main", "Main"), ("authorised_person", "Authorised person")],
                default="main",
                help_text="In case that multiple identifiers are returned (in the case of eHerkenning bewindvoering and DigiD Machtigen), should the prefill data related to the main identifier be used, or that related to the authorised person?",
                max_length=100,
                verbose_name="prefill identifier role",
            ),
        ),
    ]
