# Generated by Django 3.2.20 on 2023-08-02 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0085_auto_20230802_1025"),
    ]

    # this used to be a data migration, but it's no longer relevant on 2.3.0+
    operations = []
