# Generated by Django 3.2.20 on 2023-08-08 09:16

from django.db import migrations

from openforms.formio.utils import iter_components


def add_time_custom_error_message(apps, schema_editor):
    FormDefinition = apps.get_model("forms", "FormDefinition")

    form_definitions = FormDefinition.objects.all()

    form_definitions_to_update = []
    for form_definition in form_definitions:
        updated_form_definition = False
        for comp in iter_components(configuration=form_definition.configuration):
            if comp["type"] == "time" and (
                translated_errors := comp.get("translatedErrors")
            ):
                updated_form_definition = True
                for language_code, custom_error_messages in translated_errors.items():
                    translated_errors[language_code]["invalid_time"] = ""

        if updated_form_definition:
            form_definitions_to_update.append(form_definition)

    if form_definitions_to_update:
        FormDefinition.objects.bulk_update(
            form_definitions_to_update, fields=["configuration"]
        )


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0087_alter_formdefinition_slug"),
    ]

    operations = [
        migrations.RunPython(add_time_custom_error_message, migrations.RunPython.noop)
    ]
