# Generated by Django 3.2.20 on 2023-08-08 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0087_alter_formdefinition_slug"),
    ]

    # this used to be a data migration, but it's no longer relevant on 2.3.0+
    operations = []
