# Generated by Django 3.2.20 on 2023-07-18 14:08

import django.db.models.deletion
from django.db import migrations, models
from django.utils.translation import gettext as _

import openforms.registrations.fields


class Migration(migrations.Migration):
    dependencies = [
        ("forms", "0088_add_time_custom_error"),
    ]

    operations = [
        migrations.CreateModel(
            name="FormRegistrationBackend",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        help_text="The key to use to refer to this configuration in form logic.",
                        max_length=50,
                        verbose_name="key",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="A recognisable name for this backend configuration.",
                        max_length=255,
                        verbose_name="name",
                    ),
                ),
                (
                    "backend",
                    openforms.registrations.fields.RegistrationBackendChoiceField(
                        max_length=100, verbose_name="registration backend"
                    ),
                ),
                (
                    "options",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        verbose_name="registration backend options",
                    ),
                ),
                (
                    "form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registration_backends",
                        to="forms.form",
                    ),
                ),
            ],
            options={
                "unique_together": {("form", "key")},
                "verbose_name": "registration backend",
                "verbose_name_plural": "registration backends",
            },
        ),
        # there used to be a data migration, but it's no longer relevant on 2.3.0+
        migrations.RemoveField(
            model_name="form",
            name="registration_backend",
        ),
        migrations.RemoveField(
            model_name="form",
            name="registration_backend_options",
        ),
    ]
