# Generated by Django 3.2.20 on 2023-08-31 09:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forms", "0046_squashed_to_openforms_v230"),
    ]

    operations = [
        migrations.AddField(
            model_name="form",
            name="activate_on",
            field=models.DateTimeField(
                blank=True,
                help_text="Date and time on which the form should be activated.",
                null=True,
                verbose_name="activate on",
            ),
        ),
        migrations.AddField(
            model_name="form",
            name="deactivate_on",
            field=models.DateTimeField(
                blank=True,
                help_text="Date and time on which the form should be deactivated.",
                null=True,
                verbose_name="deactivate on",
            ),
        ),
    ]
