# Generated by Django 3.2.23 on 2024-01-22 16:14

import django.db.migrations.operations.special
import django.db.models.deletion
from django.db import migrations, models
from django.utils.module_loading import import_string

import openforms.forms.migration_operations

add_more_time_custom_errors = import_string(
    "openforms.forms.migrations.0092_more_time_custom_errors."
    "add_more_time_custom_errors"
)
add_date_component_settings = import_string(
    "openforms.forms.migrations.0093_date_component_settings."
    "add_date_component_settings"
)
add_configuration_to_family_component = import_string(
    "openforms.forms.migrations.0094_update_config_family."
    "add_configuration_to_family_component"
)
update_component_action = import_string(
    "openforms.forms.migrations.0101_update_action_property." "update_component_action"
)
migrate_fd_translations = import_string(
    "openforms.forms.migrations.0102_convert_formio_translations."
    "migrate_fd_translations"
)


class Migration(migrations.Migration):

    replaces = [
        ("forms", "0091_auto_20230831_1152"),
        ("forms", "0092_more_time_custom_errors"),
        ("forms", "0093_date_component_settings"),
        ("forms", "0094_update_config_family"),
        ("forms", "0095_formstep_form_form_definition_unique_together"),
        ("forms", "0096_move_time_component_validators"),
        ("forms", "0097_formstep_is_applicable"),
        ("forms", "0098_update_default_value_components_prefill"),
        ("forms", "0099_form_theme"),
        ("forms", "0100_ensure_datasrc_property"),
        ("forms", "0101_update_action_property"),
        ("forms", "0102_convert_formio_translations"),
        ("forms", "0103_fix_component_problems"),
        ("forms", "0104_allow_invalid_input_datetime"),
    ]

    dependencies = [
        ("forms", "0046_squashed_to_openforms_v230"),
        ("config", "0064_auto_20231206_0921"),
    ]

    operations = [
        migrations.AddField(
            model_name="form",
            name="activate_on",
            field=models.DateTimeField(
                blank=True,
                help_text="Date and time on which the form should be activated.",
                null=True,
                verbose_name="activate on",
            ),
        ),
        migrations.AddField(
            model_name="form",
            name="deactivate_on",
            field=models.DateTimeField(
                blank=True,
                help_text="Date and time on which the form should be deactivated.",
                null=True,
                verbose_name="deactivate on",
            ),
        ),
        migrations.RunPython(
            code=add_more_time_custom_errors,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.RunPython(
            code=add_date_component_settings,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.RunPython(
            code=add_configuration_to_family_component,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name="formstep",
            constraint=models.UniqueConstraint(
                fields=("form", "form_definition"),
                name="form_form_definition_unique_together",
            ),
        ),
        openforms.forms.migration_operations.ConvertComponentsOperation(
            "time", "move_time_validators"
        ),
        migrations.AddField(
            model_name="formstep",
            name="is_applicable",
            field=models.BooleanField(
                default=True,
                help_text="Whether the step is applicable by default.",
                verbose_name="is applicable",
            ),
        ),
        openforms.forms.migration_operations.ConvertComponentsOperation(
            "textfield", "alter_prefill_default_values"
        ),
        openforms.forms.migration_operations.ConvertComponentsOperation(
            "date", "alter_prefill_default_values"
        ),
        openforms.forms.migration_operations.ConvertComponentsOperation(
            "datetime", "alter_prefill_default_values"
        ),
        openforms.forms.migration_operations.ConvertComponentsOperation(
            "postcode", "alter_prefill_default_values"
        ),
        openforms.forms.migration_operations.ConvertComponentsOperation(
            "bsn", "alter_prefill_default_values"
        ),
        migrations.AddField(
            model_name="form",
            name="theme",
            field=models.ForeignKey(
                blank=True,
                help_text="Apply a specific appearance configuration to the form. If left blank, then the globally configured default is applied.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="config.theme",
                verbose_name="form theme",
            ),
        ),
        openforms.forms.migration_operations.ConvertComponentsOperation(
            "select", "set_openforms_datasrc"
        ),
        openforms.forms.migration_operations.ConvertComponentsOperation(
            "radio", "set_openforms_datasrc"
        ),
        openforms.forms.migration_operations.ConvertComponentsOperation(
            "selectboxes", "set_openforms_datasrc"
        ),
        migrations.RunPython(
            code=update_component_action,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.RunPython(
            code=migrate_fd_translations,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        openforms.forms.migration_operations.ConvertComponentsOperation(
            "columns", "fix_column_sizes"
        ),
        openforms.forms.migration_operations.ConvertComponentsOperation(
            "file", "fix_default_value"
        ),
        openforms.forms.migration_operations.ConvertComponentsOperation(
            "licenseplate", "ensure_validate_pattern"
        ),
        openforms.forms.migration_operations.ConvertComponentsOperation(
            "postcode", "ensure_validate_pattern"
        ),
        openforms.forms.migration_operations.ConvertComponentsOperation(
            "datetime", "prevent_datetime_components_from_emptying_invalid_values"
        ),
    ]
