# Generated by Django 4.2.11 on 2024-07-04 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("variables", "0012_servicefetchconfiguration_cache_timeout"),
        ("forms", "0001_initial_to_v250"),
    ]

    operations = [
        migrations.CreateModel(
            name="FormStatistics",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "form_name",
                    models.CharField(
                        help_text="The name of the submitted form. This is saved separately in case of form deletion.",
                        max_length=150,
                        verbose_name="form name",
                    ),
                ),
                (
                    "submission_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="The number of the submitted forms.",
                        verbose_name="Submission count",
                    ),
                ),
                (
                    "first_submission",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time of the first submitted form.",
                        verbose_name="first submission",
                    ),
                ),
                (
                    "last_submission",
                    models.DateTimeField(
                        help_text="Date and time of the last submitted form.",
                        verbose_name="last submission",
                    ),
                ),
                (
                    "form",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="forms.form",
                        verbose_name="form",
                    ),
                ),
            ],
            options={
                "verbose_name": "form statistics",
                "verbose_name_plural": "form statistics",
            },
        ),
        migrations.RemoveField(
            model_name="formdefinition",
            name="component_translations",
        ),
    ]
