# Generated by Django 4.2.10 on 2024-02-28 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0092_formstatistics"),
    ]

    operations = []
