# Generated by Django 4.2.10 on 2024-02-28 07:58

from django.db import migrations

from openforms.forms.migration_operations import ConvertComponentsOperation


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0092_formstatistics"),
    ]

    operations = [
        ConvertComponentsOperation("textfield", "alter_prefill_default_values"),
        ConvertComponentsOperation("date", "alter_prefill_default_values"),
        ConvertComponentsOperation("datetime", "alter_prefill_default_values"),
        ConvertComponentsOperation("postcode", "alter_prefill_default_values"),
        ConvertComponentsOperation("bsn", "alter_prefill_default_values"),
    ]
