# Generated by Django 3.2.24 on 2024-02-07 11:58

from django.db import migrations

from openforms.forms.migration_operations import ConvertComponentsOperation


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0092_formstatistics"),
    ]

    operations = [
        ConvertComponentsOperation("cosign", "update_cosign_to_include_bsn"),
    ]
