# Generated by Django 3.2.21 on 2023-09-13 08:24

from django.db import migrations
from openforms.formio.utils import iter_components


def add_date_component_settings(apps, schema_editor):
    FormDefinition = apps.get_model("forms", "FormDefinition")

    form_definitions = FormDefinition.objects.all()

    form_definitions_to_update = []
    for form_definition in form_definitions:
        for comp in iter_components(configuration=form_definition.configuration):
            if comp["type"] == "date":
                if translated_errors := comp.get("translatedErrors"):
                    for (
                        language_code,
                        custom_error_messages,
                    ) in translated_errors.items():
                        translated_errors[language_code]["minDate"] = ""
                        translated_errors[language_code]["maxDate"] = ""

                comp.setdefault("customOptions", {})
                comp["customOptions"]["allowInvalidPreload"] = True

                form_definitions_to_update.append(form_definition)

    if form_definitions_to_update:
        FormDefinition.objects.bulk_update(
            form_definitions_to_update, fields=["configuration"]
        )


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0092_more_time_custom_errors"),
    ]

    operations = [
        migrations.RunPython(add_date_component_settings, migrations.RunPython.noop)
    ]
