# Generated by Django 3.2.21 on 2023-10-04 08:48

from django.db import migrations

from openforms.formio.utils import iter_components


def add_configuration_to_family_component(apps, schema_editor):
    FormDefinition = apps.get_model("forms", "FormDefinition")

    form_definitions = FormDefinition.objects.all()

    form_definitions_to_update = []
    for form_definition in form_definitions:
        updated_form_definition = False

        for comp in iter_components(configuration=form_definition.configuration):
            if comp["type"] != "npFamilyMembers":
                continue

            comp["includePartners"] = False
            comp["includeChildren"] = True

            updated_form_definition = True

        if updated_form_definition:
            form_definitions_to_update.append(form_definition)

    if form_definitions_to_update:
        FormDefinition.objects.bulk_update(
            form_definitions_to_update, fields=["configuration"]
        )


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0093_date_component_settings"),
    ]

    operations = [
        migrations.RunPython(
            add_configuration_to_family_component, migrations.RunPython.noop
        )
    ]
