# Generated by Django 4.2.10 on 2024-03-12 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0093_fix_prefill_bis"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="formdefinition",
            name="component_translations",
        ),
    ]
