# Generated by Django 4.2.10 on 2024-03-06 14:38
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0093_fix_prefill_bis"),
        ("variables", "0012_servicefetchconfiguration_cache_timeout"),
    ]

    # Removed RunPython as part of 2.7 release cycle
    operations = []
