# Generated by Django 3.2.21 on 2023-10-09 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0094_update_config_family"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="formstep",
            constraint=models.UniqueConstraint(
                fields=("form", "form_definition"),
                name="form_form_definition_unique_together",
            ),
        ),
    ]
