# Generated by Django 4.2.10 on 2024-03-13 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0094_convert_old_service_fetch_config"),
        ("forms", "0094_remove_formdefinition_component_translations"),
    ]

    operations = []
