# Generated by Django 4.2.11 on 2024-07-04 14:01

from django.db import migrations, models
from django.db.migrations.state import StateApps

import openforms.forms.migration_operations
from openforms.formio.migration_converters import convert_simple_conditionals


def fix_forms_simple_conditionals(apps, schema_editor):
    FormDefinition = apps.get_model("forms", "FormDefinition")

    all_definitions = FormDefinition.objects.all()
    if not len(all_definitions):
        return

    definitions_to_update = []
    for definition in all_definitions:
        config_modified = convert_simple_conditionals(definition.configuration)

        if config_modified:
            definitions_to_update.append(definition)

    FormDefinition.objects.bulk_update(definitions_to_update, fields=["configuration"])


def rename_authorizee_enum(apps: StateApps, _):
    FormVariable = apps.get_model("forms", "FormVariable")
    FormVariable.objects.filter(prefill_identifier_role="authorised_person").update(
        prefill_identifier_role="authorizee"
    )


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0092_v250_to_v267"),
    ]

    operations = [
        openforms.forms.migration_operations.ConvertComponentsOperation(
            component_type="select",
            identifier="fix_multiple_empty_default_value",
        ),
        migrations.RunPython(
            code=fix_forms_simple_conditionals,
            reverse_code=migrations.RunPython.noop,
        ),
        openforms.forms.migration_operations.ConvertComponentsOperation(
            component_type="addressNL",
            identifier="ensure_addressnl_has_deriveAddress",
        ),
        migrations.RunPython(
            code=rename_authorizee_enum,
            reverse_code=migrations.RunPython.noop,
        ),
        openforms.forms.migration_operations.ConvertComponentsOperation(
            component_type="textfield",
            identifier="rename_identifier_role_authorizee",
        ),
        openforms.forms.migration_operations.ConvertComponentsOperation(
            component_type="date",
            identifier="rename_identifier_role_authorizee",
        ),
        openforms.forms.migration_operations.ConvertComponentsOperation(
            component_type="datetime",
            identifier="rename_identifier_role_authorizee",
        ),
        openforms.forms.migration_operations.ConvertComponentsOperation(
            component_type="postcode",
            identifier="rename_identifier_role_authorizee",
        ),
        openforms.forms.migration_operations.ConvertComponentsOperation(
            component_type="bsn",
            identifier="rename_identifier_role_authorizee",
        ),
        migrations.AlterField(
            model_name="formvariable",
            name="prefill_identifier_role",
            field=models.CharField(
                choices=[("main", "Main"), ("authorizee", "Authorizee")],
                default="main",
                help_text="In case that multiple identifiers are returned (in the case of eHerkenning bewindvoering and DigiD Machtigen), should the prefill data related to the main identifier be used, or that related to the authorised person?",
                max_length=100,
                verbose_name="prefill identifier role",
            ),
        ),
    ]
