# Generated by Django 4.2.11 on 2024-04-04 13:47

from django.db import migrations

from openforms.forms.migration_operations import ConvertComponentsOperation


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0096_fix_invalid_validate_configuration"),
    ]

    operations = [
        ConvertComponentsOperation("select", "fix_multiple_empty_default_value")
    ]
