# Generated by Django 3.2.21 on 2023-10-23 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0096_move_time_component_validators"),
    ]

    operations = [
        migrations.AddField(
            model_name="formstep",
            name="is_applicable",
            field=models.BooleanField(
                default=True,
                help_text="Whether the step is applicable by default.",
                verbose_name="is applicable",
            ),
        ),
    ]
