# Generated by Django 4.2.11 on 2024-04-16 12:59

from django.db import migrations
import re
import json

from openforms.formio.datastructures import FormioConfigurationWrapper


def fix_forms_simple_conditionals(apps, schema_editor):
    FormDefinition = apps.get_model("forms", "FormDefinition")

    all_definitions = FormDefinition.objects.all()
    if not len(all_definitions):
        return

    # Check for simple conditionals where the "when" is not an empty string
    pattern = r'"conditional": \{[\w\s",:]*"when": "(\w+)"[\w\s",:]*\}'
    p = re.compile(pattern)

    for definition in all_definitions:
        stringified_config = json.dumps(definition.configuration)
        if not p.search(stringified_config):
            continue

        # We know that there are simple conditionals, now let's check if they need fixing
        config = FormioConfigurationWrapper(definition.configuration)

        config_modified = False
        for component in config:
            if not (
                comparison_component_key := component.get("conditional", {}).get(
                    "when", ""
                )
            ):
                continue

            comparison_component = config[comparison_component_key]
            if comparison_component["type"] in ["number", "currency"]:
                component["conditional"]["eq"] = json.loads(
                    component["conditional"]["eq"]
                )
                config_modified = True

        if config_modified:
            definition.save()


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0096_fix_invalid_validate_configuration"),
    ]

    operations = [
        migrations.RunPython(fix_forms_simple_conditionals, migrations.RunPython.noop),
    ]
