# Generated by Django 4.2.11 on 2024-09-20 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0092_v250_to_v267"),
    ]

    # RunPython operation removed as part of 3.0 release cycle - these migrations are
    # guaranteed to have been executed on Open Forms 2.8.x for existing instances.
    operations = []
