# Generated by Django 3.2.21 on 2023-10-31 15:33


from django.db import migrations

from openforms.forms.migration_operations import ConvertComponentsOperation


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0097_formstep_is_applicable"),
    ]

    operations = [
        ConvertComponentsOperation("textfield", "alter_prefill_default_values"),
        ConvertComponentsOperation("date", "alter_prefill_default_values"),
        ConvertComponentsOperation("datetime", "alter_prefill_default_values"),
        ConvertComponentsOperation("postcode", "alter_prefill_default_values"),
        ConvertComponentsOperation("bsn", "alter_prefill_default_values"),
    ]
