# Generated by Django 4.2.15 on 2024-08-21 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0097_v267_to_v270"),
    ]

    operations = [
        migrations.AddField(
            model_name="formvariable",
            name="prefill_options",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="prefill options"
            ),
        ),
    ]
