# Generated by Django 4.2.15 on 2024-09-20 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0097_extra_mimetypes_in_file_type"),
        ("forms", "0097_v267_to_v270"),
    ]

    operations = []
