# Generated by Django 4.2.11 on 2024-06-13 04:54

from django.db import migrations

from openforms.forms.migration_operations import ConvertComponentsOperation


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0098_fix_forms_conditionals"),
    ]

    operations = [
        ConvertComponentsOperation("addressNL", "ensure_addressnl_has_deriveAddress")
    ]
