# Generated by Django 4.2.17 on 2025-01-13 20:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("forms", "0098_v270_to_v300"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FormStatistics",
        ),
        migrations.CreateModel(
            name="FormSubmissionStatistics",
            fields=[],
            options={
                "verbose_name": "form submission statistics",
                "verbose_name_plural": "form submission statistics",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("logging.timelinelogproxy",),
        ),
    ]
