# Generated by Django 3.2.23 on 2023-12-27 13:01

from django.db import migrations

from openforms.forms.migration_operations import ConvertComponentsOperation


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0099_form_theme"),
    ]

    operations = [
        ConvertComponentsOperation("select", "set_openforms_datasrc"),
        ConvertComponentsOperation("radio", "set_openforms_datasrc"),
        ConvertComponentsOperation("selectboxes", "set_openforms_datasrc"),
    ]
