# Generated by Django 4.2.17 on 2025-01-14 15:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("forms", "0099_formsubmissionstatisticsv2_delete_formstatistics"),
    ]

    # ConvertComponentsOperation removed, as it's guaranteed to have been executed in
    # OF 3.2.x
    operations = []
