# Generated by Django 4.2.11 on 2024-06-19 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0099_auto_20240613_0654"),
    ]

    operations = [
        # Moved to `registrations_objects_api.0019_add_default_objects_api_group`.
    ]
