# Generated by Django 4.2.16 on 2024-09-20 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0098_merge_20240920_1808"),
        ("forms", "0099_form_show_summary_progress"),
    ]

    operations = []
