# Generated by Django 4.2.11 on 2024-06-20 14:24

from django.db import migrations

from django.db.migrations.state import StateApps
from django.db.backends.base.schema import BaseDatabaseSchemaEditor


def change_objecttype_key_name(
    apps: StateApps, schema_editor: BaseDatabaseSchemaEditor
) -> None:
    """Change the key of the Objects API registration options from `objecttype` to `objecttype_url`."""

    FormRegistrationBackend = apps.get_model("forms", "FormRegistrationBackend")

    for registration_backend in FormRegistrationBackend.objects.filter(
        backend="objects_api"
    ):
        objecttype_url = registration_backend.options.pop("objecttype")
        registration_backend.options["objecttype_url"] = objecttype_url
        registration_backend.save()


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0100_add_default_objects_api_group"),
    ]

    operations = [
        migrations.RunPython(
            change_objecttype_key_name,
            migrations.RunPython.noop,
        ),
    ]
