# Generated by Django 4.2.16 on 2024-10-18 10:28

import re

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0100_merge_20240920_1816"),
    ]

    operations = [
        migrations.AddField(
            model_name="form",
            name="price_variable_key",
            field=models.TextField(
                blank=True,
                help_text="Key of the variable that contains the calculated submission price.",
                validators=[
                    django.core.validators.RegexValidator(
                        message="Invalid variable key. It must only contain alphanumeric characters, underscores, dots and dashes and should not be ended by dash or dot.",
                        regex=re.compile("^(\\w|\\w[\\w.\\-]*\\w)$"),
                    )
                ],
                verbose_name="price variable key",
            ),
        ),
    ]
