# Generated by Django 4.2.18 on 2025-03-05 15:25

from django.db import migrations

from openforms.forms.migration_operations import ConvertComponentsOperation


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0100_add_interaction_config_to_map_component"),
    ]

    operations = [ConvertComponentsOperation("radio", "fix_empty_default_value")]
