# Generated by Django 4.2.18 on 2025-03-05 15:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("forms", "0100_add_interaction_config_to_map_component"),
    ]

    # ConvertComponentsOperatoin removed, as it's guaranteed to have been executed in
    # OF 3.2.x
    operations = []
