# Generated by Django 4.2.11 on 2024-06-24 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0100_add_default_objects_api_group"),
    ]

    operations = [
        # Moved to `registrations_objects_api.0020_objecttype_url_to_uuid`.
    ]
