# Generated by Django 3.2.23 on 2024-01-08 15:05

from django.db import migrations
from django.db.models import Q
from glom import glom, assign


def update_component_action(apps, schema_editor):
    FormLogic = apps.get_model("forms", "FormLogic")

    logic_rules = FormLogic.objects.filter(~Q(actions=[]))

    logic_rules_to_update = []
    for logic_rule in logic_rules:
        updated_rule = False
        for action in logic_rule.actions:
            if (
                glom(action, "action.type", default=None) != "property"
                or glom(action, "action.property.value", default=None) != "validate"
            ):
                continue

            value = glom(action, "action.state.required", default=None)
            if value is None:
                continue

            assign(action, "action.property.value", "validate.required")
            assign(action, "action.property.type", "bool")
            assign(action, "action.state", value)
            updated_rule = True

        if updated_rule:
            logic_rules_to_update.append(logic_rule)

    FormLogic.objects.bulk_update(logic_rules_to_update, fields=["actions"])


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0100_ensure_datasrc_property"),
    ]

    operations = [
        migrations.RunPython(update_component_action, migrations.RunPython.noop)
    ]
