# Generated by Django 3.2.23 on 2023-12-21 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0101_update_action_property"),
    ]

    operations = []
