# Generated by Django 3.2.23 on 2024-01-09 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0101_convert_formio_translations"),
    ]

    operations = []
