# Generated by Django 4.2.16 on 2024-10-22 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0101_fix_empty_default_value"),
        ("forms", "0101_form_price_variable_key"),
    ]

    operations = []
