# Generated by Django 4.2.11 on 2024-07-02 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0102_alter_formvariable_prefill_identifier_role"),
    ]

    operations = []
