# Generated by Django 4.2.20 on 2025-04-10 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0102_execute_fix_scripts"),
    ]

    operations = [
        migrations.AddField(
            model_name="form",
            name="authentication_oidc_plugin_claims",
            field=models.JSONField(
                blank=True,
                default=list,
                verbose_name="per form additional OIDC plugin authentication claims config",
            ),
        ),
    ]
