# Generated by Django 3.2.23 on 2024-01-09 11:30

from django.db import migrations

from openforms.forms.migration_operations import ConvertComponentsOperation


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0102_convert_formio_translations"),
    ]

    operations = [
        ConvertComponentsOperation("columns", "fix_column_sizes"),
        ConvertComponentsOperation("file", "fix_default_value"),
    ]
