# Generated by Django 4.2.11 on 2024-07-02 09:03

from django.db import migrations, models
from django.db.migrations.state import StateApps

from openforms.forms.migration_operations import ConvertComponentsOperation


def rename_authorizee_enum(apps: StateApps, _):
    FormVariable = apps.get_model("forms", "FormVariable")
    FormVariable.objects.filter(prefill_identifier_role="authorised_person").update(
        prefill_identifier_role="authorizee"
    )


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0102_alter_formvariable_prefill_identifier_role"),
    ]

    operations = [
        migrations.RunPython(
            rename_authorizee_enum,
            # no point in adding a reverse operation when ConvertComponent doesn't
            # support it - if it's wrong, we recommend restoring a backup.
            migrations.RunPython.noop,
        ),
        # only lists the components that have prefill
        ConvertComponentsOperation("textfield", "rename_identifier_role_authorizee"),
        ConvertComponentsOperation("date", "rename_identifier_role_authorizee"),
        ConvertComponentsOperation("datetime", "rename_identifier_role_authorizee"),
        ConvertComponentsOperation("postcode", "rename_identifier_role_authorizee"),
        ConvertComponentsOperation("bsn", "rename_identifier_role_authorizee"),
        migrations.AlterField(
            model_name="formvariable",
            name="prefill_identifier_role",
            field=models.CharField(
                choices=[("main", "Main"), ("authorizee", "Authorizee")],
                default="main",
                help_text="In case that multiple identifiers are returned (in the case of eHerkenning bewindvoering and DigiD Machtigen), should the prefill data related to the main identifier be used, or that related to the authorised person?",
                max_length=100,
                verbose_name="prefill identifier role",
            ),
        ),
    ]
