# Generated by Django 4.2.20 on 2025-04-15 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0103_fix_component_empty_default_value"),
    ]

    operations = [
        migrations.AddField(
            model_name="form",
            name="authentication_oidc_plugin_scopes",
            field=models.JSONField(
                blank=True,
                default=list,
                verbose_name="per form additional OIDC plugin authentication scopes config",
            ),
        ),
    ]
