# Generated by Django 4.2.20 on 2025-04-22 08:22

import django.db.models.deletion
from django.db import migrations, models

import openforms.authentication.fields


class Migration(migrations.Migration):
    dependencies = [
        ("forms", "0103_fix_component_empty_default_value"),
    ]

    operations = [
        migrations.CreateModel(
            name="FormAuthenticationBackend",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "backend",
                    openforms.authentication.fields.BackendChoiceField(
                        max_length=100, verbose_name="authentication backend"
                    ),
                ),
                (
                    "options",
                    models.JSONField(
                        blank=True,
                        null=True,
                        verbose_name="authentication backend options",
                    ),
                ),
                (
                    "form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auth_backends",
                        to="forms.form",
                    ),
                ),
            ],
            options={
                "verbose_name": "authentication backend",
                "verbose_name_plural": "authentication backends",
            },
        ),
        migrations.AddConstraint(
            model_name="FormAuthenticationBackend",
            constraint=models.UniqueConstraint(
                fields=("form", "backend"), name="form_backend_unique_together"
            ),
        ),
    ]
