# Generated by Django 4.2.20 on 2025-04-23 10:01

from django.db import migrations
from django.db.migrations.state import StateApps


def transform_form_authentication_backends_and_options_to_form_authentication_backend(
    apps: StateApps, _
):
    Form = apps.get_model("forms", "Form")
    FormAuthenticationBackend = apps.get_model("forms", "FormAuthenticationBackend")

    form_authentication_backends_to_create = []
    forms_to_update = []
    forms_with_authentication_backends_or_options = Form.objects.exclude(
        authentication_backend_options={}, authentication_backends=[]
    ).iterator()

    for form in forms_with_authentication_backends_or_options:
        plugins = form.authentication_backends
        config = form.authentication_backend_options

        # Collect all authentication_backends and authentication_backend_options in one list
        form_auths_to_create = {}
        for plugin in plugins:
            form_auths_to_create[plugin] = {}
        for plugin, options in config.items():
            form_auths_to_create[plugin] = options

        for plugin, options in form_auths_to_create.items():
            # Only create a FormAuthenticationBackend if it doesn't exist already
            if not FormAuthenticationBackend.objects.filter(
                form=form, backend=plugin
            ).exists():
                form_authentication_backends_to_create.append(
                    FormAuthenticationBackend(
                        form=form, backend=plugin, options=options
                    )
                )

        form.authentication_backends = []
        form.authentication_backend_options = {}
        forms_to_update.append(form)

    FormAuthenticationBackend.objects.bulk_create(
        form_authentication_backends_to_create
    )
    Form.objects.bulk_update(
        forms_to_update,
        fields=["authentication_backends", "authentication_backend_options"],
    )


def reverse_form_authentication_backend_back_to_form_authentication_backends_and_options(
    apps: StateApps, _
):
    Form = apps.get_model("forms", "Form")
    FormAuthenticationBackend = apps.get_model("forms", "FormAuthenticationBackend")

    forms_to_update_map = {}
    form_authentication_backends = FormAuthenticationBackend.objects.iterator()

    for form_authentication_backend in form_authentication_backends:
        if form_authentication_backend.form.id not in forms_to_update_map:
            # Store the form in a dict, so it can easily be found/updated
            forms_to_update_map[form_authentication_backend.form.id] = (
                form_authentication_backend.form
            )

        # Get form from update dict, and add the config of form_authentication_backend
        form = forms_to_update_map[form_authentication_backend.form.id]
        config = form.authentication_backend_options

        form.authentication_backends.append(form_authentication_backend.backend)
        config[form_authentication_backend.backend] = (
            form_authentication_backend.options
        )

    # All FormAuthenticationBackend should have been reversed, so we can delete them all
    FormAuthenticationBackend.objects.all().delete()
    Form.objects.bulk_update(
        forms_to_update_map.values(),
        fields=["authentication_backends", "authentication_backend_options"],
    )


class Migration(migrations.Migration):
    dependencies = [
        ("forms", "0104_formauthenticationbackend"),
    ]

    operations = [
        migrations.RunPython(
            transform_form_authentication_backends_and_options_to_form_authentication_backend,
            reverse_form_authentication_backend_back_to_form_authentication_backends_and_options,
        ),
    ]
