# Generated by Django 4.2.16 on 2024-11-14 09:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0104_select_datatype_string"),
    ]

    operations = [
        migrations.AlterField(
            model_name="form",
            name="all_submissions_removal_limit",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Amount of days when all submissions of this form will be permanently deleted. Leave blank to use value in General Configuration.",
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="all submissions removal limit",
            ),
        ),
        migrations.AlterField(
            model_name="form",
            name="errored_submissions_removal_limit",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Amount of days errored submissions of this form will remain before being removed. Leave blank to use value in General Configuration.",
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="errored submission removal limit",
            ),
        ),
        migrations.AlterField(
            model_name="form",
            name="incomplete_submissions_removal_limit",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Amount of days incomplete submissions of this form will remain before being removed. Leave blank to use value in General Configuration.",
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="incomplete submission removal limit",
            ),
        ),
        migrations.AlterField(
            model_name="form",
            name="successful_submissions_removal_limit",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Amount of days successful submissions of this form will remain before being removed. Leave blank to use value in General Configuration.",
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="successful submission removal limit",
            ),
        ),
    ]
