# Generated by Django 4.2.20 on 2025-04-23 10:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("forms", "0104_formauthenticationbackend"),
    ]

    # RunPython operation removed, as it's guaranteed to have been executed in OF 3.2.x
    operations = []
