# Generated by Django 4.2.16 on 2024-11-25 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0105_alter_form_all_submissions_removal_limit_and_more"),
    ]

    operations = []
