# Generated by Django 4.2.20 on 2025-04-28 11:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "forms",
            "0105_data_migrate_form_authentication_backend_options_to_form_authentication_backend",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="form",
            name="authentication_backends",
        ),
        migrations.RemoveField(
            model_name="form",
            name="authentication_backend_options",
        ),
    ]
