# Generated by Django 4.2.27 on 2025-12-24 17:50

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [
        ("forms", "0107_delete_formpricelogic"),
        ("forms", "0108_form_internal_remarks"),
        ("forms", "0109_formvariable_data_type_and_data_subtype"),
        ("forms", "0110_add_missing_data_subtype_to_existing_form_variable"),
        (
            "forms",
            "0111_formvariable_form_variable_subtype_empty_iff_data_type_is_not_array_and_more",
        ),
        ("forms", "0112_data_migrate_objects_api_group"),
        ("forms", "0113_form_new_renderer_enabled"),
        ("forms", "0114_data_migrate_yivi_form_authentication_attribute_groups"),
        ("forms", "0115_alter_formauthenticationbackend_options"),
    ]

    dependencies = [
        ("objects_api", "0006_alter_objectsapigroupconfig_catalogue_domain"),
        ("forms", "0001_initial_to_v320"),
        ("yivi_oidc", "0005_data_migrate_set_attributegroup_uuid"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FormPriceLogic",
        ),
        migrations.AddField(
            model_name="form",
            name="internal_remarks",
            field=models.TextField(
                blank=True,
                help_text="Remarks or intentions about the form. Can also be used to save notes for later use or for another admin user.",
                verbose_name="internal remarks",
            ),
        ),
        migrations.AddField(
            model_name="formvariable",
            name="data_subtype",
            field=models.CharField(
                blank=True,
                choices=[
                    ("string", "String"),
                    ("boolean", "Boolean"),
                    ("object", "Object"),
                    ("array", "Array"),
                    ("int", "Integer"),
                    ("float", "Float"),
                    ("datetime", "Datetime"),
                    ("time", "Time"),
                    ("date", "Date"),
                    ("partners", "Partners"),
                    ("children", "Children"),
                    ("editgrid", "Edit Grid"),
                ],
                help_text="This field represents the data type of the values inside the container for components that are configured as 'multiple'.",
                max_length=50,
                verbose_name="data subtype",
            ),
        ),
        migrations.AlterField(
            model_name="formvariable",
            name="data_type",
            field=models.CharField(
                choices=[
                    ("string", "String"),
                    ("boolean", "Boolean"),
                    ("object", "Object"),
                    ("array", "Array"),
                    ("int", "Integer"),
                    ("float", "Float"),
                    ("datetime", "Datetime"),
                    ("time", "Time"),
                    ("date", "Date"),
                    ("partners", "Partners"),
                    ("children", "Children"),
                    ("editgrid", "Edit Grid"),
                ],
                help_text="The type of the value that will be associated with this variable",
                max_length=50,
                verbose_name="data type",
            ),
        ),
        migrations.AddConstraint(
            model_name="formvariable",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        models.Q(
                            models.Q(
                                ("data_type", "array"),
                                models.Q(("data_subtype", ""), _negated=True),
                            ),
                            models.Q(
                                models.Q(("data_type", "array"), _negated=True),
                                ("data_subtype", ""),
                            ),
                            _connector="OR",
                        ),
                        ("source", "component"),
                    ),
                    models.Q(("source", "component"), _negated=True),
                    _connector="OR",
                ),
                name="form_variable_subtype_empty_iff_data_type_is_not_array",
            ),
        ),
        migrations.AddConstraint(
            model_name="formvariable",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("data_type__in", ("partners", "editgrid", "children")),
                    _negated=True,
                ),
                name="form_variable_data_type_is_not_subtype_exclusive",
            ),
        ),
        migrations.AddField(
            model_name="form",
            name="new_renderer_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Enable the EXPERIMENTAL new renderer. Disclaimer: the new renderer is not feature complete and is very likely to contain bugs. You should not enable this in production.",
                verbose_name="enable new renderer",
            ),
        ),
        migrations.AlterField(
            model_name="formauthenticationbackend",
            name="options",
            field=models.JSONField(
                blank=True,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                null=True,
                verbose_name="authentication backend options",
            ),
        ),
    ]
