# Generated by Django 4.2.23 on 2025-07-09 14:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("forms", "0106_remove_form_authentication_backend_options"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FormPriceLogic",
        ),
    ]
