# Generated by Django 4.2.23 on 2025-07-17 13:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forms", "0107_delete_formpricelogic"),
    ]

    operations = [
        migrations.AddField(
            model_name="form",
            name="internal_remarks",
            field=models.TextField(
                blank=True,
                help_text="Remarks or intentions about the form. Can also be used to save notes for later use or for another admin user.",
                verbose_name="internal remarks",
            ),
        ),
    ]
