# Generated by Django 4.2.23 on 2025-07-15 14:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forms", "0108_form_internal_remarks"),
    ]

    operations = [
        migrations.AddField(
            model_name="formvariable",
            name="data_subtype",
            field=models.CharField(
                blank=True,
                choices=[
                    ("string", "String"),
                    ("boolean", "Boolean"),
                    ("object", "Object"),
                    ("array", "Array"),
                    ("int", "Integer"),
                    ("float", "Float"),
                    ("datetime", "Datetime"),
                    ("time", "Time"),
                    ("date", "Date"),
                ],
                help_text="This field represents the data type of the values inside the container for components that are configured as 'multiple'.",
                max_length=50,
                verbose_name="data subtype",
            ),
        ),
    ]
