# Generated by Django 4.2.23 on 2025-07-15 14:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forms", "0108_form_internal_remarks"),
    ]

    operations = [
        migrations.AddField(
            model_name="formvariable",
            name="data_subtype",
            field=models.CharField(
                blank=True,
                choices=[
                    ("string", "String"),
                    ("boolean", "Boolean"),
                    ("object", "Object"),
                    ("array", "Array"),
                    ("int", "Integer"),
                    ("float", "Float"),
                    ("datetime", "Datetime"),
                    ("time", "Time"),
                    ("date", "Date"),
                ],
                help_text="This field represents the data type of the values inside the container for components that are configured as 'multiple'.",
                max_length=50,
                verbose_name="data subtype",
            ),
        ),
        migrations.AddConstraint(
            model_name="formvariable",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        models.Q(
                            models.Q(
                                ("data_type", "array"),
                                models.Q(("data_subtype", ""), _negated=True),
                            ),
                            models.Q(
                                models.Q(("data_type", "array"), _negated=True),
                                ("data_subtype", ""),
                            ),
                            _connector="OR",
                        ),
                        ("source", "component"),
                    ),
                    models.Q(("source", "component"), _negated=True),
                    _connector="OR",
                ),
                name="form_variable_subtype_empty_iff_data_type_is_not_array",
            ),
        ),
    ]
