# Generated by Django 4.2.23 on 2025-08-06 12:45
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("forms", "0109_formvariable_data_type_and_data_subtype"),
    ]

    # Emptied as part of the 3.4 release cycle - they're guaranteed to have been
    # executed on 3.3.x.
    operations = []
