# Generated by Django 4.2.23 on 2025-08-06 14:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forms", "0110_add_missing_data_subtype_to_existing_form_variable"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="formvariable",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        models.Q(
                            models.Q(
                                ("data_type", "array"),
                                models.Q(("data_subtype", ""), _negated=True),
                            ),
                            models.Q(
                                models.Q(("data_type", "array"), _negated=True),
                                ("data_subtype", ""),
                            ),
                            _connector="OR",
                        ),
                        ("source", "component"),
                    ),
                    models.Q(("source", "component"), _negated=True),
                    _connector="OR",
                ),
                name="form_variable_subtype_empty_iff_data_type_is_not_array",
            ),
        ),
        migrations.AddConstraint(
            model_name="formvariable",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("data_type__in", ("partners", "editgrid", "children")),
                    _negated=True,
                ),
                name="form_variable_data_type_is_not_subtype_exclusive",
            ),
        ),
    ]
