# Generated by Django 4.2.23 on 2025-08-13 15:15

from django.db import migrations
from django.db.migrations.state import StateApps


def transform_data_migrate_yivi_form_authentication_attribute_groups(
    apps: StateApps, _
):
    AttributeGroup = apps.get_model("yivi_oidc", "AttributeGroup")
    FormAuthenticationBackend = apps.get_model("forms", "FormAuthenticationBackend")

    form_authentication_backends_to_update = []
    form_authentication_backends_using_yivi = FormAuthenticationBackend.objects.filter(
        backend="yivi_oidc"
    )

    for form_authentication_backend in form_authentication_backends_using_yivi:
        if (
            additional_attributes_groups := form_authentication_backend.options.get(
                "additional_attributes_groups", []
            )
        ) and len(additional_attributes_groups):
            updated_attribute_groups = []

            for additional_attributes_group in additional_attributes_groups:
                try:
                    attribute_group = AttributeGroup.objects.get(
                        name=additional_attributes_group
                    )
                    updated_attribute_groups.append(attribute_group.slug)
                except AttributeGroup.DoesNotExist:
                    pass

            form_authentication_backend.options["additional_attributes_groups"] = (
                updated_attribute_groups
            )
            form_authentication_backends_to_update.append(form_authentication_backend)

    FormAuthenticationBackend.objects.bulk_update(
        form_authentication_backends_to_update,
        fields=["options"],
    )


def reverse_data_migrate_yivi_form_authentication_attribute_groups(apps: StateApps, _):
    AttributeGroup = apps.get_model("yivi_oidc", "AttributeGroup")
    FormAuthenticationBackend = apps.get_model("forms", "FormAuthenticationBackend")

    form_authentication_backends_to_update = []
    form_authentication_backends_using_yivi = FormAuthenticationBackend.objects.filter(
        backend="yivi_oidc"
    )

    for form_authentication_backend in form_authentication_backends_using_yivi:
        if (
            additional_attributes_groups := form_authentication_backend.options.get(
                "additional_attributes_groups", []
            )
        ) and len(additional_attributes_groups):
            updated_attribute_groups = []

            for additional_attributes_group in additional_attributes_groups:
                try:
                    attribute_group = AttributeGroup.objects.get(
                        slug=additional_attributes_group
                    )
                    updated_attribute_groups.append(attribute_group.name)
                except AttributeGroup.DoesNotExist:
                    pass

            form_authentication_backend.options["additional_attributes_groups"] = (
                updated_attribute_groups
            )
            form_authentication_backends_to_update.append(form_authentication_backend)

    FormAuthenticationBackend.objects.bulk_update(
        form_authentication_backends_to_update,
        fields=["options"],
    )


class Migration(migrations.Migration):
    dependencies = [
        (
            "forms",
            "0111_formvariable_form_variable_subtype_empty_iff_data_type_is_not_array_and_more",
        ),
        ("yivi_oidc", "0003_data_migrate_set_attributegroup_slug"),
    ]

    operations = [
        migrations.RunPython(
            transform_data_migrate_yivi_form_authentication_attribute_groups,
            reverse_data_migrate_yivi_form_authentication_attribute_groups,
        ),
    ]
