# Generated by Django 4.2.23 on 2025-08-06 12:45

from django.db import migrations
from django.db.migrations.state import StateApps

from openforms.formio.datastructures import FormioConfigurationWrapper
from openforms.formio.utils import get_component_data_subtype, get_component_datatype
from openforms.variables.constants import FormVariableDataTypes


def add_data_subtype_to_existing_form_variables(apps: StateApps, _):
    FormVariable = apps.get_model("forms", "FormVariable")
    FormDefinition = apps.get_model("forms", "FormDefinition")

    for form_definition in FormDefinition.objects.iterator():
        wrapper = FormioConfigurationWrapper(form_definition.configuration)

        variables_to_update = []
        for variable in form_definition.formvariable_set.filter(
            data_subtype="", data_type=FormVariableDataTypes.array
        ).iterator():
            if variable.key not in wrapper:
                continue

            component = wrapper[variable.key]

            # We update the data type as well to make sure there is no mismatch
            # between a (possibly) outdated array data type
            variable.data_type = get_component_datatype(component)
            variable.data_subtype = get_component_data_subtype(component)
            variables_to_update.append(variable)

        FormVariable.objects.bulk_update(
            variables_to_update, fields=["data_type", "data_subtype"]
        )


class Migration(migrations.Migration):
    dependencies = [
        ("forms", "0112_alter_formvariable_data_subtype_and_more"),
    ]

    operations = [
        migrations.RunPython(
            add_data_subtype_to_existing_form_variables,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
