# Generated by Django 4.2.23 on 2025-08-21 08:52
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "forms",
            "0113_form_new_renderer_enabled",
        ),
        ("yivi_oidc", "0005_data_migrate_set_attributegroup_uuid"),
    ]

    # Emptied as part of the 3.4 release cycle - they're guaranteed to have been
    # executed on 3.3.x.
    operations = []
