# Generated by Django 4.2.24 on 2025-09-08 12:43

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forms", "0114_data_migrate_yivi_form_authentication_attribute_groups"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formauthenticationbackend",
            name="options",
            field=models.JSONField(
                blank=True,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                null=True,
                verbose_name="authentication backend options",
            ),
        ),
    ]
