# Generated by Django 5.2.14 on 2026-06-02 07:19

import django.db.models.fields.json
from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [
        (
            "forms",
            "0116_formvariable_unique_form_id_and_profile_form_variable_for_prefill_plugin_communication_preferences",
        ),
        ("forms", "0117_stuf_zds_variables_mapping"),
        ("forms", "0118_alter_form_new_renderer_enabled"),
        ("forms", "0119_fix_component_configurations"),
        ("forms", "0120_change_disable_next_logic_action"),
        ("forms", "0121_auth_org_visible_mapping"),
        ("forms", "0122_formlogic_form_steps"),
        ("forms", "0123_form_logic_new_rule_evaluation_enabled"),
        ("forms", "0124_alter_form_new_renderer_enabled"),
        ("forms", "0125_alter_form_new_logic_evaluation_enabled"),
    ]

    dependencies = [
        ("forms", "0107_v320_to_v330"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="formvariable",
            constraint=models.UniqueConstraint(
                models.F("form_id"),
                models.F("prefill_plugin"),
                django.db.models.fields.json.KeyTransform(
                    "profile_form_variable", "prefill_options"
                ),
                condition=models.Q(("prefill_plugin", "communication_preferences")),
                name="unique_form_id_and_profile_form_variable_for_prefill_plugin_communication_preferences",
            ),
        ),
        migrations.AddField(
            model_name="formlogic",
            name="form_steps",
            field=models.ManyToManyField(
                blank=True,
                help_text="Collection of form steps on which this logic rule should be executed.",
                related_name="logic_rules",
                to="forms.formstep",
                verbose_name="form steps",
            ),
        ),
        migrations.AlterField(
            model_name="form",
            name="new_renderer_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Enable the new renderer.",
                verbose_name="enable new renderer",
            ),
        ),
        migrations.AddField(
            model_name="form",
            name="new_logic_evaluation_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Enabling this will analyze logic rules and re-order them according to their dependency on other logic rules (happens when the form is saved). Each rule will be automatically assigned to one or more steps on which it will be executed.",
                verbose_name="enable new logic rule evaluation",
            ),
        ),
    ]
