# Generated by Django 4.2.26 on 2025-12-02 16:29

import django.db.models.fields.json
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forms", "0115_alter_formauthenticationbackend_options"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="formvariable",
            constraint=models.UniqueConstraint(
                models.F("form_id"),
                models.F("prefill_plugin"),
                django.db.models.fields.json.KeyTransform(
                    "profile_form_variable", "prefill_options"
                ),
                condition=models.Q(("prefill_plugin", "communication_preferences")),
                name="unique_form_id_and_profile_form_variable_for_prefill_plugin_communication_preferences",
            ),
        ),
    ]
