# Generated by Django 4.2.27 on 2025-12-15 08:18

from django.db import migrations
from django.db.migrations.state import StateApps


def change_payment_status_update_mapping_to_variables_mapping(apps: StateApps, _):
    """
    Data migration for StUF-ZDS registration backend.

    The old key name (`payment_status_update_mapping`) for the payment variables mapping
    is changed to a more generic name so for all the saved configurations we update that
    to `variables_mapping` (it now handles the default StUF-ZDS payment variables and the
    user defined variables too).
    """
    FormRegistrationBackend = apps.get_model("forms", "FormRegistrationBackend")

    for registration_backend in FormRegistrationBackend.objects.filter(
        backend="stuf-zds-create-zaak"
    ):
        if (backend_options := registration_backend.options) and (
            backend_options.get("payment_status_update_mapping")
        ):
            backend_options["variables_mapping"] = backend_options.pop(
                "payment_status_update_mapping"
            )
            registration_backend.save(update_fields=["options"])


def change_variables_mapping_to_payment_status_update_mapping(apps: StateApps, _):
    """
    The reverse data migration.
    """
    FormRegistrationBackend = apps.get_model("forms", "FormRegistrationBackend")

    for registration_backend in FormRegistrationBackend.objects.filter(
        backend="stuf-zds-create-zaak"
    ):
        if (backend_options := registration_backend.options) and (
            backend_options.get("variables_mapping")
        ):
            backend_options["payment_status_update_mapping"] = backend_options.pop(
                "variables_mapping"
            )
            registration_backend.save(update_fields=["options"])


class Migration(migrations.Migration):
    dependencies = [
        (
            "forms",
            "0116_formvariable_unique_form_id_and_profile_form_variable_for_prefill_plugin_communication_preferences",
        ),
    ]

    operations = [
        migrations.RunPython(
            change_payment_status_update_mapping_to_variables_mapping,
            change_variables_mapping_to_payment_status_update_mapping,
        ),
    ]
