# Generated by Django 4.2.27 on 2025-12-15 08:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "forms",
            "0116_formvariable_unique_form_id_and_profile_form_variable_for_prefill_plugin_communication_preferences",
        ),
    ]

    # RunPython operation removed as part of the 4.0 dev cycle
    operations = []
