# Generated by Django 4.2.26 on 2025-11-27 14:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "forms",
            "0116_formvariable_unique_form_id_and_profile_form_variable_for_prefill_plugin_communication_preferences",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="formlogic",
            name="form_steps",
            field=models.ManyToManyField(
                blank=True,
                help_text="List of form steps on which this logic rule should be executed.",
                related_name="logic_rules",
                to="forms.formstep",
                verbose_name="form steps",
            ),
        ),
    ]
