# Generated by Django 4.2.27 on 2025-12-23 17:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forms", "0117_stuf_zds_variables_mapping"),
    ]

    operations = [
        migrations.AlterField(
            model_name="form",
            name="new_renderer_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Enable the new renderer.",
                verbose_name="enable new renderer",
            ),
        ),
    ]
