# Generated by Django 4.2.27 on 2026-01-12 11:37

from django.db import migrations

from openforms.forms.migration_operations import ConvertComponentsOperation


class Migration(migrations.Migration):
    dependencies = [
        ("forms", "0118_alter_form_new_renderer_enabled"),
    ]

    operations = [
        ConvertComponentsOperation("bsn", "fix_empty_default_value"),
        ConvertComponentsOperation("postcode", "fix_empty_default_value"),
        ConvertComponentsOperation("select", "fix_empty_default_value"),
    ]
