# Generated by Django 4.2.27 on 2026-01-12 11:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("forms", "0118_alter_form_new_renderer_enabled"),
    ]

    # ConvertComponentsOperations removed as part of the 4.0 dev cycle
    operations = []
