# Generated by Django 4.2.27 on 2026-01-07 10:25
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("forms", "0119_fix_component_configurations"),
    ]

    # RunPython operation removed as part of the 4.0 dev cycle
    operations = []
