# Generated by Django 4.2.27 on 2025-12-15 08:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "forms",
            "0120_change_disable_next_logic_action",
        ),
    ]

    # RunPython operation removed as part of the 4.0 dev cycle
    operations = []
