# Generated by Django 4.2.27 on 2025-12-15 08:18

from django.db import migrations
from django.db.migrations.state import StateApps


def add_auth_backend_option_visible(apps: StateApps, _):
    """
    Data migration for org-oidc auth backend for backward compatibility.
    """
    FormRegistrationBackend = apps.get_model("forms", "FormRegistrationBackend")
    FormRegistrationBackend.objects.filter(backend="org-oidc", options={}).update(
        options={"visible": True}
    )


def remove_auth_backend_option_visible(apps: StateApps, _):
    """
    The reverse data migration.
    """
    FormRegistrationBackend = apps.get_model("forms", "FormRegistrationBackend")
    FormRegistrationBackend.objects.filter(backend="org-oidc").exclude(
        options={}
    ).update(options={})


class Migration(migrations.Migration):
    dependencies = [
        (
            "forms",
            "0120_change_disable_next_logic_action",
        ),
    ]

    operations = [
        migrations.RunPython(
            add_auth_backend_option_visible,
            remove_auth_backend_option_visible,
        ),
    ]
