# Generated by Django 5.2.12 on 2026-03-10 10:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forms", "0123_form_logic_new_rule_evaluation_enabled"),
    ]

    operations = [
        migrations.AlterField(
            model_name="form",
            name="new_renderer_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Enable the new renderer.",
                verbose_name="enable new renderer",
            ),
        ),
    ]
