# Generated by Django 5.2.12 on 2026-03-20 08:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forms", "0124_alter_form_new_renderer_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="form",
            name="type",
            field=models.CharField(
                choices=[
                    ("regular", "Regular"),
                    ("appointment", "Appointment"),
                    ("single_page", "Single page"),
                ],
                default="regular",
                help_text="The type of the form. It can be a choice between regular, appointment and a single page form. Depending on the choice a different form design is required/rendered.",
                max_length=50,
                verbose_name="form type",
            ),
        ),
    ]
