# Generated by Django 5.2.12 on 2026-04-07 10:01

from django.db import migrations
from django.db.migrations.state import StateApps

from ..constants import FormTypeChoices


def update_existing_form_types(apps: StateApps, _):
    """
    Data migration for form type.

    The forms used to be divided to the regular and the appointment ones. Now, a new type
    (single_page_form) is required so we have a new field (type) in the Form which is
    used to define the form type. This function makes sure the existing forms in the db
    have the new field populated in the correct way.
    """
    Form = apps.get_model("forms", "Form")

    available_forms = Form.objects.all()
    for form in available_forms:
        form.type = (
            FormTypeChoices.appointment
            if form.is_appointment
            else FormTypeChoices.regular
        )
        form.save(update_fields=["type"])


def revert_form_types(apps: StateApps, _):
    """
    The reverse data migration.
    """
    Form = apps.get_model("forms", "Form")

    available_forms = Form.objects.all()
    for form in available_forms:
        if form.type == FormTypeChoices.appointment:
            form.is_appointment = True
            form.save(update_fields=["is_appointment"])


class Migration(migrations.Migration):
    dependencies = [
        ("forms", "0126_form_type"),
    ]

    operations = [
        migrations.RunPython(update_existing_form_types, revert_form_types),
    ]
