# Generated by Django 5.2.13 on 2026-04-22 08:56


from django.db import migrations
from django.db.migrations.state import StateApps
from django.db.models import Case, Value, When

from ..constants import FormTypeChoices

# TODO
# squash the migrations when it's safe


def update_existing_form_types(apps: StateApps, _):
    """
    Data migration for form type.

    The forms used to be divided between the regular and the appointment types. Now, a
    new type called single_page_form, is introduced through the new "type" field on the
    Form. This function makes sure the existing forms in the db have the new field
    populated in the correct way.
    """
    Form = apps.get_model("forms", "Form")

    available_forms = Form.objects.all()
    available_forms.update(
        type=Case(
            When(is_appointment=True, then=Value(FormTypeChoices.appointment)),
            default=Value(FormTypeChoices.regular),
        )
    )


def revert_form_types(apps: StateApps, _):
    """
    The reverse data migration.
    """
    Form = apps.get_model("forms", "Form")

    available_forms = Form.objects.all()
    available_forms.filter(type=FormTypeChoices.appointment).update(is_appointment=True)


class Migration(migrations.Migration):
    dependencies = [
        ("forms", "0126_form_type"),
    ]

    operations = [
        migrations.RunPython(update_existing_form_types, revert_form_types),
    ]
