# Generated by Django 5.2.12 on 2026-03-20 10:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("forms", "0126_update_form_type_in_existing_forms"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="form",
            name="is_appointment",
        ),
    ]
