# Generated by Django 5.2.13 on 2026-04-22 08:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("forms", "0127_update_form_type_in_existing_forms"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="form",
            name="is_appointment",
        ),
    ]
