# Generated by Django 5.2.12 on 2026-04-07 10:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forms", "0127_remove_form_is_appointment"),
    ]

    operations = [
        migrations.AddField(
            model_name="form",
            name="is_appointment",
            field=models.BooleanField(
                default=False,
                help_text="Mark the form as an appointment form. Appointment forms do not support form designer steps.",
                verbose_name="appointment enabled",
            ),
        ),
    ]
