# Generated by Django 5.2.13 on 2026-05-01 07:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("forms", "0128_remove_form_is_appointment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="form",
            name="new_renderer_enabled",
        ),
    ]
