# Generated by Django 5.2.14 on 2026-05-15 20:47

from django.db import migrations

import privates.fields


class Migration(migrations.Migration):
    dependencies = [
        ("forms", "0129_remove_form_new_renderer_enabled"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formsexport",
            name="export_content",
            field=privates.fields.PrivateMediaFileField(
                help_text="Zip file containing all the exported forms.",
                upload_to="exports/%Y/%m/%d",
                verbose_name="export content",
            ),
        ),
    ]
