# Generated by Django 5.2.14 on 2026-05-20 15:50

from django.db import migrations

from openforms.registrations.contrib.objects_api.constants import (
    PLUGIN_IDENTIFIER as OBJECTS_API_PLUGIN_IDENTIFIER,
)


def move_objects_group_config_to_backends(apps, _):
    ObjectsAPIGroupConfig = apps.get_model("objects_api", "ObjectsAPIGroupConfig")
    FormRegistrationBackend = apps.get_model("forms", "FormRegistrationBackend")

    # there is a DB constraint that validates both domain and RSIN are set at the
    # same time, or none are set
    api_groups_by_identifier = ObjectsAPIGroupConfig.objects.exclude(
        catalogue_domain=""
    ).in_bulk(field_name="identifier")
    if not api_groups_by_identifier:
        return

    backends = FormRegistrationBackend.objects.filter(
        backend=OBJECTS_API_PLUGIN_IDENTIFIER
    )
    # we can't use the registration option serializers here because they resolve to real
    # models :(

    for backend in backends:
        # shouldn't happen, but they're plain JSONFields that can have anything
        if not backend.options:
            continue
        # don't touch backends that already have an explicit catalogue - those options
        # aren't affected by the group level defaults anyway
        if isinstance(backend.options.get("catalogue"), dict):
            continue
        identifier = backend.options.get("objects_api_group", "")
        if not identifier:
            continue
        if (api_group := api_groups_by_identifier.get(identifier)) is None:
            continue

        # ok, there is stuff to copy over, let's do it (safely!)
        backend.options["catalogue"] = {
            "domain": api_group.catalogue_domain,
            "rsin": api_group.catalogue_rsin,
        }
        backend.options.setdefault(
            "iot_submission_report",
            api_group.iot_submission_report,
        )
        backend.options.setdefault(
            "iot_submission_csv",
            api_group.iot_submission_csv,
        )
        backend.options.setdefault(
            "iot_attachment",
            api_group.iot_attachment,
        )
        backend.save()


class Migration(migrations.Migration):
    dependencies = [
        ("forms", "0129_remove_form_new_renderer_enabled"),
        ("objects_api", "0006_alter_objectsapigroupconfig_catalogue_domain"),
    ]

    operations = [
        migrations.RunPython(
            move_objects_group_config_to_backends,
            # 4.0 is a major release, we can't reverse these kind of data migrations
            migrations.RunPython.noop,
        )
    ]
