# Generated by Django 5.2.14 on 2026-05-18 09:53

from django.db import migrations
from django.db.migrations.state import StateApps


def add_default_summary_document(apps: StateApps, _) -> None:
    FormRegistrationBackend = apps.get_model("forms", "FormRegistrationBackend")

    # fmt:off
    zgw_registration_backends = (
        FormRegistrationBackend.objects
        .exclude(options__isnull=True)
        .filter(
            backend="zgw-create-zaak"
        )
    )
    # fmt:on

    for backend in zgw_registration_backends:
        if "summary_documents" in backend.options:
            print(f"Not updating backend {backend}")
            continue
        backend.options["summary_documents"] = ["pdf"]
        backend.save(update_fields=("options",))


def remove_summary_options_option(apps: StateApps, _) -> None:
    FormRegistrationBackend = apps.get_model("forms", "FormRegistrationBackend")

    # fmt:off
    zgw_registration_backends = (
        FormRegistrationBackend.objects
        .exclude(options__isnull=True)
        .filter(
            backend="zgw-create-zaak"
        )
    )
    # fmt:on

    for backend in zgw_registration_backends:
        backend.options.pop("summary_documents", None)
        backend.save(update_fields=("options",))


class Migration(migrations.Migration):
    dependencies = [
        ("forms", "0129_remove_form_new_renderer_enabled"),
    ]

    operations = [
        migrations.RunPython(
            add_default_summary_document,
            reverse_code=remove_summary_options_option,
        ),
    ]
