# Generated by Django 5.2.15 on 2026-06-15 21:10

from django.db import migrations

from openforms.forms.migration_operations import ConvertComponentsOperation


class Migration(migrations.Migration):
    dependencies = [
        ("forms", "0131_move_api_group_configuration_to_backends"),
    ]

    operations = [
        ConvertComponentsOperation("date", "remove_empty_min_max_validation_spec"),
        ConvertComponentsOperation("datetime", "remove_empty_min_max_validation_spec"),
    ]
