# Generated by Django 5.2.15 on 2026-06-11 13:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("forms", "0131_move_api_group_configuration_to_backends"),
    ]

    operations = []
