# Generated by Django 5.2.15 on 2026-06-11 13:19

from collections.abc import Iterator
from itertools import chain
from typing import cast  # noqa: TID251

from django.db import migrations
from django.db.migrations.state import StateApps
from django.db.models import Model, Prefetch

from openforms.formio.service import iter_components
from openforms.formio.typing import FileComponent
from openforms.registrations.contrib.objects_api.constants import (
    PLUGIN_IDENTIFIER as OBJECTS_API_PLUGIN_IDENTIFIER,
)
from openforms.registrations.contrib.zgw_apis.plugin import (
    PLUGIN_IDENTIFIER as ZGW_APIS_PLUGIN_IDENTIFIER,
)
from openforms.registrations.contrib.zgw_apis.typing import (
    FileComponentOptions,  # identical to Objects API
)

RELEVANT_BACKENDS = {
    OBJECTS_API_PLUGIN_IDENTIFIER,
    ZGW_APIS_PLUGIN_IDENTIFIER,
}


def iter_file_components(form) -> Iterator[FileComponent]:
    step_components_generator = (
        iter_components(
            step.form_definition.configuration,
            recursive=True,
            recurse_into_editgrid=True,
        )
        for step in form.formstep_set.all()
    )
    for component in chain.from_iterable(step_components_generator):
        if component["type"] != "file":
            continue
        yield cast(FileComponent, component)


def copy_file_component_overrides_to_registration_backends(apps: StateApps, _):
    """
    Extract Documents API overrides to save them in registration backend options.

    For forms that make use of the Documents API in their registration flow (ZGW APIs,
    Objects API), there may be document type or other metadata overrides stored in file
    components in the Formio configuration. These overrides are copied into the
    backend options so that different backend requirements can be addressed (e.g.
    not all document types are used in all case types).

    A pre-requisite is that the migration tool has run on Open Forms 3.5, which is
    covered by upgrade checks. The legacy resource URLs have been translated to indirect
    references *at the component level*. However, there may still be a mismatch between
    the catalogue used for the file component configuration, and the catalogue specified
    in the registration backend. This mismatch is ignored:

    * during registration, it would either already lead to failing registrations, or
      lead to issues down the chain if something like GZAC tries to relate a case and
      document.
    * we cannot currently detect this mismatch, and this data migration is a step in the
      direction to be able to detect/validate it.
    * data migrations should definitely not depend on external services due to their
      potential of being (temporarily) unavailable.
    """
    Form: type[Model] = apps.get_model("forms", "Form")
    FormRegistrationBackend: type[Model] = apps.get_model(
        "forms", "FormRegistrationBackend"
    )
    FormStep: type[Model] = apps.get_model("forms", "FormStep")

    queryset = (
        Form.objects.prefetch_related(
            Prefetch(
                "registration_backends",
                queryset=FormRegistrationBackend.objects.filter(
                    backend__in=RELEVANT_BACKENDS
                ),
            ),
            Prefetch(
                "formstep_set",
                queryset=FormStep.objects.select_related("form_definition"),
            ),
        )
        .filter(registration_backends__backend__in=RELEVANT_BACKENDS)
        .distinct()
    )

    for form in queryset.iterator(chunk_size=10):
        files_configuration: list[FileComponentOptions] = []

        for file_component in iter_file_components(form):
            if not (registration := file_component.get("registration")):
                continue

            options: FileComponentOptions = {"key": file_component["key"]}

            if (
                doc_type_description := registration.get("documentType", {}).get(
                    "description"
                )
                or ""
            ):
                options["document_type_description"] = doc_type_description
            if org_rsin := registration.get("bronorganisatie") or "":
                options["organization_rsin"] = org_rsin
            if (
                confidentiality_level := registration.get(
                    "docVertrouwelijkheidaanduiding"
                )
                or ""
            ):
                options["confidentiality_level"] = confidentiality_level  # type: ignore
            if title := registration.get("titel") or "":
                options["title"] = title

            if set(options.keys()) != {"key"}:
                files_configuration.append(options)

        # nothing to copy, skip this form iteration
        if not files_configuration:
            continue

        for backend in form.registration_backends.all():
            backend.options["files"] = files_configuration
            backend.save(update_fields=("options",))


class Migration(migrations.Migration):
    dependencies = [
        ("forms", "0131_move_api_group_configuration_to_backends"),
    ]

    operations = [
        migrations.RunPython(
            copy_file_component_overrides_to_registration_backends,
            migrations.RunPython.noop,
        ),
    ]
