# Generated by Django 5.2.15 on 2026-07-06 10:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forms", "0133_move_file_component_registration_overrides"),
    ]

    operations = [
        migrations.AddField(
            model_name="form",
            name="help_callout_page_display",
            field=models.CharField(
                choices=[
                    ("before_start_page", "Before the start page"),
                    ("after_start_page", "After the start page"),
                    ("never", "Never"),
                ],
                default="never",
                help_text="When to display the help callout page. Note that this field is disabled when the help callout page content in the global configuration is not specified.",
                verbose_name="help callout page display",
            ),
        ),
    ]
