# Generated by Django 5.2.16 on 2026-07-27 13:03

from django.db import migrations, models

import tinymce.models

import csp_post_processor.fields


class Migration(migrations.Migration):
    dependencies = [
        ("forms", "0134_form_help_callout_page_display"),
    ]

    operations = [
        migrations.AddField(
            model_name="form",
            name="help_dialog_content",
            field=csp_post_processor.fields.CSPPostProcessedWYSIWYGField(
                base_field=tinymce.models.HTMLField(
                    blank=True,
                    help_text="Content displayed in the dialog/modal when the users clicks the help icon on a step. Leave blank to disable this functionality.",
                    verbose_name="help dialog content",
                ),
                blank=True,
                help_text="Content displayed in the dialog/modal when the users clicks the help icon on a step. Leave blank to disable this functionality.",
                verbose_name="help dialog content",
            ),
        ),
        migrations.AddField(
            model_name="form",
            name="help_dialog_content_en",
            field=csp_post_processor.fields.CSPPostProcessedWYSIWYGField(
                base_field=tinymce.models.HTMLField(
                    blank=True,
                    help_text="Content displayed in the dialog/modal when the users clicks the help icon on a step. Leave blank to disable this functionality.",
                    verbose_name="help dialog content",
                ),
                blank=True,
                help_text="Content displayed in the dialog/modal when the users clicks the help icon on a step. Leave blank to disable this functionality.",
                null=True,
                verbose_name="help dialog content",
            ),
        ),
        migrations.AddField(
            model_name="form",
            name="help_dialog_content_nl",
            field=csp_post_processor.fields.CSPPostProcessedWYSIWYGField(
                base_field=tinymce.models.HTMLField(
                    blank=True,
                    help_text="Content displayed in the dialog/modal when the users clicks the help icon on a step. Leave blank to disable this functionality.",
                    verbose_name="help dialog content",
                ),
                blank=True,
                help_text="Content displayed in the dialog/modal when the users clicks the help icon on a step. Leave blank to disable this functionality.",
                null=True,
                verbose_name="help dialog content",
            ),
        ),
        migrations.AddField(
            model_name="form",
            name="help_dialog_image",
            field=models.ImageField(
                blank=True,
                help_text="The image shown below the content in the help dialog. If no help content is configured, this has no effect.",
                upload_to="forms/help-dialog/",
                verbose_name="help dialog image",
            ),
        ),
    ]
