# Generated by Django 5.2.15 on 2026-08-26 09:31

from django.db import migrations

from openforms.forms.migration_operations import ConvertComponentsOperation


class Migration(migrations.Migration):
    dependencies = [
        ("forms", "0135_form_help_dialog_content_form_help_dialog_content_en_and_more"),
    ]

    operations = [
        ConvertComponentsOperation("time", "fix_min_max_time_default_values"),
    ]
