# Generated by Django 5.2.17 on 2026-09-01 19:35

from django.db import migrations

from openforms.forms.migration_operations import ConvertComponentsOperation


class Migration(migrations.Migration):
    dependencies = [
        ("forms", "0136_fix_min_and_max_time_default_values_in_time_component"),
    ]

    operations = [
        ConvertComponentsOperation("date", "fix_empty_default_value"),
        ConvertComponentsOperation("datetime", "fix_empty_default_value"),
        ConvertComponentsOperation("time", "fix_empty_default_value"),
    ]
