# Generated by Django 5.2.17 on 2026-09-14 14:03

from django.db import migrations
from django.db.migrations.state import StateApps

BACKENDS = ("json_dump",)


def opt_into_legacy(apps: StateApps, _):
    FormRegistrationBackend = apps.get_model("forms", "FormRegistrationBackend")
    for backend in FormRegistrationBackend.objects.filter(backend__in=BACKENDS):
        match backend.backend:
            case "json_dump":
                if "use_empty_string_for_empty_datelike_variables" in backend.options:
                    continue
                backend.options["use_empty_string_for_empty_datelike_variables"] = True
            case _:
                continue

        backend.save()


class Migration(migrations.Migration):
    dependencies = [
        ("forms", "0137_normalize_datelike_empty_default_value"),
    ]

    operations = [
        migrations.RunPython(opt_into_legacy, migrations.RunPython.noop),
    ]
