# Generated by Django 5.2.17 on 2026-09-22 19:00

from django.db import migrations

from openforms.forms.migration_operations import ConvertComponentsOperation


class Migration(migrations.Migration):
    dependencies = [
        ("forms", "0138_opt_existing_backends_into_legacy_empty_datelike_behaviour"),
    ]

    operations = [
        ConvertComponentsOperation("date", "normalize_date_default_value"),
        ConvertComponentsOperation("time", "normalize_time_default_value"),
    ]
