# Generated by Django 2.2.24 on 2021-11-29 10:25

from django.db import migrations
from django.db.models import Count


def deduplicate_emails(apps, _):
    User = apps.get_model("accounts", "User")

    dupes = (
        User.objects.values("email")
        .annotate(num_email=Count("email"))
        .filter(num_email__gt=1)
        .exclude(email="")
    )

    duplicate_emails = [result["email"] for result in dupes]

    for email in duplicate_emails:
        users = User.objects.filter(email=email).order_by("pk")
        for index, user in enumerate(users):
            if index == 0:
                continue

            user_part, host_part = user.email.rsplit("@", 1)
            user.email = f"{user_part}+duplicate{index}@{host_part}"
            user.save(update_fields=["email"])


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_auto_20210521_1352"),
    ]

    operations = [
        migrations.RunPython(deduplicate_emails, migrations.RunPython.noop),
    ]
