# Generated by Django 3.2.15 on 2022-10-05 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_auto_20211216_1550"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="employee_id",
            field=models.CharField(
                blank=True,
                help_text="Employee identification in the organisation.",
                max_length=150,
                verbose_name="employee id",
            ),
        ),
    ]
