# Generated by Django 3.2.16 on 2022-11-17 09:41

from django.db import migrations


def remove_delete_user_permission_from_groups(apps, _):
    Group = apps.get_model("auth", "group")
    Permission = apps.get_model("auth", "permission")

    delete_user_permission = Permission.objects.filter(codename="delete_user").first()
    if not delete_user_permission:
        return

    default_groups = Group.objects.filter(name__in=["Beheerders", "Functioneel beheer"])
    for group in default_groups:
        group.permissions.remove(delete_user_permission)


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_user_employee_id"),
    ]

    operations = [
        migrations.RunPython(
            remove_delete_user_permission_from_groups, migrations.RunPython.noop
        ),
    ]
