# Generated by Django 3.2.18 on 2023-02-17 16:26

from django.db import migrations, models
import openforms.accounts.managers


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_remove_delete_user_perm"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPreferences",
            fields=[],
            options={
                "verbose_name": "user preferences",
                "verbose_name_plural": "user preferences",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("accounts.user",),
            managers=[
                ("objects", openforms.accounts.managers.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="ui_language",
            field=models.CharField(
                blank=True,
                choices=[("nl", "Nederlands"), ("en", "English")],
                default="",
                help_text="Preferred (admin) UI language. If unset, your browser preferences are respected.",
                max_length=10,
                verbose_name="UI language",
            ),
        ),
    ]
