# Generated by Django 5.2.17 on 2026-09-23 09:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial_squashed_0008_auto_20230217_1726"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="raw_oidc_claims",
            field=models.JSONField(
                default=dict,
                help_text="OIDC claims obtained from the last OpenID Connect login. Contains (a subset of) the claims listed on https://openid.net/specs/openid-connect-core-1_0.html#StandardClaims.",
                verbose_name="raw OIDC claims",
            ),
        ),
    ]
