# Generated by Django 4.2.11 on 2024-07-04 13:50

import django.db.models.deletion
from django.db import migrations, models

import openforms.emails.validators
import openforms.template.validators


class Migration(migrations.Migration):
    dependencies = [
        ("forms", "0001_initial_to_v320"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfirmationEmailTemplate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        blank=True,
                        help_text="Subject of the email message",
                        max_length=1000,
                        validators=[
                            openforms.template.validators.DjangoTemplateValidator()
                        ],
                        verbose_name="subject",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True,
                        help_text="The content of the email message can contain variables that will be templated from the submitted form data.",
                        validators=[
                            openforms.template.validators.DjangoTemplateValidator(
                                backend="openforms.template.openforms_backend",
                                required_template_tags=[
                                    "appointment_information",
                                    "payment_information",
                                    "cosign_information",
                                ],
                            ),
                            openforms.emails.validators.URLSanitationValidator(),
                        ],
                        verbose_name="content",
                    ),
                ),
                (
                    "form",
                    models.OneToOneField(
                        blank=True,
                        help_text="The form for which this confirmation email template will be used",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="confirmation_email_template",
                        to="forms.form",
                        verbose_name="form",
                    ),
                ),
                (
                    "content_en",
                    models.TextField(
                        blank=True,
                        help_text="The content of the email message can contain variables that will be templated from the submitted form data.",
                        null=True,
                        validators=[
                            openforms.template.validators.DjangoTemplateValidator(
                                backend="openforms.template.openforms_backend",
                                required_template_tags=[
                                    "appointment_information",
                                    "payment_information",
                                    "cosign_information",
                                ],
                            ),
                            openforms.emails.validators.URLSanitationValidator(),
                        ],
                        verbose_name="content",
                    ),
                ),
                (
                    "content_nl",
                    models.TextField(
                        blank=True,
                        help_text="The content of the email message can contain variables that will be templated from the submitted form data.",
                        null=True,
                        validators=[
                            openforms.template.validators.DjangoTemplateValidator(
                                backend="openforms.template.openforms_backend",
                                required_template_tags=[
                                    "appointment_information",
                                    "payment_information",
                                    "cosign_information",
                                ],
                            ),
                            openforms.emails.validators.URLSanitationValidator(),
                        ],
                        verbose_name="content",
                    ),
                ),
                (
                    "subject_en",
                    models.CharField(
                        blank=True,
                        help_text="Subject of the email message",
                        max_length=1000,
                        null=True,
                        validators=[
                            openforms.template.validators.DjangoTemplateValidator()
                        ],
                        verbose_name="subject",
                    ),
                ),
                (
                    "subject_nl",
                    models.CharField(
                        blank=True,
                        help_text="Subject of the email message",
                        max_length=1000,
                        null=True,
                        validators=[
                            openforms.template.validators.DjangoTemplateValidator()
                        ],
                        verbose_name="subject",
                    ),
                ),
            ],
            options={
                "verbose_name": "Confirmation email template",
                "verbose_name_plural": "Confirmation email templates",
            },
        ),
    ]
