# Generated by Django 4.2.16 on 2024-11-19 17:07

from django.db import migrations, models

import openforms.emails.validators
import openforms.template.validators


class Migration(migrations.Migration):

    dependencies = [
        ("emails", "0001_initial_to_openforms_v270"),
    ]

    operations = [
        migrations.AddField(
            model_name="confirmationemailtemplate",
            name="cosign_content",
            field=models.TextField(
                blank=True,
                help_text="The content of the email message when cosgining is required. You must include the '{% payment_information %}' and '{% cosign_information %}' instructions. Additionally, you can use the '{% confirmation_summary %}' instruction and some additional variables - see the documentation for details.",
                validators=[
                    openforms.template.validators.DjangoTemplateValidator(
                        backend="openforms.template.openforms_backend",
                        required_template_tags=[
                            "payment_information",
                            "cosign_information",
                        ],
                    ),
                    openforms.emails.validators.URLSanitationValidator(),
                ],
                verbose_name="cosign content",
            ),
        ),
        migrations.AddField(
            model_name="confirmationemailtemplate",
            name="cosign_content_en",
            field=models.TextField(
                blank=True,
                help_text="The content of the email message when cosgining is required. You must include the '{% payment_information %}' and '{% cosign_information %}' instructions. Additionally, you can use the '{% confirmation_summary %}' instruction and some additional variables - see the documentation for details.",
                null=True,
                validators=[
                    openforms.template.validators.DjangoTemplateValidator(
                        backend="openforms.template.openforms_backend",
                        required_template_tags=[
                            "payment_information",
                            "cosign_information",
                        ],
                    ),
                    openforms.emails.validators.URLSanitationValidator(),
                ],
                verbose_name="cosign content",
            ),
        ),
        migrations.AddField(
            model_name="confirmationemailtemplate",
            name="cosign_content_nl",
            field=models.TextField(
                blank=True,
                help_text="The content of the email message when cosgining is required. You must include the '{% payment_information %}' and '{% cosign_information %}' instructions. Additionally, you can use the '{% confirmation_summary %}' instruction and some additional variables - see the documentation for details.",
                null=True,
                validators=[
                    openforms.template.validators.DjangoTemplateValidator(
                        backend="openforms.template.openforms_backend",
                        required_template_tags=[
                            "payment_information",
                            "cosign_information",
                        ],
                    ),
                    openforms.emails.validators.URLSanitationValidator(),
                ],
                verbose_name="cosign content",
            ),
        ),
        migrations.AddField(
            model_name="confirmationemailtemplate",
            name="cosign_subject",
            field=models.CharField(
                blank=True,
                help_text="Subject of the email message when the form requires cosigning.",
                max_length=1000,
                validators=[openforms.template.validators.DjangoTemplateValidator()],
                verbose_name="cosign subject",
            ),
        ),
        migrations.AddField(
            model_name="confirmationemailtemplate",
            name="cosign_subject_en",
            field=models.CharField(
                blank=True,
                help_text="Subject of the email message when the form requires cosigning.",
                max_length=1000,
                null=True,
                validators=[openforms.template.validators.DjangoTemplateValidator()],
                verbose_name="cosign subject",
            ),
        ),
        migrations.AddField(
            model_name="confirmationemailtemplate",
            name="cosign_subject_nl",
            field=models.CharField(
                blank=True,
                help_text="Subject of the email message when the form requires cosigning.",
                max_length=1000,
                null=True,
                validators=[openforms.template.validators.DjangoTemplateValidator()],
                verbose_name="cosign subject",
            ),
        ),
        migrations.AlterField(
            model_name="confirmationemailtemplate",
            name="content",
            field=models.TextField(
                blank=True,
                help_text="The content of the email message can contain variables that will be templated from the submitted form data.",
                validators=[
                    openforms.template.validators.DjangoTemplateValidator(
                        backend="openforms.template.openforms_backend",
                        required_template_tags=[
                            "appointment_information",
                            "payment_information",
                        ],
                    ),
                    openforms.emails.validators.URLSanitationValidator(),
                ],
                verbose_name="content",
            ),
        ),
        migrations.AlterField(
            model_name="confirmationemailtemplate",
            name="content_en",
            field=models.TextField(
                blank=True,
                help_text="The content of the email message can contain variables that will be templated from the submitted form data.",
                null=True,
                validators=[
                    openforms.template.validators.DjangoTemplateValidator(
                        backend="openforms.template.openforms_backend",
                        required_template_tags=[
                            "appointment_information",
                            "payment_information",
                        ],
                    ),
                    openforms.emails.validators.URLSanitationValidator(),
                ],
                verbose_name="content",
            ),
        ),
        migrations.AlterField(
            model_name="confirmationemailtemplate",
            name="content_nl",
            field=models.TextField(
                blank=True,
                help_text="The content of the email message can contain variables that will be templated from the submitted form data.",
                null=True,
                validators=[
                    openforms.template.validators.DjangoTemplateValidator(
                        backend="openforms.template.openforms_backend",
                        required_template_tags=[
                            "appointment_information",
                            "payment_information",
                        ],
                    ),
                    openforms.emails.validators.URLSanitationValidator(),
                ],
                verbose_name="content",
            ),
        ),
    ]
