# Generated by Django 2.2.24 on 2021-09-09 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emails", "0002_auto_20210521_1352"),
    ]

    operations = [
        migrations.AlterField(
            model_name="confirmationemailtemplate",
            name="form",
            field=models.OneToOneField(
                blank=True,
                help_text="The form for which this confirmation email template will be used",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="confirmation_email_template",
                to="forms.Form",
                verbose_name="form",
            ),
        ),
    ]
