# Generated by Django 4.2.16 on 2024-11-29 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("emails", "0002_confirmationemailtemplate_cosign_content_and_more"),
    ]

    # RunPython operations removed in the 3.1.0 release cycle - they're guaranteed
    # to have been executed during the 3.0.x upgrades.
    operations = []
