# Generated by Django 4.2.23 on 2025-07-09 12:35

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("emails", "0003_update_summary_tags"),
    ]

    operations = [
        migrations.RunSQL(
            sql=(
                "CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_date_created_desc "
                "ON django_yubin_message (date_created DESC);"
            ),
            reverse_sql="DROP INDEX CONCURRENTLY IF EXISTS idx_date_created_desc;",
        ),
    ]
