# Generated by Django 2.2.24 on 2021-11-17 15:58

from django.db import migrations, models

import openforms.utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ("emails", "0004_auto_20211025_1419"),
    ]

    operations = [
        migrations.AlterField(
            model_name="confirmationemailtemplate",
            name="content",
            field=models.TextField(
                blank=True,
                help_text="The content of the email message can contain variables that will be templated from the submitted form data.",
                validators=[
                    openforms.utils.validators.DjangoTemplateValidator(
                        required_template_tags=[
                            "appointment_information",
                            "payment_information",
                        ]
                    )
                ],
                verbose_name="content",
            ),
        ),
        migrations.AlterField(
            model_name="confirmationemailtemplate",
            name="subject",
            field=models.CharField(
                blank=True,
                help_text="Subject of the email message",
                max_length=1000,
                verbose_name="subject",
            ),
        ),
    ]
