# Generated by Django 3.2.13 on 2022-04-14 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="IITPrefillTestCase",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "test",
                    models.CharField(
                        help_text="The name of the test in the test data set",
                        max_length=200,
                        verbose_name="test name",
                    ),
                ),
                (
                    "bsn",
                    models.CharField(
                        help_text="BSN to connect to the prefill test data",
                        max_length=50,
                        verbose_name="test bsn",
                    ),
                ),
            ],
            options={
                "unique_together": {("test", "bsn")},
            },
        ),
    ]
