# Generated by Django 3.2.16 on 2022-11-24 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    operations = [
        migrations.CreateModel(
            name="FamilyMembersTypeConfig",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_api",
                    models.CharField(
                        choices=[
                            ("haal_centraal", "Haal Centraal"),
                            ("stuf_bg", "StufBg"),
                        ],
                        help_text="Which API to use to retrieve the data of the family members.",
                        max_length=100,
                        verbose_name="data api",
                    ),
                ),
            ],
            options={
                "verbose_name": "Family members type configuration",
                "db_table": "custom_field_types_familymemberstypeconfig",
            },
        ),
    ]
