# Generated by Django 3.2.16 on 2022-11-24 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("np_family_members", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="familymemberstypeconfig",
            table=None,
        ),
    ]
