# Generated by Django 4.2.20 on 2025-05-02 12:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("config", "0056_v300_to_v330"),
        ("np_family_members", "0002_alter_familymemberstypeconfig_table"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FamilyMembersTypeConfig",
        ),
    ]
