# Generated by Django 4.2.15 on 2024-09-04 14:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("timeline_logger", "0004_alter_fields"),
        ("forms", "0001_initial_to_v320"),
    ]

    # RunPython operation removed - it's guaranteed to have been executed during earlier
    # upgrades.
    operations = []
