# Generated by Django 2.2.20 on 2021-05-17 08:23

import django.db.models.deletion
from django.db import migrations, models

import privates.fields
import privates.storages


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SoapService",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ontvanger_organisatie",
                    models.CharField(
                        max_length=200, verbose_name="ontvanger organisatie"
                    ),
                ),
                (
                    "ontvanger_applicatie",
                    models.CharField(
                        max_length=200, verbose_name="ontvanger applicatie"
                    ),
                ),
                (
                    "zender_organisatie",
                    models.CharField(max_length=200, verbose_name="zender organisatie"),
                ),
                (
                    "zender_applicatie",
                    models.CharField(max_length=200, verbose_name="zender applicatie"),
                ),
                (
                    "url",
                    models.URLField(
                        help_text="URL of the StUF-ZDS service to connect to.",
                        verbose_name="url",
                    ),
                ),
                (
                    "user",
                    models.CharField(
                        blank=True,
                        help_text="Username to use in the XML security context.",
                        max_length=200,
                        verbose_name="user",
                    ),
                ),
                (
                    "password",
                    models.CharField(
                        blank=True,
                        help_text="Password to use in the XML security context.",
                        max_length=200,
                        verbose_name="password",
                    ),
                ),
                (
                    "certificate",
                    privates.fields.PrivateMediaFileField(
                        blank=True,
                        help_text="The SSL certificate file used for client identification. If left empty, mutual TLS is disabled.",
                        null=True,
                        storage=privates.storages.PrivateMediaFileSystemStorage(),
                        upload_to="certificate/",
                    ),
                ),
                (
                    "certificate_key",
                    privates.fields.PrivateMediaFileField(
                        blank=True,
                        help_text="The SSL certificate key file used for client identification. If left empty, mutual TLS is disabled.",
                        null=True,
                        storage=privates.storages.PrivateMediaFileSystemStorage(),
                        upload_to="certificate/",
                    ),
                ),
            ],
            options={
                "verbose_name": "Soap Service",
            },
        ),
        migrations.CreateModel(
            name="StufZDSConfig",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gemeentecode", models.CharField(max_length=32)),
                (
                    "service",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stuf_zds_config",
                        to="stuf_zds.SoapService",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
