# Generated by Django 2.2.20 on 2021-05-20 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stuf_zds", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="soapservice",
            name="endpoint_async",
            field=models.CharField(
                blank=True,
                help_text="Endpoint for asynchronous Soap request, usually '/OntvangAsynchroon'.",
                max_length=200,
                verbose_name="endpoint async requests",
            ),
        ),
        migrations.AddField(
            model_name="soapservice",
            name="endpoint_sync",
            field=models.CharField(
                blank=True,
                help_text="Endpoint for synchronous Soap request, for example '/VerwerkSynchroonVrijBericht'.",
                max_length=200,
                verbose_name="endpoint sync requests",
            ),
        ),
    ]
