# Generated by Django 2.2.20 on 2021-05-20 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stuf_zds", "0002_auto_20210520_1042"),
    ]

    operations = [
        migrations.AddField(
            model_name="stufzdsconfig",
            name="zds_zaaktype_code",
            field=models.CharField(
                default="",
                max_length=32,
                verbose_name="Zaaktype code for newly created Zaken in StUF-ZDS",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="stufzdsconfig",
            name="zds_zaaktype_omschrijving",
            field=models.CharField(
                default="",
                max_length=32,
                verbose_name="Zaaktype description for newly created Zaken in StUF-ZDS",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="stufzdsconfig",
            name="gemeentecode",
            field=models.CharField(
                max_length=32, verbose_name="Gemeentecode to register Zaken"
            ),
        ),
    ]
