# Generated by Django 2.2.20 on 2021-06-04 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stuf_zds", "0002_nice_verbose_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stufzdsconfig",
            name="gemeentecode",
            field=models.CharField(
                help_text="Municipality code to register zaken",
                max_length=32,
                verbose_name="Municipality code",
            ),
        ),
        migrations.AlterField(
            model_name="stufzdsconfig",
            name="zds_zaaktype_code",
            field=models.CharField(
                help_text="Zaaktype code for newly created zaken in StUF-ZDS",
                max_length=32,
                verbose_name="Zaaktype code",
            ),
        ),
        migrations.AlterField(
            model_name="stufzdsconfig",
            name="zds_zaaktype_omschrijving",
            field=models.CharField(
                help_text="Zaaktype description for newly created zaken in StUF-ZDS",
                max_length=32,
                verbose_name="Zaaktype description",
            ),
        ),
    ]
