# Generated by Django 3.2.20 on 2023-09-11 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("soap", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StufService",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ontvanger_organisatie",
                    models.CharField(
                        blank=True,
                        help_text="Field 'ontvanger organisatie' in StUF",
                        max_length=200,
                        verbose_name="receiving organisation",
                    ),
                ),
                (
                    "ontvanger_applicatie",
                    models.CharField(
                        help_text="Field 'ontvanger applicatie' in StUF",
                        max_length=200,
                        verbose_name="receiving application",
                    ),
                ),
                (
                    "ontvanger_administratie",
                    models.CharField(
                        blank=True,
                        help_text="Field 'ontvanger administratie' in StUF",
                        max_length=200,
                        verbose_name="receiving administration",
                    ),
                ),
                (
                    "ontvanger_gebruiker",
                    models.CharField(
                        blank=True,
                        help_text="Field 'ontvanger gebruiker' in StUF",
                        max_length=200,
                        verbose_name="receiving user",
                    ),
                ),
                (
                    "zender_organisatie",
                    models.CharField(
                        blank=True,
                        help_text="Field 'zender organisatie' in StUF",
                        max_length=200,
                        verbose_name="sending organisation",
                    ),
                ),
                (
                    "zender_applicatie",
                    models.CharField(
                        help_text="Field 'zender applicatie' in StUF",
                        max_length=200,
                        verbose_name="sending application",
                    ),
                ),
                (
                    "zender_administratie",
                    models.CharField(
                        blank=True,
                        help_text="Field 'zender administratie' in StUF",
                        max_length=200,
                        verbose_name="sending administration",
                    ),
                ),
                (
                    "zender_gebruiker",
                    models.CharField(
                        blank=True,
                        help_text="Field 'zender gebruiker' in StUF",
                        max_length=200,
                        verbose_name="sending user",
                    ),
                ),
                (
                    "endpoint_beantwoord_vraag",
                    models.URLField(
                        blank=True,
                        help_text="Endpoint for synchronous request messages, usually '[...]/BeantwoordVraag'",
                        verbose_name="endpoint BeantwoordVraag",
                    ),
                ),
                (
                    "endpoint_vrije_berichten",
                    models.URLField(
                        blank=True,
                        help_text="Endpoint for synchronous free messages, usually '[...]/VerwerkSynchroonVrijBericht' or '[...]/VrijeBerichten'.",
                        verbose_name="endpoint VrijeBerichten",
                    ),
                ),
                (
                    "endpoint_ontvang_asynchroon",
                    models.URLField(
                        blank=True,
                        help_text="Endpoint for asynchronous messages, usually '[...]/OntvangAsynchroon'.",
                        verbose_name="endpoint OntvangAsynchroon",
                    ),
                ),
                (
                    "soap_service",
                    models.OneToOneField(
                        help_text="The soap service this stuf service uses",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stuf_service",
                        to="soap.soapservice",
                    ),
                ),
            ],
            options={
                "verbose_name": "StUF service",
                "verbose_name_plural": "StUF services",
            },
        ),
    ]
