# Generated by Django 2.2.20 on 2021-06-04 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stuf", "0002_auto_20210527_1125"),
    ]

    operations = [
        migrations.AlterField(
            model_name="soapservice",
            name="endpoint_async",
            field=models.CharField(
                blank=True,
                help_text="Endpoint for asynchronous SOAP request, usually '/OntvangAsynchroon'.",
                max_length=200,
                verbose_name="endpoint async requests",
            ),
        ),
        migrations.AlterField(
            model_name="soapservice",
            name="endpoint_sync",
            field=models.CharField(
                blank=True,
                help_text="Endpoint for synchronous SOAP request, usually '/VerwerkSynchroonVrijBericht'.",
                max_length=200,
                verbose_name="endpoint sync requests",
            ),
        ),
    ]
