# Generated by Django 2.2.24 on 2021-07-22 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stuf", "0005_auto_20210722_1827"),
    ]

    # data migration removed, as these have been executed on Open Forms 2.3.0+
    operations = []
