# Generated by Django 2.2.24 on 2021-09-24 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stuf", "0006_auto_20210722_1832"),
    ]

    operations = [
        migrations.AlterField(
            model_name="soapservice",
            name="ontvanger_organisatie",
            field=models.CharField(
                blank=True,
                help_text="Field 'ontvanger organisatie' in StUF",
                max_length=200,
                verbose_name="receiving organisation",
            ),
        ),
        migrations.AlterField(
            model_name="soapservice",
            name="zender_organisatie",
            field=models.CharField(
                blank=True,
                help_text="Field 'zender organisatie' in StUF",
                max_length=200,
                verbose_name="sending organisation",
            ),
        ),
    ]
