# Generated by Django 3.2.12 on 2022-04-04 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("zgw_consumers", "0015_auto_20220307_1522"),
        ("stuf", "0008_auto_20210927_1555"),
    ]

    operations = [
        migrations.AddField(
            model_name="soapservice",
            name="soap_version",
            field=models.CharField(
                choices=[("1.1", "SOAP 1.1"), ("1.2", "SOAP 1.2")],
                default="1.2",
                help_text="The SOAP version to use for the message envelope.",
                max_length=5,
                verbose_name="SOAP version",
            ),
        ),
        migrations.AddField(
            model_name="soapservice",
            name="client_certificate",
            field=models.ForeignKey(
                blank=True,
                help_text="The SSL certificate file used for client identification. If left empty, mutual TLS is disabled.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="soap_services_client",
                to="zgw_consumers.certificate",
            ),
        ),
        migrations.AddField(
            model_name="soapservice",
            name="endpoint_security",
            field=models.CharField(
                blank=True,
                choices=[
                    ("basicauth", "Basic authentication"),
                    ("wss", "SOAP extension: WS-Security"),
                    ("wss_basicauth", "Both"),
                ],
                help_text="The security to use for messages sent to the endpoints.",
                max_length=20,
                verbose_name="Security",
            ),
        ),
        migrations.AddField(
            model_name="soapservice",
            name="password",
            field=models.CharField(
                blank=True,
                help_text="Password to use in the XML security context.",
                max_length=200,
                verbose_name="password",
            ),
        ),
        migrations.AddField(
            model_name="soapservice",
            name="server_certificate",
            field=models.ForeignKey(
                blank=True,
                help_text="The SSL/TLS certificate of the server",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="soap_services_server",
                to="zgw_consumers.certificate",
            ),
        ),
        migrations.AddField(
            model_name="soapservice",
            name="user",
            field=models.CharField(
                blank=True,
                help_text="Username to use in the XML security context.",
                max_length=200,
                verbose_name="user",
            ),
        ),
    ]
