# Generated by Django 3.2.12 on 2022-04-04 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stuf", "0009_auto_20220404_1050"),
    ]

    # made no-op for 2.0 - you should upgrade to 1.1.0 BEFORE upgrading to 2.0 to
    # automatically migrate certificate information
    operations = []
