# Generated by Django 3.2.12 on 2022-04-04 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stuf", "0010_auto_20220404_1053"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stufservice",
            name="soap_version",
        ),
        migrations.RemoveField(
            model_name="stufservice",
            name="certificate",
        ),
        migrations.RemoveField(
            model_name="stufservice",
            name="certificate_key",
        ),
        migrations.RemoveField(
            model_name="stufservice",
            name="endpoint_security",
        ),
        migrations.RemoveField(
            model_name="stufservice",
            name="password",
        ),
        migrations.RemoveField(
            model_name="stufservice",
            name="user",
        ),
    ]
