# Generated by Django 3.2.15 on 2022-09-05 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simple_certmanager", "0001_initial"),
        ("zgw_consumers", "0016_auto_20220818_1412"),
        ("stuf", "0011_auto_20220404_1119"),
    ]

    operations = [
        migrations.AlterField(
            model_name="soapservice",
            name="client_certificate",
            field=models.ForeignKey(
                blank=True,
                help_text="The SSL certificate file used for client identification. If left empty, mutual TLS is disabled.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="soap_services_client",
                to="simple_certmanager.certificate",
            ),
        ),
        migrations.AlterField(
            model_name="soapservice",
            name="server_certificate",
            field=models.ForeignKey(
                blank=True,
                help_text="The SSL/TLS certificate of the server",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="soap_services_server",
                to="simple_certmanager.certificate",
            ),
        ),
    ]
