# Generated by Django 3.2.20 on 2023-07-18 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("soap", "0001_initial"),
        ("stuf", "0012_auto_20220905_2218"),
        # The following 2 migrations are the ones that replace the link from StufBGConfig/StufZDSConfig and the SoapService.
        # So they need to have been applied before we can move the SoapService
        ("stuf_bg", "0003_auto_20211001_1300"),
        ("stuf_zds", "0006_auto_20211001_1300"),
    ]

    operations = []
