# Generated by Django 2.2.20 on 2021-05-26 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stuf_zds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StufBGConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stuf_bg_config', to='stuf_zds.SoapService')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
