# Generated by Django 4.2.27 on 2026-02-09 08:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zgw_apis", "0001_initial_to_v330"),
    ]

    operations = [
        migrations.AddField(
            model_name="zgwapigroupconfig",
            name="use_generated_zaaknummer",
            field=models.BooleanField(
                default=True,
                help_text=(
                    "Indicates whether the zaaknummer is used as public reference. "
                    "When unchecked, then the public reference is generated by Open "
                    "Forms."
                ),
                verbose_name="Use generated zaaknummer",
            ),
        ),
    ]
