# Generated by Django 2.2.20 on 2021-05-14 09:29

from django.db import migrations, models

import openforms.utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ("zgw_apis", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="zgwconfig",
            name="informatieobjecttype",
            field=models.URLField(
                blank=True,
                help_text="Default URL of the INFORMATIEOBJECTTYPE in Catalogi API",
                max_length=1000,
            ),
        ),
        migrations.AlterField(
            model_name="zgwconfig",
            name="organisatie_rsin",
            field=models.CharField(
                blank=True,
                help_text="Default RSIN of organization, which creates the ZAAK",
                max_length=9,
                validators=[openforms.utils.validators.RSINValidator()],
            ),
        ),
        migrations.AlterField(
            model_name="zgwconfig",
            name="zaaktype",
            field=models.URLField(
                blank=True,
                help_text="Default URL of the ZAAKTYPE in Catalogi API",
                max_length=1000,
            ),
        ),
    ]
