# Generated by Django 2.2.24 on 2021-09-02 19:20

from django.db import migrations, models

import openforms.utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ("zgw_apis", "0003_auto_20210521_1352"),
    ]

    operations = [
        migrations.AlterField(
            model_name="zgwconfig",
            name="organisatie_rsin",
            field=models.CharField(
                blank=True,
                help_text="Default RSIN of organization, which creates the ZAAK",
                max_length=9,
                validators=[openforms.utils.validators.RSINValidator()],
                verbose_name="organisation RSIN",
            ),
        ),
    ]
