# Generated by Django 5.2.14 on 2026-05-20 17:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("zgw_apis", "0003_alter_zgwapigroupconfig_use_generated_zaaknummer"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="zgwapigroupconfig",
            name="registrations_zgw_apis_catalogue_composite_key",
        ),
        migrations.RemoveField(
            model_name="zgwapigroupconfig",
            name="catalogue_domain",
        ),
        migrations.RemoveField(
            model_name="zgwapigroupconfig",
            name="catalogue_rsin",
        ),
    ]
