# Generated by Django 3.2.18 on 2023-02-21 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zgw_apis", "0004_auto_20210902_2120"),
    ]

    operations = [
        migrations.AddField(
            model_name="zgwconfig",
            name="auteur",
            field=models.CharField(
                default="Aanvrager", max_length=200, verbose_name="auteur"
            ),
        ),
        migrations.AddField(
            model_name="zgwconfig",
            name="doc_vertrouwelijkheidaanduiding",
            field=models.CharField(
                blank=True,
                choices=[
                    ("openbaar", "Openbaar"),
                    ("beperkt_openbaar", "Beperkt openbaar"),
                    ("intern", "Intern"),
                    ("zaakvertrouwelijk", "Zaakvertrouwelijk"),
                    ("vertrouwelijk", "Vertrouwelijk"),
                    ("confidentieel", "Confidentieel"),
                    ("geheim", "Geheim"),
                    ("zeer_geheim", "Zeer geheim"),
                ],
                help_text="Indication of the level to which extend the document associated with the ZAAK is meant to be public. Can be overridden in the file upload component of a given form.",
                max_length=24,
                verbose_name="vertrouwelijkheidaanduiding document",
            ),
        ),
        migrations.AddField(
            model_name="zgwconfig",
            name="zaak_vertrouwelijkheidaanduiding",
            field=models.CharField(
                blank=True,
                choices=[
                    ("openbaar", "Openbaar"),
                    ("beperkt_openbaar", "Beperkt openbaar"),
                    ("intern", "Intern"),
                    ("zaakvertrouwelijk", "Zaakvertrouwelijk"),
                    ("vertrouwelijk", "Vertrouwelijk"),
                    ("confidentieel", "Confidentieel"),
                    ("geheim", "Geheim"),
                    ("zeer_geheim", "Zeer geheim"),
                ],
                help_text="Indication of the level to which extend the ZAAK is meant to be public. Can be overridden in the Registration tab of a given form.",
                max_length=24,
                verbose_name="vertrouwelijkheidaanduiding zaak",
            ),
        ),
    ]
