# Generated by Django 3.2.16 on 2022-11-30 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zgw_apis", "0004_auto_20210902_2120"),
    ]

    operations = [
        migrations.AddField(
            model_name="zgwconfig",
            name="medewerker_roltype",
            field=models.URLField(
                blank=True,
                help_text="URL of the ROLTYPE to use for employees filling in a form for a citizen/company.",
                max_length=1000,
                verbose_name="medewerker roltype",
            ),
        ),
    ]
