# Generated by Django 2.2.24 on 2021-09-22 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zgw_apis', '0004_auto_20210902_2120'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestPlugin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=0)),
            ],
        ),
    ]
