# Generated by Django 3.2.19 on 2023-06-08 09:35

from django.db import migrations, models
import django.db.models.deletion
import openforms.utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ("zgw_consumers", "0019_alter_service_uuid"),
        ("zgw_apis", "0005_auto_20230221_1552"),
    ]

    operations = [
        migrations.CreateModel(
            name="ZGWApiGroupConfig",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="A recognisable name for this set of ZGW APIs.",
                        max_length=255,
                        verbose_name="name",
                    ),
                ),
                (
                    "zaaktype",
                    models.URLField(
                        blank=True,
                        help_text="Default URL of the ZAAKTYPE in the Catalogi API",
                        max_length=1000,
                        verbose_name="zaaktype",
                    ),
                ),
                (
                    "informatieobjecttype",
                    models.URLField(
                        blank=True,
                        help_text="Default URL of the INFORMATIEOBJECTTYPE in the Catalogi API",
                        max_length=1000,
                        verbose_name="informatieobjecttype",
                    ),
                ),
                (
                    "organisatie_rsin",
                    models.CharField(
                        blank=True,
                        help_text="Default RSIN of organization, which creates the ZAAK",
                        max_length=9,
                        validators=[openforms.utils.validators.RSINValidator()],
                        verbose_name="organisation RSIN",
                    ),
                ),
                (
                    "zaak_vertrouwelijkheidaanduiding",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("openbaar", "Openbaar"),
                            ("beperkt_openbaar", "Beperkt openbaar"),
                            ("intern", "Intern"),
                            ("zaakvertrouwelijk", "Zaakvertrouwelijk"),
                            ("vertrouwelijk", "Vertrouwelijk"),
                            ("confidentieel", "Confidentieel"),
                            ("geheim", "Geheim"),
                            ("zeer_geheim", "Zeer geheim"),
                        ],
                        help_text="Indication of the level to which extend the ZAAK is meant to be public. Can be overridden in the Registration tab of a given form.",
                        max_length=24,
                        verbose_name="vertrouwelijkheidaanduiding zaak",
                    ),
                ),
                (
                    "doc_vertrouwelijkheidaanduiding",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("openbaar", "Openbaar"),
                            ("beperkt_openbaar", "Beperkt openbaar"),
                            ("intern", "Intern"),
                            ("zaakvertrouwelijk", "Zaakvertrouwelijk"),
                            ("vertrouwelijk", "Vertrouwelijk"),
                            ("confidentieel", "Confidentieel"),
                            ("geheim", "Geheim"),
                            ("zeer_geheim", "Zeer geheim"),
                        ],
                        help_text="Indication of the level to which extend the document associated with the ZAAK is meant to be public. Can be overridden in the file upload component of a given form.",
                        max_length=24,
                        verbose_name="vertrouwelijkheidaanduiding document",
                    ),
                ),
                (
                    "auteur",
                    models.CharField(
                        default="Aanvrager", max_length=200, verbose_name="auteur"
                    ),
                ),
                (
                    "drc_service",
                    models.ForeignKey(
                        limit_choices_to={"api_type": "drc"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="zgwset_drc_config",
                        to="zgw_consumers.service",
                        verbose_name="Documenten API",
                        null=True,
                    ),
                ),
                (
                    "zrc_service",
                    models.ForeignKey(
                        limit_choices_to={"api_type": "zrc"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="zgwset_zrc_config",
                        to="zgw_consumers.service",
                        verbose_name="Zaken API",
                        null=True,
                    ),
                ),
                (
                    "ztc_service",
                    models.ForeignKey(
                        limit_choices_to={"api_type": "ztc"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="zgwset_ztc_config",
                        to="zgw_consumers.service",
                        verbose_name="Catalogi API",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "ZGW API set",
                "verbose_name_plural": "ZGW API sets",
            },
        ),
    ]
