# Generated by Django 3.2.19 on 2023-06-08 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zgw_apis", "0006_zgwapigroupconfig"),
    ]

    # RunPython operation removed as part of 2.7 release cycle, which requires 2.6.7 to
    # be run first.
    operations = []
