# Generated by Django 4.2.11 on 2024-03-25 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zgw_apis", "0010_zgwapigroupconfig_content_json"),
        ("forms", "0092_v250_to_v267"),
    ]

    # RunPython operation removed as part of the 2.8.0 release cycle
    operations = []
