# Generated by Django 4.2.11 on 2024-03-25 16:45

from django.db import migrations


def move_defaults_from_zgw_api_group_to_backend_options(apps, _):
    raise NotImplementedError


class Migration(migrations.Migration):

    dependencies = [
        ("zgw_apis", "0010_zgwapigroupconfig_content_json"),
        ("forms", "0096_fix_invalid_validate_configuration"),
    ]

    operations = [
        migrations.RunPython(
            move_defaults_from_zgw_api_group_to_backend_options,
            migrations.RunPython.noop,
        )
    ]
