# Generated by Django 4.2.11 on 2024-03-25 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zgw_apis", "0011_move_zgw_api_group_defaults_to_form"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="zgwapigroupconfig",
            name="informatieobjecttype",
        ),
        migrations.RemoveField(
            model_name="zgwapigroupconfig",
            name="zaaktype",
        ),
    ]
