# Generated by Django 4.2.11 on 2024-06-26 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zgw_apis", "0012_remove_zgwapigroupconfig_informatieobjecttype_and_more"),
        ("forms", "0097_v267_to_v270"),
    ]

    # RunPython operation removed as part of the 2.8.0 release cycle
    operations = []
