# Generated by Django 4.2.11 on 2024-07-17 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zgw_apis", "0013_set_zgw_api_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="zgwapigroupconfig",
            name="name",
            field=models.CharField(
                help_text="A recognisable name for this set of ZGW APIs.",
                max_length=255,
                unique=True,
                verbose_name="name",
            ),
        ),
    ]
