# Generated by Django 4.2.15 on 2024-08-19 16:37

import django.core.validators
from django.db import migrations, models

import openforms.utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ("zgw_apis", "0013_set_zgw_api_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="zgwapigroupconfig",
            name="catalogue_domain",
            field=models.CharField(
                blank=True,
                help_text="The 'domein' attribute for the Catalogus resource in the Catalogi API.",
                max_length=5,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[A-Z]*$",
                        code="invalid",
                        message="Value must be all uppercase letters.",
                    )
                ],
                verbose_name="catalogus domain",
            ),
        ),
        migrations.AddField(
            model_name="zgwapigroupconfig",
            name="catalogue_rsin",
            field=models.CharField(
                blank=True,
                help_text="The 'rsin' attribute for the Catalogus resource in the Catalogi API.",
                max_length=9,
                validators=[openforms.utils.validators.RSINValidator()],
                verbose_name="catalogus RSIN",
            ),
        ),
        migrations.AddConstraint(
            model_name="zgwapigroupconfig",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("catalogue_domain", ""), ("catalogue_rsin", "")),
                    models.Q(
                        models.Q(("catalogue_domain", ""), _negated=True),
                        models.Q(("catalogue_rsin", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="registrations_zgw_apis_catalogue_composite_key",
                violation_error_message="You must specify both domain and RSIN to uniquely identify a catalogue.",
            ),
        ),
    ]
