# Generated by Django 4.2.18 on 2025-03-17 13:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("zgw_apis", "0001_initial_to_v280"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ZgwConfig",
        ),
    ]
