# Generated by Django 4.2.16 on 2024-10-21 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0001_initial_to_v250"),
        ("registrations_objects_api", "0001_initial_to_v267"),
        ("zgw_apis", "0001_initial_to_v280"),
    ]

    # RunPython operation removed as it's guaranteed to have been executed as part of
    # the 3.0 upgrade cycle.
    operations = []
