# Generated by Django 4.2.18 on 2025-03-17 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zgw_apis", "0014_zgwapigroupconfig_catalogue_domain_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ZgwConfig",
        ),
    ]
