# Generated by Django 4.2.16 on 2024-12-02 10:30

from django.db import migrations, models
from django.utils.text import slugify


def set_zgw_api_group_config_identifier_from_name(apps, schema_editor):
    ZGWApiGroupConfig = apps.get_model("zgw_apis", "ZGWApiGroupConfig")

    def generate_unique_identifier(original_identifier, count=0):
        identifier = original_identifier + ("-" + str(count) if count else "")
        if not ZGWApiGroupConfig.objects.filter(identifier=identifier).exists():
            return identifier

        return generate_unique_identifier(original_identifier, count + 1)

    for row in ZGWApiGroupConfig.objects.all():
        candidate_slug = slugify(row.name)
        row.identifier = generate_unique_identifier(candidate_slug)
        row.save(update_fields=["identifier"])


class Migration(migrations.Migration):

    dependencies = [
        ("zgw_apis", "0015_explicit_objects_api_groups"),
    ]

    operations = [
        migrations.AddField(
            model_name="zgwapigroupconfig",
            name="identifier",
            field=models.SlugField(
                blank=True,
                help_text="A unique, human-friendly identifier to identify this group.",
                verbose_name="identifier",
            ),
        ),
        migrations.RunPython(
            set_zgw_api_group_config_identifier_from_name,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
