# Generated by Django 4.2.18 on 2025-03-17 15:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("zgw_apis", "0015_delete_zgwconfig"),
        ("zgw_apis", "0018_alter_zgwapigroupconfig_drc_service_and_more"),
    ]

    operations = []
