# Generated by Django 4.2.18 on 2025-02-04 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zgw_apis", "0019_alter_zgwapigroupconfig_auteur"),
        ("zgw_apis", "0019_alter_zgwapigroupconfig_catalogue_domain"),
    ]

    operations = []
