# Generated by Django 4.2.18 on 2025-03-17 15:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("zgw_apis", "0019_merge_20250317_1606"),
        ("zgw_apis", "0020_merge_20250204_1209"),
    ]

    operations = []
