# Generated by Django 3.2.16 on 2022-11-01 10:08


from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("digid_eherkenning", "0001_initial"),
    ]

    # Data migration removed - this was part of the 2.1 release cycle. Our upgrade checks
    # enforce that the migration was performed.
    operations = []
