# properties output because of msgspec.to_builtins call
TEXT_FIELD_DEFAULTS = {
    "autocomplete": "",
    "clearOnHide": True,
    "conditional": None,
    "defaultValue": "",
    "deriveCity": False,
    "deriveHouseNumber": "",
    "derivePostcode": "",
    "deriveStreetName": False,
    "description": "",
    "disabled": False,
    "errors": None,
    "hidden": False,
    "id": "",
    "isSensitiveData": False,
    "multiple": False,
    "openForms": None,
    "placeholder": "",
    "prefill": None,
    "registration": None,
    "showCharCount": False,
    "showInEmail": False,
    "showInPdf": True,
    "showInSummary": True,
    "tooltip": "",
    "translatedErrors": None,
    "validate": None,
    "validateOn": "blur",
}

SELECTBOXES_DEFAULTS = {
    "clearOnHide": True,
    "conditional": None,
    "defaultValue": None,
    "description": "",
    "errors": None,
    "hidden": False,
    "id": "",
    "isSensitiveData": False,
    "openForms": {
        "code": "",
        "dataSrc": "manual",
        "itemsExpression": "",
        "service": "",
        "translations": None,
    },
    "registration": None,
    "showInEmail": False,
    "showInPdf": True,
    "showInSummary": True,
    "tooltip": "",
    "translatedErrors": None,
    "validate": None,
    "values": [],
}

DATE_FIELD_DEFAULTS = {
    "clearOnHide": True,
    "conditional": None,
    "customOptions": {"allowInvalidPreload": True},
    "datePicker": None,
    "defaultValue": "",
    "description": "",
    "disabled": False,
    "errors": None,
    "hidden": False,
    "id": "",
    "isSensitiveData": False,
    "multiple": False,
    "openForms": None,
    "placeholder": "",
    "prefill": None,
    "registration": None,
    "showInEmail": False,
    "showInPdf": True,
    "showInSummary": True,
    "tooltip": "",
    "translatedErrors": None,
    "validate": None,
    "validateOn": "blur",
}

POSTCODE_FIELD_DEFAULTS = {
    "autocomplete": "",
    "clearOnHide": True,
    "conditional": None,
    "defaultValue": "",
    "description": "",
    "disabled": False,
    "errors": None,
    "hidden": False,
    "id": "",
    "isSensitiveData": False,
    "multiple": False,
    "openForms": None,
    "prefill": None,
    "registration": None,
    "showInEmail": False,
    "showInPdf": True,
    "showInSummary": True,
    "tooltip": "",
    "translatedErrors": None,
    "validate": {
        "pattern": "^[1-9][0-9]{3} ?(?!sa|sd|ss|SA|SD|SS)[a-zA-Z]{2}$",
        "plugins": [],
        "required": False,
    },
    "validateOn": "blur",
}

NUMBER_FIELD_DEFAULTS = {
    "allowNegative": False,
    "clearOnHide": True,
    "conditional": None,
    "decimalLimit": None,
    "defaultValue": None,
    "description": "",
    "errors": None,
    "hidden": False,
    "id": "",
    "isSensitiveData": False,
    "openForms": None,
    "prefix": "",
    "registration": None,
    "showInEmail": False,
    "showInPdf": True,
    "showInSummary": True,
    "suffix": "",
    "tooltip": "",
    "translatedErrors": None,
    "type": "number",
    "validate": None,
    "validateOn": "blur",
}
