# Generated by Django 2.2.20 on 2021-05-12 12:51

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ConfirmationEmailConfig",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email_template_url_allowlist",
                    django_better_admin_arrayfield.models.fields.ArrayField(
                        base_field=models.CharField(max_length=1000),
                        blank=True,
                        default=list,
                        help_text="A list of URLs (without https://www.) that will not be stripped from the content of confirmation emails",
                        size=None,
                        verbose_name="Email template URL allowlist",
                    ),
                ),
            ],
            options={
                "verbose_name": "Confirmation email configuration",
            },
        ),
    ]
