# Generated by Django 2.2.20 on 2021-05-14 08:34

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GlobalConfiguration",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email_template_netloc_allowlist",
                    django_better_admin_arrayfield.models.fields.ArrayField(
                        base_field=models.CharField(max_length=1000),
                        blank=True,
                        default=list,
                        help_text="A list of network localities (without https://www.) that will not be stripped from the content of confirmation emails",
                        size=None,
                        verbose_name="Email template netloc allowlist",
                    ),
                ),
            ],
            options={
                "verbose_name": "Global configuration",
            },
        ),
        migrations.DeleteModel(
            name="ConfirmationEmailConfig",
        ),
    ]
