# Generated by Django 2.2.20 on 2021-05-14 12:53

from django.db import migrations, models

import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0002_auto_20210514_1034"),
    ]

    operations = [
        migrations.AlterField(
            model_name="globalconfiguration",
            name="email_template_netloc_allowlist",
            field=django_better_admin_arrayfield.models.fields.ArrayField(
                base_field=models.CharField(max_length=1000),
                blank=True,
                default=list,
                help_text="Geef een lijst van toegelaten domeinen op (zonder 'https://www.'). Hyperlinks in (bevestigings)e-mails worden verwijderd, tenzij het domein hier opgegeven is.",
                size=None,
                verbose_name="Toegestane domeinen in e-mails.",
            ),
        ),
    ]
