# Generated by Django 2.2.20 on 2021-06-03 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0004_auto_20210521_1352"),
    ]

    operations = [
        migrations.AddField(
            model_name="globalconfiguration",
            name="default_test_bsn",
            field=models.CharField(
                default="",
                help_text="When provided, submissions that are started will have this BSN set as default for the session. Useful to test/demo prefill functionality.",
                max_length=9,
                verbose_name="default test BSN",
            ),
        ),
    ]
