# Generated by Django 2.2.20 on 2021-05-31 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0004_auto_20210521_1352"),
    ]

    operations = [
        migrations.AddField(
            model_name="globalconfiguration",
            name="enable_react_form",
            field=models.BooleanField(
                default=False,
                help_text="If enabled, the admin page to create forms will use the new React page.",
                verbose_name="enable React form page",
            ),
        ),
    ]
