# Generated by Django 2.2.24 on 2021-10-15 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0005_merge_20210916_1629"),
    ]

    operations = [
        migrations.AddField(
            model_name="globalconfiguration",
            name="confirmation_email_content",
            field=models.TextField(
                blank=True,
                help_text="Content of the confirmation email message. Can be overriden on the form level",
                verbose_name="content",
            ),
        ),
        migrations.AddField(
            model_name="globalconfiguration",
            name="confirmation_email_subject",
            field=models.CharField(
                blank=True,
                help_text="Subject of the confirmation email message. Can be overriden on the form level",
                max_length=1000,
                verbose_name="subject",
            ),
        ),
    ]
