# Generated by Django 2.2.24 on 2021-10-22 09:39

from django.db import migrations, models
import openforms.payments.validators


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0005_merge_20210916_1629"),
    ]

    operations = [
        migrations.AddField(
            model_name="globalconfiguration",
            name="payment_order_id_prefix",
            field=models.CharField(
                blank=True,
                default="{year}",
                help_text="Prefix to apply to generated numerical order IDs. Alpha-numerical only, supports placeholder {year}.",
                max_length=16,
                validators=[
                    openforms.payments.validators.validate_payment_order_id_prefix
                ],
                verbose_name="Payment Order ID prefix",
            ),
        ),
    ]
