# Generated by Django 2.2.20 on 2021-06-04 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0006_auto_20210603_1524"),
    ]

    operations = [
        migrations.AddField(
            model_name="globalconfiguration",
            name="display_sdk_information",
            field=models.BooleanField(
                default=False,
                help_text="When enabled, information about the used SDK is displayed.",
                verbose_name="display SDK information",
            ),
        ),
    ]
