# Generated by Django 2.2.24 on 2021-11-01 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0007_auto_20211027_1743"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="globalconfiguration",
            name="cancel_appointment_page",
        ),
    ]
