# Generated by Django 2.2.20 on 2021-06-07 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0005_globalconfiguration_enable_react_form"),
        ("config", "0007_globalconfiguration_display_sdk_information"),
    ]

    operations = []
