# Generated by Django 2.2.24 on 2021-11-10 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0008_remove_globalconfiguration_cancel_appointment_page"),
    ]

    operations = [
        migrations.AddField(
            model_name="globalconfiguration",
            name="confirmation_email_content",
            field=models.TextField(
                default="\n        Geachte heer/mevrouw,\n\n        Wij hebben uw inzending, met referentienummer {{ public_reference }}, in goede orde ontvangen.\n\n        {% summary %}\n\n        {% appointment_information %}\n\n        {% appointment_links as links %}\n        Cancel Appointment: {{ links.cancel_url|urlize }}\n\n        {% payment_information %}\n        ",
                help_text="Content of the confirmation email message. Can be overridden on the form level",
                verbose_name="confirmation email content",
            ),
        ),
        migrations.AddField(
            model_name="globalconfiguration",
            name="confirmation_email_subject",
            field=models.CharField(
                default="Bevestiging van uw inzending",
                help_text="Subject of the confirmation email message. Can be overridden on the form level",
                max_length=1000,
                verbose_name="confirmation email subject",
            ),
        ),
    ]
