# Generated by Django 2.2.20 on 2021-06-21 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0008_globalconfiguration_default_test_kvk"),
    ]

    operations = [
        migrations.AddField(
            model_name="globalconfiguration",
            name="submission_confirmation_template",
            field=models.TextField(
                default="Thank you for submitting this form.",
                help_text="The content of the submission confirmation page. It can contain variables that will be templated from the submitted form data.",
                verbose_name="submission confirmation template",
            ),
        ),
    ]
