# Generated by Django 2.2.20 on 2021-06-21 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0008_merge_20210607_1043"),
        ("config", "0008_globalconfiguration_default_test_kvk"),
    ]

    operations = []
