# Generated by Django 2.2.20 on 2021-06-21 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0009_globalconfiguration_submission_confirmation_template"),
        ("config", "0009_merge_20210621_1635"),
    ]

    operations = []
