# Generated by Django 2.2.20 on 2021-06-24 08:07

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0010_merge_20210621_1740"),
    ]

    operations = [
        migrations.AlterField(
            model_name="globalconfiguration",
            name="submission_confirmation_template",
            field=tinymce.models.HTMLField(
                default="Thank you for submitting this form.",
                help_text="The content of the submission confirmation page. It can contain variables that will be templated from the submitted form data.",
                verbose_name="submission confirmation template",
            ),
        ),
    ]
