# Generated by Django 2.2.24 on 2021-11-22 15:28

import functools

from django.db import migrations

import tinymce.models

import openforms.utils.translations


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0010_auto_20211117_1730"),
    ]

    operations = [
        migrations.AlterField(
            model_name="globalconfiguration",
            name="submission_confirmation_template",
            field=tinymce.models.HTMLField(
                default=functools.partial(
                    openforms.utils.translations.get_default,
                    *("Thank you for submitting this form.",),
                    **{}
                ),
                help_text="The content of the submission confirmation page. It can contain variables that will be templated from the submitted form data.",
                verbose_name="submission confirmation template",
            ),
        ),
    ]
