# Generated by Django 2.2.20 on 2021-06-24 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0011_auto_20210624_1007"),
    ]

    operations = [
        migrations.AddField(
            model_name="globalconfiguration",
            name="allow_empty_initiator",
            field=models.BooleanField(
                default=False,
                help_text="When enabled and the submitter is not authenticated, a case is created without any initiator. Otherwise, a fake initiator is added with BSN 111222333.",
                verbose_name="allow empty initiator",
            ),
        ),
    ]
