# Generated by Django 2.2.25 on 2021-12-31 10:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0012_datamigrate_formsessiontimeout_15mins"),
    ]

    operations = [
        migrations.AlterField(
            model_name="globalconfiguration",
            name="form_session_timeout",
            field=models.PositiveIntegerField(
                default=15,
                help_text="Amount of time in minutes a user filling in a form can be inactive for before being logged out",
                validators=[
                    django.core.validators.MinValueValidator(5),
                    django.core.validators.MaxValueValidator(
                        15,
                        message="Due to DigiD requirements this value has to be less than or equal to %(limit_value)s minutes.",
                    ),
                ],
                verbose_name="form session timeout",
            ),
        ),
    ]
