# Generated by Django 2.2.20 on 2021-07-16 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0013_auto_20210715_1615"),
    ]

    operations = [
        migrations.AddField(
            model_name="globalconfiguration",
            name="ga_code",
            field=models.CharField(
                blank=True,
                help_text="Typically looks like 'UA-XXXXX-Y'. Supplying this installs Google Analytics.",
                max_length=50,
                verbose_name="Google Analytics code",
            ),
        ),
        migrations.AddField(
            model_name="globalconfiguration",
            name="gtm_code",
            field=models.CharField(
                blank=True,
                help_text="Typically looks like 'GTM-XXXX'. Supplying this installs Google Tag Manager.",
                max_length=50,
                verbose_name="Google Tag Manager code",
            ),
        ),
        migrations.AddField(
            model_name="globalconfiguration",
            name="matomo_site_id",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="The 'idsite' of the website you're tracking in Matomo.",
                null=True,
                verbose_name="Matomo site ID",
            ),
        ),
        migrations.AddField(
            model_name="globalconfiguration",
            name="matomo_url",
            field=models.CharField(
                blank=True,
                help_text="The base URL of your Matomo server, e.g. 'matomo.example.com'.",
                max_length=255,
                verbose_name="Matomo server URL",
            ),
        ),
        migrations.AddField(
            model_name="globalconfiguration",
            name="piwik_site_id",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="The 'idsite' of the website you're tracking in Piwik.",
                null=True,
                verbose_name="Piwik site ID",
            ),
        ),
        migrations.AddField(
            model_name="globalconfiguration",
            name="piwik_url",
            field=models.CharField(
                blank=True,
                help_text="The base URL of your Piwik server, e.g. 'piwik.example.com'.",
                max_length=255,
                verbose_name="piwik server URL",
            ),
        ),
        migrations.AddField(
            model_name="globalconfiguration",
            name="siteimprove_id",
            field=models.CharField(
                blank=True,
                help_text="Your SiteImprove ID - you can find this from the embed snippet example, which should contain a URL like '//siteimproveanalytics.com/js/siteanalyze_XXXXX.js'. The XXXXX is your ID.",
                max_length=10,
                verbose_name="SiteImprove ID",
            ),
        ),
    ]
