# Generated by Django 2.2.25 on 2022-01-03 10:43

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0013_modify_form_session_timeout"),
    ]

    operations = [
        migrations.AddField(
            model_name="globalconfiguration",
            name="plugin_configuration",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True,
                default=dict,
                help_text="Configuration of plugins for authentication, payments, prefill, registrations and validation",
                verbose_name="plugin configuration",
            ),
        ),
    ]
