# Generated by Django 2.2.25 on 2022-01-06 11:39

from django.db import migrations
import functools
import openforms.config.models
import openforms.emails.validators
import openforms.utils.translations
import openforms.utils.validators
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0014_globalconfiguration_plugin_configuration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="globalconfiguration",
            name="confirmation_email_content",
            field=tinymce.models.HTMLField(
                default=openforms.config.models.get_confirmation_email_content,
                help_text="Content of the confirmation email message. Can be overridden on the form level",
                validators=[
                    openforms.utils.validators.DjangoTemplateValidator(
                        required_template_tags=[
                            "appointment_information",
                            "payment_information",
                        ]
                    ),
                    openforms.emails.validators.URLSanitationValidator(),
                ],
                verbose_name="content",
            ),
        ),
        migrations.AlterField(
            model_name="globalconfiguration",
            name="submission_confirmation_template",
            field=tinymce.models.HTMLField(
                default=functools.partial(
                    openforms.utils.translations.get_default,
                    *("Thank you for submitting this form.",),
                    **{}
                ),
                help_text="The content of the submission confirmation page. It can contain variables that will be templated from the submitted form data.",
                validators=[openforms.utils.validators.DjangoTemplateValidator()],
                verbose_name="submission confirmation template",
            ),
        ),
    ]
