# Generated by Django 2.2.25 on 2022-01-07 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0015_auto_20220106_1239"),
    ]

    operations = [
        migrations.AddField(
            model_name="globalconfiguration",
            name="enable_formio_formatters",
            field=models.BooleanField(
                default=False,
                help_text="If enabled, the FormIO specific formatters will be used when formatting submission data.",
                verbose_name="enable FormIO formatters",
            ),
        ),
    ]
