# Generated by Django 2.2.24 on 2021-07-22 09:25

from django.core.management import call_command
from django.db import migrations


def load_cookiegroups(*args):
    call_command("loaddata", "cookie_consent")


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0015_globalconfiguration_analytics_cookie_consent_group"),
        ("cookie_consent", "0002_auto__add_logitem"),
    ]

    operations = [migrations.RunPython(load_cookiegroups, migrations.RunPython.noop)]
