# Generated by Django 3.2.12 on 2022-02-15 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0016_globalconfiguration_enable_formio_formatters"),
    ]

    operations = [
        migrations.AlterField(
            model_name="globalconfiguration",
            name="design_token_values",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Values of various style parameters, such as border radii, background colors... Note that this is advanced usage. Any available but un-specified values will use fallback default values. See https://open-forms.readthedocs.io/en/latest/installation/form_hosting.html#run-time-configuration for documentation.",
                verbose_name="design token values",
            ),
        ),
        migrations.AlterField(
            model_name="globalconfiguration",
            name="plugin_configuration",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Configuration of plugins for authentication, payments, prefill, registrations and validation",
                verbose_name="plugin configuration",
            ),
        ),
    ]
