# Generated by Django 2.2.24 on 2021-07-26 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0017_auto_20210724_0801"),
        ("config", "0017_auto_20210726_0948"),
    ]

    operations = []
