# Generated by Django 3.2.12 on 2022-03-08 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0018_remove_globalconfiguration_enable_formio_formatters"),
    ]

    operations = [
        migrations.AddField(
            model_name="globalconfiguration",
            name="form_display_required_with_asterisk",
            field=models.BooleanField(
                default=True,
                help_text="Whether required fields should be displayed with an asterisk. If unchecked, optional fields will be marked with '(optional)'.",
                verbose_name="form display required with asterisk",
            ),
        ),
        migrations.AddField(
            model_name="globalconfiguration",
            name="form_fields_required_default",
            field=models.BooleanField(
                default=False,
                help_text="Whether the checkbox 'required' on form fields should be checked by default.",
                verbose_name="form fields required default",
            ),
        ),
    ]
