# Generated by Django 3.2.12 on 2022-03-10 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0018_remove_globalconfiguration_enable_formio_formatters"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="globalconfiguration",
            name="enable_react_form",
        ),
    ]
