# Generated by Django 3.2.12 on 2022-03-11 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0019_auto_20220308_1310"),
    ]

    operations = [
        migrations.AlterField(
            model_name="globalconfiguration",
            name="form_display_required_with_asterisk",
            field=models.BooleanField(
                default=True,
                help_text="If checked, required fields are marked with an asterisk and optional fields are unmarked. If unchecked, optional fields will be marked with '(optional)' and required fields are unmarked.",
                verbose_name="Mark required fields with asterisks",
            ),
        ),
        migrations.AlterField(
            model_name="globalconfiguration",
            name="form_fields_required_default",
            field=models.BooleanField(
                default=False,
                help_text="Whether the checkbox 'required' on form fields should be checked by default.",
                verbose_name="Mark form fields 'required' by default",
            ),
        ),
    ]
