# Generated by Django 2.2.24 on 2021-07-30 14:10

from django.db import migrations

import openforms.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0019_auto_20210730_1446"),
    ]

    operations = [
        migrations.AlterField(
            model_name="globalconfiguration",
            name="logo",
            field=openforms.utils.fields.SVGOrImageField(
                blank=True,
                help_text="Upload the municipality logo, visible to users filling out forms. We advise dimensions around 150px by 75px. SVG's are allowed.",
                upload_to="logo/",
                verbose_name="municipality logo",
            ),
        ),
    ]
