# Generated by Django 2.2.24 on 2021-08-30 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0020_auto_20210730_1610"),
    ]

    operations = [
        migrations.AddField(
            model_name="globalconfiguration",
            name="enable_demo_plugins",
            field=models.BooleanField(
                default=False,
                help_text="If enabled, the admin allows selection of demo backend plugins.",
                verbose_name="enable demo plugins",
            ),
        ),
    ]
