# Generated by Django 3.2.12 on 2022-03-11 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0019_remove_globalconfiguration_enable_react_form"),
        ("config", "0020_auto_20220311_1115"),
    ]

    operations = []
