# Generated by Django 2.2.24 on 2021-08-13 12:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0020_auto_20210730_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalconfiguration',
            name='all_submissions_removal_limit',
            field=models.PositiveIntegerField(default=90, help_text='Amount of days when all submissions will be permanently deleted', validators=[django.core.validators.MinValueValidator(1)], verbose_name='errored submission removal days limit'),
        ),
        migrations.AddField(
            model_name='globalconfiguration',
            name='errored_submissions_removal_limit',
            field=models.PositiveIntegerField(default=30, help_text='Amount of days errored submissions will remain before being removed', validators=[django.core.validators.MinValueValidator(1)], verbose_name='errored submission removal days limit'),
        ),
        migrations.AddField(
            model_name='globalconfiguration',
            name='errored_submissions_removal_method',
            field=models.CharField(choices=[('delete_permanently', 'Data will be permanently deleted'), ('make_anonymous', 'Data will be modified in a way to make it anonymous')], default='delete_permanently', help_text='How errored submissions will be removed after the limit of days', max_length=50, verbose_name='registration backend status'),
        ),
        migrations.AddField(
            model_name='globalconfiguration',
            name='incomplete_submissions_removal_limit',
            field=models.PositiveIntegerField(default=7, help_text='Amount of days incomplete submissions will remain before being removed', validators=[django.core.validators.MinValueValidator(1)], verbose_name='incomplete submission removal limit'),
        ),
        migrations.AddField(
            model_name='globalconfiguration',
            name='incomplete_submissions_removal_method',
            field=models.CharField(choices=[('delete_permanently', 'Data will be permanently deleted'), ('make_anonymous', 'Data will be modified in a way to make it anonymous')], default='delete_permanently', help_text='How incomplete submissions will be removed after the limit', max_length=50, verbose_name='registration backend status'),
        ),
        migrations.AddField(
            model_name='globalconfiguration',
            name='successful_submissions_removal_limit',
            field=models.PositiveIntegerField(default=7, help_text='Amount of days successful submissions will remain before being removed', validators=[django.core.validators.MinValueValidator(1)], verbose_name='successful submission removal limit'),
        ),
        migrations.AddField(
            model_name='globalconfiguration',
            name='successful_submissions_removal_method',
            field=models.CharField(choices=[('delete_permanently', 'Data will be permanently deleted'), ('make_anonymous', 'Data will be modified in a way to make it anonymous')], default='delete_permanently', help_text='How successful submissions will be removed after the limit', max_length=50, verbose_name='successful submissions removal method'),
        ),
    ]
