# Generated by Django 2.2.24 on 2021-09-03 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0021_auto_20210823_0909"),
    ]

    operations = [
        migrations.AddField(
            model_name="globalconfiguration",
            name="sdk_website",
            field=models.URLField(
                blank=True,
                help_text="URL to the SDK.",
                verbose_name="sdk website link",
            ),
        ),
    ]
