# Generated by Django 3.2.13 on 2022-04-29 09:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0021_merge_20220311_1133"),
    ]

    operations = [
        migrations.AddField(
            model_name="globalconfiguration",
            name="registration_attempt_limit",
            field=models.PositiveIntegerField(
                default=5,
                help_text="How often we attempt to register the submission at the registration backend before giving up",
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="default registration backend attempt limit",
            ),
        ),
    ]
