# Generated by Django 2.2.24 on 2021-09-03 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0021_globalconfiguration_enable_demo_plugins"),
        ("config", "0021_auto_20210823_0909"),
    ]

    operations = []
