# Generated by Django 3.2.13 on 2022-05-17 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0022_globalconfiguration_registration_attempt_limit"),
    ]

    operations = [
        migrations.AddField(
            model_name="globalconfiguration",
            name="enable_form_variables",
            field=models.BooleanField(
                default=False,
                help_text="Whether to enable form variables in the form builder.",
                verbose_name="enable form variables",
            ),
        ),
    ]
