# Generated by Django 3.2.13 on 2022-06-01 14:10
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0002_make_react_ui_default_squashed_0028_auto_20220601_1422"),
    ]

    # this used to be a data migration, but it's no longer relevant on 2.3.0+
    operations = []
