# Generated by Django 3.2.13 on 2022-07-04 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0029_rename_design_tokens"),
    ]

    operations = [
        migrations.AddField(
            model_name="globalconfiguration",
            name="piwik_pro_site_id",
            field=models.UUIDField(
                blank=True,
                help_text="The 'idsite' of the website you're tracking in Piwik PRO. https://help.piwik.pro/support/questions/find-website-id/",
                null=True,
                verbose_name="Piwik PRO site ID",
            ),
        ),
        migrations.AddField(
            model_name="globalconfiguration",
            name="piwik_pro_url",
            field=models.CharField(
                blank=True,
                help_text="The base URL of your Piwik PRO server, e.g. 'https://your-instance-name.piwik.pro/'.",
                max_length=255,
                verbose_name="Piwik PRO server URL",
            ),
        ),
    ]
