# Generated by Django 3.2.14 on 2022-07-27 10:53

from django.db import migrations, models
import functools
import openforms.config.models
import openforms.emails.validators
import openforms.utils.validators
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0030_piwik_pro_support"),
    ]

    operations = [
        migrations.AddField(
            model_name="globalconfiguration",
            name="save_form_email_content",
            field=tinymce.models.HTMLField(
                default=functools.partial(
                    openforms.config.models._render,
                    *("emails/save_form/content.html",),
                    **{}
                ),
                help_text="Content of the save form email message. Can be overridden on the form level",
                validators=[
                    openforms.utils.validators.DjangoTemplateValidator(),
                    openforms.emails.validators.URLSanitationValidator(),
                ],
                verbose_name="content",
            ),
        ),
        migrations.AddField(
            model_name="globalconfiguration",
            name="save_form_email_subject",
            field=models.CharField(
                default=functools.partial(
                    openforms.config.models._render,
                    *("emails/save_form/subject.txt",),
                    **{}
                ),
                help_text="Subject of the save form email message. Can be overridden on the form level",
                max_length=1000,
                validators=[openforms.utils.validators.DjangoTemplateValidator()],
                verbose_name="subject",
            ),
        ),
        migrations.AlterField(
            model_name="globalconfiguration",
            name="confirmation_email_content",
            field=tinymce.models.HTMLField(
                default=functools.partial(
                    openforms.config.models._render,
                    *("emails/save_form/content.html",),
                    **{}
                ),
                help_text="Content of the confirmation email message. Can be overridden on the form level",
                validators=[
                    openforms.utils.validators.DjangoTemplateValidator(
                        required_template_tags=[
                            "appointment_information",
                            "payment_information",
                        ]
                    ),
                    openforms.emails.validators.URLSanitationValidator(),
                ],
                verbose_name="content",
            ),
        ),
        migrations.AlterField(
            model_name="globalconfiguration",
            name="confirmation_email_subject",
            field=models.CharField(
                default=functools.partial(
                    openforms.config.models._render,
                    *("emails/save_form/subject.txt",),
                    **{}
                ),
                help_text="Subject of the confirmation email message. Can be overridden on the form level",
                max_length=1000,
                validators=[openforms.utils.validators.DjangoTemplateValidator()],
                verbose_name="subject",
            ),
        ),
    ]
