# Generated by Django 3.2.16 on 2022-11-29 11:41

import functools

from django.db import migrations, models

import openforms.utils.translations


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0031_auto_20221024_1507"),
    ]

    operations = [
        migrations.AlterField(
            model_name="globalconfiguration",
            name="form_previous_text",
            field=models.CharField(
                default=functools.partial(
                    openforms.utils.translations.get_default, *("Previous page",), **{}
                ),
                help_text="The text that will be displayed in the overview page to go to the previous step",
                max_length=50,
                verbose_name="back to form text",
            ),
        ),
        migrations.AlterField(
            model_name="globalconfiguration",
            name="form_previous_text_en",
            field=models.CharField(
                default=functools.partial(
                    openforms.utils.translations.get_default, *("Previous page",), **{}
                ),
                help_text="The text that will be displayed in the overview page to go to the previous step",
                max_length=50,
                null=True,
                verbose_name="back to form text",
            ),
        ),
        migrations.AlterField(
            model_name="globalconfiguration",
            name="form_previous_text_nl",
            field=models.CharField(
                default=functools.partial(
                    openforms.utils.translations.get_default, *("Previous page",), **{}
                ),
                help_text="The text that will be displayed in the overview page to go to the previous step",
                max_length=50,
                null=True,
                verbose_name="back to form text",
            ),
        ),
        migrations.AlterField(
            model_name="globalconfiguration",
            name="form_step_previous_text",
            field=models.CharField(
                default=functools.partial(
                    openforms.utils.translations.get_default, *("Previous page",), **{}
                ),
                help_text="The text that will be displayed in the form step to go to the previous step",
                max_length=50,
                verbose_name="previous step text",
            ),
        ),
        migrations.AlterField(
            model_name="globalconfiguration",
            name="form_step_previous_text_en",
            field=models.CharField(
                default=functools.partial(
                    openforms.utils.translations.get_default, *("Previous page",), **{}
                ),
                help_text="The text that will be displayed in the form step to go to the previous step",
                max_length=50,
                null=True,
                verbose_name="previous step text",
            ),
        ),
        migrations.AlterField(
            model_name="globalconfiguration",
            name="form_step_previous_text_nl",
            field=models.CharField(
                default=functools.partial(
                    openforms.utils.translations.get_default, *("Previous page",), **{}
                ),
                help_text="The text that will be displayed in the form step to go to the previous step",
                max_length=50,
                null=True,
                verbose_name="previous step text",
            ),
        ),
    ]
