# Generated by Django 3.2.15 on 2022-08-10 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0031_move_analytics_tools_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="globalconfiguration",
            name="analytics_cookie_consent_group",
        ),
        migrations.RemoveField(
            model_name="globalconfiguration",
            name="ga_code",
        ),
        migrations.RemoveField(
            model_name="globalconfiguration",
            name="gtm_code",
        ),
        migrations.RemoveField(
            model_name="globalconfiguration",
            name="matomo_site_id",
        ),
        migrations.RemoveField(
            model_name="globalconfiguration",
            name="matomo_url",
        ),
        migrations.RemoveField(
            model_name="globalconfiguration",
            name="piwik_pro_site_id",
        ),
        migrations.RemoveField(
            model_name="globalconfiguration",
            name="piwik_pro_url",
        ),
        migrations.RemoveField(
            model_name="globalconfiguration",
            name="piwik_site_id",
        ),
        migrations.RemoveField(
            model_name="globalconfiguration",
            name="piwik_url",
        ),
        migrations.RemoveField(
            model_name="globalconfiguration",
            name="siteimprove_id",
        ),
    ]
