# Generated by Django 3.2.15 on 2022-08-12 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0031_remove_globalconfiguration_enable_form_variables"),
        ("config", "0032_auto_20220810_1526"),
    ]

    operations = []
