# Generated by Django 3.2.14 on 2022-08-16 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0031_custom_email_save_form"),
        ("config", "0033_merge_20220812_1019"),
    ]

    operations = []
