# Generated by Django 3.2.16 on 2023-01-05 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0034_alter_globalconfiguration_form_upload_default_file_types"),
    ]

    # this used to be a data migration, but it's no longer relevant on 2.3.0+
    operations = []
