# Generated by Django 3.2.15 on 2022-09-05 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0035_globalconfiguration_theme_stylesheet_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="globalconfiguration",
            name="allow_indexing_form_detail",
            field=models.BooleanField(
                default=True,
                help_text="Whether form detail pages may be indexed and displayed in search engine result lists. Disable this to prevent listing.",
                verbose_name="Allow form page indexing",
            ),
        ),
    ]
