# Generated by Django 3.2.16 on 2023-01-26 14:10

from django.db import migrations
import openforms.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0036_globalconfiguration_favicon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalconfiguration',
            name='favicon',
            field=openforms.utils.fields.SVGOrImageField(blank=True, help_text='Allow the uploading of a favicon, .png .jpg .svg and .ico are compatible', upload_to='logo/', verbose_name='favicon'),
        ),
    ]
