# Generated by Django 3.2.16 on 2023-01-18 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0036_alter_globalconfiguration_form_upload_default_file_types"),
        ("config", "0036_auto_20230113_1623"),
    ]

    operations = []
