# Generated by Django 3.2.16 on 2023-02-01 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0036_globalconfiguration_favicon"),
        ("config", "0038_auto_20230127_0942"),
    ]

    operations = []
