# Generated by Django 3.2.17 on 2023-02-09 11:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0040_alter_globalconfiguration_favicon"),
    ]

    operations = [
        migrations.AddField(
            model_name="globalconfiguration",
            name="clamav_host",
            field=models.CharField(
                blank=True,
                help_text="Hostname or IP address where ClamAV is running.",
                max_length=1000,
                verbose_name="ClamAV server hostname",
            ),
        ),
        migrations.AddField(
            model_name="globalconfiguration",
            name="clamav_port",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="The TCP port on which ClamAV is listening.",
                null=True,
                validators=[django.core.validators.MaxValueValidator(65535)],
                verbose_name="ClamAV port number",
            ),
        ),
        migrations.AddField(
            model_name="globalconfiguration",
            name="clamav_timeout",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="ClamAV socket timeout expressed in seconds (optional).",
                null=True,
                validators=[django.core.validators.MaxValueValidator(60)],
                verbose_name="ClamAV socket timeout",
            ),
        ),
        migrations.AddField(
            model_name="globalconfiguration",
            name="enable_virus_scan",
            field=models.BooleanField(
                default=False,
                help_text="Whether the files uploaded by the users should be scanned by ClamAV virus scanner.In case a file is found to be infected, the file is deleted.",
                verbose_name="Enable virus scan",
            ),
        ),
    ]
