# Generated by Django 3.2.17 on 2023-02-08 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0040_alter_globalconfiguration_favicon"),
    ]

    operations = [
        migrations.AddField(
            model_name="globalconfiguration",
            name="clamdav_host",
            field=models.CharField(
                blank=True,
                help_text="Hostname or IP address where ClamdAV is running.",
                max_length=1000,
                verbose_name="ClamdAV server hostname",
            ),
        ),
        migrations.AddField(
            model_name="globalconfiguration",
            name="clamdav_port",
            field=models.IntegerField(
                blank=True,
                help_text="The TCP port on which ClamdAV is listening.",
                null=True,
                verbose_name="ClamdAV port number",
            ),
        ),
        migrations.AddField(
            model_name="globalconfiguration",
            name="clamdav_timeout",
            field=models.FloatField(
                blank=True,
                help_text="ClamdAV socket timeout (optional). Non-negative floating point number expressing seconds.",
                null=True,
                verbose_name="ClamdAV socket timeout",
            ),
        ),
        migrations.AddField(
            model_name="globalconfiguration",
            name="enable_virus_scan",
            field=models.BooleanField(
                default=False,
                help_text="Whether the files uploaded by the users should be scanned by ClamAV virus scanner.In case a file is found to be infected, the file is deleted.",
                verbose_name="Enable virus scan",
            ),
        ),
    ]
