# Generated by Django 3.2.18 on 2023-02-23 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0041_add_antivirus_config"),
    ]

    operations = [
        migrations.AddField(
            model_name="globalconfiguration",
            name="enable_service_fetch",
            field=models.BooleanField(
                default=False,
                help_text="Allow use of unfinished, unstable service fetch feature.",
                verbose_name="enable service fetch",
            ),
        ),
    ]
