# Generated by Django 3.2.18 on 2023-04-06 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0042_globalconfiguration_enable_service_fetch"),
    ]

    operations = [
        migrations.AddField(
            model_name="globalconfiguration",
            name="hide_non_applicable_steps",
            field=models.BooleanField(
                default=False,
                help_text="If checked, form steps that become non-applicable as a result of user input are hidden from the progress indicator display (by default, they are displayed but marked as non-applicable.)",
                verbose_name="Hide non-applicable form steps",
            ),
        ),
    ]
