# Generated by Django 3.2.18 on 2023-04-12 10:00

from django.db import migrations

from openforms.config.translation import GlobalConfigurationTranslationOptions


def check_confirmation_templates(apps, schema_editor):
    GlobalConfiguration = apps.get_model("config", "GlobalConfiguration")
    configs = GlobalConfiguration.objects.all()
    config_default = GlobalConfiguration.objects.create(id=0)

    translation_options = GlobalConfigurationTranslationOptions(GlobalConfiguration)
    field_names = translation_options.get_field_names()

    for config in configs:
        for field_name in field_names:
            template_attr = getattr(config, field_name)
            default_template_attr = getattr(config_default, field_name)

            if not template_attr == default_template_attr:
                field_name_nl = field_name + "_nl"
                setattr(config, field_name_nl, template_attr)

                config.save()

    GlobalConfiguration.objects.filter(id=config_default.pk).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0043_globalconfiguration_hide_non_applicable_steps"),
    ]

    operations = [
        migrations.RunPython(check_confirmation_templates, migrations.RunPython.noop)
    ]
