# Generated by Django 3.2.18 on 2023-04-14 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0043_globalconfiguration_hide_non_applicable_steps"),
        ("config", "0043_globalconfiguration_templates"),
    ]

    operations = []
