# Generated by Django 3.2.18 on 2023-05-05 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0044_merge_20230414_1827"),
    ]

    operations = [
        migrations.AddField(
            model_name="globalconfiguration",
            name="enable_react_formio_builder",
            field=models.BooleanField(
                default=False,
                help_text="Use the experimental Form.io component builder implementation. Note that this falls back to the existing builder for components that are not supported yet.",
                verbose_name="enable new formio builder",
            ),
        ),
    ]
