# Generated by Django 3.2.19 on 2023-06-15 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0047_globalconfiguration_enable_new_appointments"),
    ]

    # this used to be a data migration, but it's no longer relevant on 2.3.0+
    operations = []
