# Generated by Django 3.2.20 on 2023-07-13 10:51

import django.core.validators
from django.db import migrations, models
import openforms.config.validators


class Migration(migrations.Migration):
    dependencies = [
        ("config", "0049_auto_20230615_1507"),
    ]

    operations = [
        migrations.AddField(
            model_name="globalconfiguration",
            name="form_map_default_latitude",
            field=models.FloatField(
                blank=True,
                default=52.132633,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(-180.0),
                    django.core.validators.MaxValueValidator(180.0),
                    openforms.config.validators.FloatValidator(
                        decimal_places=7, max_digits=10
                    ),
                ],
                verbose_name="The default latitude for the leaflet map.",
            ),
        ),
        migrations.AddField(
            model_name="globalconfiguration",
            name="form_map_default_longitude",
            field=models.FloatField(
                blank=True,
                default=5.291266,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(-90.0),
                    django.core.validators.MaxValueValidator(90.0),
                    openforms.config.validators.FloatValidator(
                        decimal_places=7, max_digits=9
                    ),
                ],
                verbose_name="The default longitude for the leaflet map.",
            ),
        ),
        migrations.AddField(
            model_name="globalconfiguration",
            name="form_map_default_zoom_level",
            field=models.IntegerField(
                blank=True,
                default=13,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(13.0),
                ],
                verbose_name="The default zoom level for the leaflet map.",
            ),
        ),
    ]
