# Generated by Django 3.2.20 on 2023-08-02 16:22

from django.db import migrations, models
import openforms.template.validators
import tinymce.models


class Migration(migrations.Migration):
    dependencies = [
        ("config", "0050_auto_20230714_1419"),
    ]

    operations = [
        migrations.AddField(
            model_name="globalconfiguration",
            name="ask_truth_consent",
            field=models.BooleanField(
                default=True,
                help_text="If enabled, the user will have to agree that he filled the form out truthfully before submitting it.",
                verbose_name="ask truth consent",
            ),
        ),
        migrations.AlterField(
            model_name="globalconfiguration",
            name="privacy_policy_label",
            field=tinymce.models.HTMLField(
                blank=True,
                default="Ik verklaar dat ik deze aanvraag naar waarheid heb ingevuld en geen informatie heb verzwegen.",
                help_text="The label of the checkbox that prompts the user to agree that he filled out the form truthfully.",
                validators=[
                    openforms.template.validators.DjangoTemplateValidator(
                        backend="openforms.template.openforms_backend"
                    )
                ],
                verbose_name="truth label",
            ),
        ),
        migrations.AlterField(
            model_name="globalconfiguration",
            name="privacy_policy_label_en",
            field=tinymce.models.HTMLField(
                blank=True,
                default="Ik verklaar dat ik deze aanvraag naar waarheid heb ingevuld en geen informatie heb verzwegen.",
                help_text="The label of the checkbox that prompts the user to agree that he filled out the form truthfully.",
                null=True,
                validators=[
                    openforms.template.validators.DjangoTemplateValidator(
                        backend="openforms.template.openforms_backend"
                    )
                ],
                verbose_name="truth label",
            ),
        ),
        migrations.AlterField(
            model_name="globalconfiguration",
            name="privacy_policy_label_nl",
            field=tinymce.models.HTMLField(
                blank=True,
                default="Ik verklaar dat ik deze aanvraag naar waarheid heb ingevuld en geen informatie heb verzwegen.",
                help_text="The label of the checkbox that prompts the user to agree that he filled out the form truthfully.",
                null=True,
                validators=[
                    openforms.template.validators.DjangoTemplateValidator(
                        backend="openforms.template.openforms_backend"
                    )
                ],
                verbose_name="truth label",
            ),
        ),
    ]
