# Generated by Django 3.2.20 on 2023-08-11 10:17

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0050_auto_20230714_1419"),
    ]

    operations = [
        migrations.AddField(
            model_name="globalconfiguration",
            name="ask_statement_of_truth",
            field=models.BooleanField(
                default=False,
                help_text="If enabled, the user will have to agree that they filled out the form truthfully before submitting it.",
                verbose_name="ask statement of truth",
            ),
        ),
        migrations.AddField(
            model_name="globalconfiguration",
            name="statement_of_truth_label",
            field=tinymce.models.HTMLField(
                blank=True,
                default="Ik verklaar dat ik deze aanvraag naar waarheid heb ingevuld en geen informatie heb verzwegen.",
                help_text="The label of the checkbox that prompts the user to agree that they filled out the form truthfully. Note that this field does not have templating support.",
                verbose_name="statement of truth label",
            ),
        ),
        migrations.AddField(
            model_name="globalconfiguration",
            name="statement_of_truth_label_en",
            field=tinymce.models.HTMLField(
                blank=True,
                default="Ik verklaar dat ik deze aanvraag naar waarheid heb ingevuld en geen informatie heb verzwegen.",
                help_text="The label of the checkbox that prompts the user to agree that they filled out the form truthfully. Note that this field does not have templating support.",
                null=True,
                verbose_name="statement of truth label",
            ),
        ),
        migrations.AddField(
            model_name="globalconfiguration",
            name="statement_of_truth_label_nl",
            field=tinymce.models.HTMLField(
                blank=True,
                default="Ik verklaar dat ik deze aanvraag naar waarheid heb ingevuld en geen informatie heb verzwegen.",
                help_text="The label of the checkbox that prompts the user to agree that they filled out the form truthfully. Note that this field does not have templating support.",
                null=True,
                verbose_name="statement of truth label",
            ),
        ),
    ]
