# Generated by Django 3.2.20 on 2023-08-02 16:24

from django.db import migrations
import openforms.template.validators
import tinymce.models


class Migration(migrations.Migration):
    dependencies = [
        ("config", "0051_auto_20230802_1822"),
    ]

    operations = [
        migrations.AddField(
            model_name="globalconfiguration",
            name="truth_label",
            field=tinymce.models.HTMLField(
                blank=True,
                default="Ik verklaar dat ik deze aanvraag naar waarheid heb ingevuld en geen informatie heb verzwegen.",
                help_text="The label of the checkbox that prompts the user to agree that he filled out the form truthfully.",
                validators=[
                    openforms.template.validators.DjangoTemplateValidator(
                        backend="openforms.template.openforms_backend"
                    )
                ],
                verbose_name="truth label",
            ),
        ),
        migrations.AddField(
            model_name="globalconfiguration",
            name="truth_label_en",
            field=tinymce.models.HTMLField(
                blank=True,
                default="Ik verklaar dat ik deze aanvraag naar waarheid heb ingevuld en geen informatie heb verzwegen.",
                help_text="The label of the checkbox that prompts the user to agree that he filled out the form truthfully.",
                null=True,
                validators=[
                    openforms.template.validators.DjangoTemplateValidator(
                        backend="openforms.template.openforms_backend"
                    )
                ],
                verbose_name="truth label",
            ),
        ),
        migrations.AddField(
            model_name="globalconfiguration",
            name="truth_label_nl",
            field=tinymce.models.HTMLField(
                blank=True,
                default="Ik verklaar dat ik deze aanvraag naar waarheid heb ingevuld en geen informatie heb verzwegen.",
                help_text="The label of the checkbox that prompts the user to agree that he filled out the form truthfully.",
                null=True,
                validators=[
                    openforms.template.validators.DjangoTemplateValidator(
                        backend="openforms.template.openforms_backend"
                    )
                ],
                verbose_name="truth label",
            ),
        ),
        migrations.AlterField(
            model_name="globalconfiguration",
            name="privacy_policy_label",
            field=tinymce.models.HTMLField(
                blank=True,
                default="Ja, ik heb kennis genomen van het {% privacy_policy %} en geef uitdrukkelijk toestemming voor het verwerken van de door mij opgegeven gegevens.",
                help_text="The label of the checkbox that prompts the user to agree to the privacy policy.",
                validators=[
                    openforms.template.validators.DjangoTemplateValidator(
                        backend="openforms.template.openforms_backend",
                        required_template_tags=["privacy_policy"],
                    )
                ],
                verbose_name="privacy policy label",
            ),
        ),
        migrations.AlterField(
            model_name="globalconfiguration",
            name="privacy_policy_label_en",
            field=tinymce.models.HTMLField(
                blank=True,
                default="Ja, ik heb kennis genomen van het {% privacy_policy %} en geef uitdrukkelijk toestemming voor het verwerken van de door mij opgegeven gegevens.",
                help_text="The label of the checkbox that prompts the user to agree to the privacy policy.",
                null=True,
                validators=[
                    openforms.template.validators.DjangoTemplateValidator(
                        backend="openforms.template.openforms_backend",
                        required_template_tags=["privacy_policy"],
                    )
                ],
                verbose_name="privacy policy label",
            ),
        ),
        migrations.AlterField(
            model_name="globalconfiguration",
            name="privacy_policy_label_nl",
            field=tinymce.models.HTMLField(
                blank=True,
                default="Ja, ik heb kennis genomen van het {% privacy_policy %} en geef uitdrukkelijk toestemming voor het verwerken van de door mij opgegeven gegevens.",
                help_text="The label of the checkbox that prompts the user to agree to the privacy policy.",
                null=True,
                validators=[
                    openforms.template.validators.DjangoTemplateValidator(
                        backend="openforms.template.openforms_backend",
                        required_template_tags=["privacy_policy"],
                    )
                ],
                verbose_name="privacy policy label",
            ),
        ),
    ]
