# Generated by Django 3.2.21 on 2023-09-08 08:46

import functools

from django.db import migrations

import tinymce.models

import openforms.template.validators
import openforms.utils.translations


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0053_auto_20230830_1432"),
    ]

    operations = [
        migrations.AlterField(
            model_name="globalconfiguration",
            name="privacy_policy_label",
            field=tinymce.models.HTMLField(
                blank=True,
                default=functools.partial(
                    openforms.utils.translations.get_default,
                    *(
                        "Yes, I have read the {% privacy_policy %} and explicitly agree to the processing of my submitted information.",
                    ),
                    **{}
                ),
                help_text="The label of the checkbox that prompts the user to agree to the privacy policy.",
                validators=[
                    openforms.template.validators.DjangoTemplateValidator(
                        backend="openforms.template.openforms_backend",
                        required_template_tags=["privacy_policy"],
                    )
                ],
                verbose_name="privacy policy label",
            ),
        ),
        migrations.AlterField(
            model_name="globalconfiguration",
            name="privacy_policy_label_en",
            field=tinymce.models.HTMLField(
                blank=True,
                default=functools.partial(
                    openforms.utils.translations.get_default,
                    *(
                        "Yes, I have read the {% privacy_policy %} and explicitly agree to the processing of my submitted information.",
                    ),
                    **{}
                ),
                help_text="The label of the checkbox that prompts the user to agree to the privacy policy.",
                null=True,
                validators=[
                    openforms.template.validators.DjangoTemplateValidator(
                        backend="openforms.template.openforms_backend",
                        required_template_tags=["privacy_policy"],
                    )
                ],
                verbose_name="privacy policy label",
            ),
        ),
        migrations.AlterField(
            model_name="globalconfiguration",
            name="privacy_policy_label_nl",
            field=tinymce.models.HTMLField(
                blank=True,
                default=functools.partial(
                    openforms.utils.translations.get_default,
                    *(
                        "Yes, I have read the {% privacy_policy %} and explicitly agree to the processing of my submitted information.",
                    ),
                    **{}
                ),
                help_text="The label of the checkbox that prompts the user to agree to the privacy policy.",
                null=True,
                validators=[
                    openforms.template.validators.DjangoTemplateValidator(
                        backend="openforms.template.openforms_backend",
                        required_template_tags=["privacy_policy"],
                    )
                ],
                verbose_name="privacy policy label",
            ),
        ),
        migrations.AlterField(
            model_name="globalconfiguration",
            name="statement_of_truth_label",
            field=tinymce.models.HTMLField(
                blank=True,
                default=functools.partial(
                    openforms.utils.translations.get_default,
                    *(
                        "I declare that I have filled out the form truthfully and have not omitted any information.",
                    ),
                    **{}
                ),
                help_text="The label of the checkbox that prompts the user to agree that they filled out the form truthfully. Note that this field does not have templating support.",
                verbose_name="statement of truth label",
            ),
        ),
        migrations.AlterField(
            model_name="globalconfiguration",
            name="statement_of_truth_label_en",
            field=tinymce.models.HTMLField(
                blank=True,
                default=functools.partial(
                    openforms.utils.translations.get_default,
                    *(
                        "I declare that I have filled out the form truthfully and have not omitted any information.",
                    ),
                    **{}
                ),
                help_text="The label of the checkbox that prompts the user to agree that they filled out the form truthfully. Note that this field does not have templating support.",
                null=True,
                verbose_name="statement of truth label",
            ),
        ),
        migrations.AlterField(
            model_name="globalconfiguration",
            name="statement_of_truth_label_nl",
            field=tinymce.models.HTMLField(
                blank=True,
                default=functools.partial(
                    openforms.utils.translations.get_default,
                    *(
                        "I declare that I have filled out the form truthfully and have not omitted any information.",
                    ),
                    **{}
                ),
                help_text="The label of the checkbox that prompts the user to agree that they filled out the form truthfully. Note that this field does not have templating support.",
                null=True,
                verbose_name="statement of truth label",
            ),
        ),
    ]
