# Generated by Django 4.2.15 on 2024-08-22 12:13

import functools

from django.db import migrations, models

import tinymce.models

import openforms.config.models.config
import openforms.emails.validators
import openforms.template.validators


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0054_v250_to_v270"),
    ]

    operations = [
        migrations.AddField(
            model_name="globalconfiguration",
            name="email_verification_request_content",
            field=tinymce.models.HTMLField(
                default=functools.partial(
                    openforms.config.models.config._render,
                    *("emails/email_verification/request.html",),
                    **{}
                ),
                help_text="Content of the email verification email message.",
                validators=[
                    openforms.template.validators.DjangoTemplateValidator(),
                    openforms.emails.validators.URLSanitationValidator(),
                ],
                verbose_name="content",
            ),
        ),
        migrations.AddField(
            model_name="globalconfiguration",
            name="email_verification_request_content_en",
            field=tinymce.models.HTMLField(
                default=functools.partial(
                    openforms.config.models.config._render,
                    *("emails/email_verification/request.html",),
                    **{}
                ),
                help_text="Content of the email verification email message.",
                null=True,
                validators=[
                    openforms.template.validators.DjangoTemplateValidator(),
                    openforms.emails.validators.URLSanitationValidator(),
                ],
                verbose_name="content",
            ),
        ),
        migrations.AddField(
            model_name="globalconfiguration",
            name="email_verification_request_content_nl",
            field=tinymce.models.HTMLField(
                default=functools.partial(
                    openforms.config.models.config._render,
                    *("emails/email_verification/request.html",),
                    **{}
                ),
                help_text="Content of the email verification email message.",
                null=True,
                validators=[
                    openforms.template.validators.DjangoTemplateValidator(),
                    openforms.emails.validators.URLSanitationValidator(),
                ],
                verbose_name="content",
            ),
        ),
        migrations.AddField(
            model_name="globalconfiguration",
            name="email_verification_request_subject",
            field=models.CharField(
                default=functools.partial(
                    openforms.config.models.config._render,
                    *("emails/email_verification/subject.txt",),
                    **{}
                ),
                help_text="Subject of the email verification email.",
                max_length=1000,
                validators=[openforms.template.validators.DjangoTemplateValidator()],
                verbose_name="subject",
            ),
        ),
        migrations.AddField(
            model_name="globalconfiguration",
            name="email_verification_request_subject_en",
            field=models.CharField(
                default=functools.partial(
                    openforms.config.models.config._render,
                    *("emails/email_verification/subject.txt",),
                    **{}
                ),
                help_text="Subject of the email verification email.",
                max_length=1000,
                null=True,
                validators=[openforms.template.validators.DjangoTemplateValidator()],
                verbose_name="subject",
            ),
        ),
        migrations.AddField(
            model_name="globalconfiguration",
            name="email_verification_request_subject_nl",
            field=models.CharField(
                default=functools.partial(
                    openforms.config.models.config._render,
                    *("emails/email_verification/subject.txt",),
                    **{}
                ),
                help_text="Subject of the email verification email.",
                max_length=1000,
                null=True,
                validators=[openforms.template.validators.DjangoTemplateValidator()],
                verbose_name="subject",
            ),
        ),
    ]
