# Generated by Django 3.2.24 on 2024-02-19 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0054_enable_new_builder"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="globalconfiguration",
            name="enable_react_formio_builder",
        ),
    ]
