# Generated by Django 3.2.20 on 2023-09-11 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0054_auto_20230908_1046"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="globalconfiguration",
            name="default_test_bsn",
        ),
        migrations.RemoveField(
            model_name="globalconfiguration",
            name="default_test_kvk",
        ),
    ]
