# Generated by Django 4.2.17 on 2025-01-13 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zgw_consumers", "0022_set_default_service_slug"),
        ("config", "0055_v270_to_v300"),
    ]

    operations = [
        migrations.AddField(
            model_name="globalconfiguration",
            name="referentielijsten_services",
            field=models.ManyToManyField(
                blank=True,
                help_text="List of services that are instances of the Referentielijsten API. The selected services will be shown as options when configuring select or selectboxes components to be populated from Referentielijsten.",
                to="zgw_consumers.service",
                verbose_name="referentielijsten services",
            ),
        ),
    ]
