# Generated by Django 4.2.16 on 2024-09-16 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "config",
            "0055_globalconfiguration_email_verification_request_content_and_more",
        ),
    ]

    # RunPython operation removed as part of 3.0 release cycle - these migrations are
    # guaranteed to have been executed on Open Forms 2.8.x for existing instances.
    operations = []
