# Generated by Django 3.2.20 on 2023-09-18 09:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("config", "0055_auto_20230911_2131"),
    ]

    operations = [
        migrations.AddField(
            model_name="globalconfiguration",
            name="show_form_link_in_cosign_email",
            field=models.BooleanField(
                default=True,
                help_text="When enabled, a link to the form is shown in the co-sign email.",
                verbose_name="show form link in co-sign email",
            ),
        ),
    ]
