# Generated by Django 4.2.16 on 2024-09-16 13:12

from django.db import migrations


def disable_objects_api_prefill_plugin(apps, _):
    GlobalConfiguration = apps.get_model("config", "GlobalConfiguration")
    config, _ = GlobalConfiguration.objects.get_or_create(
        pk=1
    )  # must match GlobalConfiguration.singleton_instance_id

    config.plugin_configuration.setdefault("prefill", {})
    config.plugin_configuration["prefill"].setdefault("objects_api", {"enabled": False})
    config.save()


class Migration(migrations.Migration):

    dependencies = [
        (
            "config",
            "0055_globalconfiguration_email_verification_request_content_and_more",
        ),
    ]

    operations = [
        migrations.RunPython(
            disable_objects_api_prefill_plugin, migrations.RunPython.noop
        ),
    ]
