# Generated by Django 4.2.25 on 2025-10-31 14:46

from django.db import migrations, models

import openforms.utils.fields


class Migration(migrations.Migration):
    dependencies = [
        ("config", "0056_v300_to_v330"),
    ]

    operations = [
        migrations.AddField(
            model_name="theme",
            name="favicon",
            field=openforms.utils.fields.SVGOrImageField(
                blank=True,
                help_text="Allow the uploading of a favicon, .png .jpg .svg and .ico are compatible. If left blank, the matching configuration option from the global configuration is used.",
                upload_to="logo/",
                verbose_name="favicon",
            ),
        ),
        migrations.AddField(
            model_name="theme",
            name="main_website",
            field=models.URLField(
                blank=True,
                help_text="URL to the main website. Used for the 'back to municipality website' link. If left blank, the matching configuration option from the global configuration is used.",
                verbose_name="main website link",
            ),
        ),
        migrations.AddField(
            model_name="theme",
            name="organization_name",
            field=models.CharField(
                blank=True,
                help_text="The name of your organization that will be used as label for elements like the logo. If left blank, the matching configuration option from the global configuration is used.",
                max_length=100,
                verbose_name="organization name",
            ),
        ),
        migrations.AlterField(
            model_name="theme",
            name="logo",
            field=openforms.utils.fields.SVGOrImageField(
                blank=True,
                help_text="Upload the theme/organization logo, visible to users filling out forms. We advise dimensions around 150px by 75px. SVG's are permitted.",
                upload_to="logo/",
                verbose_name="theme logo",
            ),
        ),
    ]
