# Generated by Django 4.2.26 on 2025-12-08 15:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("config", "0057_theme_favicon_theme_main_website_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="globalconfiguration",
            name="communication_preferences_portal_url",
            field=models.URLField(
                blank=True,
                help_text="Url to the online portal where users can update their communication preferences. This is used by the profile component.",
                verbose_name="communication preferences portal url",
            ),
        ),
    ]
