# Generated by Django 4.2.27 on 2026-02-02 08:41

from django.db import migrations, models

import openforms.utils.validators


class Migration(migrations.Migration):
    dependencies = [
        ("config", "0058_globalconfiguration_communication_preferences_portal_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="globalconfiguration",
            name="public_reference_alphabet",
            field=models.CharField(
                default="ABCDEFGHJKLMNPQRSTUVWXYZ23456789",
                help_text="Alphabet used to generate the {uid} part of the public reference of the submission. The sequence is shuffled in the unique way for each instance of Open Forms ",
                max_length=32,
                verbose_name="Public reference alphabet",
            ),
        ),
        migrations.AddField(
            model_name="globalconfiguration",
            name="public_reference_template",
            field=models.CharField(
                default="OF-{uid}",
                help_text="Template to use when generating public reference of the submission. It should be alpha-numerical and can contain the '/._-' characters. You can use the placeholder tokens: {year}, {uid}.",
                max_length=20,
                validators=[
                    openforms.utils.validators.IdTemplateValidator(
                        allowed_groups=("{year}", "{uid}", "/", ".", "_", "-")
                    )
                ],
                verbose_name="Public reference template",
            ),
        ),
    ]
