# Generated by Django 3.2.21 on 2023-10-31 14:23

from django.db import migrations

from ._design_tokens import update_button_design_token_values


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0058_auto_20231026_1525"),
    ]

    operations = [
        # reversing this is not possible - make sure you have backups!
        migrations.RunPython(
            update_button_design_token_values, migrations.RunPython.noop
        ),
    ]
