# Generated by Django 4.2.20 on 2025-05-02 13:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "config",
            "0058_alter_globalconfiguration_referentielijsten_services_to_reference_lists_services",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="globalconfiguration",
            name="family_members_data_api",
            field=models.CharField(
                blank=True,
                choices=[("haal_centraal", "Haal Centraal"), ("stuf_bg", "StufBg")],
                help_text="Which API to use to retrieve the data of the family members.",
                max_length=100,
                verbose_name="family members data api",
            ),
        ),
    ]
