# Generated by Django 4.2.11 on 2024-09-20 09:03

from django.db import migrations, models
import django_jsonform.models.fields

from openforms.config.constants import UploadFileType


def add_extra_zip_mimetypes(apps, _):
    """
    Set up the correct zip mimetypes.

    This ensures all the allowed mimetypes concerning zip files are included.
    """
    GlobalConfiguration = apps.get_model("config", "GlobalConfiguration")
    if not GlobalConfiguration.objects.exists():
        return

    config = GlobalConfiguration.objects.get()
    if "application/zip" not in config.form_upload_default_file_types:
        return

    config.form_upload_default_file_types.remove("application/zip")
    config.form_upload_default_file_types.append(UploadFileType.zip)
    config.save(update_fields=("form_upload_default_file_types",))


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0058_globalconfiguration_cosign_request_template_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="globalconfiguration",
            name="form_upload_default_file_types",
            field=django_jsonform.models.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("*", "any filetype"),
                        ("image/heic", ".heic"),
                        ("image/png", ".png"),
                        ("image/jpeg", ".jpg"),
                        ("application/pdf", ".pdf"),
                        ("application/vnd.ms-excel", ".xls"),
                        (
                            "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                            ".xlsx",
                        ),
                        ("text/csv", ".csv"),
                        ("text/plain", ".txt"),
                        ("application/msword", ".doc"),
                        (
                            "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
                            ".docx",
                        ),
                        (
                            "application/vnd.oasis.opendocument.*,application/vnd.stardivision.*,application/vnd.sun.xml.*",
                            "Open Office",
                        ),
                        (
                            "application/zip,application/zip-compressed,application/x-zip-compressed",
                            ".zip",
                        ),
                        ("application/vnd.rar", ".rar"),
                        ("application/x-tar", ".tar"),
                        ("application/vnd.ms-outlook", ".msg"),
                        (
                            "application/acad.dwg,application/autocad_dwg.dwg,application/dwg.dwg,application/x-acad.dwg,application/x-autocad.dwg,application/x-dwg.dwg,drawing/dwg.dwg,image/vnd.dwg,image/x-dwg.dwg",
                            ".dwg",
                        ),
                    ],
                    max_length=256,
                ),
                blank=True,
                default=list,
                help_text="Provide a list of default allowed file upload types. If empty, all extensions are allowed.",
                size=None,
                verbose_name="Default allowed file upload types",
            ),
        ),
        migrations.RunPython(
            add_extra_zip_mimetypes,
            migrations.RunPython.noop,
        ),
    ]
