# Generated by Django 4.2.16 on 2024-09-20 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0056_disable_prefill_objects_api_plugin"),
        ("config", "0059_alter_globalconfiguration_form_upload_default_file_types"),
    ]

    operations = []
