# Generated by Django 4.2.20 on 2025-05-02 13:31

from django.db import migrations


def copy_family_members_data_api(apps, schema_editor):
    NPFamilyMembersModel = apps.get_model(
        "np_family_members", "FamilyMembersTypeConfig"
    )
    np_family_members_config, _ = NPFamilyMembersModel.objects.get_or_create(id=1)

    GlobalConfigModel = apps.get_model("config", "GlobalConfiguration")
    global_config_model, _ = GlobalConfigModel.objects.get_or_create(id=1)

    if data_api := np_family_members_config.data_api:
        global_config_model.family_members_data_api = data_api
        global_config_model.save()


class Migration(migrations.Migration):
    dependencies = [
        ("np_family_members", "0002_alter_familymemberstypeconfig_table"),
        ("config", "0059_globalconfiguration_family_members_data_api"),
    ]

    operations = [
        migrations.RunPython(copy_family_members_data_api, migrations.RunPython.noop),
    ]
