# Generated by Django 4.2.11 on 2024-05-17 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0058_globalconfiguration_cosign_request_template_and_more"),
        ("config", "0059_theme_email_logo"),
    ]

    operations = []
