# Generated by Django 4.2.23 on 2025-09-02 12:40

from django.db import migrations

import autoslug.fields


class Migration(migrations.Migration):
    dependencies = [
        ("config", "0060_copy_family_members_data_api"),
    ]

    operations = [
        migrations.AlterField(
            model_name="maptilelayer",
            name="identifier",
            field=autoslug.fields.AutoSlugField(
                editable=True,
                help_text="A unique identifier for the tile layer.",
                max_length=100,
                populate_from="label",
                unique=True,
                verbose_name="identifier",
            ),
        ),
    ]
