# Generated by Django 5.2.11 on 2026-02-16 22:03

from django.db import migrations

import colorfield.fields


class Migration(migrations.Migration):
    dependencies = [
        ("config", "0060_shuffle_alphabet"),
    ]

    operations = [
        migrations.AlterField(
            model_name="richtextcolor",
            name="color",
            field=colorfield.fields.ColorField(
                default="#FFFFFF",
                help_text="Color in RGB hex format (#RRGGBB)",
                image_field=None,
                max_length=25,
                samples=None,
                verbose_name="color",
            ),
        ),
    ]
