# Generated by Django 3.2.21 on 2023-11-09 16:11
from django.db import migrations

from ._design_tokens import update_layout_design_token_values


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0060_create_csp_form_action_configs"),
    ]

    operations = [
        # reversing this is not possible - make sure you have backups!
        migrations.RunPython(
            update_layout_design_token_values, migrations.RunPython.noop
        ),
    ]
