# Generated by Django 3.2.21 on 2023-11-17 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0061_convert_container_layout_design_tokens"),
    ]

    operations = [
        migrations.AddField(
            model_name="cspsetting",
            name="identifier",
            field=models.CharField(
                blank=True,
                help_text="An extra tag for this CSP entry, to identify the exact source",
                max_length=64,
                verbose_name="identifier",
            ),
        ),
    ]
