# Generated by Django 5.2.16 on 2026-07-23 09:55

from django.db import migrations, models

import django_jsonform.models.fields


class Migration(migrations.Migration):
    dependencies = [
        ("config", "0061_alter_richtextcolor_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="globalconfiguration",
            name="email_template_netloc_allowlist",
            field=django_jsonform.models.fields.ArrayField(
                base_field=models.CharField(max_length=1000),
                blank=True,
                default=list,
                help_text="Provide a list of allowed (sub)domains (without 'https://www').Hyperlinks in a (confirmation) email are removed, unless the (sub)domain is provided here.",
                size=None,
                verbose_name="allowed email (sub)domain names",
            ),
        ),
    ]
