# Generated by Django 5.2.15 on 2026-07-03 13:46

from django.db import migrations, models

import tinymce.models


class Migration(migrations.Migration):
    dependencies = [
        ("config", "0061_alter_richtextcolor_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="globalconfiguration",
            name="help_callout_page_content",
            field=tinymce.models.HTMLField(
                blank=True,
                help_text="The content shown on the help callout page.",
                verbose_name="help callout page content",
            ),
        ),
        migrations.AddField(
            model_name="globalconfiguration",
            name="help_callout_page_content_en",
            field=tinymce.models.HTMLField(
                blank=True,
                help_text="The content shown on the help callout page.",
                null=True,
                verbose_name="help callout page content",
            ),
        ),
        migrations.AddField(
            model_name="globalconfiguration",
            name="help_callout_page_content_nl",
            field=tinymce.models.HTMLField(
                blank=True,
                help_text="The content shown on the help callout page.",
                null=True,
                verbose_name="help callout page content",
            ),
        ),
        migrations.AddField(
            model_name="globalconfiguration",
            name="help_callout_page_image",
            field=models.ImageField(
                blank=True,
                help_text="The image shown on the help callout page.",
                upload_to="help-callout-page",
                verbose_name="help callout page image",
            ),
        ),
    ]
