# Generated by Django 3.2.21 on 2023-11-22 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0062_cspsetting_identifier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cspsetting",
            name="directive",
            field=models.CharField(
                choices=[
                    ("default-src", "default-src"),
                    ("script-src", "script-src"),
                    ("script-src-attr", "script-src-attr"),
                    ("script-src-elem", "script-src-elem"),
                    ("img-src", "img-src"),
                    ("object-src", "object-src"),
                    ("prefetch-src", "prefetch-src"),
                    ("media-src", "media-src"),
                    ("frame-src", "frame-src"),
                    ("font-src", "font-src"),
                    ("connect-src", "connect-src"),
                    ("style-src", "style-src"),
                    ("style-src-attr", "style-src-attr"),
                    ("style-src-elem", "style-src-elem"),
                    ("base-uri", "base-uri"),
                    ("child-src", "child-src"),
                    ("frame-ancestors", "frame-ancestors"),
                    ("navigate-to", "navigate-to"),
                    ("form-action", "form-action"),
                    ("sandbox", "sandbox"),
                    ("report-uri", "report-uri"),
                    ("report-to", "report-to"),
                    ("manifest-src", "manifest-src"),
                    ("worker-src", "worker-src"),
                    ("plugin-types", "plugin-types"),
                    ("require-sri-for", "require-sri-for"),
                ],
                help_text="CSP header directive.",
                max_length=64,
                verbose_name="directive",
            ),
        ),
        migrations.AlterField(
            model_name="cspsetting",
            name="identifier",
            field=models.CharField(
                blank=True,
                help_text="An extra tag for this CSP entry, to identify the exact source.",
                max_length=64,
                verbose_name="identifier",
            ),
        ),
        migrations.AlterField(
            model_name="cspsetting",
            name="value",
            field=models.CharField(
                help_text="CSP header value.", max_length=255, verbose_name="value"
            ),
        ),
    ]
