# Generated by Django 4.2.16 on 2024-09-23 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0060_merge_20240920_1816"),
        ("config", "0062_merge_backport_zip_mimetypes"),
    ]

    operations = []
