# Generated by Django 5.2.16 on 2026-07-30 09:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("config", "0062_alter_globalconfiguration_email_template_netloc_allowlist"),
    ]

    operations = [
        migrations.AddField(
            model_name="globalconfiguration",
            name="help_callout_page_content",
            field=models.CharField(
                blank=True,
                default="",
                help_text="The content shown on the help callout page.",
                verbose_name="help callout page content",
            ),
        ),
        migrations.AddField(
            model_name="globalconfiguration",
            name="help_callout_page_content_en",
            field=models.CharField(
                blank=True,
                default="",
                help_text="The content shown on the help callout page.",
                null=True,
                verbose_name="help callout page content",
            ),
        ),
        migrations.AddField(
            model_name="globalconfiguration",
            name="help_callout_page_content_nl",
            field=models.CharField(
                blank=True,
                default="",
                help_text="The content shown on the help callout page.",
                null=True,
                verbose_name="help callout page content",
            ),
        ),
        migrations.AddField(
            model_name="globalconfiguration",
            name="help_callout_page_image",
            field=models.ImageField(
                blank=True,
                help_text="The image shown on the help callout page.",
                upload_to="help-callout-page",
                verbose_name="help callout page image",
            ),
        ),
    ]
