# Generated by Django 4.2.24 on 2025-10-02 10:19

import uuid

from django.db import migrations, models


def add_default_wfs_tile_layers(apps, schema_editor):
    from django.core.management import call_command

    call_command("loaddata", "default_map_wfs_tile_layers")


class Migration(migrations.Migration):
    dependencies = [
        ("config", "0063_alter_globalconfiguration_form_map_default_latitude_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MapWFSTileLayer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="An easily recognizable name for the WFS tile layer, used to identify it.",
                        max_length=100,
                        verbose_name="name",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        help_text="URL to collect the WFS tile layer capabilities. To ensure correct functionality of the map, the WFS tile layer `getFeature` request should support EPSG 4326 projection and 'application/json' as output format.Example value: https://service.pdok.nl/lv/bag/wfs/v2_0?request=getCapabilities&service=WFS",
                        max_length=255,
                        verbose_name="tile layer url",
                    ),
                ),
            ],
            options={
                "verbose_name": "WFS layer",
                "verbose_name_plural": "WFS layers",
            },
        ),
        migrations.RunPython(
            code=add_default_wfs_tile_layers,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
