# Generated by Django 4.2.16 on 2024-11-11 14:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0063_merge_20240923_1612"),
    ]

    operations = [
        migrations.AlterField(
            model_name="globalconfiguration",
            name="all_submissions_removal_limit",
            field=models.PositiveIntegerField(
                default=90,
                help_text="Amount of days when all submissions will be permanently deleted",
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="all submissions removal limit",
            ),
        ),
        migrations.AlterField(
            model_name="globalconfiguration",
            name="errored_submissions_removal_limit",
            field=models.PositiveIntegerField(
                default=30,
                help_text="Amount of days errored submissions will remain before being removed",
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="errored submission removal limit",
            ),
        ),
        migrations.AlterField(
            model_name="globalconfiguration",
            name="incomplete_submissions_removal_limit",
            field=models.PositiveIntegerField(
                default=7,
                help_text="Amount of days incomplete submissions will remain before being removed",
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="incomplete submission removal limit",
            ),
        ),
        migrations.AlterField(
            model_name="globalconfiguration",
            name="successful_submissions_removal_limit",
            field=models.PositiveIntegerField(
                default=7,
                help_text="Amount of days successful submissions will remain before being removed",
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="successful submission removal limit",
            ),
        ),
    ]
