# Generated by Django 3.2.23 on 2023-12-07 14:11

import uuid

from django.db import migrations, models


def set_uuid(apps, _):
    Theme = apps.get_model("config", "Theme")
    for theme in Theme.objects.all():
        theme.uuid = uuid.uuid4()
        theme.save()


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0064_auto_20231206_0921"),
    ]

    operations = [
        migrations.AddField(
            model_name="theme",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, verbose_name="UUID"
            ),
        ),
        migrations.RunPython(set_uuid, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="theme",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, unique=True, verbose_name="UUID"
            ),
        ),
    ]
