# Generated by Django 3.2.23 on 2023-12-12 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0065_theme_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="globalconfiguration",
            name="wait_for_payment_to_register",
            field=models.BooleanField(
                default=False,
                help_text="Should a submission be processed (sent to the registration backend) only after payment has been received?",
                verbose_name="wait for payment to register",
            ),
        ),
    ]
