# Generated by Django 3.2.23 on 2024-01-10 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0066_globalconfiguration_wait_for_payment_to_register"),
    ]

    operations = [
        migrations.AlterField(
            model_name="globalconfiguration",
            name="enable_react_formio_builder",
            field=models.BooleanField(
                default=True,
                help_text="Use the new Form.io component builder implementation.",
                verbose_name="enable new formio builder",
            ),
        ),
    ]
