# Generated by Django 4.2.16 on 2024-11-29 18:47

import re

from django.db import migrations
from django.db.migrations.state import StateApps


def replace_tag(tpl: str) -> str:
    return re.sub(
        r"{%\s*summary\s*%}",
        "{% confirmation_summary %}",
        tpl,
    )


def update_summary_tags(apps: StateApps, _):
    GlobalConfiguration = apps.get_model("config", "GlobalConfiguration")
    config = GlobalConfiguration.objects.first()
    if config is None:
        return

    # the cosign fields are new in 3.0.0 so they're not expected to hold the legacy
    # tag.
    config.submission_confirmation_template_en = replace_tag(
        config.submission_confirmation_template_en
    )
    config.submission_confirmation_template_nl = replace_tag(
        config.submission_confirmation_template_nl
    )
    config.confirmation_email_content_nl = replace_tag(
        config.confirmation_email_content_nl
    )
    config.confirmation_email_content_en = replace_tag(
        config.confirmation_email_content_en
    )
    config.save()


class Migration(migrations.Migration):

    dependencies = [
        (
            "config",
            "0068_alter_globalconfiguration_cosign_request_template_and_more",
        ),
    ]

    operations = [
        # reverse not needed, since the new format worked on old code too
        migrations.RunPython(update_summary_tags, migrations.RunPython.noop),
    ]
