# Generated by Django 3.2.23 on 2024-01-15 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0067_alter_globalconfiguration_enable_react_formio_builder"),
    ]

    operations = [
        migrations.AddField(
            model_name="globalconfiguration",
            name="organization_oin",
            field=models.CharField(
                blank=True,
                help_text="The OIN of the organization.",
                max_length=20,
                verbose_name="organization OIN",
            ),
        ),
    ]
