# Generated by Django 4.2.16 on 2024-12-03 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "config",
            "0067_globalconfiguration_cosign_confirmation_email_content_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="LeafletMapBackground",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "identifier",
                    models.SlugField(
                        help_text="A unique identifier for the Leaflet map background",
                        verbose_name="identifier",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        help_text="URL to the Leaflet map background. Used for the form map components",
                        verbose_name="background url",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="An easily recognizable name for the background, used to identify it.",
                        max_length=100,
                        verbose_name="label",
                    ),
                ),
            ],
            options={
                "verbose_name": "leaflet map background",
                "verbose_name_plural": "leaflet map backgrounds",
                "ordering": ("label",),
            },
        ),
    ]
