# Generated by Django 4.2.17 on 2024-12-17 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0068_update_summary_tags"),
    ]

    operations = [
        migrations.CreateModel(
            name="MapTileLayer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "identifier",
                    models.SlugField(
                        help_text="A unique identifier for the tile layer.",
                        unique=True,
                        verbose_name="identifier",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        help_text="URL to the tile layer image, used to define the map component background. To ensure correct functionality of the map, EPSG 28992 projection should be used. Example value: https://service.pdok.nl/brt/achtergrondkaart/wmts/v2_0/standaard/EPSG:28992/{z}/{x}/{y}.png",
                        max_length=255,
                        verbose_name="tile layer url",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="An easily recognizable name for the tile layer, used to identify it.",
                        max_length=100,
                        verbose_name="label",
                    ),
                ),
            ],
            options={
                "verbose_name": "map tile layer",
                "verbose_name_plural": "map tile layers",
                "ordering": ("label",),
            },
        ),
    ]
