# Generated by Django 2.2.24 on 2021-12-08 10:25

from django.db import migrations, models

import openforms.prefill.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PrefillConfig",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "default_person_plugin",
                    openforms.prefill.fields.PrefillPluginChoiceField(
                        help_text="Default prefill plugin to use for person data",
                        max_length=100,
                        verbose_name="default person plugin",
                    ),
                ),
                (
                    "default_company_plugin",
                    openforms.prefill.fields.PrefillPluginChoiceField(
                        help_text="Default prefill plugin to use for company data",
                        max_length=100,
                        verbose_name="default company plugin",
                    ),
                ),
            ],
            options={
                "verbose_name": "global prefill configuration",
            },
        ),
    ]
