# Generated by Django 2.2.24 on 2021-08-20 13:32

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RestAPI",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=100, verbose_name="label")),
                (
                    "api_root",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="api root url"
                    ),
                ),
                (
                    "auth_type",
                    models.CharField(
                        choices=[
                            ("no_auth", "No authentication"),
                            ("basic_auth", "Basic authentication"),
                            ("api_key", "API key"),
                            ("jwt", "JWT"),
                            ("custom_header", "Custom header"),
                        ],
                        default="no_auth",
                        max_length=20,
                        verbose_name="authorization type",
                    ),
                ),
                (
                    "basic_auth_username",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="username"
                    ),
                ),
                (
                    "basic_auth_password",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="password"
                    ),
                ),
                (
                    "api_key",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="API key"
                    ),
                ),
                (
                    "jwt_payload",
                    django.contrib.postgres.fields.jsonb.JSONField(
                        blank=True, default=dict, verbose_name="payload"
                    ),
                ),
                (
                    "jwt_secret",
                    models.CharField(blank=True, max_length=255, verbose_name="secret"),
                ),
                (
                    "custom_header_key",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="header key"
                    ),
                ),
                (
                    "custom_header_value",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="header value"
                    ),
                ),
            ],
            options={
                "verbose_name": "Rest API",
                "verbose_name_plural": "Rest APIs",
            },
        ),
    ]
