# Generated by Django 4.2.11 on 2024-06-17 07:41

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "digid_eherkenning_oidc_generics",
            "0006_alter_digidconfig_oidc_rp_scopes_list_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="OFDigiDConfig",
            fields=[],
            options={
                "verbose_name": "DigiD (OIDC)",
                "verbose_name_plural": "DigiD (OIDC)",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("digid_eherkenning_oidc_generics.digidconfig",),
        ),
        migrations.CreateModel(
            name="OFDigiDMachtigenConfig",
            fields=[],
            options={
                "verbose_name": "DigiD Machtigen (OIDC)",
                "verbose_name_plural": "DigiD Machtigen (OIDC)",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("digid_eherkenning_oidc_generics.digidmachtigenconfig",),
        ),
        migrations.CreateModel(
            name="OFEHerkenningBewindvoeringConfig",
            fields=[],
            options={
                "verbose_name": "eHerkenning bewindvoering (OIDC)",
                "verbose_name_plural": "eHerkenning bewindvoering (OIDC)",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("digid_eherkenning_oidc_generics.eherkenningbewindvoeringconfig",),
        ),
        migrations.CreateModel(
            name="OFEHerkenningConfig",
            fields=[],
            options={
                "verbose_name": "eHerkenning (OIDC)",
                "verbose_name_plural": "eHerkenning (OIDC)",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("digid_eherkenning_oidc_generics.eherkenningconfig",),
        ),
    ]
