# Generated by Django 3.2.12 on 2022-03-01 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("digid_eherkenning_oidc", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="openidconnecteherkenningconfig",
            name="enabled",
            field=models.BooleanField(
                default=False,
                help_text="Indicates whether OpenID Connect for authentication/authorization is enabled",
                verbose_name="enable",
            ),
        ),
        migrations.AlterField(
            model_name="openidconnecteherkenningconfig",
            name="oidc_rp_sign_algo",
            field=models.CharField(
                default="HS256",
                help_text="Algorithm the Identity Provider uses to sign ID tokens",
                max_length=50,
                verbose_name="OpenID sign algorithm",
            ),
        ),
        migrations.AlterField(
            model_name="openidconnectpublicconfig",
            name="enabled",
            field=models.BooleanField(
                default=False,
                help_text="Indicates whether OpenID Connect for authentication/authorization is enabled",
                verbose_name="enable",
            ),
        ),
        migrations.AlterField(
            model_name="openidconnectpublicconfig",
            name="oidc_rp_sign_algo",
            field=models.CharField(
                default="HS256",
                help_text="Algorithm the Identity Provider uses to sign ID tokens",
                max_length=50,
                verbose_name="OpenID sign algorithm",
            ),
        ),
    ]
