# Generated by Django 4.2.21 on 2025-07-10 10:16

from django.db import migrations, models

import django_jsonform.models.fields


def get_default_scopes_eidas():
    """
    Returns the default scopes to request for OpenID Connect logins for eIDAS.
    """
    return ["openid", "profile"]


def get_default_scopes_eidas_company():
    """
    Returns the default scopes to request for OpenID Connect logins for eIDAS with
    company.
    """
    return ["openid", "profile", "legal"]


class Migration(migrations.Migration):
    dependencies = [
        ("digid_eherkenning_oidc", "0003_ofeidascompanyconfig_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ofeidascompanyconfig",
            name="oidc_rp_scopes_list",
            field=django_jsonform.models.fields.ArrayField(  # type: ignore
                base_field=models.CharField(
                    max_length=50, verbose_name="OpenID Connect scope"
                ),
                blank=True,
                default=get_default_scopes_eidas_company,
                help_text="OpenID Connect scopes that are requested during login. These scopes are hardcoded and must be supported by the identity provider.",
                size=None,
                verbose_name="OpenID Connect scopes",
            ),
        ),
        migrations.AlterField(
            model_name="ofeidasconfig",
            name="oidc_rp_scopes_list",
            field=django_jsonform.models.fields.ArrayField(  # type: ignore
                base_field=models.CharField(
                    max_length=50, verbose_name="OpenID Connect scope"
                ),
                blank=True,
                default=get_default_scopes_eidas,
                help_text="OpenID Connect scopes that are requested during login. These scopes are hardcoded and must be supported by the identity provider.",
                size=None,
                verbose_name="OpenID Connect scopes",
            ),
        ),
    ]
