# Generated by Django 4.2.23 on 2025-07-16 09:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "digid_eherkenning_oidc",
            "0004_alter_ofeidascompanyconfig_oidc_rp_scopes_list_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="ofeidascompanyconfig",
            name="default_loa",
            field=models.CharField(
                blank=True,
                choices=[
                    ("urn:etoegang:core:assurance-class:loa2", "Low"),
                    ("urn:etoegang:core:assurance-class:loa2plus", "Low Plus"),
                    ("urn:etoegang:core:assurance-class:loa3", "Substantial"),
                    ("urn:etoegang:core:assurance-class:loa4", "High"),
                ],
                help_text="Fallback level of assurance, in case no claim value could be extracted.",
                max_length=100,
                verbose_name="default LOA",
            ),
        ),
        migrations.AlterField(
            model_name="ofeidasconfig",
            name="default_loa",
            field=models.CharField(
                blank=True,
                choices=[
                    ("urn:etoegang:core:assurance-class:loa2", "Low"),
                    ("urn:etoegang:core:assurance-class:loa2plus", "Low Plus"),
                    ("urn:etoegang:core:assurance-class:loa3", "Substantial"),
                    ("urn:etoegang:core:assurance-class:loa4", "High"),
                ],
                help_text="Fallback level of assurance, in case no claim value could be extracted.",
                max_length=100,
                verbose_name="default LOA",
            ),
        ),
    ]
