# Generated by Django 4.2.21 on 2025-05-30 10:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "mozilla_django_oidc_db",
            "0006_oidcprovider_oidcclient",
        ),
        (
            "digid_eherkenning_oidc",
            "0005_alter_ofeidascompanyconfig_default_loa_and_more",
        ),
        (
            "digid_eherkenning_oidc_generics",
            "0009_remove_digidconfig_oidc_exempt_urls_and_more",
        ),
    ]
    run_before = [
        (
            "digid_eherkenning_oidc_generics",
            "0010_delete_digidconfig_delete_digidmachtigenconfig_and_more",
        ),
        ("mozilla_django_oidc_db", "0008_delete_openidconnectconfig"),
    ]

    # Emptied as part of the 3.4 release cycle - they're guaranteed to have been
    # executed on 3.3.x.
    operations = []
