# Generated by Django 4.2.21 on 2025-06-03 11:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("digid_eherkenning_oidc", "0006_move_data_oidc_config"),
    ]

    operations = [
        migrations.DeleteModel(
            name="OFDigiDConfig",
        ),
        migrations.DeleteModel(
            name="OFDigiDMachtigenConfig",
        ),
        migrations.DeleteModel(
            name="OFEHerkenningBewindvoeringConfig",
        ),
        migrations.DeleteModel(
            name="OFEHerkenningConfig",
        ),
        migrations.DeleteModel(
            name="OFEIDASConfig",
        ),
        migrations.DeleteModel(
            name="OFEIDASCompanyConfig",
        ),
    ]
