# Generated by Django 3.2.21 on 2023-09-21 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kadaster", "0002_kadasterapiconfig_bag_service"),
    ]

    # This used to be a data migration copying over the configuration from
    # openforms.contrib.bag to openforms.contrib.kadaster, as part of the API client
    # refactor. Once OF 2.4 has been deployed, this operation became obsolete and it's
    # been removed since OF 2.5.
    operations = []
