# Generated by Django 3.2.15 on 2022-08-12 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("submissions", "0059_remove_submission_prefill_data"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuthInfo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "plugin",
                    models.CharField(
                        help_text="Identifier of the authentication plugin.",
                        max_length=250,
                        verbose_name="plugin",
                    ),
                ),
                (
                    "attribute",
                    models.CharField(
                        choices=[
                            ("bsn", "BSN"),
                            ("kvk", "KvK number"),
                            ("pseudo", "Pseudo ID"),
                        ],
                        help_text="Name of the attribute returned by the authentication plugin.",
                        max_length=50,
                        verbose_name="attribute",
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        help_text="Value of the attribute returned by the authentication plugin.",
                        max_length=250,
                        verbose_name="value",
                    ),
                ),
                (
                    "machtigen",
                    models.JSONField(
                        blank=True,
                        help_text="Data related to any 'machtiging' (authorising someone else to perform actions on your behalf).",
                        null=True,
                        verbose_name="machtigen",
                    ),
                ),
                (
                    "attribute_hashed",
                    models.BooleanField(
                        default=False,
                        help_text="Are the auth/identifying attributes hashed?",
                        verbose_name="identifying attributes hashed",
                    ),
                ),
                (
                    "submission",
                    models.OneToOneField(
                        help_text="Submission related to this authentication information",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auth_info",
                        to="submissions.submission",
                        verbose_name="Submission",
                    ),
                ),
            ],
            options={
                "verbose_name": "Authentication details",
                "verbose_name_plural": "Authentication details",
            },
        ),
    ]
