# Generated by Django 4.2.11 on 2024-05-31 07:13

from django.db import migrations, models
import openforms.authentication.models


class Migration(migrations.Migration):

    dependencies = [
        ("of_authentication", "0001_initial_to_openforms_v230"),
    ]

    operations = [
        migrations.AddField(
            model_name="authinfo",
            name="acting_subject_identifier_type",
            field=models.CharField(
                blank=True,
                choices=[("opaque", "Opaque")],
                help_text="The identifier type determines how to interpret the identifier value.",
                max_length=50,
                verbose_name="acting subject identifier type",
            ),
        ),
        migrations.AddField(
            model_name="authinfo",
            name="acting_subject_identifier_value",
            field=models.CharField(
                blank=True,
                help_text="(Contextually) unique identifier for the acting subject.",
                max_length=250,
                verbose_name="acting subject identifier",
            ),
        ),
        migrations.AddField(
            model_name="authinfo",
            name="legal_subject_identifier_type",
            field=models.CharField(
                blank=True,
                choices=[("bsn", "BSN"), ("kvk", "KvK number"), ("rsin", "RSIN")],
                help_text="The identifier type determines how to interpret the identifier value.",
                max_length=50,
                verbose_name="legal subject identifier type",
            ),
        ),
        migrations.AddField(
            model_name="authinfo",
            name="legal_subject_identifier_value",
            field=models.CharField(
                blank=True,
                help_text="(Contextually) unique identifier for the legal subject.",
                max_length=250,
                verbose_name="legal subject identifier",
            ),
        ),
        migrations.AddField(
            model_name="authinfo",
            name="mandate_context",
            field=models.JSONField(
                blank=True,
                help_text="If a mandate is in play, then the mandate context must be provided. The details are tracked here, in line with the authentication context data JSON schema definition.",
                null=True,
                verbose_name="mandate context",
            ),
        ),
        migrations.AddConstraint(
            model_name="authinfo",
            constraint=openforms.authentication.models.ConjointConstraint(
                fields=(
                    "acting_subject_identifier_type",
                    "acting_subject_identifier_value",
                ),
                name="acting_subject_integrity",
            ),
        ),
        migrations.AddConstraint(
            model_name="authinfo",
            constraint=openforms.authentication.models.ConjointConstraint(
                fields=(
                    "legal_subject_identifier_type",
                    "legal_subject_identifier_value",
                ),
                name="legal_subject_integrity",
            ),
        ),
        migrations.AddConstraint(
            model_name="authinfo",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("legal_subject_identifier_value", ""),
                        ("mandate_context__isnull", True),
                    ),
                    models.Q(
                        models.Q(("legal_subject_identifier_value", ""), _negated=True),
                        ("mandate_context__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="mandate_context_not_null",
            ),
        ),
    ]
