# Generated by Django 3.2.15 on 2022-08-12 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("of_authentication", "0001_initial"),
    ]

    # data migration removed, as these have been executed on Open Forms 2.3.0+
    operations = []
