# Generated by Django 5.2.17 on 2026-09-23 11:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("of_authentication", "0002_v230_to_v330"),
    ]

    operations = [
        migrations.AlterField(
            model_name="authinfo",
            name="attribute",
            field=models.CharField(
                choices=[
                    ("bsn", "BSN"),
                    ("kvk", "KvK number"),
                    ("pseudo", "Pseudo ID"),
                    ("employee_id", "Employee ID"),
                    ("local_user_id", "Local user ID"),
                ],
                help_text="Name of the attribute returned by the authentication plugin.",
                max_length=50,
                verbose_name="attribute",
            ),
        ),
        migrations.AlterField(
            model_name="registratorinfo",
            name="attribute",
            field=models.CharField(
                choices=[
                    ("bsn", "BSN"),
                    ("kvk", "KvK number"),
                    ("pseudo", "Pseudo ID"),
                    ("employee_id", "Employee ID"),
                    ("local_user_id", "Local user ID"),
                ],
                help_text="Name of the attribute returned by the authentication plugin.",
                max_length=50,
                verbose_name="attribute",
            ),
        ),
    ]
