# Generated by Django 4.2.11 on 2024-07-03 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("of_authentication", "0002_add_authentication_context_mandate_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="authinfo",
            name="legal_subject_service_restriction",
            field=models.CharField(
                blank=True,
                help_text="Optional service restriction information within the bigger legal subject.",
                max_length=250,
                verbose_name="legal subject service restriction",
            ),
        ),
    ]
