# Generated by Django 4.2.17 on 2024-12-12 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "of_authentication",
            "0003_authinfo_legal_subject_service_restriction_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="authinfo",
            name="machtigen",
        ),
    ]
