# Generated by Django 4.2.21 on 2025-05-15 09:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("of_authentication", "0004_remove_authinfo_machtigen"),
    ]

    operations = [
        migrations.AddField(
            model_name="authinfo",
            name="additional_claims",
            field=models.JSONField(
                default=dict,
                help_text="Additional claims, configurable in form OIDC configuration, returned by the authentication plugin.",
                verbose_name="additional claims",
            ),
        ),
    ]
