# Generated by Django 3.2.16 on 2022-10-24 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("of_authentication", "0004_registratorinfo"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="registratorinfo",
            options={
                "permissions": [
                    (
                        "can_register_customer_submission",
                        "Can register submission for customers",
                    )
                ],
                "verbose_name": "Registrator authentication details",
                "verbose_name_plural": "Registrator authentication details",
            },
        ),
    ]
