# Generated by Django 3.2.16 on 2022-10-31 16:11

from django.conf import settings
from django.db import migrations


def digid_to_db_config(apps, _):
    import bpdb

    bpdb.set_trace()


def eherkenning_to_db_config(apps, _):
    import bpdb

    bpdb.set_trace()


class Migration(migrations.Migration):

    dependencies = [
        ("of_authentication", "0005_alter_registratorinfo_options"),
        ("digid_eherkenning", "0001_initial"),
    ]

    # TODO: once 2.1 is out and 2.2 development starts, we can remove the settings
    # and these operations (and make the migration noop).
    operations = [
        migrations.RunPython(digid_to_db_config, migrations.RunPython.noop),
        migrations.RunPython(eherkenning_to_db_config, migrations.RunPython.noop),
    ]
