# Generated by Django 4.2.21 on 2025-07-08 10:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("of_authentication", "0005_authinfo_additional_claims"),
    ]

    operations = [
        migrations.AlterField(
            model_name="authinfo",
            name="acting_subject_identifier_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("opaque", "Opaque"),
                    ("national_id", "National ID"),
                    ("bsn", "BSN"),
                ],
                help_text="The identifier type determines how to interpret the identifier value.",
                max_length=50,
                verbose_name="acting subject identifier type",
            ),
        ),
        migrations.AlterField(
            model_name="authinfo",
            name="attribute",
            field=models.CharField(
                choices=[
                    ("bsn", "BSN"),
                    ("kvk", "KvK number"),
                    ("pseudo", "Pseudo ID"),
                    ("employee_id", "Employee ID"),
                    ("national_id", "National ID"),
                ],
                help_text="Name of the attribute returned by the authentication plugin.",
                max_length=50,
                verbose_name="attribute",
            ),
        ),
        migrations.AlterField(
            model_name="authinfo",
            name="legal_subject_identifier_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("bsn", "BSN"),
                    ("kvk", "KvK number"),
                    ("rsin", "RSIN"),
                    ("national_id", "National ID"),
                    ("opaque", "Opaque"),
                ],
                help_text="The identifier type determines how to interpret the identifier value.",
                max_length=50,
                verbose_name="legal subject identifier type",
            ),
        ),
        migrations.AlterField(
            model_name="registratorinfo",
            name="attribute",
            field=models.CharField(
                choices=[
                    ("bsn", "BSN"),
                    ("kvk", "KvK number"),
                    ("pseudo", "Pseudo ID"),
                    ("employee_id", "Employee ID"),
                    ("national_id", "National ID"),
                ],
                help_text="Name of the attribute returned by the authentication plugin.",
                max_length=50,
                verbose_name="attribute",
            ),
        ),
    ]
