# Generated by Django 3.2.19 on 2023-06-23 13:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("of_authentication", "0005_alter_registratorinfo_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="authinfo",
            name="loa",
            field=models.TextField(
                blank=True,
                default="",
                help_text="How certain is the identity provider that this identity belongs to this user.",
                verbose_name="Level of assurance",
            ),
        ),
    ]
