# Generated by Django 4.2.23 on 2025-08-05 15:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "of_authentication",
            "0006_alter_authinfo_acting_subject_identifier_type_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="authinfo",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="registratorinfo",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
