# Generated by Django 4.2.23 on 2025-08-25 09:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "of_authentication",
            "0008_data_migrate_authinfo_and_registratorinfo_attribute_national_id_to_pseudo",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="authinfo",
            name="attribute",
            field=models.CharField(
                choices=[
                    ("bsn", "BSN"),
                    ("kvk", "KvK number"),
                    ("pseudo", "Pseudo ID"),
                    ("employee_id", "Employee ID"),
                ],
                help_text="Name of the attribute returned by the authentication plugin.",
                max_length=50,
                verbose_name="attribute",
            ),
        ),
        migrations.AlterField(
            model_name="registratorinfo",
            name="attribute",
            field=models.CharField(
                choices=[
                    ("bsn", "BSN"),
                    ("kvk", "KvK number"),
                    ("pseudo", "Pseudo ID"),
                    ("employee_id", "Employee ID"),
                ],
                help_text="Name of the attribute returned by the authentication plugin.",
                max_length=50,
                verbose_name="attribute",
            ),
        ),
    ]
