from import_export.resources import ModelResource

from openforms.forms.models import Form
from openforms.typing import JSONObject


class BaseResource(ModelResource):
    """
    The base resource for all import/export resources.

    Attributes:
        deep_comparison_fields:
            The fields to use for deep comparison when searching for an existing
            instance. An instance will have to match all these fields to be considered
            an exact match.
        identifier_field:
            The field that uniquely identifies the instance. This field will be assigned
            a new identifier value when the identifier in the import-data is already in
            use, and we want to create a new instance.
    """

    deep_comparison_fields = ()
    identifier_field: str

    def export_for_form(self, form: Form):
        raise NotImplementedError(
            f"{self.__class__.__name__} must implement export_for_form()"
        )

    def generate_identifier(self, row: JSONObject):
        """
        A method to generate a unique identifier used when creating a new instance.
        """
        raise NotImplementedError(
            f"{self.__class__.__name__} must implement generate_identifier()"
        )

    def get_or_init_instance(self, instance_loader, row) -> tuple[JSONObject, bool]:
        """
        Search for an existing AttributeGroup with matching attributes.

        The default get_or_init_instance uses the import_id_fields. This does a lookup
        using the resource unique identifier.

        If the identifier lookup doesn't find an existing instance, we do a deep
        comparison and return the first match.

        Finally, if no match is found, we create a new instance.

        The return value is a tuple of (instance, is_new).
        """
        instance = super().get_instance(instance_loader, row)

        # Return the existing instance, found using the import_id_fields.
        if instance is not None:
            row["_matched_existing_instance"] = True
            return instance, False

        # Collect the parameters for the deep comparison.
        params = {}
        for key in self.deep_comparison_fields:
            params[key] = self.fields[key].clean(row)

        # Perform the deep comparison and return the first match.
        if (
            params
            and (new_found := self.get_queryset().filter(**params).first()) is not None
        ):
            row["_matched_existing_instance"] = True
            return new_found, False

        # No match found, return a new instance.
        new_instance = super().init_instance(row)
        new_instance._generated_new_identifier = True
        return new_instance, True

    def import_field(self, field, instance, row, is_m2m=False, **kwargs) -> None:
        if field.attribute == self.identifier_field and getattr(
            instance, "_generated_new_identifier", False
        ):
            # Set the identifier field to a new value, generated by the subclass.
            setattr(instance, field.attribute, self.generate_identifier(row))
            return

        # Import the field value normally.
        super().import_field(field, instance, row, is_m2m=is_m2m, **kwargs)

    def skip_row(self, instance, original, row, import_validation_errors=None):
        """
        When importing an existing instance, we don't update it.
        """
        if row.get("_matched_existing_instance"):
            return True

        return super().skip_row(instance, original, row, import_validation_errors)
