#
# Taken and adapted from https://github.com/maykinmedia/open-object/blob/master/docker-compose.yml
#

name: objects-apis

x-open-object-env: &x-open-object-env
  - DJANGO_SETTINGS_MODULE=objects.conf.docker
  - SECRET_KEY=${SECRET_KEY:-fgv=c0hz&tl*8*3m3893@m+1pstrvidc9e^5@fpspmg%cy$15d}
  - ALLOWED_HOSTS=*
  - DB_HOST=open-object-db
  - DB_NAME=objects
  - DB_USER=objects
  - IS_HTTPS=no
  - CACHE_DEFAULT=open-object-redis:6379/1
  - CACHE_AXES=open-object-redis:6379/1
  - CELERY_BROKER_URL=redis://open-object-redis:6379/1
  - CELERY_RESULT_EXPIRES=3600
  - CELERY_RESULT_BACKEND=redis://open-object-redis:6379/1
  - CELERY_LOGLEVEL=INFO
  - OBJECTS_SUPERUSER_USERNAME=admin
  - OBJECTS_SUPERUSER_PASSWORD=admin
  - OBJECTS_SUPERUSER_EMAIL=admin@localhost
  - DISABLE_2FA=true
  - DB_CONN_MAX_AGE=0
  - DB_POOL_ENABLED=True
  - SITE_DOMAIN=open-object-web:8000
  - OTEL_SDK_DISABLED=true
  - NOTIFICATIONS_DISABLED=true

services:
  open-object-db:
    image: postgis/postgis:${PG_VERSION:-17-3.5}
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./objects-apis/docker-initdb.d/:/docker-entrypoint-initdb.d:ro
      - open-object-db:/var/lib/postgresql/data
    networks:
      - open-forms-dev

  open-object-redis:
    image: redis:8
    command: ["redis-server", "--appendonly", "yes"]
    networks:
      - open-forms-dev

  open-object-web:
    image: maykinmedia/open-object:${TAG:-4.1.1}
    environment: *x-open-object-env
    volumes: &open-object-volumes
      # mount fixtures dir to automatically populate the DB
      - ./objects-apis/fixtures/:/app/fixtures/
    depends_on:
      - open-object-db
      - open-object-redis
    ports:
      - '8001:8000'
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - open-forms-dev

  open-object-celery:
    image: maykinmedia/open-object:${TAG:-4.1.1}
    environment: *x-open-object-env
    volumes: *open-object-volumes
    command: /celery_worker.sh
    depends_on:
      - open-object-db
      - open-object-redis
    networks:
      - open-forms-dev

volumes:
  open-object-db:

networks:
  open-forms-dev:
    name: open-forms-dev
