services:
  personen-mock:
    container_name: personen-mock
    image: ghcr.io/brp-api/personen-mock:2.3.0-latest
    volumes:
      # mount test data dir to volume so we can easily apply patches in an automated
      # way. docker engine will copy the data to the volume initially if this is a fresh
      # container/volume
      - hc-test-data:/app/Data/
    environment:
      - ASPNETCORE_ENVIRONMENT=Release
      - ASPNETCORE_URLS=http://+:5010
    ports:
      - '5010:5010'
    # volumes:
    #   - ./haal_centraal_brp/data/test-data.json:/app/Data/test-data.json
    networks:
      - open-forms-dev

volumes:
  hc-test-data:

networks:
  open-forms-dev:
    name: open-forms-dev
