# Generated by Django 4.2.17 on 2025-01-13 16:18

from django.db import migrations
from django.db.migrations.state import StateApps

from openforms.logging import logevent


def populate_submission_event_extra_data(apps: StateApps, _):
    """
    Add the missing snapshot information to log records for submissions that haven't
    been deleted yet.

    The new statistics page requires this snapshot data for proper aggregation and for
    continuity with the previous statistics page. We can only retrieve this information
    for submissions that haven't been deleted yet.
    """
    TimelineLogProxy = apps.get_model("logging", "TimelineLogProxy")
    ContentType = apps.get_model("contenttypes", "ContentType")
    Submission = apps.get_model("submissions", "Submission")
    relevant_records = TimelineLogProxy.objects.filter(
        extra_data__log_event=logevent.FORM_SUBMIT_SUCCESS_EVENT,
        content_type=ContentType.objects.get_for_model(Submission),
    )

    # use iterator since there may be *many* log records and we need to look up each
    # GFK to check if there's still a submission...
    for record in relevant_records:
        # can't access the content_object field in migrations because it's a private field.
        submission = Submission.objects.filter(pk=record.object_id).first()
        # the object will be deleted for old records because of our pruning settings
        if submission is None:
            continue

        # inject the snapshot data, but make sure to keep the original extra_data in
        # case there are conflicts on keys
        record.extra_data = {
            **logevent._snapshot_submission_statistics(submission),
            **record.extra_data,
        }
        record.save()


class Migration(migrations.Migration):

    dependencies = [
        ("logging", "0002_avgtimelinelogproxy"),
        ("submissions", "0002_v230_to_v300"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.RunPython(
            populate_submission_event_extra_data, migrations.RunPython.noop
        ),
    ]
