# Generated by Django 4.2.17 on 2025-01-13 16:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("logging", "0002_avgtimelinelogproxy"),
        ("submissions", "0002_v230_to_v300"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    # RunPython operation removed as part of the 3.3.x development cycle
    operations = []
