# Generated by Django 3.2.18 on 2023-03-13 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("variables", "0003_servicefetchconfiguration__query_params"),
    ]

    # data migration removed, as these have been executed on Open Forms 2.3.0+
    operations = []
