# Generated by Django 3.2.18 on 2023-03-13 15:38

from urllib.parse import parse_qs, urlencode

from django.db import migrations


def migrate_query_params_to_jsonfield(apps, _):
    ServiceFetchConfiguration = apps.get_model("variables", "ServiceFetchConfiguration")

    for config in ServiceFetchConfiguration.objects.all():
        if config.query_params:
            config._query_params = parse_qs(
                config.query_params[1:]
                if config.query_params.startswith("?")
                else config.query_params
            )
        else:
            config._query_params = {}
        config.save()


def migrate_query_params_to_textfield(apps, _):
    ServiceFetchConfiguration = apps.get_model("variables", "ServiceFetchConfiguration")

    for config in ServiceFetchConfiguration.objects.all():
        if config._query_params:
            config.query_params = f"?{urlencode(config._query_params, doseq=True)}"
            config.save()


class Migration(migrations.Migration):

    dependencies = [
        ("variables", "0003_servicefetchconfiguration__query_params"),
    ]

    operations = [
        migrations.RunPython(
            migrate_query_params_to_jsonfield, migrate_query_params_to_textfield
        )
    ]
