# Generated by Django 3.2.18 on 2023-03-13 15:38

import json

from django.db import migrations


def migrate_query_params_to_jsonfield(apps, _):
    ServiceFetchConfiguration = apps.get_model("variables", "ServiceFetchConfiguration")

    for config in ServiceFetchConfiguration.objects.all():
        try:
            config._query_params = json.loads(config.query_params)
        except json.decoder.JSONDecodeError:
            config._query_params = {}
        config.save()


def migrate_query_params_to_textfield(apps, _):
    ServiceFetchConfiguration = apps.get_model("variables", "ServiceFetchConfiguration")

    for config in ServiceFetchConfiguration.objects.all():
        config.query_params = json.dumps(config._query_params)
        config.save()


class Migration(migrations.Migration):

    dependencies = [
        ("variables", "0003_servicefetchconfiguration__query_params"),
    ]

    operations = [
        migrations.RunPython(
            migrate_query_params_to_jsonfield, migrate_query_params_to_textfield
        )
    ]
