# Generated by Django 3.2.18 on 2023-03-13 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("variables", "0005_remove_servicefetchconfiguration_query_params"),
    ]

    operations = [
        migrations.RenameField(
            model_name="servicefetchconfiguration",
            old_name="_query_params",
            new_name="query_params",
        ),
    ]
