# Generated by Django 3.2.18 on 2023-03-27 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("variables", "0008_alter_servicefetchconfiguration_query_params"),
    ]

    # data migration removed, as these have been executed on Open Forms 2.3.0+
    operations = []
