# Generated by Django 3.2.18 on 2023-03-27 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("variables", "0009_servicefetchconfiguration_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicefetchconfiguration",
            name="name",
            field=models.CharField(
                help_text="human readable name for the configuration", max_length=250
            ),
        ),
    ]
