# Generated by Django 3.2.18 on 2023-03-28 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("variables", "0010_alter_servicefetchconfiguration_name"),
    ]

    # data migration removed, as these have been executed on Open Forms 2.3.0+
    operations = []
