# Generated by Django 3.2.21 on 2023-09-20 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("variables", "0001_initial_to_openforms_v230"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicefetchconfiguration",
            name="cache_timeout",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="The responses for service fetch are cached to prevent repeating the same request multiple times when performing the logic check. If specified, the cached responses will expire after the timeout (in seconds).",
                null=True,
                verbose_name="cache timeout",
            ),
        ),
    ]
