# Generated by Django 2.2.24 on 2021-08-30 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("digid_oidc", "0002_auto_20210827_1708"),
    ]

    operations = [
        migrations.AddField(
            model_name="openidconnectpublicconfig",
            name="bsn_claim_name",
            field=models.CharField(
                default="bsn",
                help_text="The name of the claim in which the BSN of the user is stored",
                max_length=100,
                verbose_name="BSN claim name",
            ),
        ),
    ]
