# Generated by Django 2.2.24 on 2021-09-10 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("digid_oidc", "0003_openidconnectpublicconfig_bsn_claim_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="openidconnectpublicconfig",
            name="oidc_op_logout_endpoint",
            field=models.URLField(
                blank=True,
                help_text="URL of your OpenID Connect provider logout endpoint",
                max_length=1000,
                verbose_name="Logout endpoint",
            ),
        ),
    ]
