# Generated by Django 2.2.24 on 2021-11-19 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("digid_oidc", "0005_openidconnectpublicconfig_oidc_redirect_allowed_hosts"),
    ]

    operations = [
        migrations.AddField(
            model_name="openidconnectpublicconfig",
            name="oidc_keycloak_idp_hint",
            field=models.CharField(
                blank=True,
                help_text="Specific for Keycloak: parameter that indicates which identity provider should be used (therefore skipping the Keycloak login screen).",
                max_length=1000,
                verbose_name="Keycloak Identity Provider hint",
            ),
        ),
    ]
