# Generated by Django 2.2.24 on 2021-11-30 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("digid_oidc", "0006_openidconnectpublicconfig_oidc_keycloak_idp_hint"),
    ]

    operations = [
        migrations.AddField(
            model_name="openidconnectpublicconfig",
            name="acting_bsn_claim_name",
            field=models.CharField(
                blank=True,
                help_text="The name of the claim in which the BSN of the person who is acting on behalf of the `machtiger`",
                max_length=100,
                verbose_name="Acting BSN claim name",
            ),
        ),
        migrations.AddField(
            model_name="openidconnectpublicconfig",
            name="legal_bsn_claim_name",
            field=models.CharField(
                blank=True,
                help_text="The name of the claim in which the BSN of the user is stored in case of `machtigen`",
                max_length=100,
                verbose_name="Legal BSN claim name",
            ),
        ),
    ]
