# Generated by Django 3.2.15 on 2022-08-10 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [("cookie_consent", "0002_auto__add_logitem")]

    operations = [
        migrations.CreateModel(
            name="AnalyticsToolsConfiguration",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gtm_code",
                    models.CharField(
                        blank=True,
                        help_text="Typically looks like 'GTM-XXXX'. Supplying this installs Google Tag Manager.",
                        max_length=50,
                        verbose_name="Google Tag Manager code",
                    ),
                ),
                (
                    "ga_code",
                    models.CharField(
                        blank=True,
                        help_text="Typically looks like 'UA-XXXXX-Y'. Supplying this installs Google Analytics.",
                        max_length=50,
                        verbose_name="Google Analytics code",
                    ),
                ),
                (
                    "enable_google_analytics",
                    models.BooleanField(
                        default=False,
                        help_text="Enabling this installs Google Analytics",
                        verbose_name="enable google analytics",
                    ),
                ),
                (
                    "matomo_url",
                    models.CharField(
                        blank=True,
                        help_text="The base URL of your Matomo server, e.g. 'matomo.example.com'.",
                        max_length=255,
                        verbose_name="Matomo server URL",
                    ),
                ),
                (
                    "matomo_site_id",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="The 'idsite' of the website you're tracking in Matomo.",
                        null=True,
                        verbose_name="Matomo site ID",
                    ),
                ),
                (
                    "enable_matomo_site_analytics",
                    models.BooleanField(
                        default=False,
                        help_text="Enabling this installs Matomo",
                        verbose_name="enable matomo site analytics",
                    ),
                ),
                (
                    "piwik_url",
                    models.CharField(
                        blank=True,
                        help_text="The base URL of your Piwik server, e.g. 'piwik.example.com'.",
                        max_length=255,
                        verbose_name="Piwik server URL",
                    ),
                ),
                (
                    "piwik_site_id",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="The 'idsite' of the website you're tracking in Piwik.",
                        null=True,
                        verbose_name="Piwik site ID",
                    ),
                ),
                (
                    "enable_piwik_site_analytics",
                    models.BooleanField(
                        default=False,
                        help_text="Enabling this installs Piwik",
                        verbose_name="enable piwik site analytics",
                    ),
                ),
                (
                    "piwik_pro_url",
                    models.CharField(
                        blank=True,
                        help_text="The base URL of your Piwik PRO server, e.g. 'https://your-instance-name.piwik.pro/'.",
                        max_length=255,
                        verbose_name="Piwik PRO server URL",
                    ),
                ),
                (
                    "piwik_pro_site_id",
                    models.UUIDField(
                        blank=True,
                        help_text="The 'idsite' of the website you're tracking in Piwik PRO. https://help.piwik.pro/support/questions/find-website-id/",
                        null=True,
                        verbose_name="Piwik PRO site ID",
                    ),
                ),
                (
                    "enable_piwik_pro_site_analytics",
                    models.BooleanField(
                        default=False,
                        help_text="Enabling this installs Piwik Pro",
                        verbose_name="enable piwik pro site analytics",
                    ),
                ),
                (
                    "siteimprove_id",
                    models.CharField(
                        blank=True,
                        help_text="Your SiteImprove ID - you can find this from the embed snippet example, which should contain a URL like '//siteimproveanalytics.com/js/siteanalyze_XXXXX.js'. The XXXXX is your ID.",
                        max_length=10,
                        verbose_name="SiteImprove ID",
                    ),
                ),
                (
                    "enable_siteimprove_analytics",
                    models.BooleanField(
                        default=False,
                        help_text="Enabling this installs SiteImprove",
                        verbose_name="enable siteImprove analytics",
                    ),
                ),
                (
                    "analytics_cookie_consent_group",
                    models.ForeignKey(
                        blank=True,
                        help_text="The cookie group used for analytical cookies. The analytics scripts are loaded only if this cookie group is accepted by the end-user.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="cookie_consent.cookiegroup",
                    ),
                ),
            ],
            options={
                "verbose_name": "Analytics tools configuration",
            },
        ),
    ]
