# Generated by Django 5.2.16 on 2026-07-16 12:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analytics_tools", "0001_initial_to_v300"),
    ]

    operations = [
        migrations.AddField(
            model_name="analyticstoolsconfiguration",
            name="force_tag_manager_usage",
            field=models.BooleanField(
                default=False,
                help_text="Force the tag manager scripts to run, even if no cookie consent is given or individual tools are not enabled. You typically need this when you are using an external Consent Management Platform (CMP) through a tag manager. Be careful when you enable this, as incorrect configuration may have privacy and/or legal implications.",
                verbose_name="force enable tag manager(s)",
            ),
        ),
    ]
