# Generated by Django 3.2.21 on 2023-11-22 17:27

from django.db import migrations
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django.db.migrations.state import StateApps


class Migration(migrations.Migration):

    dependencies = [
        ("analytics_tools", "0002_auto_20230119_1500"),
        ("config", "0001_initial_to_v250"),
    ]

    # RunPython operation is removed, it was executed as part of the 2.5.0 upgrade.
    operations = []
