# Generated by Django 5.2.16 on 2026-07-16 12:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analytics_tools", "0002_analyticstoolsconfiguration_force_tag_manager_usage"),
    ]

    operations = [
        migrations.AddField(
            model_name="analyticstoolsconfiguration",
            name="use_external_cmp",
            field=models.BooleanField(
                default=False,
                help_text="Enable when using an external Consent Management Platform (through a tag manager). When this is checked, the built-in cookie consent notice will not be shown.",
                verbose_name="use external CMP",
            ),
        ),
    ]
