# Generated by Django 3.2.23 on 2023-11-30 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics_tools", "0003_cspsetting_identifier"),
    ]

    operations = [
        migrations.AddField(
            model_name="analyticstoolsconfiguration",
            name="enable_piwik_pro_tag_manager",
            field=models.BooleanField(
                default=False,
                help_text="Enabling this installs Piwik Pro Tag Manager, on top of Piwik Pro (meaning it will use the same URL and site ID).",
                verbose_name="enable piwik pro tag manager",
            ),
        ),
    ]
