# Generated by Django 5.2.16 on 2026-09-12 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analytics_tools", "0003_analyticstoolsconfiguration_use_external_cmp"),
    ]

    operations = [
        migrations.AddField(
            model_name="analyticstoolsconfiguration",
            name="enable_silktide_analytics",
            field=models.BooleanField(
                default=False,
                help_text="Enabling this installs Silktide",
                verbose_name="enable Silktide analytics",
            ),
        ),
        migrations.AddField(
            model_name="analyticstoolsconfiguration",
            name="silktide_site_id",
            field=models.CharField(
                blank=True,
                help_text="Your Silktide site ID - you can find this from the embed snippet example, which should contain a URL like 'https://analytics.silktide.com/XXXXX.js'. The XXXXX is your site ID.",
                max_length=50,
                verbose_name="Silktide site ID",
            ),
        ),
    ]
