# Generated by Django 3.2.23 on 2023-12-06 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "analytics_tools",
            "0004_analyticstoolsconfiguration_enable_piwik_pro_tag_manager",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="analyticstoolsconfiguration",
            name="enable_piwik_pro_site_analytics",
            field=models.BooleanField(
                default=False,
                help_text="Enabling this installs Piwik PRO Analytics",
                verbose_name="enable Piwik PRO Site Analytics",
            ),
        ),
        migrations.AlterField(
            model_name="analyticstoolsconfiguration",
            name="enable_piwik_pro_tag_manager",
            field=models.BooleanField(
                default=False,
                help_text="Enabling this installs Piwik PRO Tag Manager.",
                verbose_name="enable piwik Pro Tag Manager",
            ),
        ),
    ]
