# Generated by Django 3.2.23 on 2023-12-28 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics_tools", "0005_auto_20231206_1202"),
    ]

    operations = [
        migrations.AddField(
            model_name="analyticstoolsconfiguration",
            name="enable_govmetric_analytics",
            field=models.BooleanField(
                default=False,
                help_text="This enables GovMetric to collect data while a user fills in a form and it adds a button at the end of a form to fill in a client satisfaction survey.",
                verbose_name="enable GovMetric analytics",
            ),
        ),
        migrations.AddField(
            model_name="analyticstoolsconfiguration",
            name="govmetric_secure_guid",
            field=models.CharField(
                blank=True,
                help_text="Your GovMetric secure GUID - This is an optional value. It is created by KLANTINFOCUS when a list of questions is created. It is a string that is unique per set of questions.",
                max_length=10,
                verbose_name="GovMetric secure GUID",
            ),
        ),
        migrations.AddField(
            model_name="analyticstoolsconfiguration",
            name="govmetric_source_id",
            field=models.CharField(
                blank=True,
                help_text="Your GovMetric source ID - This is created by KLANTINFOCUS when a list of questions is created. It is a numerical value that is unique per set of questions.",
                max_length=10,
                verbose_name="GovMetric source ID",
            ),
        ),
    ]
