# Generated by Django 4.2.11 on 2024-04-17 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cookie_consent", "0002_auto__add_logitem"),
        ("analytics_tools", "0006_auto_20240112_1046"),
    ]

    operations = [
        migrations.AlterField(
            model_name="analyticstoolsconfiguration",
            name="analytics_cookie_consent_group",
            field=models.ForeignKey(
                help_text="The cookie group used for analytical cookies. The analytics scripts are loaded only if this cookie group is accepted by the end-user.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="cookie_consent.cookiegroup",
            ),
        ),
    ]
