# Generated by Django 4.2.11 on 2024-04-12 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "analytics_tools",
            "0007_alter_analyticstoolsconfiguration_analytics_cookie_consent_group",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="analyticstoolsconfiguration",
            name="govmetric_secure_guid_form_aborted",
            field=models.CharField(
                blank=True,
                help_text="Your GovMetric secure GUID for when a form is aborted - This is an optional value. It is created by KLANTINFOCUS when a list  of questions is created. It is a string that is unique per set of questions.",
                max_length=50,
                verbose_name="GovMetric secure GUID form aborted",
            ),
        ),
        migrations.AddField(
            model_name="analyticstoolsconfiguration",
            name="govmetric_secure_guid_form_finished",
            field=models.CharField(
                blank=True,
                help_text="Your GovMetric secure GUID for when a form is finished - This is an optional value. It is created by KLANTINFOCUS when a list  of questions is created. It is a string that is unique per set of questions.",
                max_length=50,
                verbose_name="GovMetric secure GUID form finished",
            ),
        ),
        migrations.AddField(
            model_name="analyticstoolsconfiguration",
            name="govmetric_source_id_form_aborted",
            field=models.CharField(
                blank=True,
                help_text="Your GovMetric source ID for when a form is aborted - This is created by KLANTINFOCUS when a list of questions is created. It is a numerical value that is unique per set of questions.",
                max_length=10,
                verbose_name="GovMetric source ID form aborted",
            ),
        ),
        migrations.AddField(
            model_name="analyticstoolsconfiguration",
            name="govmetric_source_id_form_finished",
            field=models.CharField(
                blank=True,
                help_text="Your GovMetric source ID for when a form is finished - This is created by KLANTINFOCUS when a list of questions is created. It is a numerical value that is unique per set of questions.",
                max_length=10,
                verbose_name="GovMetric source ID form finished",
            ),
        ),
        migrations.AddField(
            model_name="analyticstoolsconfiguration",
            name="govmetric_secure_guid_form_aborted_en",
            field=models.CharField(
                blank=True,
                help_text="Your GovMetric secure GUID for when a form is aborted - This is an optional value. It is created by KLANTINFOCUS when a list  of questions is created. It is a string that is unique per set of questions.",
                max_length=50,
                null=True,
                verbose_name="GovMetric secure GUID form aborted",
            ),
        ),
        migrations.AddField(
            model_name="analyticstoolsconfiguration",
            name="govmetric_secure_guid_form_aborted_nl",
            field=models.CharField(
                blank=True,
                help_text="Your GovMetric secure GUID for when a form is aborted - This is an optional value. It is created by KLANTINFOCUS when a list  of questions is created. It is a string that is unique per set of questions.",
                max_length=50,
                null=True,
                verbose_name="GovMetric secure GUID form aborted",
            ),
        ),
        migrations.AddField(
            model_name="analyticstoolsconfiguration",
            name="govmetric_secure_guid_form_finished_en",
            field=models.CharField(
                blank=True,
                help_text="Your GovMetric secure GUID for when a form is finished - This is an optional value. It is created by KLANTINFOCUS when a list  of questions is created. It is a string that is unique per set of questions.",
                max_length=50,
                null=True,
                verbose_name="GovMetric secure GUID form finished",
            ),
        ),
        migrations.AddField(
            model_name="analyticstoolsconfiguration",
            name="govmetric_secure_guid_form_finished_nl",
            field=models.CharField(
                blank=True,
                help_text="Your GovMetric secure GUID for when a form is finished - This is an optional value. It is created by KLANTINFOCUS when a list  of questions is created. It is a string that is unique per set of questions.",
                max_length=50,
                null=True,
                verbose_name="GovMetric secure GUID form finished",
            ),
        ),
        migrations.AddField(
            model_name="analyticstoolsconfiguration",
            name="govmetric_source_id_form_aborted_en",
            field=models.CharField(
                blank=True,
                help_text="Your GovMetric source ID for when a form is aborted - This is created by KLANTINFOCUS when a list of questions is created. It is a numerical value that is unique per set of questions.",
                max_length=10,
                null=True,
                verbose_name="GovMetric source ID form aborted",
            ),
        ),
        migrations.AddField(
            model_name="analyticstoolsconfiguration",
            name="govmetric_source_id_form_aborted_nl",
            field=models.CharField(
                blank=True,
                help_text="Your GovMetric source ID for when a form is aborted - This is created by KLANTINFOCUS when a list of questions is created. It is a numerical value that is unique per set of questions.",
                max_length=10,
                null=True,
                verbose_name="GovMetric source ID form aborted",
            ),
        ),
        migrations.AddField(
            model_name="analyticstoolsconfiguration",
            name="govmetric_source_id_form_finished_en",
            field=models.CharField(
                blank=True,
                help_text="Your GovMetric source ID for when a form is finished - This is created by KLANTINFOCUS when a list of questions is created. It is a numerical value that is unique per set of questions.",
                max_length=10,
                null=True,
                verbose_name="GovMetric source ID form finished",
            ),
        ),
        migrations.AddField(
            model_name="analyticstoolsconfiguration",
            name="govmetric_source_id_form_finished_nl",
            field=models.CharField(
                blank=True,
                help_text="Your GovMetric source ID for when a form is finished - This is created by KLANTINFOCUS when a list of questions is created. It is a numerical value that is unique per set of questions.",
                max_length=10,
                null=True,
                verbose_name="GovMetric source ID form finished",
            ),
        ),
    ]
