# Generated by Django 4.2.11 on 2024-04-12 08:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "analytics_tools",
            "0008_analyticstoolsconfiguration_govmetric_secure_guid_form_abort_and_more",
        ),
    ]

    # RunPython operation removed as part of the 2.8.0 release cycle
    operations = []
