# Generated by Django 4.2.11 on 2024-04-12 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics_tools", "0009_convert_ids_govmetric"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="analyticstoolsconfiguration",
            name="govmetric_secure_guid",
        ),
        migrations.RemoveField(
            model_name="analyticstoolsconfiguration",
            name="govmetric_secure_guid_en",
        ),
        migrations.RemoveField(
            model_name="analyticstoolsconfiguration",
            name="govmetric_secure_guid_nl",
        ),
        migrations.RemoveField(
            model_name="analyticstoolsconfiguration",
            name="govmetric_source_id",
        ),
        migrations.RemoveField(
            model_name="analyticstoolsconfiguration",
            name="govmetric_source_id_en",
        ),
        migrations.RemoveField(
            model_name="analyticstoolsconfiguration",
            name="govmetric_source_id_nl",
        ),
    ]
