# Generated by Django 4.2.11 on 2024-07-08 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "analytics_tools",
            "0010_remove_analyticstoolsconfiguration_govmetric_secure_guid_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="analyticstoolsconfiguration",
            name="enable_expoints_analytics",
            field=models.BooleanField(
                default=False,
                help_text="This adds a button at the end of a form to fill in a client satisfaction survey using Expoints.",
                verbose_name="enable Expoints analytics",
            ),
        ),
        migrations.AddField(
            model_name="analyticstoolsconfiguration",
            name="expoints_config_uuid",
            field=models.CharField(
                blank=True,
                help_text="The UUID used to retrieve the configuration from Expoints to initialize the client satisfaction survey.",
                max_length=50,
                verbose_name="Expoints configuration identifier",
            ),
        ),
        migrations.AddField(
            model_name="analyticstoolsconfiguration",
            name="expoints_organization_name",
            field=models.SlugField(
                blank=True,
                help_text="The name of your organization as registered in Expoints. This is used to construct the URL to communicate with Expoints.",
                verbose_name="Expoints organization name",
            ),
        ),
        migrations.AddField(
            model_name="analyticstoolsconfiguration",
            name="expoints_use_test_mode",
            field=models.BooleanField(
                default=False,
                help_text="Indicates whether or not the test mode should be enabled. If enabled, filled out surveys won't actually be sent, to avoid cluttering Expoints while testing.",
                verbose_name="use Expoints test mode",
            ),
        ),
    ]
