# Generated by Django 4.2.16 on 2024-10-10 15:06

import datetime
from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "products",
            "0002_product_is_deleted_product_upl_name_product_upl_uri_and_more",
        ),
        ("zgw_consumers", "0020_service_timeout"),
    ]

    operations = [
        migrations.CreateModel(
            name="Price",
            fields=[
                ("uuid", models.UUIDField(primary_key=True, serialize=False)),
                (
                    "valid_from",
                    models.DateField(
                        help_text="The date at which this price is valid",
                        unique=True,
                        validators=[
                            django.core.validators.MinValueValidator(
                                datetime.date.today
                            )
                        ],
                        verbose_name="Start date",
                    ),
                ),
                (
                    "product_type",
                    models.ForeignKey(
                        help_text="The product type that this price belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prices",
                        to="products.product",
                        verbose_name="Product type",
                    ),
                ),
            ],
            options={
                "verbose_name": "Price",
                "verbose_name_plural": "Prices",
                "unique_together": {("product_type", "valid_from")},
            },
        ),
        migrations.CreateModel(
            name="PriceOption",
            fields=[
                ("uuid", models.UUIDField(primary_key=True, serialize=False)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="The amount of the price option",
                        max_digits=8,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Price",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="Short description of the option",
                        max_length=100,
                        verbose_name="Description",
                    ),
                ),
                (
                    "price",
                    models.ForeignKey(
                        help_text="The price this option belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="open_producten.price",
                        verbose_name="Price",
                    ),
                ),
            ],
            options={
                "verbose_name": "Price option",
                "verbose_name_plural": "Price options",
            },
        ),
        migrations.CreateModel(
            name="OpenProductenConfig",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "producten_service",
                    models.OneToOneField(
                        limit_choices_to={"api_type": "orc"},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="zgw_consumers.service",
                        verbose_name="Producten API",
                    ),
                ),
            ],
            options={
                "verbose_name": "Open Producten configuration",
            },
        ),
    ]
