# Generated by Django 2.2.24 on 2021-09-02 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("submissions", "0027_submission__is_cleaned"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppointmentsConfig",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "config_path",
                    models.CharField(
                        blank=True,
                        choices=[
                            (
                                "openforms.appointments.contrib.jcc.models.JccConfig",
                                "Jcc",
                            ),
                            (
                                "openforms.appointments.contrib.qmatic.models.QmaticConfig",
                                "Qmatic",
                            ),
                        ],
                        max_length=255,
                        verbose_name="config path",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AppointmentInfo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            (
                                "form_missing_info",
                                "Submission does not contain all the info needed to make an appointment",
                            ),
                            ("failed", "Failed"),
                        ],
                        max_length=50,
                        verbose_name="status",
                    ),
                ),
                (
                    "appointment_id",
                    models.CharField(blank=True, max_length=50, verbose_name="status"),
                ),
                (
                    "error_information",
                    models.TextField(blank=True, verbose_name="error information"),
                ),
                (
                    "submission",
                    models.OneToOneField(
                        help_text="The submission that made the appointment",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointment_info",
                        to="submissions.Submission",
                    ),
                ),
            ],
            options={
                "verbose_name": "Appointment information",
                "verbose_name_plural": "Appointment information",
            },
        ),
    ]
