# Generated by Django 2.2.24 on 2021-08-30 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AppointmentsConfig",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "config_path",
                    models.CharField(
                        blank=True,
                        choices=[
                            (
                                "openforms.appointments.contrib.jcc.models.JccConfig",
                                "Jcc",
                            ),
                            (
                                "openforms.appointments.contrib.qmatic.models.QmaticConfig",
                                "Qmatic",
                            ),
                        ],
                        max_length=255,
                        verbose_name="config path",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
