# Generated by Django 2.2.24 on 2021-09-06 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0002_auto_20210902_2120"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointmentinfo",
            name="start_time",
            field=models.DateTimeField(
                blank=True,
                help_text="Start time of the appointment",
                null=True,
                verbose_name="start time",
            ),
        ),
    ]
