# Generated by Django 2.2.24 on 2021-09-03 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0002_appointmentinfo_start_time"),
        ("appointments", "0002_auto_20210902_2120"),
    ]

    operations = []
