# Generated by Django 2.2.24 on 2021-09-16 14:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0003_auto_20210908_1350"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointmentinfo",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                help_text="Timestamp when the appointment details were created",
                verbose_name="created",
            ),
            preserve_default=False,
        ),
    ]
