# Generated by Django 2.2.25 on 2021-12-10 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0004_appointmentinfo_created"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="appointmentsconfig",
            options={"verbose_name": "Appointment configuration"},
        ),
    ]
