# Generated by Django 2.2.25 on 2022-02-03 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0005_auto_20211210_1804"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointmentinfo",
            name="appointment_id",
            field=models.CharField(
                blank=True, max_length=64, verbose_name="appointment ID"
            ),
        ),
    ]
