# Generated by Django 3.2.16 on 2023-01-09 16:40

from django.db import migrations
import openforms.appointments.fields


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0006_auto_20220203_1500"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointmentsconfig",
            name="config_path",
            field=openforms.appointments.fields.AppointmentBackendChoiceField(
                blank=True, max_length=100, verbose_name="appointment plugin"
            ),
        ),
    ]
