# Generated by Django 3.2.19 on 2023-06-13 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0008_rename_config_path_appointmentsconfig_plugin"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointmentsconfig",
            name="limit_to_location",
            field=models.CharField(
                blank=True,
                help_text="If configured, only products connected to this location are exposed. Additionally, the user can only select this location for the appointment.",
                max_length=50,
                verbose_name="location",
            ),
        ),
    ]
