# Generated by Django 3.2.20 on 2023-07-21 15:00

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0010_appointment_appointmentproduct"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="contact_details",
            field=models.JSONField(
                default=dict,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                help_text="Additional contact detail field values.",
                verbose_name="contact details",
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="contact_details_meta",
            field=models.JSONField(
                default=list,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                help_text="Contact detail field definitions, depending on the required fields in the selected plugin. Recorded for historical purposes.",
                verbose_name="contact details meta",
            ),
        ),
    ]
