# Generated by Django 3.2.20 on 2023-09-05 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0001_initial_squashed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointmentsconfig",
            name="limit_to_location",
            field=models.CharField(
                blank=True,
                help_text="If configured, only products connected to this location are exposed. Additionally, the user can only select this location for the appointment.",
                max_length=100,
                verbose_name="location",
            ),
        ),
    ]
