# Generated by Django 2.2.24 on 2021-11-19 12:04

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        (
            "eherkenning_oidc",
            "0003_openidconnecteherkenningconfig_oidc_op_logout_endpoint",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="openidconnecteherkenningconfig",
            name="oidc_redirect_allowed_hosts",
            field=django_better_admin_arrayfield.models.fields.ArrayField(
                base_field=models.CharField(
                    max_length=1000, verbose_name="Allowed redirect hosts"
                ),
                blank=True,
                default=list,
                help_text="Hosts that are allowed for redirection after authentication is successful",
                size=None,
                verbose_name="Allowed redirect hosts",
            ),
        ),
    ]
