# Generated by Django 4.2.21 on 2025-05-30 10:50

from django.db import migrations

from ..constants import (
    OIDC_DIGID_IDENTIFIER,
    OIDC_DIGID_MACHTIGEN_IDENTIFIER,
    OIDC_EH_BEWINDVOERING_IDENTIFIER,
    OIDC_EH_IDENTIFIER,
    OIDC_ORG_IDENTIFIER,
)


def _migrate_config_forward(config_old, identifier, options, apps):
    OIDCClient = apps.get_model("mozilla_django_oidc_db", "OIDCClient")
    OIDCProvider = apps.get_model("mozilla_django_oidc_db", "OIDCProvider")

    # Maybe reuse an existing provider
    oidc_provider, _ = OIDCProvider.objects.get_or_create(
        oidc_op_discovery_endpoint=(config_old.oidc_op_discovery_endpoint),
        defaults={
            "identifier": f"{identifier}-provider",
            "oidc_op_discovery_endpoint": (config_old.oidc_op_discovery_endpoint),
            "oidc_op_jwks_endpoint": config_old.oidc_op_jwks_endpoint,
            "oidc_op_authorization_endpoint": (
                config_old.oidc_op_authorization_endpoint
            ),
            "oidc_op_token_endpoint": config_old.oidc_op_token_endpoint,
            "oidc_op_user_endpoint": config_old.oidc_op_user_endpoint,
            "oidc_op_logout_endpoint": config_old.oidc_op_logout_endpoint,
            "oidc_token_use_basic_auth": config_old.oidc_token_use_basic_auth,
            "oidc_use_nonce": config_old.oidc_use_nonce,
            "oidc_nonce_size": config_old.oidc_nonce_size,
            "oidc_state_size": config_old.oidc_state_size,
        },
    )

    OIDCClient.objects.update_or_create(
        identifier=identifier,
        defaults={
            "enabled": config_old.enabled,
            "oidc_provider": oidc_provider,
            "oidc_rp_client_id": config_old.oidc_rp_client_id,
            "oidc_rp_client_secret": config_old.oidc_rp_client_secret,
            "oidc_rp_sign_algo": config_old.oidc_rp_sign_algo,
            "oidc_rp_scopes_list": config_old.oidc_rp_scopes_list,
            "oidc_rp_idp_sign_key": config_old.oidc_rp_idp_sign_key,
            "oidc_keycloak_idp_hint": config_old.oidc_keycloak_idp_hint,
            "userinfo_claims_source": config_old.userinfo_claims_source,
            "options": options,
        },
    )


def move_data_forward(apps, schema_editor):
    OFDigiDConfig = apps.get_model("digid_eherkenning_oidc", "OFDigiDConfig")
    OFDigiDMachtigenConfig = apps.get_model(
        "digid_eherkenning_oidc", "OFDigiDMachtigenConfig"
    )
    OFEHerkenningConfig = apps.get_model(
        "digid_eherkenning_oidc", "OFEHerkenningConfig"
    )
    OFEHerkenningBewindvoeringConfig = apps.get_model(
        "digid_eherkenning_oidc", "OFEHerkenningBewindvoeringConfig"
    )
    OrgOpenIDConnectConfig = apps.get_model(
        "authentication_org_oidc", "OrgOpenIDConnectConfig"
    )

    # Solo model, there should be only one
    digid_config_old = OFDigiDConfig.objects.first()
    if digid_config_old:
        options = {
            "loa_settings": {
                "claim_path": digid_config_old.loa_claim,
                "default": digid_config_old.default_loa,
                "value_mapping": digid_config_old.loa_value_mapping,
            },
            "identity_settings": {
                "bsn_claim_path": digid_config_old.bsn_claim,
            },
        }
        _migrate_config_forward(digid_config_old, OIDC_DIGID_IDENTIFIER, options, apps)

    digid_machtigen_config_old = OFDigiDMachtigenConfig.objects.first()
    if digid_machtigen_config_old:
        options = {
            "loa_settings": {
                "claim_path": digid_machtigen_config_old.loa_claim,
                "default": digid_machtigen_config_old.default_loa,
                "value_mapping": digid_machtigen_config_old.loa_value_mapping,
            },
            "identity_settings": {
                "representee_bsn_claim_path": digid_machtigen_config_old.representee_bsn_claim,
                "authorizee_bsn_claim_path": digid_machtigen_config_old.authorizee_bsn_claim,
                "mandate_service_id_claim_path": digid_machtigen_config_old.mandate_service_id_claim,
            },
        }
        _migrate_config_forward(
            digid_machtigen_config_old, OIDC_DIGID_MACHTIGEN_IDENTIFIER, options, apps
        )

    eherkenning_config_old = OFEHerkenningConfig.objects.first()
    if eherkenning_config_old:
        options = {
            "loa_settings": {
                "claim_path": eherkenning_config_old.loa_claim,
                "default": eherkenning_config_old.default_loa,
                "value_mapping": eherkenning_config_old.loa_value_mapping,
            },
            "identity_settings": {
                "identifier_type_claim_path": eherkenning_config_old.identifier_type_claim,
                "legal_subject_claim_path": eherkenning_config_old.legal_subject_claim,
                "acting_subject_claim_path": eherkenning_config_old.acting_subject_claim,
                "branch_number_claim_path": eherkenning_config_old.branch_number_claim,
            },
        }
        _migrate_config_forward(
            eherkenning_config_old, OIDC_EH_IDENTIFIER, options, apps
        )

    eherkenning_bewindvoering_config_old = (
        OFEHerkenningBewindvoeringConfig.objects.first()
    )
    if eherkenning_bewindvoering_config_old:
        options = {
            "loa_settings": {
                "claim_path": eherkenning_bewindvoering_config_old.loa_claim,
                "default": eherkenning_bewindvoering_config_old.default_loa,
                "value_mapping": eherkenning_bewindvoering_config_old.loa_value_mapping,
            },
            "identity_settings": {
                "identifier_type_claim_path": eherkenning_bewindvoering_config_old.identifier_type_claim,
                "legal_subject_claim_path": eherkenning_bewindvoering_config_old.legal_subject_claim,
                "acting_subject_claim_path": eherkenning_bewindvoering_config_old.acting_subject_claim,
                "branch_number_claim_path": eherkenning_bewindvoering_config_old.branch_number_claim,
                "representee_claim_path": eherkenning_bewindvoering_config_old.representee_claim,
                "mandate_service_id_claim_path": eherkenning_bewindvoering_config_old.mandate_service_id_claim,
                "mandate_service_uuid_claim_path": eherkenning_bewindvoering_config_old.mandate_service_uuid_claim,
            },
        }
        _migrate_config_forward(
            eherkenning_bewindvoering_config_old,
            OIDC_EH_BEWINDVOERING_IDENTIFIER,
            options,
            apps,
        )

    org_config_old = OrgOpenIDConnectConfig.objects.first()
    if org_config_old:
        options = {
            "user_settings": {
                "claim_mappings": {
                    "username": org_config_old.username_claim,
                    **org_config_old.claim_mapping,
                },
                "username_case_sensitive": True,
            },
            "groups_settings": {
                "claim_mapping": org_config_old.groups_claim,
                "sync": org_config_old.sync_groups,
                "sync_pattern": org_config_old.sync_groups_glob_pattern,
                "default_groups": [
                    group.name for group in org_config_old.default_groups.all()
                ],
                "make_users_staff": org_config_old.make_users_staff,
                "superuser_group_names": org_config_old.superuser_group_names,
            },
        }
        _migrate_config_forward(
            org_config_old,
            OIDC_ORG_IDENTIFIER,
            options,
            apps,
        )


def move_data_backwards(apps, schema_editor):
    # TODO
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("oidc_plugins", "0001_initial"),
        (
            "mozilla_django_oidc_db",
            "0006_oidcprovider_oidcclient",
        ),
        ("digid_eherkenning_oidc", "0001_initial"),
        ("authentication_org_oidc", "0001_initial"),
    ]
    run_before = [
        ("mozilla_django_oidc_db", "0008_delete_openidconnectconfig"),
    ]

    operations = [migrations.RunPython(move_data_forward, move_data_backwards)]
