# Generated by Django 3.2.18 on 2023-06-14 13:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prefill_haalcentraal", "0002_nice_verbose_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="haalcentraalconfig",
            name="version",
            field=models.CharField(
                choices=[
                    ("1.3", "BRP Bevragen Personen 1.3"),
                    ("2.0", "BRP Bevragen Personen 2.0"),
                ],
                default="1.3",
                help_text="The API version provided by the selected service.",
                max_length=30,
                verbose_name="API version",
            ),
        ),
    ]
