# Generated by Django 3.2.18 on 2023-05-23 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("zgw_consumers", "0019_alter_service_uuid"),
        ("prefill_haalcentraal", "0002_nice_verbose_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="haalcentraalconfig",
            name="version",
            field=models.CharField(
                choices=[
                    ("1.3", "BRP Bevragen Personen 1.3"),
                    ("2.0", "BRP Bevragen Personen 2.0"),
                ],
                default="1.3",
                help_text="The BRP Bevragen Personen version.",
                max_length=30,
                verbose_name="BRP Bevragen Personen version",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="haalcentraalconfig",
            name="service",
            field=models.OneToOneField(
                limit_choices_to={"api_type": "orc"},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="zgw_consumers.service",
                verbose_name="BRP Bevragen Personen service",
            ),
        ),
    ]
