# Generated by Django 3.2.18 on 2023-05-25 07:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prefill_haalcentraal", "0003_auto_20230523_0240"),
    ]

    operations = [
        migrations.AlterField(
            model_name="haalcentraalconfig",
            name="version",
            field=models.CharField(
                choices=[
                    ("1.3", "BRP Bevragen Personen 1.3"),
                    ("2.0", "BRP Bevragen Personen 2.0"),
                ],
                default="1.3",
                help_text="The BRP Bevragen Personen version.",
                max_length=30,
                verbose_name="BRP Bevragen Personen version",
            ),
        ),
    ]
