# Generated by Django 2.2.24 on 2021-08-02 09:26

import uuid

import django.db.models.deletion
from django.db import migrations, models

import openforms.utils.fields
from openforms.plugins.constants import UNIQUE_ID_MAX_LENGTH


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("submissions", "0025_auto_20210726_0832"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubmissionPayment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    openforms.utils.fields.StringUUIDField(
                        default=uuid.uuid4, unique=True, verbose_name="UUID"
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "plugin_id",
                    models.CharField(
                        max_length=UNIQUE_ID_MAX_LENGTH, verbose_name="Payment backend"
                    ),
                ),
                ("form_url", models.URLField(max_length=255, verbose_name="Form URL")),
                (
                    "order_id",
                    models.CharField(
                        help_text="Unique tracking across backend",
                        max_length=255,
                        verbose_name="Order ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total payment amount.",
                        max_digits=8,
                        verbose_name="payment amount",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("started", "Started by user"),
                            ("processing", "Backend is processing"),
                            ("failed", "Cancelled or failed"),
                            ("completed", "Completed by user"),
                            ("registered", "Completed and registered"),
                        ],
                        default="started",
                        help_text="Status of the payment process in the configured backend.",
                        max_length=32,
                        verbose_name="payment status",
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="submissions.Submission",
                    ),
                ),
            ],
            options={
                "unique_together": {("submission", "plugin_id", "order_id")},
            },
        ),
    ]
