# Generated by Django 4.2.11 on 2024-07-04 14:13

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("submissions", "0001_initial_to_openforms_v230"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubmissionPayment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, unique=True, verbose_name="UUID"
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "plugin_id",
                    models.CharField(max_length=100, verbose_name="Payment backend"),
                ),
                (
                    "plugin_options",
                    models.JSONField(
                        blank=True,
                        help_text="Copy of payment options at time of initializing payment.",
                        null=True,
                        verbose_name="Payment options",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total payment amount.",
                        max_digits=8,
                        verbose_name="payment amount",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("started", "Started by user"),
                            ("processing", "Backend is processing"),
                            ("failed", "Cancelled or failed"),
                            ("completed", "Completed by user"),
                            ("registered", "Completed and registered"),
                        ],
                        default="started",
                        help_text="Status of the payment process in the configured backend.",
                        max_length=32,
                        verbose_name="payment status",
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="submissions.submission",
                    ),
                ),
                (
                    "public_order_id",
                    models.CharField(
                        blank=True,
                        help_text="The order ID to be sent to the payment provider. This ID is built by concatenating an optional global prefix, the submission public reference and a unique incrementing ID.",
                        max_length=32,
                        verbose_name="Order ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "submission payment details",
                "verbose_name_plural": "submission payment details",
            },
        ),
        migrations.AddConstraint(
            model_name="submissionpayment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("public_order_id", ""), _negated=True),
                fields=("public_order_id",),
                name="unique_public_order_id",
            ),
        ),
    ]
