# Generated by Django 2.2.24 on 2021-08-12 12:12

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="submissionpayment",
            name="plugin_options",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True,
                help_text="Copy of payment options at time of initializing payment.",
                null=True,
                verbose_name="Payment options",
            ),
        ),
    ]
