# Generated by Django 2.2.24 on 2021-10-22 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_submissionpayment_public_order_id"),
    ]

    # Removed as part of Open Forms 2.7 release cycle
    operations = []
