# Generated by Django 4.2.14 on 2024-08-05 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_submissionpayment_provider_payment_id"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="submissionpayment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("provider_payment_id", ""), _negated=True),
                fields=("plugin_id", "provider_payment_id"),
                name="unique_plugin_payment",
            ),
        ),
    ]
