# Generated by Django 2.2.24 on 2021-10-28 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_set_public_order_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submissionpayment",
            name="order_id",
            field=models.BigIntegerField(
                help_text="Unique tracking across backend",
                null=True,
                unique=True,
                verbose_name="Order ID (internal)",
            ),
        ),
        migrations.AlterField(
            model_name="submissionpayment",
            name="public_order_id",
            field=models.CharField(
                blank=True,
                help_text="Order ID stored with payment provider.",
                max_length=32,
                verbose_name="Order ID",
            ),
        ),
    ]
