# Generated by Django 4.2.23 on 2025-08-05 15:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0003_submissionpayment_unique_plugin_payment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submissionpayment",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
