# Generated by Django 2.2.24 on 2021-11-01 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0004_auto_20211028_1141"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="submissionpayment",
            name="form_url",
        ),
    ]
