# Generated by Django 3.2.23 on 2024-01-30 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0007_alter_submissionpayment_plugin_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="submissionpayment",
            name="order_id",
        ),
        migrations.AlterField(
            model_name="submissionpayment",
            name="public_order_id",
            field=models.CharField(
                blank=True,
                help_text="The order ID to be sent to the payment provider. This ID is built by concatenating an optional global prefix, the submission public reference and a unique incrementing ID.",
                max_length=32,
                verbose_name="Order ID",
            ),
        ),
    ]
