# Generated by Django 4.2.10 on 2024-02-22 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("soap", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="soapservice",
            name="timeout",
            field=models.PositiveSmallIntegerField(
                default=10,
                help_text="Timeout (in seconds) for HTTP calls.",
                verbose_name="timeout",
            ),
        ),
    ]
