from django.test import TestCase

from openforms.formio.typing import Component

from ...service import format_value


class IssuesTestCase(TestCase):
    def test_issue_1428_none_select(self):
        component = {
            "id": "ei69nt",
            "key": "wanneerKuntUHelpen",
            "tree": False,
            "type": "fieldset",
            "input": False,
            "label": "Wanneer kunt u helpen?",
            "logic": [],
            "hidden": False,
            "legend": "Wanneer kunt u helpen?",
            "prefix": "",
            "suffix": "",
            "unique": False,
            "widget": None,
            "dbIndex": False,
            "overlay": {"top": "", "left": "", "style": "", "width": "", "height": ""},
            "tooltip": "",
            "disabled": False,
            "multiple": False,
            "redrawOn": "",
            "tabindex": "",
            "validate": {
                "custom": "",
                "unique": False,
                "multiple": False,
                "required": False,
                "customPrivate": False,
                "strictDateValidation": False,
            },
            "autofocus": False,
            "encrypted": False,
            "hideLabel": False,
            "modalEdit": False,
            "protected": False,
            "refreshOn": "",
            "tableView": False,
            "attributes": {},
            "components": [
                {
                    "id": "e6ab416",
                    "key": "content",
                    "html": "<p>We hebben 20 vrijwilligers per dag nodig. De vrijwilligers werken in 2 ploegen. Een ploeg voor overdag, ongeveer tussen 7.00 en 15.30 uur. En een ploeg voor de avond, ongeveer tussen 15.00 en 22.00 uur. Het precieze tijdstip hangt af van wat u gaat doen.&nbsp;</p><p>Geef hieronder aan op welke momenten u zou kunnen helpen.&nbsp;</p>",
                    "tags": [],
                    "type": "content",
                    "input": False,
                    "label": "toelichting",
                    "logic": [],
                    "hidden": False,
                    "prefix": "",
                    "suffix": "",
                    "unique": False,
                    "widget": None,
                    "dbIndex": False,
                    "overlay": {
                        "top": "",
                        "left": "",
                        "page": "",
                        "style": "",
                        "width": "",
                        "height": "",
                    },
                    "tooltip": "",
                    "disabled": False,
                    "multiple": False,
                    "redrawOn": "",
                    "tabindex": "",
                    "validate": {
                        "custom": "",
                        "unique": False,
                        "multiple": False,
                        "required": False,
                        "customPrivate": False,
                        "strictDateValidation": False,
                    },
                    "autofocus": False,
                    "encrypted": False,
                    "hideLabel": False,
                    "modalEdit": False,
                    "protected": False,
                    "refreshOn": "",
                    "tableView": False,
                    "attributes": {},
                    "errorLabel": "",
                    "persistent": True,
                    "properties": {},
                    "validateOn": "change",
                    "clearOnHide": True,
                    "conditional": {"eq": "", "json": "", "show": None, "when": None},
                    "customClass": "",
                    "description": "",
                    "placeholder": "",
                    "defaultValue": None,
                    "dataGridLabel": False,
                    "labelPosition": "top",
                    "showCharCount": False,
                    "showWordCount": False,
                    "calculateValue": "",
                    "calculateServer": False,
                    "refreshOnChange": False,
                    "customConditional": "",
                    "allowMultipleMasks": False,
                    "customDefaultValue": "",
                    "allowCalculateOverride": False,
                },
                {
                    "id": "eu66hmq",
                    "key": "select1",
                    "data": {
                        "url": "",
                        "json": "",
                        "custom": "",
                        "values": [
                            {
                                "label": "Vrijdag 11 maart, overdag",
                                "value": "vrijdag11MaartOverdag",
                            },
                            {
                                "label": "Vrijdag 11 maart, avond",
                                "value": "vrijdag11MaartAvond",
                            },
                            {
                                "label": "Zaterdag 12 maart, overdag",
                                "value": "zaterdag12MaartOverdag",
                            },
                            {
                                "label": "Zaterdag 12 maart, avond",
                                "value": "zaterdag12MaartAvond",
                            },
                            {
                                "label": "Zondag 13 maart, overdag",
                                "value": "zondag13MaartOverdag",
                            },
                            {
                                "label": "Zondag 13 maart, avond",
                                "value": "zondag13MaartAvond",
                            },
                            {
                                "label": "Maandag 14 maart, overdag",
                                "value": "maandag14MaartOverdag",
                            },
                            {
                                "label": "Maandag 14 maart, avond",
                                "value": "maandag14MaartAvond",
                            },
                            {
                                "label": "Dinsdag 15 maart, overdag",
                                "value": "dinsdag15MaartOverdag",
                            },
                            {
                                "label": "Dinsdag 15 maart, avond",
                                "value": "dinsdag15MaartAvond",
                            },
                            {
                                "label": "Woensdag 16 maart, overdag",
                                "value": "woensdag16MaartOverdag",
                            },
                            {
                                "label": "Woensdag 16 maart, avond",
                                "value": "woensdag16MaartAvond",
                            },
                            {
                                "label": "Donderdag 17 maart, overdag",
                                "value": "donderdag17MaartOverdag",
                            },
                            {
                                "label": "Donderdag 17 maart, avond",
                                "value": "donderdag17MaartAvond",
                            },
                            {
                                "label": "Vrijdag 18 maart, overdag",
                                "value": "vrijdag18MaartOverdag",
                            },
                            {
                                "label": "Vrijdag 18 maart, avond",
                                "value": "vrijdag18MaartAvond",
                            },
                            {
                                "label": "Zaterdag 19 maart, overdag",
                                "value": "zaterdag19MaartOverdag",
                            },
                            {
                                "label": "Zaterdag 19 maart, avond",
                                "value": "zaterdag19MaartAvond",
                            },
                            {
                                "label": "Zondag 20 maart, overdag",
                                "value": "zondag20MaartOverdag",
                            },
                            {
                                "label": "Zondag 20 maart, avond",
                                "value": "zondag20MaartAvond",
                            },
                            {
                                "label": "Maandag 21 maart, overdag",
                                "value": "maandag21MaartOverdag",
                            },
                            {
                                "label": "Maandag 21 maart, avond",
                                "value": "maandag21MaartAvond",
                            },
                            {
                                "label": "Dinsdag 22 maart, overdag",
                                "value": "dinsdag22MaartOverdag",
                            },
                            {
                                "label": "Dinsdag 22 maart, avond",
                                "value": "dinsdag22MaartAvond",
                            },
                            {
                                "label": "Woensdag 23 maart, overdag",
                                "value": "woensdag23MaartOverdag",
                            },
                            {
                                "label": "Woensdag 23 maart, avond",
                                "value": "woensdag23MaartAvond",
                            },
                            {
                                "label": "Donderdag 24 maart, overdag",
                                "value": "donderdag24MaartOverdag",
                            },
                            {
                                "label": "Donderdag 24 maart, avond",
                                "value": "donderdag24MaartAvond",
                            },
                            {"label": "", "value": ""},
                        ],
                        "resource": "",
                    },
                    "type": "select",
                    "input": True,
                    "label": "Select",
                    "limit": 100,
                    "filter": "",
                    "hidden": False,
                    "idPath": "id",
                    "prefix": "",
                    "suffix": "",
                    "unique": False,
                    "widget": None,
                    "dataSrc": "values",
                    "dbIndex": False,
                    "overlay": {
                        "top": "",
                        "left": "",
                        "style": "",
                        "width": "",
                        "height": "",
                    },
                    "tooltip": "",
                    "disabled": False,
                    "lazyLoad": True,
                    "multiple": True,
                    "redrawOn": "",
                    "tabindex": "",
                    "template": "<span>{{ item.label }}</span>",
                    "validate": {
                        "custom": "",
                        "unique": False,
                        "plugins": [],
                        "multiple": False,
                        "required": False,
                        "customPrivate": False,
                        "onlyAvailableItems": False,
                        "strictDateValidation": False,
                    },
                    "autofocus": False,
                    "encrypted": False,
                    "hideLabel": False,
                    "indexeddb": {"filter": {}},
                    "minSearch": 0,
                    "modalEdit": False,
                    "protected": False,
                    "refreshOn": "",
                    "tableView": True,
                    "attributes": {},
                    "errorLabel": "",
                    "persistent": True,
                    "properties": {},
                    "validateOn": "change",
                    "clearOnHide": True,
                    "conditional": {"eq": "", "show": None, "when": None},
                    "customClass": "",
                    "description": "",
                    "fuseOptions": {"include": "score", "threshold": 0.3},
                    "ignoreCache": False,
                    "placeholder": "",
                    "searchField": "",
                    "showInEmail": False,
                    "authenticate": False,
                    "defaultValue": [],
                    "registration": {"attribute": ""},
                    "selectFields": "",
                    "customOptions": {},
                    "dataGridLabel": False,
                    "labelPosition": "top",
                    "readOnlyValue": False,
                    "searchEnabled": True,
                    "showCharCount": False,
                    "showWordCount": False,
                    "uniqueOptions": False,
                    "valueProperty": "",
                    "calculateValue": "",
                    "clearOnRefresh": False,
                    "useExactSearch": False,
                    "calculateServer": False,
                    "isSensitiveData": False,
                    "selectThreshold": 0.3,
                    "allowMultipleMasks": False,
                    "customDefaultValue": "",
                    "allowCalculateOverride": False,
                },
            ],
            "errorLabel": "",
            "persistent": False,
            "properties": {},
            "validateOn": "change",
            "clearOnHide": True,
            "conditional": {"eq": "", "show": None, "when": None},
            "customClass": "",
            "description": "",
            "placeholder": "",
            "defaultValue": None,
            "dataGridLabel": False,
            "labelPosition": "top",
            "showCharCount": False,
            "showWordCount": False,
            "calculateValue": "",
            "calculateServer": False,
            "allowMultipleMasks": False,
            "customDefaultValue": "",
            "allowCalculateOverride": False,
        }

        data = {
            "watWiltUDoen": {
                "tolk": False,
                "helpenBijDeInformatiebalie": False,
                "helpenBijDeGoederenuitgifte": False,
                "helpenBijHetUitdelenVanEtenKoffieEnThee": True,
                "helpenMetWatErNodigIsContactMetVluchtelingen": False,
            },
            "opWelkeDagenKuntUHelpen": {
                "zondagAvond": False,
                "dinsdagAvond": False,
                "maandagAvond": True,
                "vrijdagAvond": False,
                "woensdagAvond": False,
                "zaterdagAvond": False,
                "zondagOverdag": False,
                "dinsdagOverdag": False,
                "donderdagAvond": False,
                "maandagOverdag": False,
                "vrijdagOverdag": False,
                "woensdagOverdag": False,
                "zaterdagOverdag": False,
                "donderdagOverdag": False,
            },
            "heeftUZichOokAangemeldAlsVrijwilligerBijVluchtelingenWerk": "nee",
            "deGemeenteVraagtMisschienEenAndereOrganisatieOmVrijwilligersVoorDeNoodopvangVanVluchtelingenTeRegelenMogenWijUwGegevensAanDieOrganisatieDoorgeven": "ja",
        }

        # note the problem seems to be nothing was submitted for the 'select1' select
        # so the value is None
        value = data.get("select1", None)

        select1 = component["components"][1]
        self.assertEqual(select1["key"], "select1")

        res = format_value(select1, value)

        self.assertEqual(res, "")

    def test_issue_1466_assertion_error_string(self):
        """
        Regression test for radio inputs with numeric values.

        Github issue #1466, when a crash occurred in the PDF generation because of
        unexpected non-string option value. This appears to happen when values are
        numeric and Formio keeps the number datatype instead of converting to string.
        """
        component: Component = {  # pyright: ignore[reportAssignmentType]
            "allowCalculateOverride": False,
            "allowMultipleMasks": False,
            "attributes": {},
            "autofocus": False,
            "calculateServer": False,
            "calculateValue": "",
            "clearOnHide": True,
            "conditional": {"eq": "", "show": None, "when": None},
            "customClass": "",
            "customDefaultValue": "",
            "dataGridLabel": False,
            "dbIndex": False,
            "defaultValue": "",
            "description": "",
            "disabled": False,
            "encrypted": False,
            "errorLabel": "",
            "fieldSet": False,
            "hidden": False,
            "hideLabel": False,
            "id": "e2n18ig",
            "input": True,
            "inputType": "radio",
            "isSensitiveData": False,
            "key": "projectmanagement",
            "label": "Hoe tevreden ben je met ons projectmanagement / consultancy en bijbehorende communicatie?",
            "labelPosition": "top",
            "modalEdit": False,
            "multiple": False,
            "overlay": {"height": "", "left": "", "style": "", "top": "", "width": ""},
            "persistent": True,
            "placeholder": "",
            "prefix": "",
            "properties": {},
            "protected": False,
            "redrawOn": "",
            "refreshOn": "",
            "registration": {"attribute": ""},
            "showCharCount": False,
            "showInEmail": False,
            "showWordCount": False,
            "suffix": "",
            "tabindex": "",
            "tableView": False,
            "tooltip": "",
            "type": "radio",
            "unique": False,
            "validate": {
                "custom": "",
                "customPrivate": False,
                "multiple": False,
                "onlyAvailableItems": False,
                "plugins": [],
                "required": True,
                "strictDateValidation": False,
                "unique": False,
            },
            "validateOn": "change",
            "values": [
                {"label": "1 - Totaal niet tevreden", "value": "1"},
                {"label": "2", "value": "2"},
                {"label": "3", "value": "3"},
                {"label": "4", "value": "4"},
                {"label": "5", "value": "5"},
                {"label": "6", "value": "6"},
                {"label": "7", "value": "7"},
                {"label": "8", "value": "8"},
                {"label": "9", "value": "9"},
                {"label": "10 - Heel erg tevreden", "value": "10"},
                {"label": "n.v.t.", "value": "nvt"},
            ],
            "widget": None,
        }
        value = 10

        res = format_value(component, value)

        self.assertEqual(res, "10 - Heel erg tevreden")
