# Generated by Django 4.2.25 on 2025-10-10 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("zgw_consumers", "0026_remove_service_oas_remove_service_oas_file"),
    ]

    operations = [
        migrations.CreateModel(
            name="JccRestConfig",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service",
                    models.OneToOneField(
                        limit_choices_to={"api_type": "orc"},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="zgw_consumers.service",
                        verbose_name="JCC Rest API",
                    ),
                ),
            ],
            options={
                "verbose_name": "JCC Rest configuration",
            },
        ),
    ]
