# Generated by Django 4.2.28 on 2026-02-24 10:15

import django.core.serializers.json
from django.db import migrations, models

import openforms.appointments.contrib.jcc_rest.models


class Migration(migrations.Migration):
    dependencies = [
        ("jcc_rest", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="jccrestconfig",
            name="configuration",
            field=models.JSONField(
                default=openforms.appointments.contrib.jcc_rest.models.get_default_components,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                help_text="The contact details components as Form.io JSON schema",
                verbose_name="components configuration",
            ),
        ),
    ]
