# Generated by Django 5.2.17 on 2026-08-11 06:53

from uuid import uuid4

from django.db import migrations


def fix_radio_definition(apps, _):
    JccRestConfig = apps.get_model("jcc_rest", "JccRestConfig")
    config = JccRestConfig.objects.first()
    if config is None:
        return

    components = config.configuration.get("components", [])
    for component in components:
        match component:
            case {"type": "radio"}:
                data_src = (component.get("openForms") or {}).get("dataSrc")
                if data_src != "manual":
                    component.setdefault("openForms", {})
                    component["openForms"]["dataSrc"] = "manual"

                # radio options must be strings for the renderer/builder
                for option in component["values"]:
                    option["value"] = str(option["value"])
            case _:
                continue

    config.save()


def esnure_components_have_unique_id(apps, _):
    JccRestConfig = apps.get_model("jcc_rest", "JccRestConfig")
    config = JccRestConfig.objects.first()
    if config is None:
        return

    components = config.configuration.get("components", [])
    for component in components:
        if not component.get("id"):
            component["id"] = str(uuid4())

    config.save()


class Migration(migrations.Migration):
    dependencies = [
        ("jcc_rest", "0002_jccrestconfig_configuration"),
    ]

    operations = [
        migrations.RunPython(fix_radio_definition, migrations.RunPython.noop),
        migrations.RunPython(
            esnure_components_have_unique_id, migrations.RunPython.noop
        ),
    ]
