# Generated by Django 4.2.27 on 2025-12-24 19:09

import uuid

from django.db import migrations, models

import django_jsonform.models.fields


class Migration(migrations.Migration):
    replaces = [
        ("yivi_oidc", "0001_initial"),
        ("yivi_oidc", "0002_move_data_oidc"),
        ("yivi_oidc", "0003_delete_yiviopenidconnectconfig"),
        ("yivi_oidc", "0004_attributegroup_uuid"),
        ("yivi_oidc", "0005_data_migrate_set_attributegroup_uuid"),
        ("yivi_oidc", "0006_alter_attributegroup_uuid"),
    ]

    dependencies = [
        ("mozilla_django_oidc_db", "0006_oidcprovider_oidcclient"),
        (
            "digid_eherkenning_oidc_generics",
            "0009_remove_digidconfig_oidc_exempt_urls_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="AttributeGroup",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="A human-readable name for the group of attributes, used in the form configuration.",
                        max_length=100,
                        unique=True,
                        verbose_name="group name",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="A longer human-readable description for the group of attributes, used in the form configuration.",
                        max_length=200,
                        verbose_name="group description",
                    ),
                ),
                (
                    "attributes",
                    django_jsonform.models.fields.ArrayField(  # type: ignore
                        base_field=models.CharField(
                            blank=True, max_length=100, verbose_name="attribute"
                        ),
                        blank=True,
                        default=list,
                        help_text="List of attributes that will be requested from the user. The user can choose whether to grant access to all these attributes, or none. If you want individually optional attributes, you should define them as separate attribute groups.",
                        size=None,
                        verbose_name="attributes",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, unique=True, verbose_name="UUID"
                    ),
                ),
            ],
            options={
                "verbose_name": "yivi attribute group",
                "verbose_name_plural": "yivi attribute groups",
            },
        ),
    ]
