# Generated by Django 4.2.23 on 2025-08-13 13:22

from django.db import migrations, models

from autoslug import AutoSlugField


class Migration(migrations.Migration):
    dependencies = [
        ("yivi_oidc", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="attributegroup",
            name="slug",
            field=AutoSlugField(
                editable=True,
                help_text="A unique identifying slug for the group of attributes.",
                max_length=100,
                populate_from="name",
                null=True,
                unique=True,
                verbose_name="slug",
            ),
        ),
        migrations.AlterField(
            model_name="attributegroup",
            name="name",
            field=models.CharField(
                help_text="A human-readable name for the group of attributes, used in the form configuration.",
                max_length=100,
                verbose_name="group name",
            ),
        ),
    ]
