# Generated by Django 4.2.21 on 2025-05-27 10:37

from django.db import migrations, models

import django_jsonform.models.fields
import mozilla_django_oidc_db.fields


class Migration(migrations.Migration):
    dependencies = [
        ("yivi_oidc", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="yiviopenidconnectconfig",
            old_name="default_loa",
            new_name="bsn_default_loa",
        ),
        migrations.RenameField(
            model_name="yiviopenidconnectconfig",
            old_name="loa_claim",
            new_name="bsn_loa_claim",
        ),
        migrations.RenameField(
            model_name="yiviopenidconnectconfig",
            old_name="loa_value_mapping",
            new_name="bsn_loa_value_mapping",
        ),
        migrations.AddField(
            model_name="yiviopenidconnectconfig",
            name="bsn_scope",
            field=models.CharField(
                default="bsn",
                help_text="The scope used during BSN authentication requests to fetch the BSN claim.",
                max_length=100,
                verbose_name="bsn scope",
            ),
        ),
        migrations.AddField(
            model_name="yiviopenidconnectconfig",
            name="kvk_default_loa",
            field=models.CharField(
                blank=True,
                choices=[
                    ("urn:etoegang:core:assurance-class:loa1", "Non existent (1)"),
                    ("urn:etoegang:core:assurance-class:loa2", "Low (2)"),
                    ("urn:etoegang:core:assurance-class:loa2plus", "Low (2+)"),
                    ("urn:etoegang:core:assurance-class:loa3", "Substantial (3)"),
                    ("urn:etoegang:core:assurance-class:loa4", "High (4)"),
                ],
                help_text="Fallback level of assurance, in case no claim value could be extracted.",
                max_length=100,
                verbose_name="default LOA",
            ),
        ),
        migrations.AddField(
            model_name="yiviopenidconnectconfig",
            name="kvk_loa_claim",
            field=mozilla_django_oidc_db.fields.ClaimField(
                base_field=models.CharField(
                    max_length=50, verbose_name="claim path segment"
                ),
                blank=True,
                default=None,
                help_text="Name of the claim holding the level of assurance. If left empty, it is assumed there is no LOA claim and the configured fallback value will be used.",
                null=True,
                size=None,
                verbose_name="LoA claim",
            ),
        ),
        migrations.AddField(
            model_name="yiviopenidconnectconfig",
            name="kvk_loa_value_mapping",
            field=django_jsonform.models.fields.JSONField(
                blank=True,
                default=list,
                help_text="Level of assurance claim value mappings. Useful if the values in the LOA claim are proprietary, so you can translate them into their standardized identifiers.",
                verbose_name="loa mapping",
            ),
        ),
        migrations.AddField(
            model_name="yiviopenidconnectconfig",
            name="kvk_scope",
            field=models.CharField(
                default="kvk",
                help_text="The scope used during KVK authentication requests to fetch the KVK claims.",
                max_length=100,
                verbose_name="kvk scope",
            ),
        ),
    ]
