# Generated by Django 4.2.21 on 2025-07-14 09:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("yivi_oidc", "0002_move_data_oidc"),
    ]

    operations = [
        migrations.DeleteModel(
            name="YiviOpenIDConnectConfig",
        ),
    ]
