# Generated by Django 4.2.23 on 2025-08-21 08:39


from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("yivi_oidc", "0003_delete_yiviopenidconnectconfig"),
    ]

    operations = [
        migrations.AddField(
            model_name="attributegroup",
            name="uuid",
            field=models.UUIDField(verbose_name="UUID", null=True),
        ),
    ]
