# Generated by Django 4.2.23 on 2025-08-21 08:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("yivi_oidc", "0004_attributegroup_uuid"),
    ]

    # Emptied as part of the 3.4 release cycle - they're guaranteed to have been
    # executed on 3.3.x.
    operations = []
