# Generated by Django 2.2.20 on 2021-06-04 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("prefill_haalcentraal", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="haalcentraalconfig",
            options={"verbose_name": "Haal Centraal configuration"},
        ),
    ]
