# Generated by Django 3.2.21 on 2023-09-23 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("prefill_haalcentraal", "0003_haalcentraalconfig_version"),
        ("haalcentraal", "0002_copy_config_from_prefill"),
    ]

    operations = [
        migrations.DeleteModel(
            name="HaalCentraalConfig",
        ),
    ]
