# Generated by Django 2.2.16 on 2021-04-19 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0008_auto_20210402_1428"),
        ("zgw", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ZGWFormConfig",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "zaaktype",
                    models.URLField(
                        help_text="URL of the ZAAKTYPE in Catalogi API", max_length=1000
                    ),
                ),
                (
                    "informatieobjecttype",
                    models.URLField(
                        help_text="URL of the INFORMATIEOBJECTTYPE in Catalogi API",
                        max_length=1000,
                    ),
                ),
                (
                    "organisatie_rsin",
                    models.CharField(
                        help_text="RSIN of organization, which creates the ZAAK",
                        max_length=9,
                    ),
                ),
                (
                    "vertrouwelijkheidaanduiding",
                    models.CharField(
                        help_text="Confidentiality of the ZAAK and related INFORMATIEOBJECT",
                        max_length=100,
                    ),
                ),
                (
                    "form",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="forms.Form"
                    ),
                ),
            ],
            options={
                "verbose_name": "ZGW Form Configuration",
            },
        ),
    ]
