# Generated by Django 3.2.13 on 2022-04-14 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("submissions", "0052_submission_auth_attributes_hashed"),
    ]

    operations = [
        migrations.CreateModel(
            name="DMNEvaluationResult",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "component",
                    models.CharField(max_length=255, verbose_name="DMN component key"),
                ),
                (
                    "result",
                    models.JSONField(
                        blank=True, default=dict, null=True, verbose_name="result"
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="submissions.submission",
                    ),
                ),
            ],
            options={
                "unique_together": {("submission", "component")},
            },
        ),
    ]
