# Generated by Django 3.2.15 on 2022-09-16 16:43

from django.db import migrations, models

import openforms.upgrades.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="VersionInfo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "current",
                    models.CharField(
                        default=openforms.upgrades.models.get_current_version,
                        editable=False,
                        max_length=100,
                        verbose_name="current version",
                    ),
                ),
                (
                    "git_sha",
                    models.CharField(
                        default=openforms.upgrades.models.get_default_git_sha,
                        editable=False,
                        max_length=100,
                        verbose_name="current git hash",
                    ),
                ),
            ],
            options={
                "verbose_name": "version information",
            },
        ),
    ]
