# Generated by Django 4.2.17 on 2024-12-12 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zgw_consumers", "0022_set_default_service_slug"),
        ("objects_api", "0003_objectsapigroupconfig_identifier_unique"),
    ]

    operations = [
        migrations.AlterField(
            model_name="objectsapigroupconfig",
            name="objects_service",
            field=models.ForeignKey(
                limit_choices_to={"api_type": "orc"},
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="zgw_consumers.service",
                verbose_name="Objects API",
            ),
        ),
        migrations.AlterField(
            model_name="objectsapigroupconfig",
            name="objecttypes_service",
            field=models.ForeignKey(
                limit_choices_to={"api_type": "orc"},
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="zgw_consumers.service",
                verbose_name="Objecttypes API",
            ),
        ),
    ]
