# Generated by Django 4.2.17 on 2025-01-10 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("objects_api", "0004_alter_objectsapigroupconfig_objects_service_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="objectsapigroupconfig",
            table=None,
        ),
    ]
