# Generated by Django 4.2.18 on 2025-02-03 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("objects_api", "0005_alter_objectsapigroupconfig_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="objectsapigroupconfig",
            name="catalogue_domain",
            field=models.CharField(
                blank=True,
                help_text="The 'domein' attribute for the Catalogus resource in the Catalogi API.",
                max_length=5,
                verbose_name="catalogus domain",
            ),
        ),
    ]
