# Generated by Django 3.2.21 on 2023-09-22 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("zgw_consumers", "0019_alter_service_uuid"),
    ]

    operations = [
        migrations.CreateModel(
            name="HaalCentraalConfig",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "brp_personen_version",
                    models.CharField(
                        choices=[
                            ("1.3", "BRP Personen Bevragen 1.3"),
                            ("2.0", "BRP Personen Bevragen 2.0"),
                        ],
                        default="1.3",
                        help_text="The API version provided by the selected service.",
                        max_length=30,
                        verbose_name="BRP Personen Bevragen API version",
                    ),
                ),
                (
                    "brp_personen_service",
                    models.OneToOneField(
                        limit_choices_to={"api_type": "orc"},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="zgw_consumers.service",
                        verbose_name="BRP Personen Bevragen API",
                    ),
                ),
            ],
            options={
                "verbose_name": "Haal Centraal configuration",
            },
        ),
    ]
