# Generated by Django 3.2.21 on 2023-09-22 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("haalcentraal", "0001_initial"),
        ("prefill_haalcentraal", "0003_haalcentraalconfig_version"),
    ]

    # RunPython operation removed as part of the 2.8.0 release cycle
    operations = []
