# Generated by Django 3.2.23 on 2024-01-15 14:28

import django.db.models.deletion
from django.db import migrations, models

import openforms.contrib.haal_centraal.validators


class Migration(migrations.Migration):
    dependencies = [
        ("forms", "0001_initial_to_v320"),
        ("haalcentraal", "0002_copy_config_from_prefill"),
    ]

    operations = [
        migrations.AddField(
            model_name="haalcentraalconfig",
            name="default_brp_personen_processing_header_value",
            field=models.CharField(
                blank=True,
                help_text='The default processing ("verwerking") for queries to the BRP Persoon API. If a more specific value is configured on a form, that value is used instead.',
                max_length=242,
                validators=[
                    openforms.contrib.haal_centraal.validators.validate_verwerking_header
                ],
                verbose_name="default BRP Personen processing header value",
            ),
        ),
        migrations.AddField(
            model_name="haalcentraalconfig",
            name="default_brp_personen_purpose_limitation_header_value",
            field=models.CharField(
                blank=True,
                help_text='The default purpose limitation ("doelbinding") for queries to the BRP Persoon API. If a more specific value is configured on a form, that value is used instead.',
                max_length=255,
                verbose_name="default BRP Personen purpose limitation header value",
            ),
        ),
        migrations.CreateModel(
            name="BRPPersonenRequestOptions",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "brp_personen_purpose_limitation_header_value",
                    models.CharField(
                        blank=True,
                        help_text='The purpose limitation ("doelbinding") for queries to the BRP Persoon API.',
                        max_length=255,
                        verbose_name="BRP Personen purpose limitation header value",
                    ),
                ),
                (
                    "brp_personen_processing_header_value",
                    models.CharField(
                        blank=True,
                        help_text='The processing ("verwerking") for queries to the BRP Persoon API.',
                        max_length=242,
                        validators=[
                            openforms.contrib.haal_centraal.validators.validate_verwerking_header
                        ],
                        verbose_name="BRP Personen processing header value",
                    ),
                ),
                (
                    "form",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="brp_personen_request_options",
                        to="forms.form",
                        verbose_name="Form",
                    ),
                ),
            ],
            options={
                "verbose_name": "BRP Personen request options",
                "verbose_name_plural": "BRP Personen request options",
            },
        ),
    ]
