# Generated by Django 5.2.13 on 2026-05-06 05:08

from django.db import migrations
from django.db.migrations.state import StateApps


def update_to_v2(apps: StateApps, _):
    """
    Data migration for HaalCentraal version.

    We used to support both 1.3 and 2.0 versions of HaalCentraal but the first one was
    never used in reality. Make sure we have the v2 as the default choice for the config,
    """
    HC_config = apps.get_model("haalcentraal", "HaalCentraalConfig")

    hc_config, _ = HC_config.objects.get_or_create()
    if hc_config.brp_personen_version == "1.3":
        hc_config.brp_personen_version = "2.0"
        hc_config.save(update_fields=["brp_personen_version"])


class Migration(migrations.Migration):
    dependencies = [
        ("haalcentraal", "0004_haalcentraalconfig_brp_personen_oin_header_name"),
    ]

    operations = [
        migrations.RunPython(update_to_v2, migrations.RunPython.noop),
    ]
