# Generated by Django 5.2.13 on 2026-05-06 07:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("haalcentraal", "0005_update_version"),
    ]

    operations = [
        migrations.AlterField(
            model_name="haalcentraalconfig",
            name="brp_personen_version",
            field=models.CharField(
                choices=[("2.0", "BRP Personen Bevragen 2.0")],
                default="2.0",
                help_text="The API version provided by the selected service.",
                max_length=30,
                verbose_name="BRP Personen Bevragen API version",
            ),
        ),
    ]
