# Generated by Django 2.2.24 on 2021-11-11 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("microsoft", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MSGraphRegistrationConfig",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="registration_config",
                        to="microsoft.MSGraphService",
                        verbose_name="Microsoft Graph Service",
                    ),
                ),
            ],
            options={
                "verbose_name": "Microsoft Graph registration",
            },
        ),
    ]
