# Generated by Django 3.2.21 on 2023-11-13 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("microsoft", "0003_auto_20211210_1804"),
        ("registrations_microsoft_graph", "0002_auto_20211210_1804"),
    ]

    operations = [
        migrations.AlterField(
            model_name="msgraphregistrationconfig",
            name="service",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="registration_config",
                to="microsoft.msgraphservice",
                verbose_name="Microsoft Graph service",
            ),
        ),
    ]
