# Generated by Django 3.2.21 on 2023-11-17 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0002_change_json_encoder"),
    ]

    # RunPython operation removed as part of 2.7 release cycle, which requires 2.6.7 to
    # be run first.
    operations = []
