# Generated by Django 4.2.20 on 2025-04-28 15:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("submissions", "0003_alter_submissionvaluevariable_unique_together_and_more"),
    ]

    # RunPython operation removed as part of 3.3.x release cycle
    operations = []
