# Generated by Django 4.2.22 on 2025-06-23 12:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("submissions", "0004_set_co_sign_data_version"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="main_registration_completed",
            field=models.BooleanField(
                default=False,
                help_text="Indicates whether the main registration task completed successfully.",
                verbose_name="main registration completed",
            ),
        ),
    ]
