# Generated by Django 4.2.11 on 2024-06-26 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0004_auto_20231128_1536"),
    ]

    operations = [
        migrations.AddField(
            model_name="temporaryfileupload",
            name="legacy",
            field=models.BooleanField(
                default=False,
                help_text="Whether the instance is linked to a submission instance.",
                verbose_name="legacy",
            ),
        ),
        migrations.AddField(
            model_name="temporaryfileupload",
            name="submission",
            field=models.ForeignKey(
                help_text="Submission the temporary file upload belongs to.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="submissions.submission",
                verbose_name="submission",
            ),
        ),
    ]
