# Generated by Django 2.2.16 on 2020-09-25 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0005_submission_backend_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='completed_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
