# Generated by Django 4.2.23 on 2025-07-29 09:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("submissions", "0005_update_registration_intermediate_rol_results_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="submissionvaluevariable",
            name="configuration",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="The component configuration as Form.io JSON schema",
                verbose_name="Form.io component configuration",
            ),
        ),
    ]
