# Generated by Django 4.2.11 on 2024-06-26 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0005_temporaryfileupload_legacy_and_more"),
    ]

    # RunPython operation removed as part of the 2.8.0 release cycle
    operations = []
