# Generated by Django 4.2.11 on 2024-06-29 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0006_set_legacy_true"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="temporaryfileupload",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("legacy", False), ("submission__isnull", False)),
                    models.Q(("legacy", True), ("submission__isnull", True)),
                    _connector="OR",
                ),
                name="non_legacy_submission_not_null",
            ),
        ),
    ]
