# Generated by Django 2.2.16 on 2020-09-25 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0006_submission_completed_on"),
        ("submissions", "0005_submission_bsn"),
    ]

    operations = []
