# Generated by Django 4.2.23 on 2025-07-30 09:51

from django.db import migrations
from django.db.migrations.state import StateApps
from django.core import serializers

from openforms.formio.utils import iter_components


def _load_form_step_from_history(step, FormDefinition):
    history = step.form_step_history

    if not history:
        return

    # check if the form definition still exists
    fd_exists = FormDefinition.objects.filter(
        pk=history["form_definition"]["pk"]
    ).exists()
    if not fd_exists:
        del history["form_step"]["fields"]["form_definition"]

    form_step = next(serializers.deserialize("python", [history["form_step"]])).object

    if not fd_exists:
        form_definition = next(
            serializers.deserialize("python", [history["form_definition"]])
        ).object
        form_step.form_definition = form_definition

    step.form_step = form_step


def _step_iterator(SubmissionStep, FormDefinition):
    yield from (
        SubmissionStep.objects.select_related("form_step__form_definition")
        .exclude(form_step__isnull=True)
        .iterator()
    )

    for step in SubmissionStep.objects.filter(form_step__isnull=True).iterator():
        _load_form_step_from_history(step, FormDefinition)
        yield step


def add_configuration_to_existing_submission_value_variables(
    apps: StateApps, _
) -> None:
    SubmissionValueVariable = apps.get_model("submissions", "SubmissionValueVariable")
    SubmissionStep = apps.get_model("submissions", "SubmissionStep")
    FormDefinition = apps.get_model("forms", "FormDefinition")

    variables_to_update = []
    for step in _step_iterator(SubmissionStep, FormDefinition):
        if step.form_step is None:
            continue

        config = step.form_step.form_definition.configuration
        keys_in_step = [
            component["key"]
            for component in iter_components(config, recurse_into_editgrid=False)
        ]

        step_variables_to_update = SubmissionValueVariable.objects.filter(
            configuration={}, key__in=keys_in_step
        )
        for variable in step_variables_to_update.iterator():
            variable.configuration = step.form_step.form_definition.configuration
            variables_to_update.append(variable)

    SubmissionValueVariable.objects.bulk_update(
        variables_to_update, fields=["configuration"]
    )


class Migration(migrations.Migration):
    dependencies = [
        ("submissions", "0006_submissionvaluevariable_configuration"),
    ]

    operations = [
        migrations.RunPython(
            add_configuration_to_existing_submission_value_variables,
            migrations.RunPython.noop,
        )
    ]
