# Generated by Django 4.2.14 on 2024-07-16 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0007_add_legacy_constraint"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="initial_data_reference",
            field=models.CharField(
                blank=True,
                help_text="An identifier that can be passed as a querystring when the form is started. Initial form field values are pre-populated from the retrieved data. During registration, the object may be updated again (or a new record may be created). This can be an object reference in the Objects API, for example.",
                verbose_name="initial data reference",
            ),
        ),
    ]
