# Generated by Django 4.2.14 on 2024-07-22 15:22

from django.db import migrations, models


def clear_registration_backend_key_for_incomplete_submissions(apps, _):
    Submission = apps.get_model("submissions", "Submission")

    # clear the value of the registration backend key for submissions that are not
    # completed yet
    qs = Submission.objects.filter(completed_on__isnull=True).exclude(
        finalised_registration_backend_key=""
    )
    qs.update(finalised_registration_backend_key="")


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0008_submission_initial_data_reference"),
    ]

    operations = [
        migrations.RunPython(
            clear_registration_backend_key_for_incomplete_submissions,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name="submission",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("finalised_registration_backend_key", ""),
                    models.Q(
                        models.Q(
                            ("finalised_registration_backend_key", ""), _negated=True
                        ),
                        ("completed_on__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="only_completed_submission_has_finalised_registration_backend_key",
                violation_error_message="Only completed submissions may persist a finalised registration backend key.",
            ),
        ),
    ]
