# Generated by Django 4.2.23 on 2025-08-06 14:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("submissions", "0008_submissionvaluevariable_data_type_and_subtype"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="submissionvaluevariable",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("data_type__in", ("partners", "editgrid", "children")),
                    _negated=True,
                ),
                name="submission_variable_data_type_is_not_subtype_exclusive",
            ),
        ),
    ]
