# Generated by Django 4.2.15 on 2024-08-22 07:32

import re

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

import openforms.submissions.models.email_verification


class Migration(migrations.Migration):

    dependencies = [
        (
            "submissions",
            "0009_submission_only_completed_submission_has_finalised_registration_backend_key",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailVerification",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "component_key",
                    models.TextField(
                        help_text="Key of the email component in the submission's form.",
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Invalid variable key. It must only contain alphanumeric characters, underscores, dots and dashes and should not be ended by dash or dot.",
                                regex=re.compile("^(\\w|\\w[\\w.\\-]*\\w)$"),
                            )
                        ],
                        verbose_name="component key",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="The email address that is being verified.",
                        max_length=254,
                        verbose_name="email address",
                    ),
                ),
                (
                    "verification_code",
                    models.CharField(
                        default=openforms.submissions.models.email_verification.generate_verification_code,
                        max_length=6,
                        verbose_name="verification code",
                    ),
                ),
                (
                    "verified_on",
                    models.DateTimeField(
                        blank=True,
                        help_text="Unverified emails have no timestamp set.",
                        null=True,
                        verbose_name="verification timestamp",
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        help_text="The submission during which the email verification was initiated.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="submissions.submission",
                        verbose_name="submission",
                    ),
                ),
            ],
            options={
                "verbose_name": "email verification",
                "verbose_name_plural": "email verifications",
            },
        ),
    ]
