# Generated by Django 2.2.16 on 2020-12-30 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0009_auto_20201203_1522"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="suspended_on",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
