# Generated by Django 4.2.23 on 2025-08-06 12:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("submissions", "0009_alter_submissionvaluevariable_data_subtype_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submissionvaluevariable",
            name="data_subtype",
            field=models.CharField(
                blank=True,
                choices=[
                    ("string", "String"),
                    ("boolean", "Boolean"),
                    ("object", "Object"),
                    ("array", "Array"),
                    ("int", "Integer"),
                    ("float", "Float"),
                    ("datetime", "Datetime"),
                    ("time", "Time"),
                    ("date", "Date"),
                    ("partners", "Partners"),
                    ("editgrid", "Edit Grid"),
                ],
                help_text="This field represents the data type of the values inside the container for components that are configured as 'multiple'.",
                max_length=50,
                verbose_name="data subtype",
            ),
        ),
        migrations.AlterField(
            model_name="submissionvaluevariable",
            name="data_type",
            field=models.CharField(
                choices=[
                    ("string", "String"),
                    ("boolean", "Boolean"),
                    ("object", "Object"),
                    ("array", "Array"),
                    ("int", "Integer"),
                    ("float", "Float"),
                    ("datetime", "Datetime"),
                    ("time", "Time"),
                    ("date", "Date"),
                    ("partners", "Partners"),
                    ("editgrid", "Edit Grid"),
                ],
                help_text="The type of the value that will be associated with this variable",
                max_length=50,
                verbose_name="data type",
            ),
        ),
    ]
