# Generated by Django 2.2.20 on 2021-04-30 12:36

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0010_submission_suspended_on"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="submission",
            name="backend_result",
        ),
        migrations.AddField(
            model_name="submission",
            name="registration_result",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True,
                help_text="Contains data returned by the registration backend while registrating the submission data.",
                null=True,
                verbose_name="result of backend registration",
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="registration_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending (not registered yet)"),
                    ("success", "Success"),
                    ("failed", "Failed"),
                ],
                default="pending",
                help_text="Whether registration in the configured backend was succesful.",
                max_length=50,
                verbose_name="Backend registration status",
            ),
        ),
    ]
