# Generated by Django 4.2.29 on 2026-03-04 15:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("submissions", "0010_cosignotp"),
        (
            "submissions",
            "0010_submissionvaluevariable_pre_registration_result_and_more",
        ),
    ]

    operations = []
