# Generated by Django 4.2.16 on 2024-10-10 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0010_emailverification"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="submissionstep",
            name="_data",
        ),
    ]
