# Generated by Django 5.2.11 on 2026-03-02 11:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "submissions",
            "0011_merge_20260304_1610",
        ),
    ]

    operations = [
        # Existing submission steps should have the default set to `True`, because they
        # have already been created.
        migrations.AddField(
            model_name="submissionstep",
            name="completed",
            field=models.BooleanField(
                default=True,
                help_text="Whether the submission step has been completed.",
                verbose_name="completed",
            ),
        ),
        # New submission steps should have the default `False`, because steps having a
        # pk no longer determines whether it was completed.
        migrations.AlterField(
            model_name="submissionstep",
            name="completed",
            field=models.BooleanField(
                default=False,
                help_text="Whether the submission step has been completed.",
                verbose_name="completed",
            ),
        ),
    ]
