# Generated by Django 2.2.20 on 2021-05-07 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0011_auto_20210430_1436"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submission",
            name="form",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="forms.Form"
            ),
        ),
    ]
