# Generated by Django 2.2.19 on 2021-04-30 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0011_auto_20210430_1436'),
        ('submissions', '0011_confirmationemailtemplate'),
    ]

    operations = [
    ]
