# Generated by Django 5.2.11 on 2026-03-03 13:04


from django.db import migrations
from django.db.migrations.state import StateApps


def create_submission_steps_for_form_steps_that_do_not_have_one(apps: StateApps, _):
    Submission = apps.get_model("submissions", "Submission")
    SubmissionStep = apps.get_model("submissions", "SubmissionStep")
    Form = apps.get_model("forms", "Form")

    forms = Form.objects.prefetch_related("formstep_set")
    steps_to_create = []
    for form in forms.iterator(chunk_size=100):
        form_steps = set(form.formstep_set.all())

        submissions = Submission.objects.filter(form=form).prefetch_related(
            "submissionstep_set", "submissionstep_set__form_step"
        )
        for submission in submissions.iterator(chunk_size=1000):
            # Note that this could contain submission steps for which the form step was
            # deleted. We don't have to do anything with these.
            form_steps_with_submission_step = {
                step.form_step for step in submission.submissionstep_set.all()
            }

            form_steps_without_submission_step = (
                form_steps - form_steps_with_submission_step
            )
            for step in form_steps_without_submission_step:
                steps_to_create.append(
                    SubmissionStep(
                        submission=submission, form_step=step, completed=False
                    )
                )

    if steps_to_create:
        SubmissionStep.objects.bulk_create(steps_to_create)


# TODO-6034: is this necessary? This has the potential to remove a lot more than steps
#  that we added ourselves with the migration.
# TODO-6034: add test
def remove_uncompleted_submission_steps(apps: StateApps, _):
    SubmissionStep = apps.get_model("submissions", "SubmissionStep")

    submission_steps = SubmissionStep.objects.filter(completed=False)
    if submission_steps:
        submission_steps.delete()


class Migration(migrations.Migration):
    dependencies = [
        ("submissions", "0011_submissionstep_completed"),
    ]

    operations = [
        migrations.RunPython(
            create_submission_steps_for_form_steps_that_do_not_have_one,
            remove_uncompleted_submission_steps,
        )
    ]
