# Generated by Django 5.2.14 on 2026-05-15 20:47

from django.db import migrations

import privates.fields

import openforms.submissions.models.submission_files


class Migration(migrations.Migration):
    dependencies = [
        ("submissions", "0011_merge_20260304_1610"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submissionfileattachment",
            name="content",
            field=privates.fields.PrivateMediaFileField(
                help_text="Content of the submission file attachment.",
                upload_to=openforms.submissions.models.submission_files.submission_file_upload_to,
                verbose_name="content",
            ),
        ),
        migrations.AlterField(
            model_name="submissionreport",
            name="content",
            field=privates.fields.PrivateMediaFileField(
                help_text="Content of the submission report",
                upload_to="submission-reports/%Y/%m/%d",
                verbose_name="content",
            ),
        ),
        migrations.AlterField(
            model_name="temporaryfileupload",
            name="content",
            field=privates.fields.PrivateMediaFileField(
                help_text="content of the file attachment.",
                upload_to=openforms.submissions.models.submission_files.temporary_file_upload_to,
                verbose_name="content",
            ),
        ),
    ]
