# Generated by Django 4.2.16 on 2024-11-26 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0011_remove_submissionstep__data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submission",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                editable=False,
                help_text="Cost of this submission. Either derived from the related product, or set through logic rules. The price is calculated and saved on submission completion.",
                max_digits=10,
                null=True,
                verbose_name="price",
            ),
        ),
    ]
