# Generated by Django 5.2.14 on 2026-06-04 14:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("submissions", "0012_alter_submissionfileattachment_content_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="submissionstep",
            name="completed_on",
            field=models.DateTimeField(
                blank=True,
                help_text="This is indicating the date and time that a submission step was for the first time completed (all the future are considered as modifications).",
                null=True,
                verbose_name="completed on",
            ),
        ),
    ]
