# Generated by Django 4.2.17 on 2024-12-09 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0012_alter_submission_price"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="temporaryfileupload",
            name="non_legacy_submission_not_null",
        ),
        migrations.RemoveField(
            model_name="temporaryfileupload",
            name="legacy",
        ),
        migrations.AlterField(
            model_name="temporaryfileupload",
            name="submission",
            field=models.ForeignKey(
                help_text="Submission the temporary file upload belongs to.",
                on_delete=django.db.models.deletion.CASCADE,
                to="submissions.submission",
                verbose_name="submission",
            ),
        ),
    ]
