# Generated by Django 2.2.20 on 2021-05-07 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0012_auto_20210506_0954"),
        ("submissions", "0012_auto_20210507_1206"),
    ]

    operations = []
