# Generated by Django 5.2.14 on 2026-06-08 09:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("submissions", "0012_alter_submissionfileattachment_content_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="submissionstep",
            name="completed_on",
            field=models.DateTimeField(
                blank=True,
                help_text="Marks when the step was last submitted. When a submission is being paused, the field will be empty to signal it wasn't completed yet.",
                null=True,
                verbose_name="completed on",
            ),
        ),
    ]
