# Generated by Django 5.2.12 on 2026-03-23 15:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("submissions", "0012_submissionstep_completed"),
    ]

    operations = [
        migrations.AddField(
            model_name="submissionstep",
            name="is_applicable",
            field=models.BooleanField(
                default=None,
                help_text="Whether the submission step is applicable.",
                null=True,
                verbose_name="is applicable",
            ),
        ),
    ]
