# Generated by Django 2.2.19 on 2021-05-03 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0012_merge_20210430_1550"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="confirmationemailtemplate",
            name="email_property_name",
        ),
    ]
