# Generated by Django 4.2.17 on 2024-12-11 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0013_remove_submission_previous_submission"),
        (
            "submissions",
            "0013_remove_temporaryfileupload_non_legacy_submission_not_null_and_more",
        ),
    ]

    operations = []
