# Generated by Django 2.2.20 on 2021-05-14 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0015_merge_20210514_1410"),
        ("submissions", "0013_merge_20210507_1543"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfirmationEmailTemplate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        help_text="Subject of the email message", max_length=1000
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="The content of the email message, can contain variables that will be templated form the submitted form data."
                    ),
                ),
                (
                    "form",
                    models.OneToOneField(
                        blank=True,
                        help_text="The form for which this confirmation email template will be used",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="confirmation_email_template",
                        to="forms.Form",
                    ),
                ),
            ],
            options={
                "verbose_name": "Confirmation email template",
                "verbose_name_plural": "Confirmation email templates",
            },
        ),
    ]
