# Generated by Django 2.2.20 on 2021-05-03 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0013_remove_confirmationemailtemplate_email_property_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="SMTPServerConfig",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "host",
                    models.CharField(
                        blank=True,
                        help_text="De host van de SMTP server",
                        max_length=1000,
                    ),
                ),
                (
                    "port",
                    models.IntegerField(
                        blank=True, help_text="De port van de SMTP server", null=True
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True,
                        help_text="De username van de SMTP server",
                        max_length=1000,
                    ),
                ),
                (
                    "password",
                    models.CharField(
                        blank=True,
                        help_text="Het password van de SMTP server",
                        max_length=1000,
                    ),
                ),
                (
                    "default_from_email",
                    models.CharField(
                        blank=True,
                        help_text="De afzender waarvan de bevestigingsemails afkomstig zijn",
                        max_length=1000,
                        verbose_name="Standaard e-mailadres afzender",
                    ),
                ),
            ],
            options={
                "verbose_name": "SMTP Server Configuration",
            },
        ),
    ]
