# Generated by Django 2.2.20 on 2021-05-12 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0012_auto_20210507_1206"),
        ("submissions", "0014_smtpserverconfig"),
    ]

    operations = []
