# Generated by Django 5.2.15 on 2026-07-06 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("submissions", "0014_alter_submission_registration_result"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submissionfileattachment",
            name="submission_variable",
            field=models.ForeignKey(
                help_text="submission value variable for the form component",
                on_delete=django.db.models.deletion.CASCADE,
                to="submissions.submissionvaluevariable",
                verbose_name="submission variable",
            ),
        ),
        migrations.AlterField(
            model_name="submissionfileattachment",
            name="temporary_file",
            field=models.OneToOneField(
                help_text="Temporary upload this file is sourced to.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="attachment",
                to="submissions.temporaryfileupload",
                verbose_name="temporary file",
            ),
        ),
    ]
