# Generated by Django 2.2.20 on 2021-05-14 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0014_confirmationemailtemplate"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ConfirmationEmailTemplate",
        ),
    ]
