# Generated by Django 5.2.15 on 2026-07-07 19:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "submissions",
            "0015_alter_submissionfileattachment_submission_variable_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="submissionfileattachment",
            old_name="_component_data_path",
            new_name="_data_path",
        ),
        migrations.AddField(
            model_name="submissionfileattachment",
            name="component_key",
            field=models.TextField(
                default="",
                help_text="Key of the file component for which the upload was made. Most of the time this will be identical to the submission_variable.key, except when the file component is inside an edit grid - the variable then points to the edit grid.",
                verbose_name="component key",
            ),
            preserve_default=False,
        ),
    ]
