# Generated by Django 2.2.20 on 2021-06-01 13:26

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0016_auto_20210521_1352"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="appointment_result",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True,
                help_text="Contains data returned by the appointment backend while creating the appointment.",
                null=True,
                verbose_name="appointment backend result",
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="appointment_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending (not created yet)"),
                    ("success", "Success"),
                    ("failed", "Failed"),
                ],
                default="pending",
                help_text="Indication whether the appointment was created successfully in the backend.",
                max_length=50,
                verbose_name="appointment backend status",
            ),
        ),
    ]
