# Generated by Django 5.2.15 on 2026-07-07 19:39
from itertools import batched

from django.db import migrations
from django.db.migrations.state import StateApps

from glom import glom

BATCH_SIZE = 200


def convert_attachment_metadata(apps: StateApps, _) -> None:
    """
    Convert the metadata of SubmissionFileAttachment to the new format.

    1. Ensure the component data path is always populated. This is mostly theoretical,
       but it may be missing for non-editgrid file uploads.
    2. Replace the component configuration path ('physical' path into the form
       definition JSON structure) with just the key of the file upload component, as
       that is the only information necessary for file upload processing during
       registration.

    Future improvements (no planned date, it's not urgent) will do another iteration on
    this to work with "abstract data paths" instead of component keys so that keys of
    components inside editgrids do not need to be unique to the form definition, as
    those run in their own scope (see: how formio component.conditional works with
    editgrid components).
    """
    SubmissionFileAttachment = apps.get_model("submissions", "SubmissionFileAttachment")
    qs = SubmissionFileAttachment.objects.prefetch_related(
        "submission_variable",
        "submission_step",
    ).iterator(chunk_size=BATCH_SIZE)

    # memory-efficient batch preparation for the bulk updates
    for batch in batched(qs, BATCH_SIZE):
        to_update = []
        for attachment in batch:
            # ensure the _data_path is populated. For items inside edit grids, it must have
            # been populated before or all submission rendering/registration would break.
            # This implies that if it's unset (unlikely), it's not from an editgrid, ergo,
            # equal to the variable key.
            if not attachment._data_path:
                attachment._data_path = attachment.submission_variable.key

            # extract the component key - the field was added in the previous migration
            # so it must be populated for all existing records.
            #
            # How we derive this is more complex than you'd expect, as it tries to
            # handle form definitions that have been changed since the attachment record
            # was created.
            #
            # 1. The related submission variable captures a snapshot of the formio
            #    component definition that belonged to it, at the time. Even if the
            #    component has been removed or renamed in the Form, this snapshot still
            #    has the correct component key.
            # 2. For file components in edit grids, the variable contains the outer
            #    editgrid component definition. We must then use the legacy
            #    ``_component_configuration_path`` and look that up in the attached
            #    submission step -> form step -> form definition configuration (that's
            #    the mechanism that is now used at runtime). Looking up the
            #    configuration path in the snapshotted editgrid definition is not
            #    reliable, as the editgrid itself may be inside a fieldset or columns
            #    layout component, for which no form variables are created because they
            #    don't hold data.
            #
            # It's possible that we don't get a component key resolution - that
            # shouldn't be a problem for successful registrations. To be sure, we're not
            # yet dropping the original configuration path field for historical data.

            # check if the variable points to a file component configuration - use the
            # component key from that snapshot when available
            if (
                (configuration := attachment.submission_variable.configuration)
                and isinstance(configuration, dict)
                and configuration.get("type") == "file"
            ):
                attachment.component_key = configuration["key"]
            else:
                config_path = attachment._component_configuration_path
                formio_configuration = (
                    attachment.submission_step.form_step.form_definition.configuration
                )
                configuration = glom(formio_configuration, config_path, default=None)
                attachment.component_key = (
                    configuration["key"] if configuration is not None else "<UNKNOWN>"
                )

            to_update.append(attachment)

        SubmissionFileAttachment.objects.bulk_update(
            to_update,
            ["component_key", "_data_path"],
        )


class Migration(migrations.Migration):
    dependencies = [
        (
            "submissions",
            "0016_rename__component_data_path_submissionfileattachment__data_path_and_more",
        ),
    ]

    operations = [
        migrations.RunPython(convert_attachment_metadata, migrations.RunPython.noop),
    ]
