# Generated by Django 2.2.20 on 2021-06-17 13:48

from django.db import migrations, models
import django.db.models.deletion
import privates.fields
import privates.storages


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0017_auto_20210603_1513"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubmissionReport",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Title of the submission report",
                        max_length=200,
                        verbose_name="title",
                    ),
                ),
                (
                    "content",
                    privates.fields.PrivateMediaFileField(
                        help_text="Content of the submission report",
                        storage=privates.storages.PrivateMediaFileSystemStorage(),
                        upload_to="submission-reports/%Y/%m/%d",
                        verbose_name="content",
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        blank=True,
                        help_text="Submission related to the report",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="submissions.Submission",
                        verbose_name="submission",
                    ),
                ),
            ],
            options={
                "verbose_name": "submission report",
                "verbose_name_plural": "submission reports",
            },
        ),
    ]
