# Generated by Django 5.2.15 on 2026-07-09 07:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("submissions", "0017_convert_attachment_metadata"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="submissionfileattachment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("_data_path", ""),
                    ("component_key", ""),
                    _connector="OR",
                    _negated=True,
                ),
                name="required_non_empty_component_metadata",
            ),
        ),
    ]
