# Generated by Django 5.2.15 on 2026-07-09 09:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "submissions",
            "0018_submissionfileattachment_required_non_empty_component_metadata",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="submissionfileattachment",
            name="_data_path",
            field=models.TextField(
                help_text="Path to the attachment in the submission data.",
                verbose_name="component data path",
            ),
        ),
    ]
