# Generated by Django 5.2.17 on 2026-09-11 08:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("submissions", "0012_alter_emailverification_component_key"),
        ("submissions", "0019_alter_submissionfileattachment__data_path"),
    ]

    operations = []
