# Generated by Django 2.2.20 on 2021-06-22 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0019_submissionreport"),
    ]

    operations = [
        migrations.AddField(
            model_name="submissionreport",
            name="task_id",
            field=models.CharField(
                blank=True,
                help_text="ID of the celery task creating the content of the report.",
                max_length=200,
                verbose_name="task id",
            ),
        ),
    ]
