# Generated by Django 5.2.17 on 2026-09-10 14:09

import re

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("submissions", "0019_alter_submissionfileattachment__data_path"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailverification",
            name="component_key",
            field=models.TextField(
                help_text="Key of the component in the submission's form. The supported component types are Email and Profile.",
                validators=[
                    django.core.validators.RegexValidator(
                        message="Invalid variable key. It must only contain alphanumeric characters, underscores, dots and dashes and should not be ended by dash or dot.",
                        regex=re.compile("^(\\w|\\w[\\w.\\-]*\\w)$"),
                    )
                ],
                verbose_name="component key",
            ),
        ),
    ]
