# Generated by Django 2.2.20 on 2021-06-24 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0020_submissionreport_task_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submissionreport",
            name="last_accessed",
            field=models.DateTimeField(
                blank=True,
                help_text="When the submission report was last accessed. This value is updated when the report is downloaded.",
                null=True,
                verbose_name="last accessed",
            ),
        ),
        migrations.AlterField(
            model_name="submissionreport",
            name="submission",
            field=models.OneToOneField(
                blank=True,
                help_text="Submission the report is about.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="report",
                to="submissions.Submission",
                verbose_name="submission",
            ),
        ),
        migrations.AlterField(
            model_name="submissionreport",
            name="task_id",
            field=models.CharField(
                blank=True,
                help_text="ID of the celery task creating the content of the report. This is used to check the generation status.",
                max_length=200,
                verbose_name="task id",
            ),
        ),
    ]
