# Generated by Django 2.2.20 on 2021-07-09 09:28

from django.db import migrations, models
import openforms.submissions.models
import openforms.utils.fields
import privates.fields
import privates.storages
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0021_auto_20210624_1508"),
    ]

    operations = [
        migrations.CreateModel(
            name="TemporaryFileUpload",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    openforms.utils.fields.StringUUIDField(
                        default=uuid.uuid4, unique=True, verbose_name="UUID"
                    ),
                ),
                (
                    "content",
                    privates.fields.PrivateMediaFileField(
                        help_text="content of the file attachment.",
                        storage=privates.storages.PrivateMediaFileSystemStorage(),
                        upload_to=openforms.submissions.models.temporary_file_upload_to,
                        verbose_name="content",
                    ),
                ),
                (
                    "file_name",
                    models.CharField(max_length=255, verbose_name="original name"),
                ),
                (
                    "content_type",
                    models.CharField(max_length=255, verbose_name="inhoudstype"),
                ),
                (
                    "created_on",
                    models.DateTimeField(auto_now_add=True, verbose_name="created on"),
                ),
            ],
            options={
                "verbose_name": "temporary file upload",
                "verbose_name_plural": "temporary file upload",
            },
        ),
    ]
