# Generated by Django 2.2.20 on 2021-07-15 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0023_submissionfileattachment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submissionfileattachment",
            name="submission_step",
            field=models.ForeignKey(
                help_text="SubmissionStep the file is attached to.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attachments",
                to="submissions.SubmissionStep",
                verbose_name="submission",
            ),
        ),
    ]
