# Generated by Django 2.2.24 on 2021-07-24 06:01

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import openforms.contrib.kvk.validators
import openforms.submissions.models
import privates.fields
import privates.storages


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0024_auto_20210715_1630"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="submission",
            options={"verbose_name": "Inzending", "verbose_name_plural": "Inzendingen"},
        ),
        migrations.AlterModelOptions(
            name="submissionfileattachment",
            options={
                "verbose_name": "inzendingsbijlage",
                "verbose_name_plural": "inzendingsbijlagen",
            },
        ),
        migrations.AlterModelOptions(
            name="submissionreport",
            options={"verbose_name": "document", "verbose_name_plural": "documenten"},
        ),
        migrations.AlterModelOptions(
            name="submissionstep",
            options={
                "verbose_name": "Inzendingsstap",
                "verbose_name_plural": "Inzendingsstappen",
            },
        ),
        migrations.AlterModelOptions(
            name="temporaryfileupload",
            options={
                "verbose_name": "tijdelijk bestand",
                "verbose_name_plural": "tijdelijk bestand",
            },
        ),
        migrations.AlterField(
            model_name="submission",
            name="completed_on",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="afgerond op"
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="created_on",
            field=models.DateTimeField(auto_now_add=True, verbose_name="aangemaakt op"),
        ),
        migrations.AlterField(
            model_name="submission",
            name="current_step",
            field=models.PositiveIntegerField(default=0, verbose_name="huidige stap"),
        ),
        migrations.AlterField(
            model_name="submission",
            name="kvk",
            field=models.CharField(
                blank=True,
                default=openforms.submissions.models.get_default_kvk,
                max_length=9,
                validators=[openforms.contrib.kvk.validators.KVKNumberValidator()],
                verbose_name="KvK-nummer",
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="registration_result",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True,
                help_text="Bevat de gegevens zoals teruggegeven door de registratie backend bij het versturen van de inzending.",
                null=True,
                verbose_name="registratie backend resultaat",
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="registration_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending (not registered yet)"),
                    ("success", "Success"),
                    ("failed", "Failed"),
                ],
                default="pending",
                help_text="Indicatie of de doorzetting naar de registratie backend succesvol was.",
                max_length=50,
                verbose_name="registratie backend status",
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="suspended_on",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="onderbroken op"
            ),
        ),
        migrations.AlterField(
            model_name="submissionfileattachment",
            name="content",
            field=privates.fields.PrivateMediaFileField(
                help_text="Inhoud van de inzendingsbijlage",
                storage=privates.storages.PrivateMediaFileSystemStorage(),
                upload_to=openforms.submissions.models.submission_file_upload_to,
                verbose_name="inhoud",
            ),
        ),
        migrations.AlterField(
            model_name="submissionfileattachment",
            name="content_type",
            field=models.CharField(max_length=255, verbose_name="content type"),
        ),
        migrations.AlterField(
            model_name="submissionfileattachment",
            name="created_on",
            field=models.DateTimeField(auto_now_add=True, verbose_name="aangemaakt op"),
        ),
        migrations.AlterField(
            model_name="submissionfileattachment",
            name="file_name",
            field=models.CharField(
                blank=True,
                help_text="veilige bestandsnaam",
                max_length=255,
                verbose_name="bestandsnaam",
            ),
        ),
        migrations.AlterField(
            model_name="submissionfileattachment",
            name="form_key",
            field=models.CharField(
                max_length=255, verbose_name="formulier veld sleutel"
            ),
        ),
        migrations.AlterField(
            model_name="submissionfileattachment",
            name="original_name",
            field=models.CharField(
                help_text="originele bestandsnaam",
                max_length=255,
                verbose_name="originele naam",
            ),
        ),
        migrations.AlterField(
            model_name="submissionfileattachment",
            name="submission_step",
            field=models.ForeignKey(
                help_text="Inzendingsstap waar het bestand bij hoort.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attachments",
                to="submissions.SubmissionStep",
                verbose_name="inzending",
            ),
        ),
        migrations.AlterField(
            model_name="submissionfileattachment",
            name="temporary_file",
            field=models.ForeignKey(
                help_text="Tijdelijk bestand waar deze bijlage bij hoort.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="attachments",
                to="submissions.TemporaryFileUpload",
                verbose_name="tijdelijk bestand",
            ),
        ),
        migrations.AlterField(
            model_name="submissionreport",
            name="content",
            field=privates.fields.PrivateMediaFileField(
                help_text="Inhoud van het document",
                storage=privates.storages.PrivateMediaFileSystemStorage(),
                upload_to="submission-reports/%Y/%m/%d",
                verbose_name="inhoud",
            ),
        ),
        migrations.AlterField(
            model_name="submissionreport",
            name="last_accessed",
            field=models.DateTimeField(
                blank=True,
                help_text="Datum waarom het document voor het laatst is opgevraagd. Deze waarde wordt bijgewerkt zodra het document wordt gedownload.",
                null=True,
                verbose_name="laatst gedownload",
            ),
        ),
        migrations.AlterField(
            model_name="submissionreport",
            name="submission",
            field=models.OneToOneField(
                blank=True,
                help_text="De inzending die hoort bij dit document.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="report",
                to="submissions.Submission",
                verbose_name="inzending",
            ),
        ),
        migrations.AlterField(
            model_name="submissionreport",
            name="task_id",
            field=models.CharField(
                blank=True,
                help_text="ID van de taak die het document genereerd. Dit ID kan worden gebruikt om de document generatie status te controleren.",
                max_length=200,
                verbose_name="Taak ID",
            ),
        ),
        migrations.AlterField(
            model_name="submissionreport",
            name="title",
            field=models.CharField(
                help_text="Titel van het document", max_length=200, verbose_name="titel"
            ),
        ),
        migrations.AlterField(
            model_name="submissionstep",
            name="created_on",
            field=models.DateTimeField(auto_now_add=True, verbose_name="aangemaakt op"),
        ),
        migrations.AlterField(
            model_name="submissionstep",
            name="data",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, null=True, verbose_name="gegevens"
            ),
        ),
        migrations.AlterField(
            model_name="submissionstep",
            name="modified",
            field=models.DateTimeField(auto_now=True, verbose_name="gewijzigd op"),
        ),
        migrations.AlterField(
            model_name="temporaryfileupload",
            name="content",
            field=privates.fields.PrivateMediaFileField(
                help_text="inhoud van de bijlage.",
                storage=privates.storages.PrivateMediaFileSystemStorage(),
                upload_to=openforms.submissions.models.temporary_file_upload_to,
                verbose_name="inhoud",
            ),
        ),
        migrations.AlterField(
            model_name="temporaryfileupload",
            name="content_type",
            field=models.CharField(max_length=255, verbose_name="content type"),
        ),
        migrations.AlterField(
            model_name="temporaryfileupload",
            name="created_on",
            field=models.DateTimeField(auto_now_add=True, verbose_name="aangemaakt op"),
        ),
        migrations.AlterField(
            model_name="temporaryfileupload",
            name="file_name",
            field=models.CharField(max_length=255, verbose_name="originele naam"),
        ),
    ]
