# Generated by Django 2.2.24 on 2021-08-19 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0026_auto_20210809_1526"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="_is_cleaned",
            field=models.BooleanField(
                default=False,
                help_text="Indicates whether sensitive data (if there was any) has been removed from this submission.",
                verbose_name="is cleaned",
            ),
        ),
    ]
