# Generated by Django 2.2.24 on 2021-08-26 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0026_auto_20210809_1526"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="appointment_information",
            field=models.CharField(
                blank=True,
                help_text="Any information regarding the booking of an appointment",
                max_length=1000,
                verbose_name="Appointment Information",
            ),
        ),
    ]
