# Generated by Django 2.2.24 on 2021-09-01 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0027_submission__is_cleaned"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="on_completion_task_id",
            field=models.CharField(
                blank=True,
                help_text="Celery task ID of the on_completion workflow. Use this to inspect the state of the async jobs.",
                max_length=255,
                verbose_name="on completion task ID",
            ),
        ),
    ]
