# Generated by Django 2.2.24 on 2021-09-01 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0027_submission_appointment_information"),
        ("submissions", "0027_submission__is_cleaned"),
    ]

    operations = []
