# Generated by Django 2.2.24 on 2021-09-02 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0027_submission__is_cleaned"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submission",
            name="registration_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending (not registered yet)"),
                    ("in_progress", "In progress (not registered yet)"),
                    ("success", "Success"),
                    ("failed", "Failed"),
                ],
                default="pending",
                help_text="Indication whether the registration in the configured backend was successful.",
                max_length=50,
                verbose_name="registration backend status",
            ),
        ),
    ]
