# Generated by Django 2.2.24 on 2021-09-07 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0028_submission_on_completion_task_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="public_registration_reference",
            field=models.CharField(
                blank=True,
                help_text="The registration reference communicated to the end-user completing the form. This reference is intended to be unique and the reference the end-user uses to communicate with the service desk. It should be extracted from the registration result where possible, and otherwise generated to be unique. Note that this reference is displayed to the end-user and used as payment reference!",
                max_length=100,
                verbose_name="public registration reference",
            ),
        ),
        migrations.AddConstraint(
            model_name="submission",
            constraint=models.UniqueConstraint(
                condition=models.Q(_negated=True, public_registration_reference=""),
                fields=("public_registration_reference",),
                name="unique_public_registration_reference",
            ),
        ),
    ]
