# Generated by Django 2.2.24 on 2021-09-08 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0028_auto_20210902_2120"),
        ("submissions", "0030_remove_submission_current_step"),
    ]

    operations = []
