# Generated by Django 2.2.24 on 2021-09-15 09:17

from django.db import migrations, models

import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0031_merge_20210908_1035"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="on_completion_task_ids",
            field=django_better_admin_arrayfield.models.fields.ArrayField(
                base_field=models.CharField(
                    blank=True, max_length=255, verbose_name="on completion task ID"
                ),
                blank=True,
                default=list,
                help_text="Celery task IDs of the on_completion workflow. Use this to inspect the state of the async jobs.",
                size=None,
                verbose_name="on completion task IDs",
            ),
        ),
    ]
