# Generated by Django 2.2.24 on 2021-09-15 09:18

from django.db import migrations


def migrate_to_array_field(apps, _):
    Submission = apps.get_model("submissions", "Submission")
    for submission in Submission.objects.exclude(on_completion_task_id=""):
        submission.on_completion_task_ids = [submission.on_completion_task_id]
        submission.save(update_fields=["on_completion_task_ids"])


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0032_submission_on_completion_task_ids"),
    ]

    operations = [
        migrations.RunPython(migrate_to_array_field, migrations.RunPython.noop),
    ]
