# Generated by Django 2.2.24 on 2021-09-23 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0034_remove_submission_on_completion_task_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="confirmation_email_sent",
            field=models.BooleanField(
                default=False,
                help_text="Indicates whether the confirmation email has been sent.",
                verbose_name="confirmation email sent",
            ),
        ),
    ]
