# Generated by Django 2.2.24 on 2021-10-25 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0035_submission_confirmation_email_sent"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="needs_on_completion_retry",
            field=models.BooleanField(
                default=False,
                help_text="Flag to track if the on_completion_retry chain should be invoked. This is scheduled via celery-beat.",
                verbose_name="needs on_completion retry",
            ),
        ),
    ]
