# Generated by Django 2.2.24 on 2021-10-28 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0036_submission_needs_on_completion_retry"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="submission",
            options={
                "verbose_name": "submission",
                "verbose_name_plural": "submissions",
            },
        ),
    ]
