# Generated by Django 2.2.24 on 2021-11-01 13:26

from django.db import migrations, models

import openforms.utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0037_auto_20211028_1148"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="form_url",
            field=models.URLField(
                blank=False,
                default="",
                help_text="URL where the user initialized the submission.",
                max_length=255,
                validators=[openforms.utils.validators.AllowedRedirectValidator()],
                verbose_name="form URL",
            ),
        ),
    ]
