# Generated by Django 2.2.24 on 2021-11-11 15:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0038_submission_form_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submission",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4, unique=True, verbose_name="UUID"
            ),
        ),
        migrations.AlterField(
            model_name="submissionfileattachment",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4, unique=True, verbose_name="UUID"
            ),
        ),
        migrations.AlterField(
            model_name="temporaryfileupload",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4, unique=True, verbose_name="UUID"
            ),
        ),
    ]
