# Generated by Django 2.2.24 on 2021-12-01 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0040_submission_previous_submission"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                editable=False,
                help_text="Cost of this submission. Either derived from the related product, or evaluated from price logic rules. The price is calculated and saved on submission completion.",
                max_digits=10,
                null=True,
                verbose_name="price",
            ),
        ),
    ]
