# Generated by Django 2.2.24 on 2021-12-02 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0040_submission_previous_submission"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="auth_plugin",
            field=models.CharField(
                blank=True,
                help_text="The plugin used by the user for authentication.",
                max_length=100,
                verbose_name="auth plugin",
            ),
        ),
    ]
