# Generated by Django 2.2.24 on 2021-11-30 13:49

from django.db import migrations, models
import openforms.utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0040_submission_previous_submission"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="acting_bsn",
            field=models.CharField(
                blank=True,
                max_length=9,
                validators=[openforms.utils.validators.BSNValidator()],
                verbose_name="BSN van gemachtigde",
            ),
        ),
    ]
