# Generated by Django 2.2.24 on 2021-12-02 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0041_submission_auth_plugin"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="pseudo",
            field=models.CharField(
                blank=True,
                help_text="Pseudo ID provided by authentication with eIDAS",
                max_length=9,
                verbose_name="Pseudo ID",
            ),
        ),
    ]
