# Generated by Django 2.2.24 on 2021-12-03 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0041_submission_price"),
        ("submissions", "0042_submission_pseudo"),
    ]

    operations = []
