# Generated by Django 2.2.24 on 2021-12-03 13:26

import django.contrib.postgres.fields.jsonb
from django.db import migrations
import openforms.submissions.serializers
import openforms.utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0043_merge_20211203_1259"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="co_sign_data",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True,
                default=dict,
                help_text="Authentication details of a co-signer.",
                validators=[
                    openforms.utils.validators.SerializerValidator(
                        openforms.submissions.serializers.CoSignDataSerializer
                    )
                ],
                verbose_name="co-sign data",
            ),
        ),
    ]
