# Generated by Django 2.2.25 on 2021-12-10 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0044_submission_co_sign_data"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="temporaryfileupload",
            options={
                "verbose_name": "temporary file upload",
                "verbose_name_plural": "temporary file uploads",
            },
        ),
    ]
