# Generated by Django 2.2.26 on 2022-01-21 14:16

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0046_auto_20220119_1610"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="prefill_data",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True,
                default=dict,
                help_text="Data used for prefills.",
                verbose_name="prefill data",
            ),
        ),
    ]
