# Generated by Django 2.2.27 on 2022-02-09 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0048_temporaryfileupload_file_size"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="submissionfileattachment",
            options={
                "base_manager_name": "objects",
                "verbose_name": "submission file attachment",
                "verbose_name_plural": "submission file attachments",
            },
        ),
    ]
