# Generated by Django 3.2.12 on 2022-02-23 10:01

from django.db import migrations, models

import openforms.contrib.kvk.validators
import openforms.submissions.models
import openforms.utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0050_auto_20220215_1715"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submission",
            name="bsn",
            field=models.CharField(
                blank=True,
                default=openforms.submissions.models.get_default_bsn,
                max_length=255,
                validators=[openforms.utils.validators.BSNValidator()],
                verbose_name="BSN",
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="kvk",
            field=models.CharField(
                blank=True,
                default=openforms.submissions.models.get_default_kvk,
                max_length=255,
                validators=[openforms.contrib.kvk.validators.KVKNumberValidator()],
                verbose_name="KvK number",
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="pseudo",
            field=models.CharField(
                blank=True,
                help_text="Pseudo ID provided by authentication with eIDAS",
                max_length=255,
                verbose_name="Pseudo ID",
            ),
        ),
    ]
