# Generated by Django 3.2.12 on 2022-02-23 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0051_auto_20220223_1101"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="auth_attributes_hashed",
            field=models.BooleanField(
                default=False,
                editable=False,
                help_text="are the auth/identifying attributes hashed?",
                verbose_name="identifying attributes hashed",
            ),
        ),
    ]
