# Generated by Django 3.2.13 on 2022-04-29 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0052_submission_auth_attributes_hashed"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="registration_attempts",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Counter to track how often we tried calling the registration backend. ",
                verbose_name="registration backend retry counter",
            ),
        ),
    ]
