# Generated by Django 3.2.13 on 2022-05-27 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0054_submissionvaluevariable"),
    ]

    operations = [
        migrations.AddField(
            model_name="submissionstep",
            name="_data",
            field=models.JSONField(blank=True, null=True, verbose_name="data"),
        ),
    ]
