# Generated by Django 3.2.13 on 2022-06-01 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0055_rename_submissionstep_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="submissionfileattachment",
            name="submission_variable",
            field=models.ForeignKey(
                blank=True,
                help_text="submission value variable for the form component",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="submissions.submissionvaluevariable",
                verbose_name="submission variable",
            ),
        ),
    ]
