# Generated by Django 3.2.13 on 2022-05-27 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0056_submissionstep_rename_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="submissionstep",
            name="data",
        ),
    ]
