# Generated by Django 3.2.14 on 2022-07-26 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0001_initial_squashed_0057_alter_submissionvaluevariable_key"),
    ]

    operations = [
        # data migration removed, as these have been executed on Open Forms 2.3.0+
        migrations.AlterField(
            model_name="submissionvaluevariable",
            name="source",
            field=models.CharField(
                choices=[
                    ("sensitive_data_cleaner", "Sensitive data cleaner"),
                    ("user_input", "User input"),
                    ("prefill", "Prefill"),
                    ("logic", "Logic"),
                    ("dmn", "DMN"),
                ],
                help_text="Where variable value came from",
                max_length=50,
                verbose_name="source",
            ),
        ),
    ]
