# Generated by Django 3.2.15 on 2022-08-10 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0058_alter_submissionvaluevariable_source"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="submission",
            name="prefill_data",
        ),
    ]
