# Generated by Django 3.2.15 on 2022-08-12 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0059_remove_submission_prefill_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="submission",
            name="auth_attributes_hashed",
        ),
        migrations.RemoveField(
            model_name="submission",
            name="auth_plugin",
        ),
        migrations.RemoveField(
            model_name="submission",
            name="bsn",
        ),
        migrations.RemoveField(
            model_name="submission",
            name="kvk",
        ),
        migrations.RemoveField(
            model_name="submission",
            name="pseudo",
        ),
    ]
