# Generated by Django 3.2.15 on 2022-10-13 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0061_backfill_submissionfileattachment_variable"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="submissionfileattachment",
            name="form_key",
        ),
    ]
