# Generated by Django 3.2.16 on 2022-10-25 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0062_remove_submissionfileattachment_form_key"),
        ("submissions", "0063_submissionvaluevariable_is_initially_prefilled"),
    ]

    operations = []
