# Generated by Django 3.2.16 on 2022-11-07 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0054_auto_20221103_1607"),
        ("submissions", "0063_submissionvaluevariable_is_initially_prefilled"),
    ]

    operations = []
