# Generated by Django 3.2.16 on 2022-11-07 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0064_merge_20221107_1148"),
        ("submissions", "0067_alter_submission_language_code"),
    ]

    operations = []
