# Generated by Django 3.2.18 on 2023-02-17 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0069_submission_privacy_policy_accepted"),
    ]

    operations = [
        migrations.AddField(
            model_name="submissionfileattachment",
            name="_component_configuration_path",
            field=models.CharField(
                blank=True,
                help_text="Path to the component in the configuration corresponding to this attachment. This is needed to distinguish between component that have the same key but one is within a repeating group (editgrid component).",
                max_length=255,
                verbose_name="component configuration path",
            ),
        ),
    ]
