# Generated by Django 3.2.18 on 2023-02-23 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0065_submission_attachments_paths"),
        ("submissions", "0069_submission_privacy_policy_accepted"),
    ]

    operations = []
