# Generated by Django 3.2.18 on 2023-02-16 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0069_submission_privacy_policy_accepted"),
    ]

    operations = [
        migrations.AddField(
            model_name="submissionfileattachment",
            name="_component_key",
            field=models.CharField(
                blank=True,
                help_text="Key of the file component corresponding to this attachment. It can be different from the submission variable key, for example if the file component is in a repeating group (editgrid component).",
                max_length=255,
                verbose_name="component key",
            ),
        ),
    ]
