# Generated by Django 3.2.18 on 2023-02-21 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0069_submission_privacy_policy_accepted"),
    ]

    operations = [
        migrations.AddField(
            model_name="submissionfileattachment",
            name="_component_configuration_path",
            field=models.CharField(
                blank=True,
                help_text="Path to the component in the configuration corresponding to this attachment.",
                max_length=255,
                verbose_name="component configuration path",
            ),
        ),
        migrations.AddField(
            model_name="submissionfileattachment",
            name="_component_data_path",
            field=models.CharField(
                blank=True,
                help_text="Path to the attachment in the submission data.",
                max_length=255,
                verbose_name="component data path",
            ),
        ),
    ]
