# Generated by Django 3.2.18 on 2023-05-09 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0070_merge_20230223_1254"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="pre_registration_completed",
            field=models.BooleanField(
                default=False,
                help_text="Indicates whether the pre-registration task completed successfully.",
                verbose_name="pre-registration completed",
            ),
        ),
    ]
