# Generated by Django 3.2.18 on 2023-04-18 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0070_merge_20230223_1254"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="waiting_on_cosign",
            field=models.BooleanField(
                default=False,
                help_text="Is the registration of this submission blocked because the co-signer has not co-signed yet?",
                verbose_name="waiting on co-sign",
            ),
        ),
    ]
