# Generated by Django 3.2.18 on 2023-05-16 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0071_submission_pre_registration_completed"),
    ]

    # data migration removed, as these have been executed on Open Forms 2.3.0+
    operations = []
