# Generated by Django 3.2.19 on 2023-05-31 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0074_submission_cosign_complete"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="cosign_privacy_policy_accepted",
            field=models.BooleanField(
                default=False,
                help_text="Has the co-signer accepted the privacy policy?",
                verbose_name="cosign privacy policy accepted",
            ),
        ),
    ]
