# Generated by Django 3.2.20 on 2023-08-08 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0076_alter_submission_form_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="truth_declaration_accepted",
            field=models.BooleanField(
                default=False,
                help_text="Has the user accepted the truth declaration?",
                verbose_name="truth declaration accepted",
            ),
        ),
    ]
