# Generated by Django 3.2.20 on 2023-08-03 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("forms", "0088_enable_mutiple_registration_backends"),
        ("submissions", "0077_auto_20230811_1217"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="finalised_registration_backend",
            field=models.ForeignKey(
                blank=True,
                help_text="The registration backend after logic evaluation when submission was completed.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="forms.formregistrationbackend",
            ),
        ),
    ]
