# Generated by Django 3.2.24 on 2024-02-07 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "digid_eherkenning_oidc_generics",
            "0001_initial_squashed_0007_auto_20221213_1347",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="openidconnectdigidmachtigenconfig",
            name="oidc_token_use_basic_auth",
            field=models.BooleanField(
                default=False,
                help_text="If enabled, the client ID and secret are sent in the HTTP Basic auth header when obtaining the access token. Otherwise, they are sent in the request body.",
                verbose_name="Use Basic auth for token endpoint",
            ),
        ),
        migrations.AddField(
            model_name="openidconnecteherkenningbewindvoeringconfig",
            name="oidc_token_use_basic_auth",
            field=models.BooleanField(
                default=False,
                help_text="If enabled, the client ID and secret are sent in the HTTP Basic auth header when obtaining the access token. Otherwise, they are sent in the request body.",
                verbose_name="Use Basic auth for token endpoint",
            ),
        ),
        migrations.AddField(
            model_name="openidconnecteherkenningconfig",
            name="oidc_token_use_basic_auth",
            field=models.BooleanField(
                default=False,
                help_text="If enabled, the client ID and secret are sent in the HTTP Basic auth header when obtaining the access token. Otherwise, they are sent in the request body.",
                verbose_name="Use Basic auth for token endpoint",
            ),
        ),
        migrations.AddField(
            model_name="openidconnectpublicconfig",
            name="oidc_token_use_basic_auth",
            field=models.BooleanField(
                default=False,
                help_text="If enabled, the client ID and secret are sent in the HTTP Basic auth header when obtaining the access token. Otherwise, they are sent in the request body.",
                verbose_name="Use Basic auth for token endpoint",
            ),
        ),
    ]
