# Generated by Django 3.2.12 on 2022-03-31 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("digid_eherkenning_oidc_generics", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="openidconnectpublicconfig",
            name="gemachtigde_claim_name",
            field=models.CharField(
                default="gemachtigde.bsn",
                help_text="Name of the claim in which the BSN of the person representing someone else is stored",
                max_length=50,
                verbose_name="gemachtigde claim name",
            ),
        ),
        migrations.AddField(
            model_name="openidconnectpublicconfig",
            name="vertegenwoordigde_claim_name",
            field=models.CharField(
                default="aanvrager.bsn",
                help_text="Name of the claim in which the BSN of the person being represented is stored",
                max_length=50,
                verbose_name="vertegenwoordigde claim name",
            ),
        ),
    ]
