# Generated by Django 3.2.13 on 2022-04-25 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("digid_eherkenning_oidc_generics", "0003_auto_20220421_1732"),
    ]

    operations = [
        migrations.AlterField(
            model_name="openidconnectdigidmachtigenconfig",
            name="oidc_op_jwks_endpoint",
            field=models.URLField(
                blank=True,
                help_text="URL of your OpenID Connect provider JSON Web Key Set endpoint. Required if `RS256` is used as signing algorithm.",
                max_length=1000,
                verbose_name="JSON Web Key Set endpoint",
            ),
        ),
        migrations.AlterField(
            model_name="openidconnectdigidmachtigenconfig",
            name="oidc_rp_idp_sign_key",
            field=models.CharField(
                blank=True,
                help_text="Key the Identity Provider uses to sign ID tokens in the case of an RSA sign algorithm. Should be the signing key in PEM or DER format.",
                max_length=1000,
                verbose_name="Sign key",
            ),
        ),
        migrations.AlterField(
            model_name="openidconnecteherkenningconfig",
            name="oidc_op_jwks_endpoint",
            field=models.URLField(
                blank=True,
                help_text="URL of your OpenID Connect provider JSON Web Key Set endpoint. Required if `RS256` is used as signing algorithm.",
                max_length=1000,
                verbose_name="JSON Web Key Set endpoint",
            ),
        ),
        migrations.AlterField(
            model_name="openidconnecteherkenningconfig",
            name="oidc_rp_idp_sign_key",
            field=models.CharField(
                blank=True,
                help_text="Key the Identity Provider uses to sign ID tokens in the case of an RSA sign algorithm. Should be the signing key in PEM or DER format.",
                max_length=1000,
                verbose_name="Sign key",
            ),
        ),
        migrations.AlterField(
            model_name="openidconnectpublicconfig",
            name="oidc_op_jwks_endpoint",
            field=models.URLField(
                blank=True,
                help_text="URL of your OpenID Connect provider JSON Web Key Set endpoint. Required if `RS256` is used as signing algorithm.",
                max_length=1000,
                verbose_name="JSON Web Key Set endpoint",
            ),
        ),
        migrations.AlterField(
            model_name="openidconnectpublicconfig",
            name="oidc_rp_idp_sign_key",
            field=models.CharField(
                blank=True,
                help_text="Key the Identity Provider uses to sign ID tokens in the case of an RSA sign algorithm. Should be the signing key in PEM or DER format.",
                max_length=1000,
                verbose_name="Sign key",
            ),
        ),
    ]
