# Generated by Django 3.2.16 on 2023-01-09 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digid_eherkenning_oidc_generics', '0007_auto_20221213_1347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='openidconnectdigidmachtigenconfig',
            name='userinfo_claims_source',
        ),
        migrations.RemoveField(
            model_name='openidconnecteherkenningbewindvoeringconfig',
            name='userinfo_claims_source',
        ),
        migrations.RemoveField(
            model_name='openidconnecteherkenningconfig',
            name='userinfo_claims_source',
        ),
        migrations.RemoveField(
            model_name='openidconnectpublicconfig',
            name='userinfo_claims_source',
        ),
    ]
