# Generated by Django 3.2.16 on 2023-01-09 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digid_eherkenning_oidc_generics', '0008_auto_20230109_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='openidconnectdigidmachtigenconfig',
            name='userinfo_claims_source',
            field=models.CharField(choices=[('userinfo_endpoint', 'Userinfo endpoint'), ('id_token', 'ID token')], default='userinfo_endpoint', help_text='Indicates the source from which the user information claims should be extracted.', max_length=100, verbose_name='user information claims extracted from'),
        ),
        migrations.AddField(
            model_name='openidconnecteherkenningbewindvoeringconfig',
            name='userinfo_claims_source',
            field=models.CharField(choices=[('userinfo_endpoint', 'Userinfo endpoint'), ('id_token', 'ID token')], default='userinfo_endpoint', help_text='Indicates the source from which the user information claims should be extracted.', max_length=100, verbose_name='user information claims extracted from'),
        ),
        migrations.AddField(
            model_name='openidconnecteherkenningconfig',
            name='userinfo_claims_source',
            field=models.CharField(choices=[('userinfo_endpoint', 'Userinfo endpoint'), ('id_token', 'ID token')], default='userinfo_endpoint', help_text='Indicates the source from which the user information claims should be extracted.', max_length=100, verbose_name='user information claims extracted from'),
        ),
        migrations.AddField(
            model_name='openidconnectpublicconfig',
            name='userinfo_claims_source',
            field=models.CharField(choices=[('userinfo_endpoint', 'Userinfo endpoint'), ('id_token', 'ID token')], default='userinfo_endpoint', help_text='Indicates the source from which the user information claims should be extracted.', max_length=100, verbose_name='user information claims extracted from'),
        ),
    ]
