# Generated by Django 4.2.11 on 2024-07-04 14:19

import uuid
from decimal import Decimal

import django.core.validators
from django.db import migrations, models

import tinymce.models

import csp_post_processor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="name")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="price",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="Globally unique identifier",
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "information",
                    csp_post_processor.fields.CSPPostProcessedWYSIWYGField(
                        base_field=tinymce.models.HTMLField(
                            blank=True,
                            help_text="Information text to be displayed in the confirmation page and confirmation email.",
                            verbose_name="information",
                        ),
                        blank=True,
                        help_text="Information text to be displayed in the confirmation page and confirmation email.",
                        verbose_name="information",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
            },
        ),
    ]
