# Generated by Django 4.2.16 on 2024-10-10 12:59

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("open_producten", "0001_initial"),
        ("products", "0001_initial_to_v270"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_deleted",
            field=models.BooleanField(
                default=False,
                help_text="set when the product is deleted in open producten but is linked to existing submission.",
                verbose_name="Is deleted",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="open_producten_price",
            field=models.OneToOneField(
                blank=True,
                editable=False,
                help_text="The price this option belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_type",
                to="open_producten.price",
                verbose_name="Price",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="upl_name",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="Uniform product name",
                max_length=100,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="upl_uri",
            field=models.URLField(
                blank=True,
                editable=False,
                help_text="Url to the upn definition.",
                null=True,
                verbose_name="Url",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                verbose_name="price",
            ),
        ),
    ]
