# Generated by Django 4.2.27 on 2026-01-19 11:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial_to_v270"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="product_type_uuid",
            field=models.UUIDField(
                blank=True,
                editable=False,
                help_text="Unique identifier of the product type (originates from Open Product).",
                null=True,
                unique=True,
                verbose_name="product type UUID",
            ),
        ),
    ]
