# Generated by Django 5.2.17 on 2026-10-09 13:53

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial_to_v270"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="producttype",
            field=models.UUIDField(
                blank=True,
                help_text="Open Product producttype UUID",
                null=True,
                verbose_name="Producttype",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                verbose_name="price",
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("price__isnull", False), ("producttype__isnull", True)),
                    models.Q(("price__isnull", True), ("producttype__isnull", False)),
                    _connector="OR",
                ),
                name="price_not_blank_without_producttype",
                violation_error_message="Price cannot be blank without a producttype.",
            ),
        ),
    ]
