# Generated by Django 4.2.27 on 2026-01-19 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_product_product_type_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="price_option_uuid",
            field=models.UUIDField(
                blank=True,
                editable=False,
                help_text="Unique identifier of the price option (originates from Open Product).",
                null=True,
                verbose_name="price option UUID",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_type_uuid",
            field=models.UUIDField(
                blank=True,
                editable=False,
                help_text="Identifier of the product type (originates from Open Product).",
                null=True,
                verbose_name="product type UUID",
            ),
        ),
    ]
