# Generated by Django 2.2.24 on 2021-08-16 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_auto_20210521_1352"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="url",
        ),
        migrations.AddField(
            model_name="product",
            name="uuid",
            field=models.UUIDField(
                help_text="Globally unique identifier", null=True, verbose_name="UUID"
            ),
        ),
    ]
