# Generated by Django 4.2.27 on 2026-01-19 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_product_price_option_uuid_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="price_option_uuid",
        ),
        migrations.AlterField(
            model_name="product",
            name="product_type_uuid",
            field=models.UUIDField(
                blank=True,
                editable=False,
                help_text="Unique identifier of the product type (originates from Open Product).",
                null=True,
                unique=True,
                verbose_name="product type UUID",
            ),
        ),
    ]
