# Generated by Django 2.2.24 on 2021-08-16 14:35
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_auto_20210816_1635"),
    ]

    operations = []
