# Generated by Django 4.2.23 on 2025-07-09 07:42

from django.db import migrations

from openforms.products.models import PriceOption


def update_intermediate_rol_results_name(apps, schema_editor):
    Product = apps.get_model("products", "Product")

    products = Product.objects.all()
    for product in products:
        if not product.price:
            return

        # Define the old price as a price option
        price_option: PriceOption = PriceOption.objects.create(
            product_id=product.id, price=product.price, name="Default"
        )

        price_option.save()


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_priceoption"),
    ]

    operations = [
        migrations.RunPython(
            update_intermediate_rol_results_name, migrations.RunPython.noop
        ),
    ]
