# Generated by Django 2.2.24 on 2021-08-16 14:39

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_set_product_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4,
                help_text="Globally unique identifier",
                unique=True,
                verbose_name="UUID",
            ),
        ),
    ]
