# Generated by Django 4.2.27 on 2026-01-19 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_move_price_values_to_priceoption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
