# Generated by Django 4.2.27 on 2026-01-20 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_remove_product_price_option_uuid_and_more"),
        ("products", "0005_remove_product_price"),
    ]

    operations = []
