# Generated by Django 2.2.26 on 2022-02-01 11:13

from django.db import migrations

import tinymce.models

import csp_post_processor.fields


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_product_information"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="information",
            field=csp_post_processor.fields.CSPPostProcessedWYSIWYGField(
                base_field=tinymce.models.HTMLField(
                    blank=True,
                    help_text="Information text to be displayed in the confirmation page and confirmation email.",
                    verbose_name="information",
                ),
                blank=True,
                help_text="Information text to be displayed in the confirmation page and confirmation email.",
                verbose_name="information",
            ),
        ),
    ]
