# Generated by Django 2.2.16 on 2020-09-25 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("zgw_consumers", "0011_remove_service_extra"),
    ]

    operations = [
        migrations.CreateModel(
            name="BRPConfig",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "brp_service",
                    models.ForeignKey(
                        help_text="Select which service to use for the BRP API.",
                        limit_choices_to={"api_type": "orc"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="zgw_consumers.Service",
                        verbose_name="BRP service",
                    ),
                ),
            ],
            options={
                "verbose_name": "BRP Configuration",
            },
        ),
    ]
