# Generated by Django 2.2.24 on 2021-08-05 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kvk", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="kvkconfig",
            name="use_operation",
        ),
    ]
