# Generated by Django 4.2.27 on 2026-01-30 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "zgw_consumers",
            "0027_service_oauth2_scope_service_oauth2_token_url_and_more",
        ),
        ("kvk", "0001_initial_to_v270"),
    ]

    operations = [
        migrations.AddField(
            model_name="kvkconfig",
            name="branch_profile_service",
            field=models.OneToOneField(
                help_text="Service for API used to retrieve vestingings profielen.",
                limit_choices_to={"api_type": "orc"},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="zgw_consumers.service",
                verbose_name="KvK API Vestigingsprofiel",
            ),
        ),
    ]
