# Generated by Django 2.2.25 on 2022-02-03 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kvk", "0003_auto_20211217_1234"),
    ]

    operations = [
        migrations.RenameField(
            model_name="kvkconfig",
            old_name="profiles",
            new_name="_profiles",
        ),
        migrations.RenameField(
            model_name="kvkconfig",
            old_name="service",
            new_name="_service",
        ),
    ]
