# Generated by Django 3.2.21 on 2023-09-21 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kvk", "0005_normalize_kvk_service_config"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="kvkconfig",
            name="_profiles",
        ),
        migrations.RemoveField(
            model_name="kvkconfig",
            name="_service",
        ),
    ]
