# Generated by Django 4.2.10 on 2024-03-14 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zgw_consumers", "0020_service_timeout"),
        ("kvk", "0006_remove_refactored_service_config_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="kvkconfig",
            name="profile_service",
            field=models.OneToOneField(
                help_text="Service for API used to retrieve basis profielen.",
                limit_choices_to={"api_type": "orc"},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="zgw_consumers.service",
                verbose_name="KvK API Basisprofiel",
            ),
        ),
        migrations.AddField(
            model_name="kvkconfig",
            name="search_service",
            field=models.OneToOneField(
                help_text="Service for API used for validation of KvK, RSIN and vestigingsnummer's.",
                limit_choices_to={"api_type": "orc"},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="zgw_consumers.service",
                verbose_name="KvK API Zoeken",
            ),
        ),
        # Removed RunPython operation, it ran in 2.6 for existing instances.
    ]
