# Generated by Django 4.2.10 on 2024-03-14 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kvk", "0007_kvkconfig_profile_service_kvkconfig_search_service"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="kvkconfig",
            name="service",
        ),
    ]
