# Generated by Django 4.2.25 on 2025-11-12 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        (
            "zgw_consumers",
            "0027_service_oauth2_scope_service_oauth2_token_url_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerInteractionsAPIGroupConfig",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="A recognisable name for this API group",
                        max_length=255,
                        verbose_name="name",
                    ),
                ),
                (
                    "identifier",
                    models.SlugField(
                        help_text="A unique, human-friendly identifier to identify this group.",
                        unique=True,
                        verbose_name="identifier",
                    ),
                ),
                (
                    "customer_interactions_service",
                    models.ForeignKey(
                        limit_choices_to={"api_type": "kc"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="zgw_consumers.service",
                        verbose_name="Customer Interactions API",
                    ),
                ),
            ],
            options={
                "verbose_name": "Customer interactions API group",
                "verbose_name_plural": "Customer interactions API groups",
            },
        ),
    ]
