# Generated by Django 5.2.16 on 2026-07-24 07:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer_interactions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerinteractionsapigroupconfig",
            name="digital_address_reference",
            field=models.CharField(
                blank=True,
                help_text="The 'referentie' attribute of the digital address resource sent to the Customer Interactions API.",
                max_length=50,
                verbose_name="digital address reference",
            ),
        ),
    ]
