# Generated by Django 3.2.19 on 2023-06-29 11:28

from django.db import migrations, models

import django_jsonform.models.fields

import openforms.appointments.contrib.qmatic.models


class Migration(migrations.Migration):

    dependencies = [
        ("qmatic", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="qmaticconfig",
            name="required_customer_fields",
            field=django_jsonform.models.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("firstName", "First name"),
                        ("lastName", "Last name"),
                        ("email", "Email address"),
                        ("phone", "Phone number"),
                        ("addressLine1", "Street name and number"),
                        ("addressLine2", "Address line 2"),
                        ("addressCity", "City"),
                        ("addressState", "State"),
                        ("addressZip", "Postal code"),
                        ("addressCountry", "Country"),
                        ("identificationNumber", "Identification number"),
                        ("externalId", "Unique customer identification/account number"),
                        ("dateOfBirth", "Birthday"),
                    ],
                    max_length=50,
                ),
                default=openforms.appointments.contrib.qmatic.models.get_default_customer_fields,
                help_text="Select the customer fields for the contact details step. Fields that you select here are REQUIRED fields for the user making the appointment. You must have at least one field to be able to identify the customer.",
                size=None,
                verbose_name="Required customer fields",
            ),
        ),
    ]
