# Generated by Django 3.2.20 on 2023-09-05 10:49
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("qmatic", "0002_qmaticconfig_required_customer_fields"),
    ]

    # Removed as part of Open Forms 2.7 release cycle
    operations = []
