# Generated by Django 3.2.20 on 2023-09-11 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("stuf_bg", "0001_initial"),
        ("stuf_bg", "0002_nice_verbose_name"),
        ("stuf_bg", "0003_auto_20211001_1300"),
    ]

    dependencies = [
        ("stuf", "0008_auto_20210927_1555"),
    ]

    operations = [
        migrations.CreateModel(
            name="StufBGConfig",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="stuf.stufservice",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "verbose_name": "StUF-BG configuration",
            },
        ),
    ]
