# Generated by Django 2.2.24 on 2021-10-01 11:00

from django.db import migrations, models
import django.db.models.deletion


def migrate_services(apps, _):
    StufService = apps.get_model("stuf", "StufService")
    StufBGConfig = apps.get_model("stuf_bg", "StufBGConfig")

    try:
        stuf_bg_config = StufBGConfig.objects.get()  # There can be only one (or none)
        stuf_bg_config.new_service = StufService.objects.get(
            soap_service=stuf_bg_config.old_service
        )
        stuf_bg_config.save()
    except StufBGConfig.DoesNotExist:
        # This config has not been created, no need to migrate anything
        pass


class Migration(migrations.Migration):

    dependencies = [
        ("stuf", "0008_auto_20210927_1555"),
        ("stuf_bg", "0002_nice_verbose_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="stufbgconfig",
            old_name="service",
            new_name="old_service",
        ),
        migrations.AddField(
            model_name="stufbgconfig",
            name="new_service",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="stuf.StufService",
            ),
        ),
        migrations.RunPython(migrate_services, migrations.RunPython.noop),
        migrations.RenameField(
            model_name="stufbgconfig",
            old_name="new_service",
            new_name="service",
        ),
        migrations.RemoveField(
            model_name="stufbgconfig",
            name="old_service",
        ),
    ]
