# Generated by Django 2.2.24 on 2021-09-29 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("stuf_bg", "0002_nice_verbose_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stufbgconfig",
            name="service",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="stuf.StufService",
            ),
        ),
    ]
