# Generated by Django 2.2.24 on 2021-07-26 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OgoneMerchant",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Human readable label",
                        max_length=255,
                        verbose_name="Label",
                    ),
                ),
                (
                    "pspid",
                    models.CharField(
                        help_text="Ogone PSPID", max_length=255, verbose_name="PSPID"
                    ),
                ),
                (
                    "sha_in_passphrase",
                    models.CharField(
                        help_text="This must match with the Ogone backend",
                        max_length=255,
                        verbose_name="SHA-IN passphrase",
                    ),
                ),
                (
                    "sha_out_passphrase",
                    models.CharField(
                        help_text="This must match with the Ogone backend",
                        max_length=255,
                        verbose_name="SHA-OUT passphrase",
                    ),
                ),
                (
                    "hash_algorithm",
                    models.CharField(
                        choices=[
                            ("sha1", "SHA-1"),
                            ("sha256", "SHA-256"),
                            ("sha512", "SHA-512"),
                        ],
                        help_text="This must match with the Ogone backend",
                        max_length=8,
                        verbose_name="Hash algorithm",
                    ),
                ),
                (
                    "endpoint_preset",
                    models.URLField(
                        choices=[
                            (
                                "https://ogone.test.v-psp.com/ncol/test/orderstandard_utf8.asp",
                                "Ogone Test",
                            ),
                            (
                                "https://secure.ogone.com/ncol/prod/orderstandard_utf8.asp",
                                "Ogone Live",
                            ),
                        ],
                        default="https://ogone.test.v-psp.com/ncol/test/orderstandard_utf8.asp",
                        help_text="Select a common preset endpoint",
                        verbose_name="Preset Endpoint",
                    ),
                ),
                (
                    "endpoint_custom",
                    models.URLField(
                        blank=True,
                        help_text="Optionally override the preset endpoint",
                        verbose_name="Custom Endpoint",
                    ),
                ),
            ],
        ),
    ]
