# Generated by Django 4.2.23 on 2025-08-11 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments_ogone", "0002_auto_20210902_2120"),
    ]

    operations = [
        migrations.CreateModel(
            name="OgoneWebhookConfiguration",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "webhook_key_id",
                    models.CharField(
                        default="", max_length=255, verbose_name="Webhook Key ID"
                    ),
                ),
                (
                    "webhook_key_secret",
                    models.CharField(
                        default="", max_length=255, verbose_name="Webhook Key Secret"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="ogonemerchant",
            name="api_key",
            field=models.CharField(
                blank=True,
                help_text="API Key created for the specified PSPID. This value will be used when upgrading to a Open Forms version supporting the Worldline payment provider.",
                max_length=255,
                verbose_name="API Key",
            ),
        ),
        migrations.AddField(
            model_name="ogonemerchant",
            name="api_secret",
            field=models.CharField(
                blank=True,
                help_text="API Secret created for the specified PSPID. This value will be used when upgrading to a Open Forms version supporting the Worldline payment provider.",
                max_length=255,
                verbose_name="API Secret",
            ),
        ),
    ]
