# Generated by Django 4.2.23 on 2025-08-07 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("payments_ogone", "0003_ogonemerchant_api_key_ogonemerchant_api_secret"),
        ("payments_ogone", "0004_alter_ogonemerchant_api_key_and_more"),
    ]

    dependencies = [
        ("payments_ogone", "0002_auto_20210902_2120"),
    ]

    operations = [
        migrations.AddField(
            model_name="ogonemerchant",
            name="api_key",
            field=models.CharField(
                blank=True,
                help_text="API Key created for the specified PSPID. This value will be used when upgrading to a Open Forms version supporting the Worldline payment provider.",
                max_length=255,
                verbose_name="API Key",
            ),
        ),
        migrations.AddField(
            model_name="ogonemerchant",
            name="api_secret",
            field=models.CharField(
                blank=True,
                help_text="API Secret created for the specified PSPID. This value will be used when upgrading to a Open Forms version supporting the Worldline payment provider.",
                max_length=255,
                verbose_name="API Secret",
            ),
        ),
    ]
