# Generated by Django 4.2.23 on 2025-10-28 13:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "payments_ogone",
            "0003_ogonewebhookconfiguration_ogonemerchant_api_key_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ogonewebhookconfiguration",
            options={
                "verbose_name": "Worldline webhook configuration (transition)",
                "verbose_name_plural": "Worldline webhook configurations (transition)",
            },
        ),
        migrations.AddField(
            model_name="ogonewebhookconfiguration",
            name="pspid",
            field=models.CharField(
                default="(ONBEKEND)",
                help_text="Ogone PSPID",
                max_length=255,
                unique=True,
                verbose_name="PSPID",
            ),
        ),
    ]
