# Generated by Django 5.2.13 on 2026-06-16 15:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("payments_ogone", "0004_alter_ogonewebhookconfiguration_options_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="OgoneMerchant",
        ),
        migrations.DeleteModel(
            name="OgoneWebhookConfiguration",
        ),
    ]
