name: Build the target Docker image

on:
  workflow_call:
    inputs:
      target-env:
        required: true
        type: string
        # choice is not available yet :(
        # type: choice
        # options:
        #   - production
        #   - extensions
      image-name:
        required: true
        type: string # image name without tag, e.g. 'openforms/open-forms'
      image-tag-prefix:
        required: true
        type: string
        default: ''
      version:
        required: true
        type: string
        default: ''
      git-hash:
        required: true
        type: string
        default: ''
      extensions:
        required: true
        type: string
        default: ''
    outputs:
      image-name:
        description: Image name + tag of the built image
        value: ${{ jobs.image_build.outputs.image-name }}
      artifact-name:
        description: Artifact name for the built image
        value: ${{ jobs.image_build.outputs.artifact-name }}

permissions: {}

jobs:
  image_build:
    name: Build image
    runs-on: ubuntu-latest

    env:
      COMPOSE_DOCKER_CLI_BUILD: 1
      DOCKER_BUILDKIT: 1

    outputs:
      image-name: ${{ steps.build-args.outputs.image-name }}
      artifact-name: ${{ steps.build-args.outputs.artifact-name }}

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - name: Extract build args
        id: build-args
        run: |
          # Obtain the SDK release to bundle along, use latest if backend is also latest
          SDK_RELEASE=$(cat .sdk-release | tr -d '[:space:]')
          [ "${INPUTS_VERSION}" == "latest" ] && SDK_RELEASE=latest
          echo "sdk_release=${SDK_RELEASE}" >> $GITHUB_OUTPUT

          echo "image-name=${INPUTS_IMAGE_NAME}:${INPUTS_IMAGE_TAG_PREFIX}${INPUTS_VERSION}" >> $GITHUB_OUTPUT
          echo "artifact-name=docker-image-${INPUTS_IMAGE_TAG_PREFIX}${INPUTS_VERSION}" >> $GITHUB_OUTPUT
        env:
          INPUTS_VERSION: ${{ inputs.version }}
          INPUTS_IMAGE_NAME: ${{ inputs.image-name }}
          INPUTS_IMAGE_TAG_PREFIX: ${{ inputs.image-tag-prefix }}

      - name: Build the Docker image
        run: |
          docker build . \
            --tag ${STEPS_BUILD_ARGS_OUTPUTS_IMAGE_NAME} \
            --build-arg TARGET_ENVIRONMENT=${INPUTS_TARGET_ENV} \
            --build-arg EXTENSIONS=${INPUTS_EXTENSIONS} \
            --build-arg SDK_RELEASE=${STEPS_BUILD_ARGS_OUTPUTS_SDK_RELEASE} \
            --build-arg COMMIT_HASH=${INPUTS_GIT_HASH} \
            --build-arg RELEASE=${INPUTS_VERSION}
        env:
          STEPS_BUILD_ARGS_OUTPUTS_IMAGE_NAME: ${{ steps.build-args.outputs.image-name }}
          INPUTS_TARGET_ENV: ${{ inputs.target-env }}
          INPUTS_EXTENSIONS: ${{ inputs.extensions }}
          STEPS_BUILD_ARGS_OUTPUTS_SDK_RELEASE: ${{ steps.build-args.outputs.sdk_release }}
          INPUTS_GIT_HASH: ${{ inputs.git-hash }}
          INPUTS_VERSION: ${{ inputs.version }}

      - name: Dump image to file
        run: docker image save -o image.tar ${STEPS_BUILD_ARGS_OUTPUTS_IMAGE_NAME}
        env:
          STEPS_BUILD_ARGS_OUTPUTS_IMAGE_NAME: ${{ steps.build-args.outputs.image-name }}

      - name: Store image artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: ${{ steps.build-args.outputs.artifact-name }}
          path: image.tar
          retention-days: 1
