name: Run CI

# Run this workflow every time a new commit pushed to your repository
on:
  push:
    branches:
      - main
      - stable/*
    tags:
      - '*'
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '30 7 * * *'

permissions: {}

env:
  IMAGE_NAME: openformulieren/open-forms
  DJANGO_SETTINGS_MODULE: openforms.conf.ci
  TEST_REPORT_RANDOM_STATE: 'true'
  OTEL_SERVICE_NAME: openforms-ci

jobs:

  setup:
    name: Set up the build variables
    runs-on: ubuntu-latest
    outputs:
      # see https://github.com/orgs/community/discussions/26671
      image-name: ${{ steps.envars-to-outputs.outputs.image-name }}
      version: ${{ steps.vars.outputs.version }}
      git_hash: ${{ steps.vars.outputs.git_hash }}
      sdk-version: ${{ steps.sdk-vars.outputs.sdk-version }}
      sdk-ref: ${{ steps.sdk-vars.outputs.sdk-ref }}
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false
      - name: Set output with default values
        id: envars-to-outputs
        run: |
          echo "image-name=${{ env.IMAGE_NAME }}" >> $GITHUB_OUTPUT
      - name: Extract version info
        id: vars
        uses: maykinmedia/open-api-workflows/actions/extract-version@0a5525c13f8eea10be40c8eaee5e535ea3a10721 # v6.4.1
      - name: Extract SDK version info
        id: sdk-vars
        uses: ./.github/actions/extract-sdk-version
        with:
          backend-version: ${{ steps.vars.outputs.version }}

  tests:
    name: Run the Django test suite
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_HOST_AUTH_METHOD: trust
        ports:
          - 5432:5432
        # Needed because the postgres container does not provide a healthcheck
        options:
          --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
          --name postgres
      redis:
        image: redis:8
        ports:
          - 6379:6379
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false
          submodules: true
      - name: Set up backend environment
        uses: ./.github/actions/setup-backend

      - name: Start CI docker services
        run: |
          docker compose -f docker-compose.ci.yml up -d
        working-directory: docker

      - name: Run tests
        run: |
          echo "# Profiling stats" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_OUTPUT

          python src/manage.py compilemessages
          python src/manage.py collectstatic --noinput --link
          mkdir private_media
          coverage run \
            --concurrency=multiprocessing \
            --parallel-mode \
            src/manage.py test src \
              --force-color \
              --parallel 4 \
              --exclude-tag=e2e \
              --verbosity 3
          coverage combine

        env:
          SECRET_KEY: dummy
          DB_USER: postgres
          DB_PASSWORD: ''
          DEBUG: 'true'
          # deliberatey broken
          CELERY_BROKER_URL: 'redis://bad-host:6379/0'
          # specified explicitly, since the broker URL is broken, but the once backend
          # needs to be available even with CELERY_TASK_ALWAYS_EAGER
          CELERY_ONCE_REDIS_URL: 'redis://localhost:6379/0'

      - name: Run JS tests
        run: npm test

      - name: Publish coverage report
        uses: codecov/codecov-action@e79a6962e0d4c0c17b229090214935d2e33f8354 # v6.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Check that private-media tests are properly isolated
        run: |
          num_private_media_files=$(find private_media -type f | wc -l)
          if [[ "$num_private_media_files" == "0" ]]; then
            exit 0
          else
            echo "# Writes to private_media detected!" >> $GITHUB_STEP_SUMMARY
            echo "$num_private_media_files were written into the private media storage, while tests should not leave any files." >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "Files:" >> $GITHUB_STEP_SUMMARY
            find private_media -type f >> $GITHUB_STEP_SUMMARY
            exit 1
          fi

  tests-reverse:
    name: Run the Django test suite in reverse
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_HOST_AUTH_METHOD: trust
        ports:
          - 5432:5432
        # Needed because the postgres container does not provide a healthcheck
        options:
          --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
          --name postgres
      redis:
        image: redis:6
        ports:
          - 6379:6379
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false
          submodules: true
      - name: Set up backend environment
        uses: ./.github/actions/setup-backend

      - name: Start CI docker services
        run: |
          docker compose -f docker-compose.ci.yml up -d
        working-directory: docker

      - name: Run tests
        run: |
          python src/manage.py compilemessages
          python src/manage.py collectstatic --noinput --link
          mkdir private_media
          src/manage.py test src \
            --force-color \
            --parallel 4 \
            --exclude-tag=e2e \
            --verbosity 3 \
            --reverse

        env:
          PYTHONOPTIMIZE: '1'  # skip 'assert' execution
          SECRET_KEY: dummy
          DB_USER: postgres
          DB_PASSWORD: ''
          DEBUG: 'true'
